{
  "hash": "1e5d00b9a78006e888b3524d80b501a1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Wrapup Multiple regression\"\nauthor: \"Lieven Clement, Jeroen Gilis and Milan Malfait\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\n---\n\n<a rel=\"license\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png\" /></a>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ntheme_set(theme_bw())\n```\n:::\n\n\n# Puromycin data\n\nData on the velocity of an enzymatic reaction were obtained by Treloar (1974).\nThe number of counts per minute of radioactive product from the reaction was\nmeasured as a function of substrate concentration in parts per million (ppm) and\nfrom these counts the initial rate (or velocity) of the reaction was calculated (counts/min/min). The experiment was conducted once with the enzyme treated\nwith Puromycin, and once with the enzyme untreated.\n\nAssess if there is an association between the substrate concentration and rate\n**for both the treated and untreated enzymes.**\n\n# Import data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(Puromycin)\n```\n:::\n\n\n# Data wrangling\n\nFor a clearer interpretation of the model parameters later on, we will make\nthe untreated state enzymes the reference category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuromycin <- Puromycin |>\n  mutate(state = fct_relevel(state, c(\"untreated\", \"treated\")))\n```\n:::\n\n\n## Data Exploration\n\nFirst, we visualize the association between the concentration and the enzyme\nrate, for both of the enzyme states.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuromycin |>\n  ggplot(aes(conc, rate,col=state)) +\n  geom_point() +\n  stat_smooth(method = \"lm\") +\n  labs(\n    x = \"Substrate concentration (ppm)\",\n    y = \"Reaction rate (counts/min/min)\"\n  ) +\n  ggtitle(\"Reaction rates for puromycin-treated enzymes\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe plot shows that there is a relation between the velocity and the\nconcentration, however, the relation does not seem to be linear.\n\nWe will assess the impact of log-transforming the concentration. Because the\nconcentration is measured in ppm we will log$_{10}$ transform the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuromycin |>\n  ggplot(aes(x = log10(conc), y = rate,col=state)) +\n  geom_point() +\n  stat_smooth(method = \"lm\") +\n    labs(\n      x = \"Substrate concentration (log10(ppm))\",\n      y = \"Reaction rate (counts/min/min)\"\n    ) +\n    ggtitle(\"Reaction rates for puromycin-treated enzymes\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe relation between the velocity and the log$_{10}$ transformed concentration\nseems to be linear.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuromycin <- Puromycin |>\n  mutate(log10conc = log10(conc))\n```\n:::\n\n\n# Linear regression\n\nWe will fit the following model to the data\n\n$Y_i = \\beta_0 + \\beta_c x_c+ \\beta_s x_s +\\beta_{c:s}x_{c}x_{s} + \\epsilon_i$\n\nwith\n\n- $Y_i$ the reaction rate,\n\n- $\\beta_0$ the intercept,\n\n- $\\beta_{c}$ the main effect for log10 concentration,\n\n- $x_c$ the log10 concentration,\n\n- $\\beta_{p}$ the main effect for treatment ,\n\n- $x_s$ a dummy variable for \"state\" that is 0 if the enzymes that are untreated and 1 if\nthe enzymes are treated with Puromycin,\n\n- $\\beta_{c:s}$ the interaction effect between concentration and treatment state,\n\n- $\\epsilon_i$ i.i.d. normally distributed with mean 0 and variance $\\sigma^2$.\n\nNote, that we write the substrate concentration with a small letter because\nthe predictor is not random. The researchers have chosen the substrate\nconcentrations in the design phase and it is thus no random variable.\n\nThe model implies two different regression lines\n\n- no treatment ($x_s = 0$)\n$$\nY_i = \\beta_0 + \\beta_c x_c + \\epsilon\n$$\n- treatment (x_s = 1)\n\n$$\nY_i = (\\beta_0 + \\beta_s)  + (\\beta_c+\\beta_{c:s}) x_c + \\epsilon\n$$\n\nSo the main effect for treatment has the interpretation as the change in intercept between treated and untreated samples.\n\nThe interaction term has the interpretation as the change in slope between treated and untreated samples.\n\n\n## Intermezzo: Graphical interpretation of the parameters\n\n### Simple linear model: 1 slope {-}\n\nThis is the same model that we fit in the\n[Chapter 6 exercise](./06_1_puromycin.html):\n\n$$ Y_i = \\beta_0 + \\beta_{\\text{rate}} X_{i, \\text{rate}} + \\epsilon_i $$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_simple <- lm(rate ~ log10conc, data = Puromycin)\nmod_simple\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rate ~ log10conc, data = Puromycin)\n\nCoefficients:\n(Intercept)    log10conc  \n     190.09        76.45  \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(Puromycin, aes(log10conc, rate)) +\n  geom_point(aes(color = state)) +\n  geom_abline(\n     intercept = coef(mod_simple)[1],\n     slope = coef(mod_simple)[2]\n  ) +\n  scale_color_manual(values = c(\"darkorchid\", \"forestgreen\")) +\n  ggtitle(\"The simple linear model\")\n```\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n### Additive model: 2 parallel slopes {-}\n\nWe add an additional term for the state of the reactin (treated or untreated).\nNote that this variable is **categorical**.\n\n$$\nY_i = \\beta_0 + \\beta_{\\text{rate}} X_{i, \\text{rate}} +\n  \\beta_{\\text{state}} X_{i, \\text{state}} + \\epsilon_i\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_add <- lm(rate ~ log10conc + state, data = Puromycin)\nmod_add\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rate ~ log10conc + state, data = Puromycin)\n\nCoefficients:\n (Intercept)     log10conc  statetreated  \n      175.73         74.98         25.18  \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(Puromycin, aes(log10conc, rate, col = state)) +\n  geom_point() +\n  ## Line for the untreated group\n  geom_abline(\n     intercept = coef(mod_add)[1],\n     slope = coef(mod_add)[2],\n     col = \"darkorchid\"\n  ) +\n  ## Line for the treated group\n  geom_abline(\n     intercept = coef(mod_add)[1] + coef(mod_add)[3],\n     slope = coef(mod_add)[2],\n     col = \"forestgreen\"\n  ) +\n  scale_color_manual(values = c(\"darkorchid\", \"forestgreen\")) +\n  ggtitle(\"The additive linear model with parallel slopes\")\n```\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n### The interaction model: 2 non-parallel slopes {-}\n\n$$\nY_i = \\beta_0 + \\beta_{\\text{rate}} X_{i, \\text{rate}} +\n  \\beta_{\\text{state}} X_{i, \\text{state}} +\n  \\beta_{\\text{rate:state}} X_{i, \\text{rate}} X_{i, \\text{state}} +\n  \\epsilon_i\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_int <- lm(rate ~ log10conc * state, data = Puromycin)\nmod_int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rate ~ log10conc * state, data = Puromycin)\n\nCoefficients:\n           (Intercept)               log10conc            statetreated  \n                164.59                   62.13                   44.61  \nlog10conc:statetreated  \n                 23.32  \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(Puromycin, aes(log10conc, rate, col = state)) +\n  geom_point() +\n  ## Line for the untreated group\n  geom_abline(\n     intercept = coef(mod_int)[1],\n     slope = coef(mod_int)[2],\n     col = \"darkorchid\"\n  ) +\n  ## Line for the treated group\n  geom_abline(\n     intercept = coef(mod_int)[1] + coef(mod_int)[3],\n     slope = coef(mod_int)[2] + coef(mod_int)[4],\n     col = \"forestgreen\"\n  ) +\n  scale_color_manual(values = c(\"darkorchid\", \"forestgreen\")) +\n  ggtitle(\"The linear model with interaction: non-parallel slopes\")\n```\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(rate ~ log10conc * state, Puromycin)\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = rate ~ log10conc * state, data = Puromycin)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-17.018  -6.381  -1.005   7.616  13.323 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             164.588      5.153  31.938  < 2e-16 ***\nlog10conc                62.129      5.020  12.375 1.54e-10 ***\nstatetreated             44.606      6.811   6.549 2.85e-06 ***\nlog10conc:statetreated   23.321      6.763   3.448  0.00269 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.151 on 19 degrees of freedom\nMultiple R-squared:  0.968,\tAdjusted R-squared:  0.9629 \nF-statistic: 191.3 on 3 and 19 DF,  p-value: 2.267e-14\n```\n\n\n:::\n:::\n\n\nBefore we perform inference we will first assess the assumptions\n\n## Assumptions\n\n\n1. Linearity and representative sample\n\n\\[E[\\hat \\beta_j]=\\beta_j\\]\n\n2. Normal distribution of the residuals\n\n\\[Y_{i} \\sim N(\\mu_i,\\sigma^2)\\]\n\\[Y_i \\sim N(\\beta_0 + \\beta_c x_{ci}+ \\beta_s x_{si} +\\beta_{c:s}x_{ci}x_{si},\\sigma^2)  \\longrightarrow \\hat \\beta_j \\sim N(\\beta_j, \\sigma^2_{\\hat \\beta_j})\\]\n\nlinear combinations of model parameter estimators are also normally distributed, e.g.\n$$\n\\longrightarrow \\hat \\beta_c + \\hat \\beta_{c:s} \\sim N(\\beta_c+\\beta_{cs}, \\sigma^2_{\\hat\\beta_c+\\hat\\beta_{c:s}})\n$$\n$$\n\\longrightarrow L^T\\hat \\beta \\sim N(L^T\\beta, \\sigma^2_{L^T\\hat{\\boldsymbol{\\beta}}})\n$$\n\n\n\n4. Independence and Homoscedasticity\n\nWe assume that the experiment was well designed and that the different reactions that were use in the experiment are independent.\n\n$$\\sigma^2_{L^T\\hat{\\boldsymbol{\\beta}}} = c_L \\sigma^2$$\n\n\n- $\\sigma^2?$\n\n$$\\hat \\sigma^2 = MSE = \\sum\\limits_{i=1} ^ n \\frac{(Y_i - \\hat Y_i)^2}{n-p}$$\n\n$$\nSE_{L^T\\hat{\\boldsymbol{\\beta}}} = c_L \\hat \\sigma^2\n$$\n\n- t-statistic\n\n$$\nT = \\frac{L\\hat{\\boldsymbol{\\beta}} - L\\boldsymbol{\\beta}}{\\text{SE}_{L\\hat{\\boldsymbol{\\beta}}}}\n \\sim t_{n-p}\n$$\n\n- CI and T-test $H_0: L\\boldsymbol{\\beta} = 0$ vs  $H_1: L\\boldsymbol{\\beta} \\neq 0$\n\n- F statistic follows F-distribution under $H_0$\n\\[ F = \\frac{MSR_2 - MSR_1}{MSE} \\sim F_{p_2 - p_1,n-p_2}\\]\n\n\n### Linearity\n\nWe assess linearity in a residual analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(mod1, which = 1)\n```\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThe assumption of linearity is met.\n\n### Normality\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(mod1, which = 2)\n```\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThe QQ-plot does not show large deviations from normality.\n\n### Homoscedasticity: equality of the variance\n\nWe can again use the residual plot for assessing this assumption or the plot\nwere we plot the square root of the standardized residuals in function of\nthe fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(mod1, which = 1)\n```\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(mod1, which = 3)\n```\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n\nWe see that the spread of the majority of the residuals is more or less similar.\nAs such, we may assume homoscedasticity of the data.\n\n\n\n## Inference\n\nWe first do an omnibus test to assess is there is an effect of the log10 concentration on the velocity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod0 <- lm(rate ~ state, data = Puromycin)\nanova(mod0, mod1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"RSS\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sum of Sq\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"21\",\"2\":\"44201.098\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\",\"6\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"19\",\"2\":\"1591.245\",\"3\":\"2\",\"4\":\"42609.85\",\"5\":\"254.3879\",\"6\":\"1.927032e-14\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNext, we assess the interaction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Sum Sq\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Mean Sq\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"43455.2759\",\"3\":\"43455.27595\",\"4\":\"518.87046\",\"5\":\"2.955477e-15\",\"_rn_\":\"log10conc\"},{\"1\":\"1\",\"2\":\"3622.8453\",\"3\":\"3622.84529\",\"4\":\"43.25798\",\"5\":\"2.694833e-06\",\"_rn_\":\"state\"},{\"1\":\"1\",\"2\":\"995.9377\",\"3\":\"995.93770\",\"4\":\"11.89183\",\"5\":\"2.692345e-03\",\"_rn_\":\"log10conc:state\"},{\"1\":\"19\",\"2\":\"1591.2454\",\"3\":\"83.74976\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nWe cannot remove the interaction of the model.\n\nHence, we cannot study the effect of the concentration without accounting for the treatment and have to assess following research questions.\n\n1. the association between velocity and the concentration is significant in the untreated group\n\n$$\nH_0: \\beta_c = 0 \\text{ vs } H_1: \\beta_c \\neq 0\n$$\n\n2. the association between velocity and the concentration is significant in the treated group\n\n$$\nH_0: \\beta_c + \\beta_{c:s}= 0 \\text{ vs } H_1: \\beta_c + \\beta_{c:s}\\neq 0\n$$\n\n3. the association between velocity and the concentration is different between treated and untreated group\n\n$$\nH_0: \\beta_{c:s}= 0\\text{ vs }H_1: \\beta_{c:s}\\neq 0\n$$\n\nWe can assess all these hypotheses using multcomp while correcting for multiple testing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multcomp)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: mvtnorm\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: survival\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: TH.data\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: MASS\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'MASS'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    select\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'TH.data'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:MASS':\n\n    geyser\n```\n\n\n:::\n\n```{.r .cell-code}\nmcp1 <- glht(mod1,\n  linfct = c(\n    \"log10conc = 0\",\n    \"log10conc + log10conc:statetreated = 0\",\n    \"log10conc:statetreated = 0\"\n  )\n)\nsummary(mcp1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nFit: lm(formula = rate ~ log10conc * state, data = Puromycin)\n\nLinear Hypotheses:\n                                        Estimate Std. Error t value Pr(>|t|)\nlog10conc == 0                            62.129      5.020  12.375  < 0.001\nlog10conc + log10conc:statetreated == 0   85.450      4.531  18.858  < 0.001\nlog10conc:statetreated == 0               23.321      6.763   3.448  0.00674\n                                           \nlog10conc == 0                          ***\nlog10conc + log10conc:statetreated == 0 ***\nlog10conc:statetreated == 0             ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(mcp1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nFit: lm(formula = rate ~ log10conc * state, data = Puromycin)\n\nQuantile = 2.5097\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                                        Estimate lwr     upr    \nlog10conc == 0                          62.1285  49.5289 74.7281\nlog10conc + log10conc:statetreated == 0 85.4499  74.0782 96.8217\nlog10conc:statetreated == 0             23.3214   6.3489 40.2940\n```\n\n\n:::\n:::\n\n\n\n## Conclusion\n\nThere is an extremely significant effect of the substrate concentration on the reaction rate (p<<0.001).\nThe effect of the substrate concentration on the reaction rate is extremely significant for reactions catalysed with untreated enzymes. A reaction at a substrate concentration that is 10 times higher will have a reaction speed that is on average  62.1 counts/min higher (95% CI [49.5, 74.7] counts/min) (p << 0.001).\nThe effect of the substrate concentration on the reaction rate is extremely significant for reactions catalysed puromycin treated enzymes  (p << 0.001). A reaction at a substrate concentration that is 10 times higher will have a reaction speed that is on average  85.4 counts/min higher (95% CI [74.1, 96.8] counts/min).\nThe effect of the substrate concentration on the reaction rate is very significantly higher for reactions catalysed with Puromycin treated enzymes than when catalysed with non-treated enzymes  (p = 0.007). A reaction at a substrate concentration that is 10 times higher will have a reaction speed that is on average 23.3 counts/min higher for reactions that are catalysed with Puromycin treated enzymes than with untreated enzymes (95% CI [6.3, 40.3] counts/min).\n\n\n# Additional concepts\n\n## Interaction between two continuous predictors?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n$$\nY_i = \\beta_0 + \\beta_v x_{iv} + \\beta_w x_{iw} +\\beta_s x_{is} + \\beta_{vw} x_{iv}x_{iw} +\\epsilon_i\n$$\n\n---\n\nPatient with a 1 unit difference in $X_v$ have an average difference in lpsa of\n\n$$\n\\begin{array}{l}\nE(Y | X_v=x_v +1, X_w=x_w, X_s=x_s) - E(Y | X_v=x_v, X_w=x_w, X_s=x_s) \\\\\n\\quad = \\left[\\beta_0 + \\beta_v (x_{v}+1) + \\beta_w x_w +\\beta_s x_{s} + \\beta_{vw} (x_{v}+1) x_w \\right] - \\left[\\beta_0 + \\beta_v x_{v} + \\beta_w x_w  + \\beta_s x_{s} + \\beta_{vw} (x_{v}) x_w \\right]\\\\\n\\quad = \\beta_v +  \\beta_{vw} x_w\n \\end{array}\n $$\n\n- Slope for lcavol depends on log weight of prostate!\n\n- We can do the same for the lweight. Slope for lweight depends on lcavol of prostate!\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmVWS_IntVW <- lm(\n  lpsa ~ lcavol +\n    lweight +\n    svi +\n    lcavol:lweight,\n  prostate)\n\nsummary(lmVWS_IntVW)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi + lcavol:lweight, \n    data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.65886 -0.44673  0.02082  0.50244  1.57457 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)   \n(Intercept)     -0.6430     0.7030  -0.915  0.36278   \nlcavol           1.0046     0.5427   1.851  0.06734 . \nlweight          0.6146     0.1961   3.134  0.00232 **\nsviinvasion      0.6859     0.2114   3.244  0.00164 **\nlcavol:lweight  -0.1246     0.1478  -0.843  0.40156   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7179 on 92 degrees of freedom\nMultiple R-squared:  0.6293,\tAdjusted R-squared:  0.6132 \nF-statistic: 39.05 on 4 and 92 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in fun(libname, pkgname): no display name and no $DISPLAY environment\nvariable\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Interaction between two factors?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkpna2 <- read_tsv(\"https://raw.githubusercontent.com/statOmics/SGA21/master/data/kpna2.txt\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 24 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \"\\t\"\ndbl (3): grade, node, gene\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nkpna2 <- kpna2 |>\n  mutate(\n    grade = as.factor(grade),\n    node = as.factor(node),\n    node = fct_recode(node, Unaffected = \"0\", Removed = \"1\"),\n    log2gene = log2(gene)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(kpna2, aes(x = grade, y = gene, fill = node)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = position_jitterdodge(), shape = 21, size = 2) +\n  labs(\n    x = \"Histologic grade\", y = \"KPNA2 expression\",\n    fill = \"Lymph node status\"\n  ) +\n  ggtitle(\"KPNA2 gene expression in breast cancer patients\")\n```\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(kpna2, aes(x = grade, y = log2gene, fill = node)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = position_jitterdodge(), shape = 21, size = 2) +\n  labs(\n    x = \"Histologic grade\", y = \"KPNA2 log2 expression\",\n    fill = \"Lymph node status\"\n  ) +\n  ggtitle(\"KPNA2 gene expression in breast cancer patients\")\n```\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(log2(gene) ~ grade * node, data = kpna2)\nExploreModelMatrix::VisualizeDesign(kpna2, ~ grade * node)$plotlist[[1]]\n```\n\n::: {.cell-output-display}\n![](08-wrapup-puromycin_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n",
    "supporting": [
      "08-wrapup-puromycin_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}