{
  "hash": "e6f4ff633dd1fac96eb45fe36786153e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"8.4. Multiple Regression: KPNA2 example - solution\"\nauthor: \"Lieven Clement and Milan Malfait\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\n---\n\n<a rel=\"license\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png\" /></a>\n\n\n\n\n# Background\n\nHistologic grade in breast cancer (BC) provides clinically important prognostic\ninformation. Researchers examined whether histologic grade was associated with\ngene expression profiles of breast cancers and whether such profiles could be\nused to improve histologic grading. In this tutorial we will assess the\nassociation between histologic grade and the expression of the KPNA2 gene that\nis known to be associated with poor BC prognosis. The patients, however, do not\nonly differ in the histologic grade, but also on their lymph node status.\n\nThe lymph nodes were not affected (0) or surgically removed (1).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nlibrary(multcomp)\n\nlibrary(tidyverse)\n\n## Set default theme for ggplot2\ntheme_set(theme_bw(base_size = 14))\n```\n:::\n\n\n# Data analysis\n\n## Import KPNA2 data in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkpna2 <- read_table(\"https://raw.githubusercontent.com/statOmics/SGA21/master/data/kpna2.txt\")\nkpna2\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"grade\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"node\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gene\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"3\",\"2\":\"1\",\"3\":\"367.8179\"},{\"1\":\"3\",\"2\":\"1\",\"3\":\"590.3576\"},{\"1\":\"1\",\"2\":\"1\",\"3\":\"346.6583\"},{\"1\":\"1\",\"2\":\"1\",\"3\":\"258.4455\"},{\"1\":\"1\",\"2\":\"0\",\"3\":\"153.8416\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"643.6799\"},{\"1\":\"3\",\"2\":\"1\",\"3\":\"817.8558\"},{\"1\":\"1\",\"2\":\"1\",\"3\":\"329.4113\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"746.4951\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"380.0940\"},{\"1\":\"1\",\"2\":\"0\",\"3\":\"205.2980\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"703.5070\"},{\"1\":\"1\",\"2\":\"0\",\"3\":\"223.5533\"},{\"1\":\"1\",\"2\":\"0\",\"3\":\"186.6673\"},{\"1\":\"1\",\"2\":\"0\",\"3\":\"165.5948\"},{\"1\":\"3\",\"2\":\"1\",\"3\":\"439.0382\"},{\"1\":\"1\",\"2\":\"1\",\"3\":\"252.0597\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"495.8720\"},{\"1\":\"1\",\"2\":\"1\",\"3\":\"286.7907\"},{\"1\":\"3\",\"2\":\"1\",\"3\":\"552.1972\"},{\"1\":\"1\",\"2\":\"1\",\"3\":\"233.5769\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"521.4048\"},{\"1\":\"3\",\"2\":\"1\",\"3\":\"474.2651\"},{\"1\":\"1\",\"2\":\"0\",\"3\":\"148.1059\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Transform the variable grade and node to a factor\n\n::: {.cell}\n\n```{.r .cell-code}\nkpna2 <- kpna2 |>\n  mutate(\n    grade = as.factor(grade),\n    node = as.factor(node),\n    node = fct_recode(node, Unaffected = \"0\", Removed = \"1\")\n  )\nkpna2\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"grade\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"node\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"gene\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"3\",\"2\":\"Removed\",\"3\":\"367.8179\"},{\"1\":\"3\",\"2\":\"Removed\",\"3\":\"590.3576\"},{\"1\":\"1\",\"2\":\"Removed\",\"3\":\"346.6583\"},{\"1\":\"1\",\"2\":\"Removed\",\"3\":\"258.4455\"},{\"1\":\"1\",\"2\":\"Unaffected\",\"3\":\"153.8416\"},{\"1\":\"3\",\"2\":\"Unaffected\",\"3\":\"643.6799\"},{\"1\":\"3\",\"2\":\"Removed\",\"3\":\"817.8558\"},{\"1\":\"1\",\"2\":\"Removed\",\"3\":\"329.4113\"},{\"1\":\"3\",\"2\":\"Unaffected\",\"3\":\"746.4951\"},{\"1\":\"3\",\"2\":\"Unaffected\",\"3\":\"380.0940\"},{\"1\":\"1\",\"2\":\"Unaffected\",\"3\":\"205.2980\"},{\"1\":\"3\",\"2\":\"Unaffected\",\"3\":\"703.5070\"},{\"1\":\"1\",\"2\":\"Unaffected\",\"3\":\"223.5533\"},{\"1\":\"1\",\"2\":\"Unaffected\",\"3\":\"186.6673\"},{\"1\":\"1\",\"2\":\"Unaffected\",\"3\":\"165.5948\"},{\"1\":\"3\",\"2\":\"Removed\",\"3\":\"439.0382\"},{\"1\":\"1\",\"2\":\"Removed\",\"3\":\"252.0597\"},{\"1\":\"3\",\"2\":\"Unaffected\",\"3\":\"495.8720\"},{\"1\":\"1\",\"2\":\"Removed\",\"3\":\"286.7907\"},{\"1\":\"3\",\"2\":\"Removed\",\"3\":\"552.1972\"},{\"1\":\"1\",\"2\":\"Removed\",\"3\":\"233.5769\"},{\"1\":\"3\",\"2\":\"Unaffected\",\"3\":\"521.4048\"},{\"1\":\"3\",\"2\":\"Removed\",\"3\":\"474.2651\"},{\"1\":\"1\",\"2\":\"Unaffected\",\"3\":\"148.1059\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Data exploration\n\nHistologic grade and lymph node status can be associated with the kpna2 gene expression. Moreover, it is also possible that the differential expression associated with histological grade is different in patients that have unaffected lymph nodes and patients for which the lymph nodes had to be removed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(kpna2, aes(x = grade, y = gene, fill = node)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = position_jitterdodge(), shape = 21, size = 2) +\n  labs(\n    x = \"Histologic grade\", y = \"KPNA2 expression\",\n    fill = \"Lymph node status\"\n  ) +\n  ggtitle(\"KPNA2 gene expression in breast cancer patients\")\n```\n\n::: {.cell-output-display}\n![](08_4_kpna2_sol_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe plot suggests\n\n- An effect of the histological grade\n- An effect of node status\n- The differential expression associated to grade seems to differ according to the lymph node status (interaction)\n- Mean variance relation?\n\n## Model\n\nHistologic grade and lymph node status can be associated with the kpna2 gene expression. Moreover, it is also possible that the differential expression associated with histological grade is different in patients that have unaffected lymph nodes and patients for which the lymph nodes had to be removed. Hence, we will have to model the gene expression by using main effects for grade, node and a grade x node interaction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model with main effects for histological grade and node and grade x node interaction\nfit <- lm(gene ~ grade * node, data = kpna2)\n\npar(mfrow = c(2, 2))\nplot(fit)\n```\n\n::: {.cell-output-display}\n![](08_4_kpna2_sol_files/figure-html/unnamed-chunk-5-1.png){width=1152}\n:::\n:::\n\n\nThe variance seems to increase with the mean, i.e. the residuals do not seem to\nbe **homoscedastic**.  The QQ-plot of the residuals shows deviations from\nnormality or some outliers.\n\nWe will first log2 transform the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(log2(gene) ~ grade * node, data = kpna2)\n\npar(mfrow = c(2, 2))\nplot(fit)\n```\n\n::: {.cell-output-display}\n![](08_4_kpna2_sol_files/figure-html/unnamed-chunk-6-1.png){width=1152}\n:::\n:::\n\n\n- The variance is now more or less equal for every treatment x node combination.\n- The QQ-plot of the residuals shows no deviations from normality.\n\n\n## Inference\n\nWe perform a **type III ANOVA** to test the interaction effect. Note that we use\nthe `Anova()` function (with capital A) from the **car** package here. This\nfunction allows to test type-II and type-III tests. The default `anova()` from\nbase R only performs type-I tests.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Anova from car package, make sure it's loaded with `library(car)`\nanova_res <- Anova(fit, type = \"III\")\nanova_res\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Sum Sq\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"335.6676323\",\"2\":\"1\",\"3\":\"3351.610907\",\"4\":\"9.530118e-24\",\"_rn_\":\"(Intercept)\"},{\"1\":\"8.3420526\",\"2\":\"1\",\"3\":\"83.294639\",\"4\":\"1.437549e-08\",\"_rn_\":\"grade\"},{\"1\":\"1.2978311\",\"2\":\"1\",\"3\":\"12.958726\",\"4\":\"1.789077e-03\",\"_rn_\":\"node\"},{\"1\":\"0.9003583\",\"2\":\"1\",\"3\":\"8.989996\",\"4\":\"7.102512e-03\",\"_rn_\":\"grade:node\"},{\"1\":\"2.0030227\",\"2\":\"20\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe output shows that there is a very significant interaction\n($p=$ 0.0071).\nHence, the association of the histological grade on the gene expression differs\naccording to the lymph node status and vice versa.\n\nThe researchers are therefore interested in studying and reporting on the following hypotheses:\n\n- Is the KPNA2 expression on average different between grade 3 and grade 1 tumors from patients with unaffected lymph nodes (by testing $H_0: \\log_2{FC}_{g3n0-g1n0}=0\\text{ vs }H1: \\log_2{FC}_{g3n0-g1n0}\\neq 0$)\n- Is the KPNA2 expression on average different between grade 3 and grade 1 tumors from patients with affected lymph nodes (by testing $H_0: \\log_2{FC}_{g3n1-g1n1}=0\\text{ vs }H1: \\log_2{FC}_{g3n1-g1n1}\\neq 0$)\n\n- Is the KPNA2 expression on average different in grade 1 tumors of patients with affected and patients with unaffected lymph nodes (by testing $H_0: \\log_2{FC}_{g1n1-g1n0}=0\\text{ vs }H1: \\log_2{FC}_{g1n1-g1n0}\\neq 0$)\n\n- Is the KPNA2 expression on average different in grade 3 tumors of patients with affected and patients with unaffected lymph nodes (by testing $H_0: \\log_2{FC}_{g3n1-g3n0}=0\\text{ vs }H1: \\log_2{FC}_{g3n1-g3n0}\\neq 0$)\n\n- Is the fold change of the KPNA2 gene between grade 3 and grade 1 different according to the lymph node status and vice versa (tested already by assessing the interaction: $H_0: \\log_2{FC}_{g3n0-g1n0}=\\log_2{FC}_{g3n1-g1n1} \\text{ vs }H1:\\log_2{FC}_{g3n0-g1n0}\\neq\\log_2{FC}_{g3n1-g1n1}$).\n\n\n# Interpretation of model parameters and statistical tests\n\n\n::: {.cell}\n\n```{.r .cell-code}\nExploreModelMatrix::VisualizeDesign(kpna2, ~ grade * node)$plotlist[[1]]\n```\n\n::: {.cell-output-display}\n![](08_4_kpna2_sol_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log2(gene) ~ grade * node, data = kpna2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.57694 -0.19857 -0.04079  0.20807  0.64557 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          7.4796     0.1292  57.893  < 2e-16 ***\ngrade3               1.6675     0.1827   9.127 1.44e-08 ***\nnodeRemoved          0.6577     0.1827   3.600  0.00179 ** \ngrade3:nodeRemoved  -0.7748     0.2584  -2.998  0.00710 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3165 on 20 degrees of freedom\nMultiple R-squared:  0.848,\tAdjusted R-squared:  0.8252 \nF-statistic: 37.18 on 3 and 20 DF,  p-value: 2.266e-08\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate confidence intervals for parameters of model\nCIfit <- confint(fit)\n\n# log_2 FC between g3n0-g1n0, g1n1-g1n0\n# and log_2 difference in FC g3n1-g1n1 and FC g3n0-g1n0\nCIfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        2.5 %     97.5 %\n(Intercept)         7.2101125  7.7491128\ngrade3              1.2864076  2.0486691\nnodeRemoved         0.2766005  1.0388620\ngrade3:nodeRemoved -1.3137511 -0.2357505\n```\n\n\n:::\n\n```{.r .cell-code}\n# Transform parameters and the CI back to the original scale\n2^coef(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       (Intercept)             grade3        nodeRemoved grade3:nodeRemoved \n       178.4792627          3.1767209          1.5775997          0.5844896 \n```\n\n\n:::\n\n```{.r .cell-code}\n2^CIfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         2.5 %      97.5 %\n(Intercept)        148.0676336 215.1371400\ngrade3               2.4391992   4.1372414\nnodeRemoved          1.2113372   2.0546063\ngrade3:nodeRemoved   0.4022736   0.8492431\n```\n\n\n:::\n:::\n\n\nWe model the log$_2$-transformed intensities with the following model:\n$$\ny=\\beta_0+\\beta_{g3}x_{g3}+\\beta_{n1}x_{n1}+\\beta_{g3n1}x_{g3}x_{n1},\n$$\n\nwith $\\beta_0$ the intercept, $\\beta_{g3}$ the main effect for grade, $x_{g3}$ a dummy variable for grade which is 0 for the control treatment in the absence of grade and 1 for the treatment with grade, $\\beta_{n1}$ the main effect for node, $x_{n1}$ a dummy variable that is 0 for the measurements of patients with unaffected lymph nodes and 1 for patients for which the lymph nodes were removed and $\\beta_{g3n1}$ the interaction effect between grade and node.\nTo ease the interpretation of the parameters, $\\log_2$ transformed geometric mean intensities are given for each treatment group as well as corresponding contrasts between treatments, which have an interpretation in terms of $\\log_2$ transformed fold changes (FC).\n\n- $\\log_2\\hat{\\mu}_{g1n0}=\\hat\\beta_0$, $\\log_2 \\hat{\\mu}_{g3n0}=\\hat\\beta_0+\\hat\\beta_{g3}$ --> $\\log_2 \\widehat{FC}_{g3n0-g1n0}=\\hat\\beta_{g3}$\n\n- $\\log_2 \\hat{\\mu}_{g1n1}=\\hat\\beta_0+\\hat\\beta_{n1}$, $\\log_2 \\hat {\\mu}_{g3n1}=\\hat\\beta_0+\\hat\\beta_{g3}+\\hat\\beta_{n1}+\\hat\\beta_{g3n1}$ --> $\\log_2 \\widehat{FC}_{g3n1-g1n1}=\\hat \\beta_{g3} +\\hat\\beta_{g3n1}$\n\n- Similarly, $\\log_2 \\widehat{FC}_{g1n1-g1n0}=\\hat\\beta_{n1}$, $\\log_2 \\widehat{FC}_{g3n1-g3n0}=\\hat\\beta_{n1}+\\hat\\beta_{g3n1}$\n\n- $\\log_2\\frac{\\widehat{FC}_{g3n1-g1n1}}{\\widehat{FC}_{g3n0-g1n0}}=\\log_2\\frac{\\widehat{FC}_{g3n1-g3n0}}{\\widehat{FC}_{g1n1-g1n0}}=\\hat\\beta_{g3n1}$\n\nwith $\\log_2\\hat{\\mu}_{g1n0}$, $\\log_2\\hat{\\mu}_{g3n0}$, $\\log_2\\hat {\\mu}_{g1n1}$ and $\\log_2\\hat{\\mu}_{g3n1}$ the estimated mean $\\log_2$ transformed intensity for patients with grade 1 and node 0 status, grade 3 and node 0 status, grade 1 and node 1 status and grade 3 and node 1 status, respectively. With $\\log_2 \\widehat{FC}_{b-a}$ we indicate $\\log_2$ transformed fold change estimates between treatment b and treatment a, i.e. $\\log_2 \\widehat{FC}_{b-a}=\\log_2 \\hat{\\mu}_{b}-\\log_2 \\hat{\\mu}_a=\\log_2 \\frac{\\hat{\\mu}_{b}}{\\hat{\\mu}_{a}}$.\n\nThe model immediately provides statistical tests for assessing the significance of fold changes between grade 3 and grade 1 for patients with unaffected lymph nodes (n=0) $\\log_2 {FC}_{g3n0-g1n0}$,  fold changes between the grade 1-node 1 patients and grade 1- node 0 patients $\\log_2 {FC}_{g1n1-g3n0}$ and for differences in fold change related to histological grade for node 1 patients and node 0 patients. $\\log_2\\frac{{FC}_{g3n1-g1n1}}{{FC}_{g3n0-g1n0}}$, the interaction term.\n\nInterpretation of the model parameters in the model output:\n\n- The geometric mean intensity for grade 1 patients with unaffected lymph nodes equals $\\exp(\\hat \\beta_0)$=\n178.48.\n\t- When lymph nodes are unaffected, the expression is on average 3.18 times higher for patients with histological grade 3 than patients with histological grade 1.\n\t- The gene expression in histological grade 1 patients with affected lymph nodes is on average 1.58 times higher than for grade 1 patients with unaffected lymph nodes.\n- The fold change corresponding to histological grade is on average 1.71 times lower in patients with affected lymph nodes as compared to patients with unaffected lymph node.\n\n\nFor the remaining hypothesis of interest we will have to define contrasts: linear combinations of the model parameters and evaluate the contrasts with the multcomp package.\n\nThe F-test showed an extremely significant association of the node status, hystological grade and/or the interaction between the node status and the grade (p<<0.001).\n\n# Assessing the significance of all hypothesis of interest\n\nWe can assess all contrasts of interest using the multcomp package. This will also allow us to correct for multiple testing, since we assess multiple hypotheses to answer the relevant research question.\n\n\n- $H_0: \\log_2{FC}_{g3n0-g1n0}= \\beta_{g3}=0$ $\\rightarrow$ \"grade3 = 0\"\n- $H_0: \\log_2{FC}_{g3n1-g1n1}= \\beta_{g3} + \\hat\\beta_{g3n1}=0$ $\\rightarrow$ \"grade3+grade3:nodeRemoved = 0\"\n- $H_0: \\log_2{FC}_{g1n1-g1n0}= \\beta_{n1}$  $\\rightarrow$ \"nodeRemoved = 0\"\n- $H_0: \\log_2{FC}_{g3n1-g3n0}= \\beta_{n1} + \\hat\\beta_{g3n1}=0$ $\\rightarrow$ \"nodeRemoved+grade3:nodeRemoved = 0\"\n- $H_0: \\log_2{FC}_{g3n1-g1n1} - \\log_2{FC}_{g3n0-g1n0} = \\hat\\beta_{g3n1}=0$, note that the latter hypothesis is also equivalent to $H_0: \\log_2{FC}_{g3n1-g3n0} - \\log_2{FC}_{g1n1-g1n0} = \\hat\\beta_{g3n1}=0$ $\\rightarrow$ \"grade3:nodeRemoved = 0\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## glht() function from the multcomp package\nfitGlht <- glht(fit,\n  linfct = c(\n    \"grade3 = 0\",\n    \"grade3+grade3:nodeRemoved = 0\",\n    \"nodeRemoved = 0\",\n    \"nodeRemoved+grade3:nodeRemoved = 0\",\n    \"grade3:nodeRemoved = 0\"\n  )\n)\n\nsummary(fitGlht)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nFit: lm(formula = log2(gene) ~ grade * node, data = kpna2)\n\nLinear Hypotheses:\n                                      Estimate Std. Error t value Pr(>|t|)    \ngrade3 == 0                             1.6675     0.1827   9.127  < 0.001 ***\ngrade3 + grade3:nodeRemoved == 0        0.8928     0.1827   4.886  < 0.001 ***\nnodeRemoved == 0                        0.6577     0.1827   3.600  0.00717 ** \nnodeRemoved + grade3:nodeRemoved == 0  -0.1170     0.1827  -0.640  0.89821    \ngrade3:nodeRemoved == 0                -0.7748     0.2584  -2.998  0.02650 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(fitGlht)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nFit: lm(formula = log2(gene) ~ grade * node, data = kpna2)\n\nQuantile = 2.6968\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                                      Estimate lwr      upr     \ngrade3 == 0                            1.66754  1.17481  2.16027\ngrade3 + grade3:nodeRemoved == 0       0.89279  0.40006  1.38552\nnodeRemoved == 0                       0.65773  0.16500  1.15046\nnodeRemoved + grade3:nodeRemoved == 0 -0.11702 -0.60975  0.37571\ngrade3:nodeRemoved == 0               -0.77475 -1.47158 -0.07792\n```\n\n\n:::\n\n```{.r .cell-code}\n2^confint(fitGlht)$confint\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                  Estimate       lwr       upr\ngrade3                           3.1767209 2.2578915 4.4694600\ngrade3 + grade3:nodeRemoved      1.8567602 1.3197140 2.6123528\nnodeRemoved                      1.5775997 1.1212975 2.2195903\nnodeRemoved + grade3:nodeRemoved 0.9220906 0.6553867 1.2973274\ngrade3:nodeRemoved               0.5844896 0.3606474 0.9472632\nattr(,\"conf.level\")\n[1] 0.95\nattr(,\"calpha\")\n[1] 2.695838\n```\n\n\n:::\n:::\n\n\n# Conclusion\n\n- There is an extremely significant association between the KPNA2 expression and hystological grade in patients with unaffected as well as in patients with affected lymph nodes (both $p<<0.001$).\n  When lymph nodes are unaffected, the expression is on average 3.18 times higher for patients with histological grade 3 than patients with histological grade 1 (95% CI [2.26, 4.47]).\n  For patients with affected lymph nodes the expression is on average 1.86 times higher for patients with histological grade 3 tumors than patients with histological grade 1 tumors (95% CI [1.32, 2.61]).\n\n- The association between the KPNA2 expression with the lymph node status in grade 1 patients is very significant ($p=$ 0.007).\nThe KPNA2 expression in histological grade 1 patients with affected lymph nodes is on average 1.58 times higher than for grade 1 patients with unaffected lymph nodes (95% CI [1.12, 2.22]).\nIn grade 3 patients, however, this association is not significant ($p=$ 0.9, 95% CI [0.66, 1.3] ).\n\n- There is also a significant interaction between the hystological grade and the lymph node status. So the association between the KPNA2 expression and the histological grade depends on the lymph node status and vice versa ($p=$ 0.027). The fold change corresponding to histological grade is on average 1.71 times lower in patients with affected lymph nodes as compared to patients with unaffected lymph node (95% CI [1.06, 2.77]). (Similarly, the fold change corresponding to the node status is on average 1.71 times lower in patients with grade 3 tumors as compared to patients with grade 1 tumors, 95% CI [1.06, 2.77])\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}