{
  "hash": "ad1cf145331ea1bdaab0d528ab9b27f7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"5. Statistical Inference\"\nauthor: \"Lieven Clement\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html: default\n  pdf: default\n---\n\n<a rel=\"license\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png\" /></a>\n\n\n\n\n\n\n# Introduction\n## Population\n\n- The aim of a scientific study is to draw conclusions on the general population.\n\n- Here, we study the effect of captopril on the blood pressure of patients with hypertension.\n\n- We will collect data and we will model the data\n\n- Therefore, we always have to translate the research question into an effect size that can be estimated with a model parameter or a combination of model parameters.\n\n- e.g. the population mean\n   $$E(X)=\\mu$$\n\n- Does the blood pressure decreases on average after administering captopril to patients with hypertension?\n\n---\n\n## Overview\n\n- Experimental Design & Data Exploration\n- Point estimators (Estimation)\n- Interval estimators (Statistical inference)\n- Hypothesis tests (Statistical inference)\n\n---\n\n# Experimental Design\n\n- 15 patients were drawn at random from the population of patients with hypertension\n- pre-test/post-test design: the systolic and diasystolic blood pressure are measured before and after administering captopril\n- Advantage: we can assess the effect of administering captopril on the blood pressure for each individual patient.\n- Disadvantage?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/pop2Samp2Pop-1.pdf){fig-align='center'}\n:::\n:::\n\n\n---\n\n# Data exploration and Descriptive Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril <- read_csv(\"https://raw.githubusercontent.com/GTPB/PSLS20/master/data/captopril.txt\")\nhead(captopril)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 5\n     id  SBPb  DBPb  SBPa  DBPa\n  <dbl> <dbl> <dbl> <dbl> <dbl>\n1     1   210   130   201   125\n2     2   169   122   165   121\n3     3   187   124   166   121\n4     4   160   104   157   106\n5     5   167   112   147   101\n6     6   176   101   145    85\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(captopril)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       id            SBPb            DBPb            SBPa          DBPa      \n Min.   : 1.0   Min.   :146.0   Min.   : 98.0   Min.   :129   Min.   : 82.0  \n 1st Qu.: 4.5   1st Qu.:163.5   1st Qu.:103.0   1st Qu.:146   1st Qu.: 98.0  \n Median : 8.0   Median :174.0   Median :112.0   Median :157   Median :103.0  \n Mean   : 8.0   Mean   :176.9   Mean   :112.3   Mean   :158   Mean   :103.1  \n 3rd Qu.:11.5   3rd Qu.:192.5   3rd Qu.:121.5   3rd Qu.:168   3rd Qu.:108.0  \n Max.   :15.0   Max.   :210.0   Max.   :130.0   Max.   :201   Max.   :125.0  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril_tidy <- captopril |> gather(type, bp, -id)\ncaptopril_summary <- captopril_tidy |>\n  group_by(type) |>\n  summarize(\n    mean = mean(bp, na.rm = TRUE),\n    sd = sd(bp, na.rm = TRUE),\n    n = n()\n  ) |>\n  mutate(se = sd / sqrt(n))\n  captopril_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 5\n  type   mean    sd     n    se\n  <chr> <dbl> <dbl> <int> <dbl>\n1 DBPa   103.  12.6    15  3.24\n2 DBPb   112.  10.5    15  2.70\n3 SBPa   158   20.0    15  5.16\n4 SBPb   177.  20.6    15  5.31\n```\n\n\n:::\n\n```{.r .cell-code}\ncaptopril_summary |>\n  ggplot(aes(x = type, y = mean)) +\n  geom_bar(stat = \"identity\") +\n  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = .2) +\n  ylim(0, 210) +\n  ylab(\"blood pressure (mmHg)\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- This figure is not informative! It does not show the raw data.\n\nWe see that a lot of the space that was taken by the barplot does not contain data!\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril_tidy |>\n  ggplot(aes(x = type, y = bp)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- This plot would have been informative if the data was gathered on different individuals.\n\n- However, the blood pressures are measured op the same subject!\n\n- We will make a plot by filtering the systolic blood pressures\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril_tidy |>\n  filter(type %in% c(\"SBPa\", \"SBPb\")) |>\n  mutate(type = factor(type, levels = c(\"SBPb\", \"SBPa\"))) |>\n  ggplot(aes(x = type, y = bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- We have paired data. So we might estimate the effect of the treatment directly by comparing the blood pressure after treatment to the blood pressure before the treatment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril$deltaSBP <- captopril$SBPa - captopril$SBPb\ncaptopril |>\n  ggplot(aes(x = \"Systolic blood pressure\", y = deltaSBP)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\") +\n  ylab(\"Difference (mm mercury)\") +\n  xlab(\"\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril |>\n  summarize(\n    mean = mean(deltaSBP, na.rm = TRUE),\n    sd = sd(deltaSBP, na.rm = TRUE),\n    n = n()\n  ) |>\n  mutate(se = sd / sqrt(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 4\n   mean    sd     n    se\n  <dbl> <dbl> <int> <dbl>\n1 -18.9  9.03    15  2.33\n```\n\n\n:::\n:::\n\n\n\n- Pre-test/post-test design: Effect of captopril in sample using  $X=\\Delta_\\text{after-before}$!\n\n- How will we model $X=\\Delta_\\text{after-na}$ and estimate the effect of captopril?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril |>\n  ggplot(aes(sample = deltaSBP)) +\n  stat_qq() +\n  stat_qq_line()\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe systolic blood pressure differences are approximately normally distributed.\n\n---\n\n# Estimation\n\n\n- No substantial deviations from normality\n\n- We can assume that the differences  $X \\sim N(\\mu, \\sigma^2)$.\n\n- Effect of captopril in the population is captured by the average blood pressure difference $\\mu$.\n\n- The average blood pressure $\\mu$ in the population can be estimated using the sample mean $\\bar x$=-18.93\n\n- The standard deviation $\\sigma$ with the sample standard deviation $\\text{S}$=9.03.\n\n- Is the effect that we observe in the sample large enough to conclude that there is an effect of the captopril treatment on the blood pressure at population level?\n\n- Our estimates will change from sample to sample!\n\n- How are the estimators $\\bar X$ and $S$ distributed?\n\n\n## Point estimator the sample mean\n\n- Suppose that $X$ is a random sample from the population and assume that $X \\sim N(\\mu,\\sigma^2)$\n\n- Estimate $\\mu$ based on sample $X_1,...,X_n$, using the sample mean\n  $$\\bar X = \\frac{X_1+ X_2+ ... + X_n}{n} = \\frac{\\sum_{i=1}^{n} X_i}{n}$$ of random variables $X_1,X_2, ..., X_n$.\n\n- Sample mean $\\bar X$ is a random variable that varies from sample to sample\n\n- Study the theoretical distribution of the sample mean to get insight\n\n    1. in how the sample mean can vary in a new similar study\n    2. how far $\\bar X$ can be from the population mean $\\mu$\n\n---\n\n### Overview\n\n1. The sample mean is unbiased\n2. Precision of sample mean\n3. Distribution of sample mean\n\n---\n\n### The sample mean is unbiased\n\n- We can generalize our observations based on the sample towards the population if the estimate is good approximation of the population value.\n\n- A representative sample is required to generalize the results from the sample towards the population\n\n- Avoid bias (so that the population mean is not systematically under or overestimated)\n\n- Report how the sample is taken!\n\n- Randomisation!\n\n- Draw the subjects at random from population so every subject has the same probability to end up in the sample.\n\n- Subjects with hypertension are sampled at random from the population\n\n\n- Simple random sample:  $X_1,...,X_n$ for characteristic $X$\n\n- $X_1,...,X_n$ have same distribution\n- They have same mean $\\mu$ and variance $\\sigma^2$\n\n- $E(X_1)=...=E(X_n)=\\mu$ and $\\text{Var}(X_1)=...=\\text{Var}(X_n)=\\sigma^2$\n\n- $\\bar X$ is an *unbiased estimator* for $\\mu$\n\n<details><summary>Click to see proof</summary><p>\n\\begin{eqnarray*}\nE(\\bar X) &=& E \\left(\\frac{X_1+ X_2+ ... + X_n}{n}\\right) \\\\\n&= & \\frac{E(X_1)+ E(X_2)+ ... + E(X_n)}{n} \\\\\n&=& \\frac{\\mu + \\mu + ... +\\mu}{n} \\\\\n&= & \\mu\n\\end{eqnarray*}\n</p></details>\n\n---\n\n### Imprecision/standard error\n\n- Also for representative samples the results are imprecise.\n\\vspace{10pt}\n- Different samples from the same population give different results.\n\n- We illustrated this by using the NHANES\n\n    - We will draw 15 females at random from the NHANES study and we will register their log2 direct cholesterol values\n    - We repeat this 50 times to assess the variation from sample to sample\n    - We will plot the boxplot for each sample and will indicate the mean\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\n\nfem <- NHANES |>\n  filter(Gender == \"female\" & !is.na(DirectChol)) |>\n  select(\"DirectChol\")\n\nn <- 15 # number of subjects per sample\nnSim <- 50 # number of simulations\n\nfemSamp <- matrix(nrow = n, ncol = nSim)\nfor (j in 1:nSim) {\n  femSamp[, j] <- sample(fem$DirectChol, 15)\n  if (j < 4) {\n    p <- data.frame(log2(femSamp)) |>\n      gather(key = \"sample\", value = \"log2cholesterol\") |>\n      ggplot(aes(x = sample, y = log2cholesterol)) +\n      geom_boxplot(na.rm = TRUE) +\n      stat_summary(\n        fun = mean, geom = \"point\",\n        size = 3, color = \"red\", na.rm = TRUE\n      ) +\n      geom_hline(yintercept = mean(fem$DirectChol |> log2())) +\n      ylab(\"cholesterol (log2)\")\n    print(p)\n  }\n}\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-9-2.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-9-3.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndata.frame(log2(femSamp)) |>\n  gather(key = \"sample\", value = \"log2cholesterol\") |>\n  ggplot(aes(x = sample, y = log2cholesterol)) +\n  geom_boxplot() +\n  stat_summary(\n    fun = mean, geom = \"point\",\n    size = 3, color = \"red\", na.rm = TRUE\n  ) +\n  geom_hline(yintercept = mean(fem$DirectChol |> log2())) +\n  ylab(\"cholesterol (log2)\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-9-4.pdf){fig-pos='H'}\n:::\n:::\n\n\nWe observe that the mean nicely fluctuates around the population mean.\n\nCopy the code, increase the sample size to 100 subjects and observe what happens!\n\n---\n\n### How to do this based on a single sample?\n\n- Insight in how close we can expect $\\bar X$ to $\\mu$?\n\n- How varies $\\bar X$ from sample to sample?\n\n- Variability on $\\bar X$\n\n- We have to determine this based on a single sample!\n\n- We need to make assumptions\n\n- We assume that the random variables $X_1, X_2, ..., X_n$ originate from $n$ *independent* subjects.\n\n- For the captopril study we had dependent observations.\n\n    - Blood pressure measurements before ($Y_{i,before}$) and  after ($Y_{i,after}$) administering captopril for the same subject $i=1,\\ldots,n$.\n    - We turned them into n independent measurements by taking the difference $Y_{i,after}-Y_{i,before}$\n\n---\n\n### Variance estimator for $\\bar X$\n\n$$\\sigma^2_{\\bar X}=\\frac{\\sigma^2}{n}$$\n\n- The standard deviation of $\\bar X$ around $\\mu$ is $\\sqrt{n}$ times smaller that the deviation around the original observations $X$.\n\n- The more observations we have the more precise $\\bar X$.\n\n\n<details><summary>Click to see proof</summary><p>\n\\begin{eqnarray*}\n\\text{Var}(\\bar X)&=&\\text{Var} \\left(\\frac{X_1+ X_2+ ... + X_n}{n}\\right) \\\\\n&= & \\frac{\\text{Var} (X_1+ X_2+ ... + X_n)}{n^2} \\\\\n&\\overset{*}{=} & \\frac{\\text{Var}(X_1)+ \\text{Var}(X_2)+ ... + \\text{Var}(X_n)}{n^2} \\\\\n&=& \\frac{\\sigma^2 + \\sigma^2 + ... \\sigma^2}{n^2} \\\\\n&= & \\frac{\\sigma^2}{n}.\n\\end{eqnarray*}\n\n- (*) this is based on the assumption of independence.\n$$\\text{Var}[X_1 + X_2] = \\text{Var}[X_1] + \\text{Var}[X_2] + 2 \\text{Covar}[X_1,X_2]$$\n\n    - With $Covar[X_1,X_2]=0$ when $X_1$ and $X_2$ are independent.\n</p></details>\n\n**Definition: standard error**\n\nThe standard deviation of $\\bar{X}$ is $\\sigma/\\sqrt{n}$ and is also referred to as the **standard error** of the mean.\nGenerally one refers to the standard deviation of an estimator for a particular parameter $\\theta$ with the term **standard error** of the estimator, which is denoted as $SE$.\n\n---\n\n### Captopril example\n\n\n- $n = 15$ differences in systolic blood pressure\n\n- Suppose that the standard deviation of the blood pressure differences in the population is $\\sigma = 9.0$ mmHg\n\n- Then, the standard error (SE) on the average systolic blood pressure differs $\\bar X$ becomes:\n\n$$\nSE= \\frac{9.0}{\\sqrt{15}}=2.32\\text{mmHg.}\n$$\n\n- Generally $\\sigma$, and thus the SE on the sample mean are unknown.\n- So we also have to estimate the standard deviation of the sample to obtain the standard error\n- Estimator: $SE=S/\\sqrt{n},$\n- with $S^2$ the sample variance of $X_1,...,X_n$  and $S$ the sample standard deviation\n\n- For the captopril example we obtain:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(captopril$deltaSBP)\nse <- sd(captopril$deltaSBP) / sqrt(n)\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.330883\n```\n\n\n:::\n:::\n\n\n---\n\n### Standard deviation vs standard error\n\n#### Illustrate via repeated sampling\n\n- Different sample sizes: 10, 50, 100\n- Draw 1000 samples per sample size from the NHANES study, for each sample we calculate\n    - The mean\n    - The sample standard deviation\n    - The standard error\n- We make a boxplot of the sample standard deviations and the standard errors for the different sample sizes\n\n- Instead of using a for loop we will use the sapply function which is more efficient. It takes a vector or a list as input and applies a function on each element of the vector or on each list element.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nfemSamp10 <- replicate(1000, sample(fem$DirectChol, size = 10))\nfemSamp50 <- replicate(1000, sample(fem$DirectChol, size = 50))\nfemSamp100 <- replicate(1000, sample(fem$DirectChol, size = 100))\n\n## Calculate log2 and convert to data.frame\nfemSamp10_log2 <- data.frame(log2(femSamp10))\nfemSamp50_log2 <- data.frame(log2(femSamp50))\nfemSamp100_log2 <- data.frame(log2(femSamp100))\n\n## Custom function to calculate summary statistics\ncalculate_stats <- function(x) {\n  x |>\n    gather(sample, log2Chol) |>\n    group_by(sample) |>\n    summarize(\n        median = median(log2Chol, na.rm = TRUE),\n        mean = mean(log2Chol, na.rm = TRUE),\n        sd = sd(log2Chol, na.rm = TRUE),\n        n = n()\n    ) |>\n    mutate(se = sd / sqrt(n))\n}\n\nres <- rbind(\n  calculate_stats(femSamp10_log2),\n  calculate_stats(femSamp50_log2),\n  calculate_stats(femSamp100_log2)\n)\n```\n:::\n\n\n##### Means {-}\n\nWe first illustrate the impact of sample size on the distribution of the means of the different samples\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  ggplot(aes(x = as.factor(n), y = mean)) +\n  geom_boxplot() +\n  ylab(\"Direct cholesterol (log2)\") +\n  xlab(\"sample size\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- Note, that the variation of the sample means indeed reduces as the sample size increases. So the estimation gets more precise with increasing sample size.\n\n---\n\n##### Standard deviation {-}\n\nWe now illustrate the impact of sample size on the distribution of the standard deviation of the different samples\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  ggplot(aes(x = as.factor(n), y = sd)) +\n  geom_boxplot() +\n  ylab(\"standard deviation\") +\n  xlab(\"sample size\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n- The standard deviation remains similar across sample size.\nIt is centred around the same value: the standard deviation in the population. Indeed increasing the sample size does affect the variability in the population!\n\n- Again we see that the variability of the standard deviation reduces with increasing sample size. So the standard deviation can also be estimated more precise with increasing sample size.\n\n---\n\n##### Standard error on the mean {-}\n\nFinally, we illustrate the impact of sample size on the distribution of the standard deviation on the mean of the different samples\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  ggplot(aes(x = as.factor(n), y = se)) +\n  geom_boxplot() +\n  ylab(\"standard error\") +\n  xlab(\"sample size\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- The standard error, the estimator for the precision of the sample mean, however, reduces considerably with increasing sample size again confirming that the estimation of the sample mean gets more precise.\n\n---\n\n### Normally distributed data\n\n- For normally distributed data we have multiple estimators for the population mean $\\mu$ e.g mean and median.\n\n- But, $\\bar{X}$ is the unbiased estimator of $\\mu$ with the smallest standard error\n\n-  $\\bar{X}$ deviates less from the mean $\\mu$ than the median\n\n- We illustrate this for repeated sampling with sample size 10\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 10) |>\n  select(mean, median) |>\n  gather(type, estimate) |>\n  ggplot(aes(x = type, y = estimate)) +\n  geom_boxplot() +\n  geom_hline(yintercept = mean(log2(fem$DirectChol))) +\n  ggtitle(\"10 subjects\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nNext, we compare the distribution of mean and median in repeated samples of sample size 50.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 50) |>\n  select(mean, median) |>\n  gather(type, estimate) |>\n  ggplot(aes(x = type, y = estimate)) +\n  geom_boxplot() +\n  geom_hline(yintercept = mean(log2(fem$DirectChol))) +\n  ggtitle(\"50 subjects\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### Distribution of sample mean\n\n\n- How varies $\\bar X$ from sample to sample?\n- Distribution of $\\bar X$?\n- If $\\bar X$ is normally distributed the standard error has a good interpretation: the s.e. is the standard deviation of the sample mean.\n- If the data $X_i$ are normally distributed, the sample mean is also normally distributed.\n\n$$X_i \\sim N(\\mu,\\sigma^2) \\rightarrow  \\bar X \\sim N(\\mu,  \\sigma^2/n)$$\n\n---\n\n#### NHANES: cholesterol\n\nWe illustrate this again with simulation using the NHANES study.\nThe log2 cholesterol levels were normally distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfem |>\n  ggplot(aes(x = DirectChol |> log2())) +\n  geom_histogram(aes(y = ..density.., fill = ..count..)) +\n  xlab(\"Direct cholesterol (log2)\") +\n  stat_function(\n    fun = dnorm, color = \"red\",\n    args = list(mean = mean(log2(fem$DirectChol)), sd = sd(log2(fem$DirectChol)))\n  ) +\n  ggtitle(\"All females in Nhanes study\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nfem |>\n  ggplot(aes(sample = log2(DirectChol))) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"All females in Nhanes study\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-17-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n---\n\n##### Evaluate distribution for samples with 5 subjects {-}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nfemSamp5 <- replicate(1000, sample(fem$DirectChol, size = 5))\nfemSamp5_log2 <- data.frame(log2(femSamp5))\n\nfemSamp5_log2 |>\n  ggplot(aes(x = X1)) +\n  geom_histogram(aes(y = ..density.., fill = ..count..), bins = 10) +\n  xlab(\"Direct cholesterol (log2)\") +\n  stat_function(\n    fun = dnorm, color = \"red\",\n    args = list(mean = mean(femSamp5_log2$X1), sd = sd(femSamp5_log2$X1))\n  ) +\n  ggtitle(\"5 random females\") +\n  xlim(range(log2(fem$DirectChol)))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-18-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nfemSamp5_means <- colMeans(femSamp5_log2)\nggplot(data.frame(means = femSamp5_means), aes(x = means)) +\n  geom_histogram(aes(y = ..density.., fill = ..count..), bins = 15) +\n  xlab(\"Mean cholesterol (log2)\") +\n  stat_function(\n    fun = dnorm, color = \"red\",\n    args = list(mean = mean(femSamp5_means), sd = sd(femSamp5_means))\n  ) +\n  ggtitle(\"Means on 5 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-18-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndata.frame(means = femSamp5_means) |>\n  ggplot(aes(sample = means)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 5 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-18-3.pdf){fig-pos='H'}\n:::\n:::\n\n\n---\n\n##### Explore the distribution of the mean for samples of size 10 {-}\n\nNow we explore the results for the sample size of 10.\n\nWe first illustrate the plot for the first sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfemSamp10_log2 |>\n  ggplot(aes(x = X1)) +\n  geom_histogram(aes(y = ..density.., fill = ..count..), binwidth = 0.5) +\n  xlab(\"Direct cholesterol (log2)\") +\n  stat_function(\n    fun = dnorm, color = \"red\",\n    args = list(mean = mean(femSamp10_log2$X1), sd = sd(femSamp10_log2$X1))\n  ) +\n  ggtitle(\"10 random females\") +\n  xlim(range(log2(fem$DirectChol)))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nNext we look at the distribution of the sample mean over 1000 samples of sample size 10.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfemSamp10_means <- colMeans(femSamp10_log2)\nggplot(data.frame(means = femSamp10_means), aes(x = means)) +\n  geom_histogram(aes(y = ..density.., fill = ..count..), bins = 15) +\n  xlab(\"Mean cholesterol (log2)\") +\n  stat_function(\n    fun = dnorm, color = \"red\",\n    args = list(mean = mean(femSamp10_means), sd = sd(femSamp10_means))\n  ) +\n  ggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-20-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndata.frame(means = femSamp10_means) |>\n  ggplot(aes(sample = means)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-20-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n**So we confirmed that the mean is approximately normally distributed for studies with 5 and 10 females when the original data are approximately normally distributed.**\n\n---\n\n#### Captopril study\n\n- For Captopril study the systolic blood pressure differences are approximatively normally distributed.\n\n- s.e.= 2.32 mm Hg\n\n- In 95 out of 100 studies with n = 15 subjects we expect the sample mean of the systolic blood pressure differences ($\\bar X$) on less then $2 \\times 2.32 = 4.64$mm Hg of the real population mean of the blood pressure differences ($\\mu$).\n\n---\n\n### Non-normally distributed data\n\n- When individual observations do not have a normal distribution,   $\\bar X$ is still \\textit{approximately} Normally distributed\nwhen the number observations are large enough.\n\n- How large does the sample needs to be for the Normal approximation to work?\n\n- This depends on the skewness of the distribution!\n\n---\n\n#### NHANES: cholesterol {-}\n\n- When can evaluated this in the NHanes study if we do not log2 transform the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(fem, aes(x = DirectChol)) +\n  geom_histogram(aes(y = ..density.., fill = ..count..)) +\n  xlab(\"Direct cholesterol\") +\n  stat_function(\n    fun = dnorm, color = \"red\",\n    args = list(mean = mean(fem$DirectChol), sd = sd(fem$DirectChol))) +\n  ggtitle(\"All females in Nhanes study\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nggplot(fem, aes(sample = DirectChol)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"All females in Nhanes study\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-21-2.pdf){fig-pos='H'}\n:::\n:::\n\n\nThe cholesterol data is clearly non-Normally distributed.\n\n##### Distribution of the sample mean for different sample sizes {-}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Calculating the means of the simulated samples WITHOUT first log2-transforming\nfemSamp5_means <- colMeans(femSamp5)\nfemSamp10_means <- colMeans(femSamp10)\nfemSamp50_means <- colMeans(femSamp50)\nfemSamp100_means <- colMeans(femSamp100)\n\nggplot(data.frame(means = femSamp5_means), aes(x = means)) +\n  geom_histogram(aes(y = ..density.., fill = ..count..), bins = 15) +\n  xlab(\"Mean cholesterol (log2)\") +\n  stat_function(\n    fun = dnorm, color = \"red\",\n    args = list(mean = mean(femSamp5_means), sd = sd(femSamp5_means))\n  ) +\n  ggtitle(\"Means on 5 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-22-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndata.frame(means = femSamp5_means) |>\n  ggplot(aes(sample = means)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 5 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-22-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nggplot(data.frame(means = femSamp10_means), aes(x = means)) +\n  geom_histogram(aes(y = ..density.., fill = ..count..), bins = 15) +\n  xlab(\"Mean cholesterol (log2)\") +\n  stat_function(\n    fun = dnorm, color = \"red\",\n    args = list(mean = mean(femSamp10_means), sd = sd(femSamp10_means))\n  ) +\n  ggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-22-3.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndata.frame(means = femSamp10_means) |>\n  ggplot(aes(sample = means)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 10 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-22-4.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndata.frame(means = femSamp50_means) |>\n  ggplot(aes(sample = means)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 50 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-22-5.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndata.frame(means = femSamp100_means) |>\n  ggplot(aes(sample = means)) +\n  stat_qq() +\n  stat_qq_line() +\n  ggtitle(\"Means on 100 females\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-22-6.pdf){fig-pos='H'}\n:::\n:::\n\n\n- **We observe that when the data are not normally distributed the distribution of the sample mean is not normally distributed in small samples**\n\n- **For large samples, however, the sample mean of non normal data is still approximately normally distributed.**\n\n---\n\n### Central Limit Theorem\n\nLet $X_1, \\ldots, X_n$ are sequence of random variables that are drawn independently from the same distribution (population).\nAs long as the sample size n is sufficiently large, the sample mean $\\bar X$ is approximately normally distributed, irrespective of the distribution of the observations $X_i$.\n\n### Overview on the distribution of the mean\n\nhttps://www.nature.com/articles/nmeth.2613.pdf\n\n---\n\n# Interval estimators\n\n- $\\bar X$ varies around $\\mu$\n\n- Here we will develop an interval around $\\bar X$ that will contain the value of $\\mu$ with a probability of 95% for a random sample.\n\n- We first assume $\\sigma^2$ to be known and we will later relax this assumption.\n\n---\n\n## Normally distributed data with known variance\n\n- $X\\sim N(\\mu,\\sigma^2) \\rightarrow \\bar X\\sim N\\left(\\mu,\\frac{\\sigma^2}{n}\\right)$\n\n- 95% reference-interval for sample mean\n\n$$\n\\left[\\mu - 1.96 \\frac{\\sigma}{\\sqrt{n}},\\mu + 1.96 \\frac{\\sigma}{\\sqrt{n}}%\n\\right]\n$$\n\n- The interval contains the sample mean of a random sample with a probability of 95%.\n\n- We can not calculate it because $\\mu$ is unknown.\n\n- Estimate $\\mu$ by $\\bar X$.\n$$\n\\left[\\bar X - 1.96 \\frac{\\sigma}{\\sqrt{n}},\\bar X + 1.96 \\frac{\\sigma}{\\sqrt{n}}\\right]\n$$\n\n\n- More useful interpretation:\n\\vspace{15pt}\n- Rewrite $\\mu - 1.96 \\ \\sigma/\\sqrt{n} < \\bar{X}$ as $\\mu < \\bar{X} + 1.96 \\ \\sigma/\\sqrt{n}$.\n\nSo that we can write\n\\begin{eqnarray*}\n95\\% &=& P( \\mu - 1.96 \\ \\sigma/\\sqrt{n} < \\bar{X} < \\mu + 1.96 \\ \\sigma/\\sqrt{n} ) \\\\\n&=&P( \\bar{X} - 1.96 \\ \\sigma/\\sqrt{n} < \\mu < \\bar{X} + 1.96 \\ \\sigma/\\sqrt{n} )\n\\end{eqnarray*}\n\n---\n\n**Definition of 95% confidence interval on mean**\nFor a random sample, the interval\n$$\n[\\bar{X} - 1.96 \\ \\sigma/\\sqrt{n} , \\bar{X} + 1.96 \\ \\sigma/\\sqrt{n} ],\n$$\ncontains the population mean $\\mu$ with a probability of 95%.\n\n---\n\n- The probability that the CI for a random sample contains the population parameter $\\mu$, i.e. 95%, is also referred to as the **confidence level**.\n\n- Note, that the lower and upper limit of the interval are also random variables that vary from sample to sample. Different samples indeed result in different confidence intervals because they are based on different observation.\n\n- So they are *stochastic intervals*\n\n- 95% of the samples will produce a 95% confidence interval that will contain the population mean $\\mu$. The remaining 5% will produce intervals that do not contain the population mean.\n\n- Based on one interval you cannot conclude that it contains the real population parameter, because its value is unknown.\n\nGenerally the standard deviation is unknown and has to be estimated e.g. by $S$\n\n- For large $n$ $[\\bar{X} - 1.96 \\ s/\\sqrt{n} , \\bar{X} + 1.96 \\ s/\\sqrt{n} ]$ will contain the population mean with a probability of approximately 95%.\n\n---\n\n### NHANES log2 cholesterol example\n\n#### One sample\n\n::: {.cell}\n\n```{.r .cell-code}\nsamp50 <- sample(fem$DirectChol, 50)\n\nll <- mean(samp50 |> log2()) - 1.96 * sd(samp50 |> log2()) / sqrt(50)\nul <- mean(samp50 |> log2()) + 1.96 * sd(samp50 |> log2()) / sqrt(50)\npopMean <- mean(fem$DirectChol |> log2())\n\nc(ll = ll, ul = ul, popMean = popMean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       ll        ul   popMean \n0.3992544 0.5866900 0.5142563 \n```\n\n\n:::\n:::\n\n\n#### Repeated sampling\n\n::: {.cell}\n\n```{.r .cell-code}\nres$ll <- res$mean - 1.96 * res$se\nres$ul <- res$mean + 1.96 * res$se\nmu <- fem$DirectChol |>\n  log2() |>\n  mean()\nres$inside <- res$ll <= mu & mu <= res$ul\nres$n <- as.factor(res$n)\nres |>\n  group_by(n) |>\n  summarize(coverage = mean(inside)) |>\n  spread(n, coverage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 3\n   `10`  `50` `100`\n  <dbl> <dbl> <dbl>\n1 0.901 0.946 0.953\n```\n\n\n:::\n:::\n\n\n- Note, that the coverage in the samples with 10 observations is too low because we do not account for the uncertainty in the estimation of the standard deviation.\n\n- If we look to the first 20 intervals, 2  out of 20 do not contain the population mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 10) |>\n  slice(1:20) |>\n  ggplot(aes(x = sample, y = mean, color = inside)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = mean - 1.96 * se, ymax = mean + 1.96 * se)) +\n  geom_hline(yintercept = mean(log2(fem$DirectChol))) +\n  ggtitle(\"20 CI for N=10\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-25-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n---\n\n- For large sample sizes (100) the coverage is fine because we can estimate the standard deviation with a relative high precision.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 50) |>\n  slice(1:20) |>\n  ggplot(aes(x = sample, y = mean, color = inside)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = mean - 1.96 * se, ymax = mean + 1.96 * se)) +\n  geom_hline(yintercept = mean(log2(fem$DirectChol))) +\n  ggtitle(\"20 CI for N=50\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-26-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nres |>\n  filter(n == 100) |>\n  slice(1:20) |>\n  ggplot(aes(x = sample, y = mean, color = inside)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = mean - 1.96 * se, ymax = mean + 1.96 * se)) +\n  geom_hline(yintercept = mean(log2(fem$DirectChol))) +\n  ggtitle(\"20 CI for N=100\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-26-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n- What have you observed for the interval width?\n\n---\n\n### Other confidence levels\n\n- We can replace the $z_{2.5\\%}=1.96$ by another quantile of the normal distribution $z_{\\alpha/2}$ to obtain an interval with another confidence level $1-\\alpha$.\n\n- Confidence intervals are not only used for the mean but also for other population parameters.\n\n---\n\n## Unknown variance\n\nIn real examples $\\sigma$ is unknown and estimated based on the sample using the sample standard deviation $S$.\n\n- The previous intervals were a bit to small because they did not account for the uncertainty on the estimation of $S$.\n\n- When $n$ is large, $S$ is close to $\\sigma$.\n\n- Hence, ${(\\bar{X} - \\mu)}/{(S/\\sqrt{n}) }$ is approximately standard normal and\n$$\n\\left[\\bar{X} - z_{\\alpha/2} \\ \\frac{S}{\\sqrt{n}} , \\bar{X} + z_{\\alpha/2} \\\n\\frac{S}{\\sqrt{n}}\\right]\n$$\nis an approximate $(1- \\alpha)100\\%$ CI for $\\mu$.\n\n- For small samples this no longer holds (e.g. n=10)\n\nThe estimation of $S$ introduces additional uncertainty in the standardized value ${(\\bar{X} - \\mu)}/{(S/\\sqrt{n})}$. Its distribution\n\n- is still symmetric but has heavier tails that the normal distribution.\n\n- it depends on $n$ how much heavier the tails are\n\n- is a (Student) $t$-distribution with $n-1$ *degrees of freedom*.\n\n---\n\n### T-distribution\n\nMore formally: Let $X_1, X_2, ..., X_n$ be an independent random sample from a Normal distribution $N(\\mu, \\sigma^2)$, then $(\\bar{X} - \\mu)/(S/\\sqrt{n})$ follows a $t$-distribution with $n-1$ degrees of freedom.\n\nThe density of a t-distribution can be calculated in R using the function `dt`. It has arguments `x` for the quantile and `df` for the degrees of freedom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- seq(-5, 5, .1)\ndensDist <- cbind(grid, dnorm(grid), sapply(c(2, 5, 10), dt, x = grid))\ncolnames(densDist) <- c(\"x\", \"normal\", paste0(\"t\", c(2, 5, 10)))\n\ndensDist |>\n  as.data.frame() |>\n  gather(dist, dens, -x) |>\n  ggplot(aes(x = x, y = dens, color = dist)) +\n  geom_line() +\n  ylab(\"Density\")\n```\n:::\n\n\n\nt-distributions have heavier tails then the normal distribution $\\rightarrow$ larger quantiles so broader intervals for the same confidence level.\n\n- This captures the additional uncertainty for estimating $S$.\n\n- If $n \\rightarrow \\infty$ then $t(df) \\rightarrow N(0,1)$\n\n\n- Quantiles of the $t$-distribution can be calculated in R using `qt`. e.g. 95%, 97.5%, 99.5% quantile for a t-distribution with 14 degrees of freedom:\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(.975, df = 14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.144787\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(c(.95, .975, .995), df = 14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.761310 2.144787 2.976843\n```\n\n\n:::\n:::\n\n\n- These quantiles can be used to calculate 90%, 95% and 99% CI.\n\n- 97.5% quantile 2.14 of a t-distribution with $n-1=14$ degrees of freedom is indeed larger than that of a standard Normal distribution 1.96.\n\n---\n\n### Confidence interval based on the t-distribution\n\nThe $100\\% (1-\\alpha)$ CI for the mean $\\mu$ of a\nNormal distributed random variable $X$ with unknown variance is\n\n$$\n\\left[\\bar{X} - t_{n-1, \\alpha/2} \\frac{s}{\\sqrt{n}} , \\bar{X} + t_{n-1,\n\\alpha/2} \\frac{s}{\\sqrt{n}}\\right]\n$$\n\n- We simply replace the $(1-\\alpha/2)100\\%$ quantile of the Normal distribution by that of the t-distribution with $n-1$ degrees of freedom.\n\n#### Captopril example\n\n\n95% CI for the average blood pressure change becomes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(captopril$deltaSBP) - qt(.975, df = 14) * sd(captopril$deltaSBP) / sqrt(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -23.93258\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(captopril$deltaSBP) + qt(.975, df = 14) * sd(captopril$deltaSBP) / sqrt(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -13.93409\n```\n\n\n:::\n:::\n\n\nThe 99% CI is given by\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(captopril$deltaSBP) - qt(.995, df = 14) * sd(captopril$deltaSBP) / sqrt(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -25.87201\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(captopril$deltaSBP) + qt(.995, df = 14) * sd(captopril$deltaSBP) / sqrt(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -11.99466\n```\n\n\n:::\n:::\n\n\nNote, that zero is outside the interval and that the entire interval is negative indicating that there is on average a large effect by administrating captopril on the blood pressure of patients with hypertension.\n\n---\n\n### Interpretation of the confidence interval\n\n- We will revisit the results for sampling log2 cholesterol levels from the large NHANES study. We first focus on the repeated experiments with sample size 10.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres$n <- as.character(res$n) |> as.double(res$n)\nres$ll <- res$mean - qt(0.975, df = res$n - 1) * res$se\nres$ul <- res$mean + qt(0.975, df = res$n - 1) * res$se\nmu <- fem$DirectChol |>\n  log2() |>\n  mean()\nres$inside <- res$ll <= mu & mu <= res$ul\nres$n <- as.factor(res$n)\nres |>\n  group_by(n) |>\n  summarize(coverage = mean(inside)) |>\n  spread(n, coverage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 3\n   `10`  `50` `100`\n  <dbl> <dbl> <dbl>\n1 0.941 0.948 0.955\n```\n\n\n:::\n:::\n\n\nWe observe that all the coverages of the intervals are now controlled at their nominal 95% confidence level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres |>\n  filter(n == 10) |>\n  slice(1:20) |>\n  ggplot(aes(x = sample, y = mean, color = inside)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = mean - qt(0.975, df = 9) * se, ymax = mean + qt(0.975, df = 9) * se)) +\n  geom_hline(yintercept = mean(log2(fem$DirectChol))) +\n  ggtitle(\"20 CI for N=10\") +\n  ylim(range(fem$DirectChol |> log2()))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-32-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nhttps://www.nature.com/articles/nmeth.2659.pdf\n\n---\n\n## Reporting?\n\n- Always report the uncertainty on the results!\n\n- Conclusions based on a point estimate can be very misleading.\n\n- Upon a statistical analysis we therefore always report confidence intervals\n\n- They are small enough to be informative but almost never misleading\n\n- They form a good trade-off between statistical significance and biological relevance.\n\n- We conclude that the population parameter lays in the interval and know that this statement holds with a probability of 95% for random samples.\n\n### Captopril example\n\nWe conclude that the blood pressure decreases on average with\n18.9mmHg upon administering captopril (95% CI [-23.9,-13.9]mmHg).\n\nBased on these results it is obvious that the treatment causes a strong blood pressure drop for patients with hypertension.\n\n# Hypothesis tests\n\n## Captopril Example:\nResearchers want to assess if the drug captopril decreases the blood pressure for patients with hypertension.\n\n- Is there no/an effect of administering captopril on the systolic blood pressure?\n\n- It is not obvious to draw such conclusions based on a small sample\n\n- It is uncertain if we can generalized the observations in the sample towards the population!\n\n- Is the apparent beneficial effect systematic or random?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril_tidy |>\n  filter(type %in% c(\"SBPa\", \"SBPb\")) |>\n  mutate(type = factor(type, levels = c(\"SBPb\", \"SBPa\"))) |>\n  ggplot(aes(x = type, y = bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-33-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptopril$deltaSBP <- captopril$SBPa - captopril$SBPb\ncaptopril |>\n  ggplot(aes(x = \"Systolic blood pressure\", y = deltaSBP)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\") +\n  ylab(\"Difference (mm mercury)\") +\n  xlab(\"\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-34-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n- The average blood pressure difference $\\bar X$ is a natural basis to base our decision on.\n\n$$\\bar x\\text{=-18.93 (s=9.03, SE=2.33)}$$\n\n- It is not enough that $\\bar{x}< 0$ to conclude that the systolic blood pressure is on average lower upon administrating captopril *at the level of the entire population*.\n\n- To generalize the effect we observe in the sample to the population it has to be sufficiently large.\n\n- But, how large?\n\n---\n\n### Hypothesis tests\n\n- For this purpose statistical hypothesis tests have been developed\n- They give a black/white answer\n- It is almost impossible to read a scientific publication without results of statistical tests.\n- According to the *falsification principle* of Popper we can never prove a hypothesis based on data.\n\n    - Hence we will introduce two hypotheses: a null hypothesis $H_0$ and an alternative hypothesis $H_1$.\n\n    - We will try to falsify the null hypothesis based on the statistical test.\n\n#### Captopril\n\n- Based on the sample we cannot prove that there is an effect of administering captopril ($H_1$ , alternative hypothesis).\n\n- We therefore suppose that there is no effect of captopril.\n\n    - We refer to this as the null hypothesis $H_0$.\n\n    - Falsify (\"try to reject\") the $H_0$.\n\n    - How likely is it to observe an effect that is at least as large as what we have observed in our sample in a novel random sample when  $H_0$ is true?\n\n---\n\n\n#### Permutation test\n\n\n- Under $H_0$ the blood pressure measurements before and after administering captopril are two base line blood pressure measurements for a patient\n\n- Under H$_0$ we can shuffle (permute) the blood pressure measurements for each patient.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptoprilSamp <- captopril\nperm <- sample(c(FALSE, TRUE), 15, replace = TRUE)\ncaptoprilSamp$SBPa[perm] <- captopril$SBPb[perm]\ncaptoprilSamp$SBPb[perm] <- captopril$SBPa[perm]\ncaptoprilSamp$deltaSBP <- captoprilSamp$SBPa - captoprilSamp$SBPb\ncaptoprilSamp |>\n  gather(type, bp, -id) |>\n  filter(type %in% c(\"SBPa\", \"SBPb\")) |>\n  mutate(type = factor(type, levels = c(\"SBPb\", \"SBPa\"))) |>\n  ggplot(aes(x = type, y = bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-35-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  deltaSBP = c(captopril$deltaSBP, captoprilSamp$deltaSBP),\n  shuffled = rep(c(FALSE, TRUE), each = 15)\n  ) |>\n  ggplot(aes(x = shuffled, y = deltaSBP)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\") +\n  stat_summary(fun = mean, geom = \"point\", size = 3, color = \"red\") +\n  ylab(\"Difference (mm mercury)\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-36-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nAnd we permute again\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaptoprilSamp <- captopril\nperm <- sample(c(FALSE, TRUE), 15, replace = TRUE)\ncaptoprilSamp$SBPa[perm] <- captopril$SBPb[perm]\ncaptoprilSamp$SBPb[perm] <- captopril$SBPa[perm]\ncaptoprilSamp$deltaSBP <- captoprilSamp$SBPa - captoprilSamp$SBPb\n\ncaptoprilSamp |>\n  gather(type, bp, -id) |>\n  filter(type %in% c(\"SBPa\", \"SBPb\")) |>\n  mutate(type = factor(type, levels = c(\"SBPb\", \"SBPa\"))) |>\n  ggplot(aes(x = type, y = bp)) +\n  geom_line(aes(group = id)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-37-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndata.frame(\n  deltaSBP = c(captopril$deltaSBP, captoprilSamp$deltaSBP),\n  shuffled = rep(c(FALSE, TRUE), each = 15)\n  ) |>\n  ggplot(aes(x = shuffled, y = deltaSBP)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\") +\n  stat_summary(fun = mean, geom = \"point\", size = 3, color = \"red\") +\n  ylab(\"Difference (mm mercury)\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-37-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n- We will do this 10000 times and we will keep track of the mean.\n- We basically only have to swap the signs of the observed blood pressure differences $x$ when we shuffle.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate a matrix with 15 rows and 10000 columns which consist of -1 and 1\npermH <- sample(c(-1, 1), 150000, replace = TRUE)\ndim(permH) <- c(15, 10000)\n\n# calculate the means for the permuted data\nmuPerm <- colMeans(permH * captopril$deltaSBP)\nmuPerm |>\n  as.data.frame() |>\n  ggplot(aes(x = muPerm)) +\n  geom_histogram() +\n  geom_vline(xintercept = mean(captopril$deltaSBP), col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-38-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- We observe that not one of the means that were obtained under $H_0$ (by permutation) were as extreme as the sample mean we observed in the captopril study.\n\n- So the probability to observe a blood pressure drop that is larger then the one in the captopril study in a random sample generated under the null hypothesis is  smaller then 1 out of 10000.\n\nSo we have strong evidence that $H_0$ is incorrect and we thus we reject it and conclude $H_1$: There is an effect of administering captopril on the blood pressure of patients with hypertension.\n\n---\n\n### Pivot\n\n- In practice we always use statistics that balance the effect size (average difference) to the noise (standard error)\n\n- When we falsify the null hypothesis, we standardize the mean around $\\mu_0=0$ the mean under $H_0$\n\n$$t=\\frac{\\bar X-\\mu_0}{se_{\\bar X}}$$\n\n- for the captopril example this becomes:\n$$\\frac{-18.93-0}{2.33}=-8.12$$\n\n\nWe now determine the null distribution of test statistic t with permutation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeltaPerms <- permH * captopril$deltaSBP\ntPerm <- colMeans(deltaPerms) / (apply(deltaPerms, 2, sd) / sqrt(15))\ntOrig <- mean(captopril$deltaSBP) / sd(captopril$deltaSBP) * sqrt(15)\n\ntPermPlot <- tPerm |>\n  as.data.frame() |>\n  ggplot(aes(x = tPerm)) +\n  geom_histogram(aes(y = ..density.., fill = ..count..)) +\n  geom_vline(xintercept = tOrig, col = \"blue\")\ntPermPlot\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-39-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- Again, none of the permutations gives a t-statistic as extreme as the one observed in the captopril study.\n\nWhen there is no effect of captopril it is nearly impossible to obtain a test statistic as extreme as the one that was observed (  t=-8.12).\n\n- The probability to observe a larger blood pressure drop then the one we observed in our sample in a random sample under $H_0$ is smaller 1/10000.\n\n- We refer to this probability with the *p-value*.\n\n- It measures the strength of the evidence against the null: the smaller the p-value the more evidence we have that the null is not true.\n\n- The distribution has a nice bell shape.\n\n---\n\n### How do we decide?\n\nWhen is the p-value sufficiently small to conclude that there is strong evidence against the null hypothesis?\n\n- We typically work at a significance level of $\\alpha=0.05$\n\n- We state that we conducted the test at the 5% significance level\n\n---\n\n### Permutation tests are computationally demanding\n\n- Can we assess how extreme the blood pressure drop was without permutation?\n\n- We know that the blood pressure differences are approximately Normally distributed, so\n\n$$t=\\frac{\\bar X - \\mu}{se_{\\bar X}}$$\n\nfollows a t-distribution (with 14 df for the captopril example).\n\n\n- Under H$_0$ $\\mu=0$ and $$t=\\frac{\\bar X-0}{se_{\\bar X}}\\sim f_{T,14}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntPermPlot +\n  stat_function(fun = dt, color = \"red\", args = list(df = 14))\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-40-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- Note, the permutation null distribution indeed corresponds to a t-distribution with 14 degrees of freedom.\n\n- So we can conduct the statistical test using statistical modelling of the data.\n\n- We need to make assumptions for this, which we verify in the data exploration phase.\n\n\n---\n\n\n## Hypotheses\n\n<details><summary>Click to see more formal details </summary><p>\n\nTranslate the research question to a null hypothesis ($H_0$) and an alternative hypothesis ($H_1$)\n\nFirst the we need to translate the research question to a parameterized statistical model.\n\n- From the experimental design it follows that  $$X_1,...,X_n \\text{ i.i.d } f(X),$$ with $f(X)$ the density function of blood pressure differences.\n\n- **Simplify**: assume that $f(X)$ is known except for an finite dimensional set of parameters $\\mathbf{\\theta}$ that still has to be estimated (parametric statistic model).\n</p></details>\n\n### Captopril example\n\n<details><summary>Click to see more formal details </summary><p>\n$X \\sim N(\\mu,\\sigma^2)$ with $\\mathbf{\\theta}=(\\mu,\\sigma^2)$, the mean $\\mu$ and variance $\\sigma^2$.\n\nThe research question is now translated in terms of the average blood pressure drop: $\\mu=E_f[X]$.\n\nThe **alternative hypothesis** is formulated in terms of a parameter of $f(X)$ and has to express what the researchers want to prove with the study.\n\n- Here:\n$$H_1: \\mu<0.$$ On average the blood pressure of patients with hypertension decreases upon administering captopril.\n\n\nThe **null hypothesis** generally expresses a null condition, i.e. when notting exceptional happens.\n\n- Researchers typically aim to prove via empirical research that observing the data under the null is highly unlikely so that they can reject the null hypothesis:\n**Falsification principle**.\n\n- The **null hypothesis is typically expressed with the same model parameter as the one used for $H_1$.**\n\n- Here:\n$$H_0 : \\mu=0$$ i.e. on average the systolic blood pressure remains unchanged upon administering captopril.\n\n</p></details>\n\n---\n\n## Test-statistic\n\n<details><summary>Click to see more formal details </summary><p>\n\nOnce the population, the parameters, and, $H_0$ and $H_1$ are determined the concept of hypothesis testing is as follows:\n\n\nConstruct a test statistic so that it\n\n1. measures evidence in the sample,\n\\vspace{10pt}\n2. against the null hypothesis, and\n\\vspace{10pt}\n3. in favour of the alternative hypothesis.\n\nA test statistic thus has to be a function of the observations in the sample.\n\n</p></details>\n\n### Captopril example\n\n<details><summary>Click to see more formal details </summary><p>\n\n$$T=\\frac{\\bar{X}-\\mu_0}{\\text{SE}_{\\bar X}}$$\nWith $\\mu_0=0$ under $H_0$\n\nAgain\n\n- If $H_0$ holds there is no effect of captopril on the blood pressure in the population and then we expect test statistic $T$ close to 0.\n\n- If $H_1$ is true we expect $T<0$.\n\n- In the captopril example we observe $t=(-18.93-0)/2.33=-8.12$.\n\n- Is $t = -8.12$ large enough in absolute value to conclude that  $\\mu < 0$ and with which confidence can we make this conclusion?\n\n- We known that t follows a t-distribution with 14 d.f. under $H_0$\n\n</p></details>\n\n---\n\n## p-value\n\nThe p-value is the probability to balance between $H_0$ and $H_1$.\n\nThe way how we calculate it is context dependent\n\n- For the captopril example we have\n  $$\n    p = P\\left[T \\leq t \\mid H_0\\right] = \\text{P}_0\\left[T\\leq t\\right],\n  $$\nwith the index \"0\" in $\\text{P}_0\\left[.\\right]$ indicates that the probability is calculated under $H_0$.\n\nIt gives the probability to observe a test statistic $T$ lower or equal to the value observed in the current sample in a random sample under $H_0$, \n\n- i.e. a test statistic $T$ in the random sample under $H_0$ with a value that is more extreme, more in the direction of $H_1$ then the one observed in the current sample.\n\n### Captopril example\n\n<details><summary>Click to see more formal details </summary><p>\n\n- The $p$-value for the captopril example is calculated as follows\n  $$p= \\text{P}_0\\left[T\\leq -8.12\\right]=F_t(-8.12;14) = 0.6\\ 10^{-6}.$$\n\n  with $F_t(;14)$ the cumulative distribution function of a t-distribution with 14 degrees of freedom:\n\n$$F_t(x;14)=\\int\\limits_{-\\infty}^{x} f_t(x;14).$$\n\nand $f_t(.;14)$ the density function of the t-distribution.\n\n\n- We calculate this probability in R with `pt(x,df)`\n\n    - the value of the observed test statistic `x` en\n    - the number of degrees of freedom of the t-distribution `df`.\n\n- `pt(x,df)` calculates the probability to observe a value smaller or equal to x when we would draw a random sample from a t-distribution with df degrees of freedom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(captopril$deltaSBP)\nstat <- (mean(captopril$deltaSBP) - 0) / (sd(captopril$deltaSBP) / sqrt(n))\nstat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -8.122816\n```\n\n\n:::\n\n```{.r .cell-code}\npt(stat, n - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.731936e-07\n```\n\n\n:::\n:::\n\n\n</p></details>\n\nIn practice we will not calculate the test ourself, but we will use the function t.test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(captopril$deltaSBP, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  captopril$deltaSBP\nt = -8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean is less than 0\n95 percent confidence interval:\n      -Inf -14.82793\nsample estimates:\nmean of x \n-18.93333 \n```\n\n\n:::\n:::\n\n\nNote, that we need to specify the argument `alternative=\"less\"` so that the p-value would be calculated in the left tail.\n\nThe function also gives a one-sided interval because we test in one direction.\n\n---\n\n### Definition of the p-value\n\nThe **p-value** (also referred to as the **observed significance level**) is the probability to observe a test statistic in a random sample under the null hypothesis that is as or more extreme then the test statistic observed in the current sample.\n\n- The smaller the probability the more evidence against $H_0$.\n\n- Note, that the p-value is **not** the probability that null hypothesis is true!\n\n- The word \"extreme\" indicates on the direction in which the test statistic is more likely under the alternative hypothesis.\n\n- In the example $H_1: \\mu < 0$ and we thus expect very negative values for $t$ under $H_1$.\n\n- From the definition small $p$-values indicate that observed test statistic is unlikely under the assumption that $H_0$ is correct.\n\n- Thus a small value of $p$-value means that we have to **reject  $H_0$** in favour of $H_1$.\n\n- The threshold that we use to compare the $p$-value with is referred to as the **significance level** and is denoted with $\\alpha$.\n\n- A statistical test conducted on the $\\alpha$ significance level is also referred to as a **level-$\\alpha$ test**.\n\nA test result is *statistically significant* if $p<\\alpha$\n\n- $\\alpha$ is commonly set at 5\\%.\n\n- The smaller the p-value the more `significant' the test result deviates from what can be expected under $H_0$.\n\n- It summarizes the evidence against the null.\n\n$$\\begin{array}{cl}>0.10 & \\text{ non significant (no evidence)}\\\\0.05-0.10 & \\text{ marginal significant, weak evidence (do not use this yourself)}\\\\0.01-0.05 & \\text{ significant}\\\\0.001-0.01 & \\text{strongly significant}\\\\<0.001 & \\text{ extremely significant}\\end{array}$$\n\n---\n\n## Critical value\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-43-1.pdf){fig-align='center' width=100%}\n:::\n:::\n\n\n---\n\n## Decision Errors\n\nThe decision to accept or reject $H_0$ is made based on a single sample.\nA wrong decision could have been made.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{ccc}\n\\toprule\n\\multicolumn{1}{c}{ } & \\multicolumn{2}{c}{Reality} \\\\\n\\cmidrule(l{3pt}r{3pt}){2-3}\nConclusion & H0 & H1\\\\\n\\midrule\nAccept H0 & OK & Type II (\\$\\textbackslash{}beta\\$)\\\\\nReject H0 & Type I (\\$\\textbackslash{}alpha\\$) & OK\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n - Type I error, $\\alpha$: wrongly reject the null hypothesis (false positive)\n \\vspace{10pt}\n - Type II error, $\\beta$: wrongly accept the null hypothesis\n\n - Decision is also stochastic! See first chapter of the course\n\n### Captopril Example\n\n- $H_0$: administering captopril has no effect on the systolic blood pressure\n\n- $H_1$: administering captopril an average leads to a decrease in blood pressure\n\n- **Type I error**: there is on average no blood pressure drop upon administering captopril, but we conclude that there is an effect of captopril.\n- **Type II error**: there is on average a blood pressure drop upon administering captopril, but it is not picked up by the statistical test.\n\n---\n\n### Type I error is controlled\n\nThe type I error is controlled by the construction of the statistical test.\n\n$$\\text{P}\\left[\\text{type I error}\\right]=\\text{P}\\left[\\text{reject }H_0 \\mid H_0\\right] = \\text{P}_0\\left[T<t_{n-1;1-\\alpha}\\right]=\\alpha $$\n\n\n- The significance-level $\\alpha$ is the probability to make a type I error.\n\n- The statistical test ensures that the probability on a type I error is controlled at the significance level $\\alpha$.\n\n- The probability to correctly accept $H_0$ is $1-\\alpha$.\n\n- We can show that the p-value under $H_0$ is uniform distributed.\n\n- So statistical hypothesis testing leads to a uniform decision strategy.\n\nWe will illustrate this in a simulation study\n\n- n=15\n- $\\mu=0$ mmHg\n- $\\sigma =9$ mmHg\n- number of simulations 1000\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnsim <- 10000\nn <- 15\nsigma <- 9\nmu <- 0\nmu0 <- 0\nalpha <- 0.05\n\n# simulate nsim samples of size n\ndeltaSim <- matrix(rnorm(n * nsim, mu, sigma), nrow = n, ncol = nsim)\npSim <- apply(deltaSim, 2, function(x, mu, alternative) t.test(x, mu = mu, alternative = alternative)$p.value, mu = mu0, alternative = \"less\")\n\nmean(pSim < alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0471\n```\n\n\n:::\n\n```{.r .cell-code}\npSim |>\n  as.data.frame() |>\n  ggplot(aes(x = pSim)) +\n  geom_histogram() +\n  xlim(0, 1)\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-45-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- The type I error is indeed about 0.05\n- The p-values are uniform\n\n---\n\n### Type II error\n\n- Determine the type II error is less evident.\n- We have to reason under $H_1$\n- In the captopril example is $H_1: \\mu<0$\n- Many alternatives are possible\n- The distribution under $H_1$ is not fully specified\n\n- *work-around:* choose one specific distribution under $H_1$.\n\n $$H_1(\\delta): \\mu=0-\\delta \\text{ for }\\delta>0.$$\n\n- e.g. a blood pressure difference of 2 mmHg\n\n- 1-type II is also referred to as the power. It is the probability to pick up the alternative.\n\n- It is not guaranteed by the design of the test\n\n- It depends on the experimental design of the study\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnsim <- 10000\nn <- 15\nsigma <- 9\nmu <- -2\nmu0 <- 0\nalpha <- 0.05\n\n# simulate nsim samples of size n\ndeltaSim <- matrix(rnorm(n * nsim, mu, sigma), nrow = n, ncol = nsim)\npSim <- apply(deltaSim, 2, function(x, mu, alternative) t.test(x, mu = mu, alternative = alternative)$p.value, mu = mu0, alternative = \"less\")\n\nmean(pSim < alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2026\n```\n\n\n:::\n\n```{.r .cell-code}\npSim |>\n  as.data.frame() |>\n  ggplot(aes(x = pSim)) +\n  geom_histogram() +\n  xlim(0, 1)\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-46-1.pdf){fig-pos='H'}\n:::\n:::\n\n- We observe that a power of 0.2026 or a type II error of 0.7974.\n\n---\n\n- When we increase the sample size\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnsim <- 10000\nn <- 30\nsigma <- 9\nmu <- -2\nmu0 <- 0\nalpha <- 0.05\n\n# simulate nsim samples of size n\ndeltaSim <- matrix(rnorm(n * nsim, mu, sigma), nrow = n, ncol = nsim)\npSim <- apply(deltaSim, 2, function(x, mu, alternative) t.test(x, mu = mu, alternative = alternative)$p.value, mu = mu0, alternative = \"less\")\n\nmean(pSim < alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3221\n```\n\n\n:::\n\n```{.r .cell-code}\npSim |>\n  as.data.frame() |>\n  ggplot(aes(x = pSim)) +\n  geom_histogram() +\n  xlim(0, 1)\n```\n\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-47-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n- Increasing the sample size leads to a higher power.\n- Still the power to pick up such a small blood pressure drop remains very low.\n- A drop of 2 mmHg is also not relevant for drug companies.\n\nhttps://www.nature.com/articles/nmeth.2738.pdf\n\n---\n\n### Interpretation\n\nSuppose that given a particular sample $p<\\alpha$, i.e. reject $H_0$\n\n- Two possibilities\n\n    - correct decision,\n\t  - or type I error.\n\n- We known that the probability on a type error is low, i.e. $\\alpha=0.05$.\n\n\nOn the other hand, when $p\\geq\\alpha$ and we do not reject $H_0$ we also have two options:\n\n  - Correct decision,\n  - or we made a type II error.\n\nThe probability on a type II error ($\\beta$) is not controlled at a specific value.\n\nStatistical test is constructed to only control the probability on a type I error at  $\\alpha$.\n\nTo be scientifically correct we have to take a pessimistic attitude and we have to admit that $\\beta$ can be large (i.e. a small power to detect the alternative).\n\nHence,\n\n- $p < \\alpha$ we reject $H_0$\n\n    - We conclude that $H_1$ is probably correct.\n\t  - We refer to this as a strong conclusion.\n\n- $p \\geq \\alpha$ accept $H_0$\n\n  - Does not imply that we accept $H_0$ correctly.\n  - We can only conclude that the data do not have enough evidence against the $H_0$ in favour of $H_1$.\n  - We refer to this as a weak conclusion.\n  - We typically conclude that the effect of the treatment is not significant.\n\n---\n\n## Conclusions captopril example\n\nThe test we have performed is referred to as\n\n- the **one sample t-test** on the difference or\n\n- a **paired t-test**. Indeed we dispose of paired observations for each patient!\n\n- The test is done one-sided because we test against the alternative of a blood pressure drop.\n\n- Both tests (one sample t-test on the difference and paired t-test) give the same results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(captopril$deltaSBP, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  captopril$deltaSBP\nt = -8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean is less than 0\n95 percent confidence interval:\n      -Inf -14.82793\nsample estimates:\nmean of x \n-18.93333 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(captopril$SBPa, captopril$SBPb, paired = TRUE, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  captopril$SBPa and captopril$SBPb\nt = -8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean difference is less than 0\n95 percent confidence interval:\n      -Inf -14.82793\nsample estimates:\nmean difference \n      -18.93333 \n```\n\n\n:::\n:::\n\n\n---\n\n### Conclusion\n\nThere is on average an extremely significant blood pressure drop upon administering captopril to patients with hypertension ($p << 0.001$). The systolic blood pressure decreases on average with 18.9 mmHg upon the treatment with captopril (95% CI [$-\\infty,-14.82$] mmHg).\n\nNote that\n\n1. A one-sided interval is reported because we are only interested in a blood pressure drop.\n\n2. Because of the pre-test/post-test design we cannot distinguish between the effect of the treatment and a placebo effect. There was no good control! The lack of a good control typically occurs in  pre-test/post-test designs. How could we have improved the design?\n\n---\n\n## One-sided or two-side testing?\n\nDe test in the captopril example was a one-sided test. We only aim to detect if the captopril treatment on average reduces the blood pressure.\n\nSuppose that we defined the blood pressure difference as  $X_{i}^\\prime=Y_{i}^\\text{before}-Y_{i}^\\text{after}$\n\n- Now, a positive value indicates a blood pressure drop\n\n- The average change in blood pressure is now denote as $\\mu^\\prime=\\text{E}[X^\\prime]$.\n\n- So now we should use a one-sided test to assess $H_0: \\mu^\\prime=0$ against $H_1: \\mu^\\prime>0$.\n\n- p-value now becomes:\n$$p=\\text{P}_0\\left[T\\geq t\\right].$$\n\n---\n\nAnalysis based on $X^\\prime$: Argument `alternative=\"greater\"` so that we use $H_1: \\mu^\\prime>0$:\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(captopril$SBPb - captopril$SBPa, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  captopril$SBPb - captopril$SBPa\nt = 8.1228, df = 14, p-value = 5.732e-07\nalternative hypothesis: true mean is greater than 0\n95 percent confidence interval:\n 14.82793      Inf\nsample estimates:\nmean of x \n 18.93333 \n```\n\n\n:::\n:::\n\n\nOf course we obtain the same results. Only the sign is swapped.\n\n---\n\n### Two-sided test\n\nSuppose that researchers wanted to assess the mode of action of the new drug captopril in the design phase and suppose that healthy subjects were used in an early phase of the drug development.\n\nIn this case it would have been interesting to observe blood pressure drops as well as gains.\n\nThen we would require a two-sided test strategy\n\n$$H_0: \\mu=0$$\nagainst the alternative hypothesis\n\n$$H_1: \\mu\\neq0,$$\n\nso that the mean under the alternative is different from zero.\n\nIt can be positive as well as negative changes and we did not know upfront in which direction the real mean will deviate from $H_1$.\n\n\nWe can conduct a two-sided test on the $\\alpha=5\\%$ significance level by\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-statisticalInference_files/figure-pdf/unnamed-chunk-51-1.pdf){fig-align='center' width=100%}\n:::\n:::\n\n\n---\n\nThe argument `alternative` of the `t.test` function is by default `alternative=\"two.sided\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(captopril$deltaSBP)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  captopril$deltaSBP\nt = -8.1228, df = 14, p-value = 1.146e-06\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -23.93258 -13.93409\nsample estimates:\nmean of x \n-18.93333 \n```\n\n\n:::\n:::\n\n\n- We still obtain an extremely significant result.\n- The p-value is double as large because we test two-sided.\n\nIndeed\n\n$$p=P_0[T \\leq -\\vert t \\vert] + P_0[T \\geq \\vert t \\vert] = P_0[\\vert T \\vert \\geq \\vert t \\vert] = 2 \\times P_0[T \\geq \\vert t \\vert]$$\n\n- We also obtain a  two-sided confidence interval\n\n---\n\n### One-sided or two-sided test?\n\nWith a one-sided test we can more easily reject $H_0$ on condition that $H_1$ is true than with a two-sided test.\n\n- All information is used to test into one direction\n\n- The decision to test one-sided has to be done in the design phase before the experiment is conducted\n\n- Even if we have strong a priori presumptions, we are not entirely sure otherwise we would have no reason to do the research.\n\n- If we propose a one-sided test in the design phase and we observe a result in the opposite direction that would be statistically significant we can not draw conclusions from the experiment.\n\n- In the design phase we have excluded this result because it is so unexpected that it has to be a false positive.\n\n- Hence, one-sided tests are not recommended.\n\nA two-sided test can always be defended and allows you to detect any deviation of $H_0$ and is highly recommended.\n\n\nIt is **never allowed** to change a two-sided test into a one-sided test based on what has been observed in the sample! Otherwise the type I error of the test strategy is not correctly controlled.\n\n---\n\nWe illustrate this in the simulation study below:\n\n1. correct two-sided test and\n2. one-sided test with its sign based on what was observed in the sample.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- 0\nsigma <- 9.0\nnSim <- 1000\nalpha <- 0.05\nn <- 15\npvalsCor <- pvalsInCor <- array(0, nSim)\nfor (i in 1:nSim)\n{\n  x <- rnorm(n, mean = mu, sd = sigma)\n  pvalsCor[i] <- t.test(x)$p.value\n  if (mean(x) < 0) {\n    pvalsInCor[i] <- t.test(x, alternative = \"less\")$p.value\n  } else {\n    pvalsInCor[i] <- t.test(x, alternative = \"greater\")$p.value\n  }\n}\n\nmean(pvalsCor < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.041\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(pvalsInCor < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.094\n```\n\n\n:::\n:::\n\n\n- Type I error correctly controlled at $\\alpha$ for two-sided test.\n- Type I error not correctly controlled when we test one-sided based on what we observed in the sample.\n\n# Nature column on testing\n\nhttps://www.nature.com/articles/nmeth.2698.pdf\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{longtable}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{wrapfig}\n\\usepackage{float}\n\\usepackage{colortbl}\n\\usepackage{pdflscape}\n\\usepackage{tabu}\n\\usepackage{threeparttable}\n\\usepackage{threeparttablex}\n\\usepackage[normalem]{ulem}\n\\usepackage{makecell}\n\\usepackage{xcolor}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}