{
  "hash": "2c98d5aca2b492bd87e3f144c800724a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercise 5.2: Hypothesis testing on the pertussis example - solution\"\nauthor: \"Lieven Clement, and Milan Malfait\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\n---\n\n# Aim of this tutorial\n\nUpon this exercise you can\n\n1. conduct a statistical hypothesis test for a two group comparison in R and to interpret the results.\n2. critically evaluate the assumptions for a two sample t-test\n3. use simulations to assist you when evaluating the assumptions of a two group comparison\n4. select the correct test based on the data exploration.\n\n# Background\n\nResearchers wanted to study the immune response on pertussis.\nThey have set up an experiments with 40 rats.\n16 rats were infected with pertussis and 24 rats received a control treatment.\nResearchers measured the white blood cell concentration (WBC) in each rat (count per mm$^3$).\n\nDe data consists of two variables:\n\n- WBC: white blood cell count (counts/mm$^3$).\n- trt: treatment\n\n    - control: rat recieved control treatment\n    - pertussis: rat was infected with pertussis\n\n\n# Import the dataset\n\nLoad the libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\nData path:\n\n  `https://raw.githubusercontent.com/statOmics/PSLSData/main/wbcon.csv`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwbcon <- read_csv(\"https://raw.githubusercontent.com/statOmics/PSLSData/main/wbcon.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 40 Columns: 2\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): trt\ndbl (1): WBC\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(wbcon)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 40\nColumns: 2\n$ WBC <dbl> 10252, 10467, 10601, 10638, 10901, 11071, 11092, 11371, 11667, 116…\n$ trt <chr> \"control\", \"control\", \"control\", \"control\", \"control\", \"control\", …\n```\n\n\n:::\n:::\n\n\n## Aim of the study\n\nThe overarching goal of this study was to assess if the white blood cell count changes upon pertussis infection. To this end, researchers randomized 40 rats\nto two treatments: A control treatment and a treatment in which the rat was infected with pertussis.\n\n# Data exploration\n\nA crucial first step in a data analysis is to visualize and to explore the raw data.\n\nThis will allow us to gain insight in the data.\n\nA secondary goal of the data exploration is to check the assumptions of the test that we will perform.\n\n## Which test will you perform to compare the white blood cell count between infected and control rats?\n\n40 different rats are assigned at random to a control treatment or a treatment where they are infected with pertussis.\nThe white blood cells of the rats are measured on different animals and we can assume that the data between rats are independent.\nNote, that this will not be the case if multiple rats are housed in the same cages!\n\nWe will therefore perform a two-sample t-test to assess if the average white blood cell count differs between infected rats and rats that received the control treatment.\n\n## What are the assumptions of this test?\n\n1. The data are independent\n2. The data in both groups have the same variance\n3. The data in both groups are normally distributed.\n\n## Boxplots\n\nWe can assess the second assumption using boxplots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwbcon |> ggplot(aes(x = trt, y = WBC, fill = trt)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\") +\n  ylab(\"WBC (count/mm3)\") +\n  xlab(\"treatment\") +\n  stat_summary(\n    fun = mean, geom = \"point\",\n    shape = 5, size = 3, color = \"black\"\n  )\n```\n\n::: {.cell-output-display}\n![](05_2_pertussis_sol_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nWhat do you observe?\n\nBoth the mean and variance of the data seems to differ between control rats and rats infected with pertussis.\nSo the second assumption is not valid.\nIf the data are normally distributed we can compare the groups using a Welch modified t-test, which is valid if the data in both groups are exhibiting a different variance.\n\n## QQ-plots\n\nTo assess the assumption that the data are normally distributed in each treatment group, we will use QQ plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwbcon |>\n  ggplot(aes(sample = WBC)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_grid(cols = vars(trt))\n```\n\n::: {.cell-output-display}\n![](05_2_pertussis_sol_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nWhat do you observe?\n\nThe white blood cell counts appear to be normally distributed in both treatment groups.\n\n\n# Assess the research question with the appropriate t-test\n\n## Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\noutput <- t.test(WBC ~ trt, data = wbcon, var.equal = FALSE)\noutput\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  WBC by trt\nt = -5.7114, df = 15.132, p-value = 3.984e-05\nalternative hypothesis: true difference in means between group control and group pertussis is not equal to 0\n95 percent confidence interval:\n -32311.32 -14758.47\nsample estimates:\n  mean in group control mean in group pertussis \n               12215.92                35750.81 \n```\n\n\n:::\n:::\n\n\n## Conclusion\n\nThe average white blood cell count is extremely different between rats that are infected with pertussis and rads that received a control treatment  (p << 0.001).\n\nThe white blood cell count is on average 23535 blood cells/mm$^3$ higher for rats with pertussis than for rats that received a control treatment (95% CI [14758, 32311]).\n\n\n# ADDENDUM: Train yourself in checking the assumptions\n\nIn order for the learners to get more proficient in evaluating the assumptions we will simulate 8 dataset with sample sizes similar to our data for which the assumptions of normality and equal variance do hold. For the QQ-plots we will only plot the one from one of the groups.\n\n## Simulate data\n\nWe simulate 8 datasets with the same sample sizes, means and pooled variance as in the sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(21532)\nnSim <- 8\n## descriptive statistics\nwbcSum <- wbcon |>\n  group_by(trt) |>\n  summarize(\n      mean = mean(WBC, na.rm = TRUE),\n      sd = sd(WBC, na.rm = TRUE),\n      n = n()\n  ) |>\n  mutate(se = sd / sqrt(n))\n\nsigma <- sqrt(sum(wbcSum$sd^2 * (wbcSum$n - 1)) / (sum(wbcSum$n) - 2))\n\nnormSim <- matrix(\n  c(\n    wbcon$WBC,\n    rnorm(sum(wbcSum$n) * nSim,\n          mean = c(\n            rep(wbcSum$mean[1], wbcSum$n[1]),\n            rep(wbcSum$mean[2], wbcSum$n[2])\n            ),\n          sd = sigma)\n    ),\n  nrow = sum(wbcSum$n)) |>\n  as.data.frame() |>\n  mutate(trt = wbcon$trt)\n```\n:::\n\n\n## Comparisons of variances\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(normSim)[1:(nSim+1)] <- c(\"orig\",paste0(\"sim\",1:nSim))\nnormSim |>\n  gather(samp, data, -trt) |>\n  ggplot(aes(x = trt, y = data)) +\n  geom_boxplot() +\n  facet_wrap(~samp)\n```\n\n::: {.cell-output-display}\n![](05_2_pertussis_sol_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nWe observe that the difference in variability of the original observations (top left plot) is larger than in the each simulations. Indicating that there is indeed evidence that the variances in each group differ.\n\n## Evaluation of normality\n\n### Control group\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnormSim |>\n  gather(samp, data, -trt) |>\n  filter(trt == \"control\") |>\n  ggplot(aes(sample = data)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_wrap(~samp)\n```\n\n::: {.cell-output-display}\n![](05_2_pertussis_sol_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n### Pertussis group\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnormSim |>\n  gather(samp, data, -trt) |>\n  filter(trt == \"pertussis\") |>\n  ggplot(aes(sample = data)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_wrap(~samp)\n```\n\n::: {.cell-output-display}\n![](05_2_pertussis_sol_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe data in each group does not show larger deviations from normality than what we observe in each of the eight datasets that were simulated under the model assumptions.\n",
    "supporting": [
      "05_2_pertussis_sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}