{
  "hash": "63ac457b73e023e058bf49f7f2fd653a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercise 6.1: Linear regression on the fish tank dataset - solution\"\nauthor: \"Lieven Clement, Jeroen Gilis and Milan Malfait\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\n---\n\n# Fish tank dataset\n\nIn this experiment, 96 fish (dojofish, goldfish and zebrafish)\nwere placed separately in a tank with two liters of water and\na certain dose (in mg) of the poison EI-43,064. The resistance\nof the fish against the poison was measured as the amount of\nminutes the fish survived after being exposed to the poison (`Surv_time`, in\nminutes). Additionally, the weight of each fish was measured.\n\n# Goal\n\nThe research goal is to study the association between the dose of\nthe poison that was administered to the fish and their\nsurvival time.\n\nLoad the required libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n# Import the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoison <- read_csv(\"https://raw.githubusercontent.com/statOmics/PSLSData/main/poison.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(poison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 96\nColumns: 4\n$ species   <dbl> 0, 2, 1, 2, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 2, 0, …\n$ Weight    <dbl> 1.884359, 1.732261, 2.830895, 1.748562, 2.114166, 1.854602, …\n$ Dose      <dbl> 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, …\n$ Surv_time <dbl> 3.461493, 2.110417, 11.419131, 1.821191, 3.277619, 2.955556,…\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(poison)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"species\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Weight\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Dose\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Surv_time\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0\",\"2\":\"1.884359\",\"3\":\"1.0\",\"4\":\"3.461493\"},{\"1\":\"2\",\"2\":\"1.732261\",\"3\":\"1.1\",\"4\":\"2.110417\"},{\"1\":\"1\",\"2\":\"2.830895\",\"3\":\"1.2\",\"4\":\"11.419131\"},{\"1\":\"2\",\"2\":\"1.748562\",\"3\":\"1.3\",\"4\":\"1.821191\"},{\"1\":\"0\",\"2\":\"2.114166\",\"3\":\"1.4\",\"4\":\"3.277619\"},{\"1\":\"0\",\"2\":\"1.854602\",\"3\":\"1.5\",\"4\":\"2.955556\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Data tidying\n\nWe can see a couple of things in the data that can be improved:\n\n1. Capitalise the fist column name. *Hint*: use the `rename` function.\n\n2. Set the Species column as a factor. *Hint*: use the `mutate` and `as.factor`\nfunctions.\n\n3. Change the species factor levels from 0, 1 and 2 to\nDojofish, Goldfish and Zebrafish. *Hint*: use the `fct_recode` function inside\nthe `mutate` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoison <- poison |>\n  rename(\"Species\" = \"species\") |>\n  mutate(Species = as.factor(Species)) |>\n  mutate(\n    Species = fct_recode(Species,\n      Dojofish = \"0\", Goldfish = \"1\", Zebrafish = \"2\"\n    )\n  )\n\npoison\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Species\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Weight\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Dose\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Surv_time\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Dojofish\",\"2\":\"1.884359\",\"3\":\"1.0\",\"4\":\"3.461493\"},{\"1\":\"Zebrafish\",\"2\":\"1.732261\",\"3\":\"1.1\",\"4\":\"2.110417\"},{\"1\":\"Goldfish\",\"2\":\"2.830895\",\"3\":\"1.2\",\"4\":\"11.419131\"},{\"1\":\"Zebrafish\",\"2\":\"1.748562\",\"3\":\"1.3\",\"4\":\"1.821191\"},{\"1\":\"Dojofish\",\"2\":\"2.114166\",\"3\":\"1.4\",\"4\":\"3.277619\"},{\"1\":\"Dojofish\",\"2\":\"1.854602\",\"3\":\"1.5\",\"4\":\"2.955556\"},{\"1\":\"Zebrafish\",\"2\":\"1.215184\",\"3\":\"1.6\",\"4\":\"1.848889\"},{\"1\":\"Goldfish\",\"2\":\"2.054411\",\"3\":\"1.7\",\"4\":\"8.054869\"},{\"1\":\"Dojofish\",\"2\":\"1.801606\",\"3\":\"1.8\",\"4\":\"1.654597\"},{\"1\":\"Goldfish\",\"2\":\"2.501205\",\"3\":\"1.9\",\"4\":\"7.952420\"},{\"1\":\"Dojofish\",\"2\":\"1.912098\",\"3\":\"2.0\",\"4\":\"2.694585\"},{\"1\":\"Goldfish\",\"2\":\"1.782304\",\"3\":\"2.1\",\"4\":\"2.864928\"},{\"1\":\"Dojofish\",\"2\":\"2.032760\",\"3\":\"1.0\",\"4\":\"6.056393\"},{\"1\":\"Dojofish\",\"2\":\"2.263284\",\"3\":\"1.1\",\"4\":\"3.508306\"},{\"1\":\"Zebrafish\",\"2\":\"1.819726\",\"3\":\"1.2\",\"4\":\"2.792692\"},{\"1\":\"Dojofish\",\"2\":\"1.924464\",\"3\":\"1.3\",\"4\":\"3.463380\"},{\"1\":\"Dojofish\",\"2\":\"2.153471\",\"3\":\"1.4\",\"4\":\"3.183236\"},{\"1\":\"Dojofish\",\"2\":\"2.171603\",\"3\":\"1.5\",\"4\":\"3.990290\"},{\"1\":\"Zebrafish\",\"2\":\"1.543050\",\"3\":\"1.6\",\"4\":\"3.102191\"},{\"1\":\"Dojofish\",\"2\":\"2.023775\",\"3\":\"1.7\",\"4\":\"2.323233\"},{\"1\":\"Goldfish\",\"2\":\"2.158629\",\"3\":\"1.8\",\"4\":\"3.334428\"},{\"1\":\"Goldfish\",\"2\":\"2.337289\",\"3\":\"1.9\",\"4\":\"5.406935\"},{\"1\":\"Goldfish\",\"2\":\"1.900762\",\"3\":\"2.0\",\"4\":\"2.665815\"},{\"1\":\"Dojofish\",\"2\":\"2.028244\",\"3\":\"2.1\",\"4\":\"2.477966\"},{\"1\":\"Goldfish\",\"2\":\"2.159808\",\"3\":\"1.0\",\"4\":\"7.783093\"},{\"1\":\"Dojofish\",\"2\":\"1.819958\",\"3\":\"1.1\",\"4\":\"2.868702\"},{\"1\":\"Goldfish\",\"2\":\"1.999414\",\"3\":\"1.2\",\"4\":\"5.477190\"},{\"1\":\"Goldfish\",\"2\":\"2.073964\",\"3\":\"1.3\",\"4\":\"6.509285\"},{\"1\":\"Goldfish\",\"2\":\"2.058199\",\"3\":\"1.4\",\"4\":\"5.698655\"},{\"1\":\"Zebrafish\",\"2\":\"1.826108\",\"3\":\"1.5\",\"4\":\"2.377967\"},{\"1\":\"Zebrafish\",\"2\":\"1.715282\",\"3\":\"1.6\",\"4\":\"2.080905\"},{\"1\":\"Goldfish\",\"2\":\"2.482385\",\"3\":\"1.7\",\"4\":\"8.188797\"},{\"1\":\"Goldfish\",\"2\":\"2.224457\",\"3\":\"1.8\",\"4\":\"6.967697\"},{\"1\":\"Dojofish\",\"2\":\"2.780534\",\"3\":\"1.9\",\"4\":\"3.829233\"},{\"1\":\"Dojofish\",\"2\":\"1.874389\",\"3\":\"2.0\",\"4\":\"1.473436\"},{\"1\":\"Dojofish\",\"2\":\"2.405112\",\"3\":\"2.1\",\"4\":\"2.651495\"},{\"1\":\"Goldfish\",\"2\":\"2.252743\",\"3\":\"1.0\",\"4\":\"9.527555\"},{\"1\":\"Dojofish\",\"2\":\"2.183263\",\"3\":\"1.1\",\"4\":\"3.498417\"},{\"1\":\"Goldfish\",\"2\":\"2.454223\",\"3\":\"1.2\",\"4\":\"10.899650\"},{\"1\":\"Dojofish\",\"2\":\"2.529784\",\"3\":\"1.3\",\"4\":\"3.284117\"},{\"1\":\"Zebrafish\",\"2\":\"1.404543\",\"3\":\"1.4\",\"4\":\"2.529689\"},{\"1\":\"Goldfish\",\"2\":\"1.919328\",\"3\":\"1.5\",\"4\":\"3.801973\"},{\"1\":\"Dojofish\",\"2\":\"2.180245\",\"3\":\"1.6\",\"4\":\"2.471836\"},{\"1\":\"Goldfish\",\"2\":\"2.208250\",\"3\":\"1.7\",\"4\":\"4.271475\"},{\"1\":\"Dojofish\",\"2\":\"1.935201\",\"3\":\"1.8\",\"4\":\"1.913753\"},{\"1\":\"Goldfish\",\"2\":\"2.069835\",\"3\":\"1.9\",\"4\":\"5.345919\"},{\"1\":\"Dojofish\",\"2\":\"2.461620\",\"3\":\"2.0\",\"4\":\"2.103600\"},{\"1\":\"Zebrafish\",\"2\":\"2.062654\",\"3\":\"2.1\",\"4\":\"1.350661\"},{\"1\":\"Dojofish\",\"2\":\"2.339549\",\"3\":\"1.0\",\"4\":\"9.358027\"},{\"1\":\"Zebrafish\",\"2\":\"1.812377\",\"3\":\"1.1\",\"4\":\"4.241644\"},{\"1\":\"Goldfish\",\"2\":\"2.254900\",\"3\":\"1.2\",\"4\":\"6.206211\"},{\"1\":\"Dojofish\",\"2\":\"2.068002\",\"3\":\"1.3\",\"4\":\"2.323421\"},{\"1\":\"Goldfish\",\"2\":\"2.389707\",\"3\":\"1.4\",\"4\":\"7.915151\"},{\"1\":\"Goldfish\",\"2\":\"2.497137\",\"3\":\"1.5\",\"4\":\"10.996561\"},{\"1\":\"Goldfish\",\"2\":\"2.307549\",\"3\":\"1.6\",\"4\":\"4.541743\"},{\"1\":\"Dojofish\",\"2\":\"2.089716\",\"3\":\"1.7\",\"4\":\"2.041679\"},{\"1\":\"Dojofish\",\"2\":\"2.060077\",\"3\":\"1.8\",\"4\":\"3.513445\"},{\"1\":\"Goldfish\",\"2\":\"2.558311\",\"3\":\"1.9\",\"4\":\"6.198538\"},{\"1\":\"Dojofish\",\"2\":\"2.075058\",\"3\":\"2.0\",\"4\":\"1.634059\"},{\"1\":\"Goldfish\",\"2\":\"1.840242\",\"3\":\"2.1\",\"4\":\"3.059981\"},{\"1\":\"Dojofish\",\"2\":\"1.585098\",\"3\":\"1.0\",\"4\":\"2.955830\"},{\"1\":\"Goldfish\",\"2\":\"2.389859\",\"3\":\"1.1\",\"4\":\"6.426726\"},{\"1\":\"Dojofish\",\"2\":\"2.384177\",\"3\":\"1.2\",\"4\":\"7.252887\"},{\"1\":\"Goldfish\",\"2\":\"2.464393\",\"3\":\"1.3\",\"4\":\"6.813678\"},{\"1\":\"Dojofish\",\"2\":\"2.255311\",\"3\":\"1.4\",\"4\":\"2.578759\"},{\"1\":\"Goldfish\",\"2\":\"2.257577\",\"3\":\"1.5\",\"4\":\"4.862047\"},{\"1\":\"Goldfish\",\"2\":\"1.931530\",\"3\":\"1.6\",\"4\":\"3.484681\"},{\"1\":\"Zebrafish\",\"2\":\"1.585569\",\"3\":\"1.7\",\"4\":\"1.314428\"},{\"1\":\"Dojofish\",\"2\":\"2.290878\",\"3\":\"1.8\",\"4\":\"3.014636\"},{\"1\":\"Goldfish\",\"2\":\"2.475834\",\"3\":\"1.9\",\"4\":\"7.739927\"},{\"1\":\"Zebrafish\",\"2\":\"1.658319\",\"3\":\"2.0\",\"4\":\"1.549716\"},{\"1\":\"Zebrafish\",\"2\":\"1.777013\",\"3\":\"2.1\",\"4\":\"1.995267\"},{\"1\":\"Zebrafish\",\"2\":\"1.802350\",\"3\":\"1.0\",\"4\":\"1.565724\"},{\"1\":\"Dojofish\",\"2\":\"2.220584\",\"3\":\"1.1\",\"4\":\"5.277624\"},{\"1\":\"Goldfish\",\"2\":\"2.391795\",\"3\":\"1.2\",\"4\":\"13.259962\"},{\"1\":\"Dojofish\",\"2\":\"2.066648\",\"3\":\"1.3\",\"4\":\"2.707082\"},{\"1\":\"Dojofish\",\"2\":\"1.976426\",\"3\":\"1.4\",\"4\":\"2.735774\"},{\"1\":\"Dojofish\",\"2\":\"1.994567\",\"3\":\"1.5\",\"4\":\"4.475603\"},{\"1\":\"Goldfish\",\"2\":\"2.094764\",\"3\":\"1.6\",\"4\":\"3.803040\"},{\"1\":\"Zebrafish\",\"2\":\"1.531822\",\"3\":\"1.7\",\"4\":\"1.855402\"},{\"1\":\"Goldfish\",\"2\":\"2.292861\",\"3\":\"1.8\",\"4\":\"3.182463\"},{\"1\":\"Dojofish\",\"2\":\"2.078708\",\"3\":\"1.9\",\"4\":\"3.204668\"},{\"1\":\"Goldfish\",\"2\":\"2.605055\",\"3\":\"2.0\",\"4\":\"5.228839\"},{\"1\":\"Goldfish\",\"2\":\"2.458649\",\"3\":\"2.1\",\"4\":\"4.807160\"},{\"1\":\"Zebrafish\",\"2\":\"1.892714\",\"3\":\"1.0\",\"4\":\"4.262905\"},{\"1\":\"Zebrafish\",\"2\":\"1.428462\",\"3\":\"1.1\",\"4\":\"3.757364\"},{\"1\":\"Dojofish\",\"2\":\"2.582141\",\"3\":\"1.2\",\"4\":\"4.924012\"},{\"1\":\"Goldfish\",\"2\":\"1.874957\",\"3\":\"1.3\",\"4\":\"2.577720\"},{\"1\":\"Goldfish\",\"2\":\"2.655126\",\"3\":\"1.4\",\"4\":\"7.699280\"},{\"1\":\"Goldfish\",\"2\":\"1.881216\",\"3\":\"1.5\",\"4\":\"3.537592\"},{\"1\":\"Dojofish\",\"2\":\"2.331042\",\"3\":\"1.6\",\"4\":\"4.565026\"},{\"1\":\"Dojofish\",\"2\":\"2.360538\",\"3\":\"1.7\",\"4\":\"5.659547\"},{\"1\":\"Zebrafish\",\"2\":\"1.763365\",\"3\":\"1.8\",\"4\":\"2.769239\"},{\"1\":\"Goldfish\",\"2\":\"2.492774\",\"3\":\"1.9\",\"4\":\"5.176632\"},{\"1\":\"Dojofish\",\"2\":\"2.027935\",\"3\":\"2.0\",\"4\":\"2.715960\"},{\"1\":\"Zebrafish\",\"2\":\"1.890602\",\"3\":\"2.1\",\"4\":\"2.134797\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Data exploration\n\nHow many fish do we have per species?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoison |>\n  count(Species)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Species\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Dojofish\",\"2\":\"39\"},{\"1\":\"Goldfish\",\"2\":\"38\"},{\"1\":\"Zebrafish\",\"2\":\"19\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nMake a suitable visualization of the association between\nthe dose and the survival time. Additionally, add the fish species\nas a color to the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoison |>\n  ggplot(aes(x = Dose, y = Surv_time)) +\n  geom_point() +\n  stat_smooth(method = \"loess\") +\n  geom_smooth(method = \"lm\", col = \"black\") +\n  ylab(\"Survival time (min)\") +\n  xlab(\"Dose (mg)\") +\n  geom_point(aes(col = Species)) + ## not necessary, additional layer of information\n  scale_color_manual(values = c(\"red\", \"darkgoldenrod\", \"black\")) +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThe linear regression line (black) is a good approximation\nof the best fitting smooth line (blue) through the data.\nBased on this figure, it seems realistic to suggest a linear\nrelationship between dose and survival, where higher doses\nhave lower survival times (as expected). However, before we\nstart with the regression analysis we must check if all required\nassumptions are met.\n\n# Important note on the dataset\n\nIn this dataset, there are multiple variables that can have an effect on the\nsurvival time of the fish. The most obvious one is the dose of poison that was\nadministered (as displayed above). However, we could also imagine that heavier\nfish are less prone to the poison than light fish. Additionally, one fish\nspecies may be more resistant to the poison than the other.\n\nAs such, not taking into account species into the analysis will introduce\nproblems regarding the assumption of *independence* of the data. The assumption\nof *independence* entails that knowing the response value of one observation\n(fish) does not learn us anything about the response values for another\nvariable. This will not be the case here; the response values (survival times)\nof fish of the same species will be much more alike compared to those of fish\nfrom another species.\n\nThus, in order to correctly analyze this data, fish `species` and `weight`\nshould be taken into consideration. **For now, we will \"avoid\" taking into**\n**account the effect of species into the analysis by only performing an**\n**analysis for the dojofish**. As such, we will filter the dataset so that\nit only contains observations for the Dojofish.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# filter the data so it only contains dojofish\npoison_dojo <- poison |>\n  filter(Species == \"Dojofish\")\n```\n:::\n\n\nLater in the course, we will come back to this dataset and perform a analysis\nthat allows us to assess the different research hypotheses for all fish species\nat once!\n\nThe second predictor variable, `Weight`, still may influence our analysis; fish\nwith higher weight are expected to be more resistant to the poison. **If** there\nwould be a systematic bias in the experiment, e.g. if all lighter fish obtained\na low dose  of poison and heavier fish obtained a high dose of poison\n(so, if the dose was not correctly randomized accros the different weights),\nthen we would not be able to correctly estimate the linear association between\n`Dose` and `survival`; indeed, this relationship would be confounded by the\neffect of weight.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoison_dojo |>\n  ggplot(aes(x = Dose, y = Weight)) +\n  geom_point() +\n  ggtitle(\"Association between dose and weight\") +\n  theme_bw() +\n  stat_summary(\n    fun = mean, geom = \"point\",\n    col = \"black\", size = 4, shape = 24,\n    fill = \"red\"\n  )\n```\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nIn our dataset, there seems to be **no systematic bias**, i.e., no clear trend\nin the association between `Dose` and `Weight`. However, we do notice that the\nfish weights are not perfectly uniformly distributed across the different doses;\nwe don't see a clear trend, but we do see some fluctuations. To check if\nfluctuations of the size that we observe here could happen by random change if\nwe carefully randomise, we may use simulations where we simulate the allocation\nof the fish to the different doses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gridExtra)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'gridExtra'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    combine\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1351)\n\nplots <- lapply(\n  1:9,\n  function(x) {\n    poison_dojo |>\n      mutate(Dose = sample(Dose)) |> # randomization\n      ggplot(aes(x = Dose, y = Weight)) +\n      geom_point() +\n      theme_bw() +\n      stat_summary(\n        geom = \"point\",\n        fun = \"mean\",\n        col = \"black\",\n        size = 2,\n        shape = 24,\n        fill = \"red\"\n      )\n  }\n)\ndo.call(gridExtra::grid.arrange, plots)\n```\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nIn the above simulation, we randomly assigned the different fish to different\npoison doses. Even though we did this randomly, we still see that by random\nchance there can be fluctuations as large as the ones observed in our real\ndataset. As such, we may conclude that there is indeed **no systematic bias**,\ni.e., no clear trend in the association between `Dose` and `Weight`.\n\n# Linear regression analysis\n\n## Assumptions of linear regression\n\nList assumptions:\n\n1. The observations are independent of each other\n2. Linearity between the response and predictor variable\n3. The residues of the model must be normally distributed\n4. Homoscedasticity of the data\n\nThe first assumption is met based on the experimental design. In the\ndata exploration phase, we saw that there is no clear trend in the association\nbetween `Dose` and `Weight`. With respect to species, we have \"avoided\" taking\ninto account the effect of species into the analysis by only performing an\nanalysis for the dojofish.\n\nWe will check the other assumptions by first fitting the linear\nmodel and plotting the output. As such, we will get all the\nrequired diagnostic plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit a linear regression model with 'Surv_time' as response variable and\n# 'Dose' as predictor variabele\nmodel <- lm(Surv_time ~ Dose, data = poison_dojo)\n\n## display the diagnostic plots of the model\nplot(model)\n```\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-11-4.png){width=672}\n:::\n:::\n\n\nWe have four diagnostic plots:\n\n2. Linearity with the Residuals vs fitted plot\n\n- predictor of predictions $\\hat\\beta_0+\\hat\\beta_1 x$ on $X$-axis\n- *residuals* on $Y$-as\n$$e_i=y_i-\\hat{g}(x_i)=y_i-\\hat\\beta_0-\\hat\\beta_1\\times x_i,$$\n\nIf there would be a linear relationship in the data,\nthe residuals are expected to be scattered at random around y=0 for\nthe entire range of predicted values. This is clearly\nthe case: the assumption of linearity is met.\n\n3. Normal Q-Q\n\n- QQ-plot of the residuals $e_i$.\n\nThe residuals of the linear regression model should be normally\ndistributed. Given the second diagnostic plot, this seems not\nto be the case. In stead, we observe a short left tail and a\nlong right tail. The assumption of normal residues is **not met.**\n\n4. Homoscedasticity\n\n- Square-root of the absolute value of standardized residuals\nin function of the fitted values\n\nTo meet the third assumption of linear regression, the variance\non the _Square-root of the absolute value of standardized residuals_\nmust be similar over the entire range of fitted values. The smoother\nin the plot helps us with looking at this; it should be nicely\nhorizontal over the entire range of fitted values. This seems not\nto be the case: for larger fitted values, the variance increase slightly.\nThe assumption of homoscedasticity is **not met.**\n\nMultiple assumptions are not met, so we may not continue by performing\na linear regression.\n\nWe can try to remediate these deviations by log-transforming the data. Indeed,\ndata with heavy right tails can often be normalized by applying this strategy.\n\nFit a (log-)linear model by log-transforming the response.Generate diagnostic\nplots and assess the assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog.model <- lm(log10(Surv_time) ~ Dose, data = poison_dojo)\nplot(log.model)\n```\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-12-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-12-4.png){width=672}\n:::\n:::\n\n\nArguably, there might be some deviation from normality in the left tail of the\ndistribution. However, when we would simulate data under the normality\nassumption, it seems that deviations of this size may be expected when\nnormality is met:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1406)\nnobs <- nrow(poison_dojo)\n\ndata.frame(\n  y = c(log.model$res, rnorm(nobs * 8, sd = sigma(log.model))),\n  label = rep(c(\"orig\", paste0(\"sim\", 1:8)), each = nobs)\n) |>\n  ggplot(aes(sample = y)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_wrap(~label)\n```\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n1. The independence assumption is met.\n2. Upon log-transformation, the linearity assumption is still met.\n3. Upon log-transformation, the normality assumption is also met.\n4. Upon log-transformation, the homoscedasticity assumption is also met.\n\nLook at the output of the log-linear model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(log.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log10(Surv_time) ~ Dose, data = poison_dojo)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-0.2074 -0.1145 -0.0324  0.1039  0.3268 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.91722    0.10423   8.800 1.33e-10 ***\nDose        -0.27282    0.06648  -4.104 0.000215 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1453 on 37 degrees of freedom\nMultiple R-squared:  0.3128,\tAdjusted R-squared:  0.2942 \nF-statistic: 16.84 on 1 and 37 DF,  p-value: 0.0002146\n```\n\n\n:::\n:::\n\n\nCompute the 95% confidence interval on the model parameters:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(log.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept)  0.7060342  1.1284104\nDose        -0.4075255 -0.1381159\n```\n\n\n:::\n:::\n\n\n## Interpretation on the log scale\n\nCurrently, all the outcomes should be interpreted on the log-scale.\nIndeed, since we are now modelling  _the log$_{10}$ of survival time_, we\ndon't have direct inference on survival time.\n\nAs such, we may interpret the output as follows:\n\n- The slope:\n\nDojofish that are exposed to a higher dose of the poison will have a $log_{10}$\nsurvival time that is on average 0.27\nlower per gram of poison that was administered additionally\n(95% CI [0.71, 0.41, 1.13, 0.14]). This decrease in\nsurvival time is significant on the 5% significance level (p<0.001).\n\nNote, that the study is an experimental study so we can conclude that there is\na causal effect of the poison dose and the survival time.\n\n- The intercept:\n\nThe average of the log10 of survival time for fish that\nwere given a dose of 0 mg is 0.92.\n\n## Interpretation on the original scale\n\nThe interpretation the log-scale is quite difficult. To ease\nthe interpretation, we will backtransform the results to the original\nscale (time in minutes). This we can do by\n\n\n::: {.cell}\n\n```{.r .cell-code}\n10^(summary(log.model)$coefficients[, \"Estimate\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)        Dose \n  8.2646094   0.5335551 \n```\n\n\n:::\n:::\n\n\nand of their confidence intervals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n10^(confint(log.model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %     97.5 %\n(Intercept) 5.0819949 13.4403459\nDose        0.3912681  0.7275855\n```\n\n\n:::\n:::\n\n\nNow, we can interpret the results in terms of the geometric mean:\n\n- The slope:\n\nDojo fish that are exposed to a higher dose of the poison will have a geometric\nmean of the survival time that is factor 0.53\n(95% CI [0.39, 0.73]) per gram of poison that they\nreceived more than fish exposed to a lower dose. This decrease is very\nsignificant on the 5% significance level (p<0.001).\n\n- The intercept:\n\nThe geometric mean of the survival time for fish that were given a\ndose of 0 mg is 8.26 minutes.\n\nIn other words, our analysis seems to suggest that fish in uncontaminated water\nwould only survive for about 8 minutes! This seems a little bit _fishy_...\n\nNote, that this interpretation is not biologically relevant and is induced\nbecause we extrapolated considerably because all fish in the experiment were\nexposed to poison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Extract slope and intercept from the model\ndojo_intercept <- coef(log.model)[1]\ndojo_slope <- coef(log.model)[2]\n\nggplot(poison_dojo, aes(Dose, log10(Surv_time))) +\n  geom_point() +\n  geom_abline(\n    slope = dojo_slope, intercept = dojo_intercept,\n    color = \"steelblue\", size = 1.2\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](06_2_poison_sol_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nWe can see that the dose value of 0 mg does not fall within\nthe same range as our data. The model is only valid in the range of\ndata that we use to build the model on!\n\nHowever, in most applications we will never test for the intercept term.\n\n# Conclusion\n\nThere is a very significant effect of the poison on survival of Dojofish\n(p< 0.001). Dojofish that are exposed to a higher dose of the poison will\nhave a survival time that decrease on average with a factor\n1.87 per gram of poison that\nis added (95% CI [2.56, 1.37]).\n\nIn the tutorial of multiple regression, we will revisit this exercise.\nMore specifically, we will there study the association between dose and survival\nfor all the species in the dataset.\n",
    "supporting": [
      "06_2_poison_sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}