{
  "hash": "f8f5f7217364d4fddaafd445f6251c95",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tutorial 7.3: ANOVA in the NHANES dataset\"\n\n---\n\n# The NHANES dataset\n\nThe National Health and Nutrition Examination Survey (NHANES) contains data\nthat has been collected since 1960. For this tutorial, we will make use of\nthe data that were collected between 2009 and 2012, for 10.000 U.S. civilians.\nThe dataset contains a large number of physical, demographic, nutritional and\nlife-style-related parameters.\n\n# Goal\n\nIn the NHANES dataset, one of the columns is named `HealthGen`.\nHealthGen is a self-reported rating of a participant’s health\nin general terms. HealthGen is reported for participants aged 12\nyears or older. It is a factor with the following levels:\nExcellent, Vgood, Good, Fair, or Poor.\n\nWe want to test whether or not the mean systolic blood pressure\nvalue (take column `BPSys1`) is equal between the five self-reported\nhealth categories. To this end, we will use an ANOVA analysis\n(if the required assumptions are met).\n\nLoad the required libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n# Data import\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES <- read_csv(\"https://raw.githubusercontent.com/statOmics/PSLSData/main/NHANES.csv\")\nglimpse(NHANES[1:10])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,000\nColumns: 10\n$ ID            <dbl> 51624, 51624, 51624, 51625, 51630, 51638, 51646, 51647, …\n$ SurveyYr      <chr> \"2009_10\", \"2009_10\", \"2009_10\", \"2009_10\", \"2009_10\", \"…\n$ Gender        <chr> \"male\", \"male\", \"male\", \"male\", \"female\", \"male\", \"male\"…\n$ Age           <dbl> 34, 34, 34, 4, 49, 9, 8, 45, 45, 45, 66, 58, 54, 10, 58,…\n$ AgeDecade     <chr> \"30-39\", \"30-39\", \"30-39\", \"0-9\", \"40-49\", \"0-9\", \"0-9\",…\n$ AgeMonths     <dbl> 409, 409, 409, 49, 596, 115, 101, 541, 541, 541, 795, 70…\n$ Race1         <chr> \"White\", \"White\", \"White\", \"Other\", \"White\", \"White\", \"W…\n$ Race3         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ Education     <chr> \"High School\", \"High School\", \"High School\", NA, \"Some C…\n$ MaritalStatus <chr> \"Married\", \"Married\", \"Married\", NA, \"LivePartner\", NA, …\n```\n\n\n:::\n:::\n\n\n# Data Exploration\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  ggplot(aes(x = HealthGen, y = BPSys1, fill = HealthGen)) +\n  scale_fill_brewer(palette = \"RdGy\") +\n  theme_bw() +\n  geom_boxplot(outlier.shape = NA) +\n  # geom_jitter(width = 0.2,size=0.01) + ## omitted as it makes the plot messy\n  ggtitle(\"Boxplot of the systolic bloodpressure for each health category\") +\n  ylab(\"Systolic blood pressure (mmHg)\") +\nstat_summary(\n  fun = mean, geom = \"point\",\n  shape = 5, size = 3, color = \"black\",\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1763 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1763 rows containing non-finite outside the scale range\n(`stat_summary()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](07_3_NHANES_sol_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThis plot is not ideal; it would be far more intuitive if\nthe health categories were ordered properly (i.e., Poor --> excellent).\nIn addition, we observe a sixth \"category\" of NA values.\n\nTo get a more informative and intuitive visualization, you can:\n\n1. Filter out subjects with NA values for `HealthGen` or `BPSys1`\n2. Set `HealthGen` to a factor and relevel it to Poor --> Excellent\n\n**Hint:** The second task can be achieved by using the `mutate`,\n`as.factor` and `fct_relevel` functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES <- NHANES |>\n  filter(!is.na(HealthGen), !is.na(BPSys1)) |>\n  mutate(HealthGen = as.factor(HealthGen)) |>\n  mutate(HealthGen = fct_relevel(HealthGen, c(\"Poor\", \"Fair\", \"Good\", \"Vgood\", \"Excellent\")))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  ggplot(aes(x = HealthGen, y = BPSys1, fill = HealthGen)) +\n  scale_fill_brewer(palette = \"RdGy\") +\n  theme_bw() +\n  geom_boxplot(outlier.shape = NA) +\n  ggtitle(\"Boxplot of the systolic bloodpressure for each health category\") +\n  ylab(\"Systolic blood pressure (mmHg)\") +\nstat_summary(\n  fun = mean, geom = \"point\",\n  shape = 5, size = 3, color = \"black\",\n)\n```\n\n::: {.cell-output-display}\n![](07_3_NHANES_sol_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n# ANOVA\n\nTo study if the observed difference between the\naverage systolic blood pressure values of the different health groups\nare significant, we may perform an ANOVA.\n\n## Formulate null and alternative hyoptheses\n\nThe null hypothesis of ANOVA states that:\n$H0$: The mean systolic blood pressure is equal between the different health groups.\n\nThe alternative hypothesis of ANOVA states that:\n$HA$: The mean systolic blood pressure for at least one health group is different\nfrom the mean systolic blood pressure in at least one other health group.\n\n## Check the assumptions for ANOVA\n\nBefore we may proceed with the analysis, we must make sure that all\nassumptions for ANOVA are met. ANOVA has three assumptions:\n\n1. The observations are independent of each other (in all groups)\n2. The data (BPSys1) must be normally distributed (in all groups)\n3. The variability within all groups is similar\n\n### Assumption of independence\n\nThe first assumption is met; there shoud be no specific pattterns of dependence.\n\n### Assumption of normality\n\nFor the second assumption, we must check normality in each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  ggplot(aes(sample = BPSys1)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_grid(~HealthGen)\n```\n\n::: {.cell-output-display}\n![](07_3_NHANES_sol_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThe data does not appear to be normally distributed for\neach group. It seems to have a heavy right tail. We can\nperform a log transformation on the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  mutate(BPSys1_log = log(BPSys1)) |>\n  ggplot(aes(sample = BPSys1_log)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_grid(~HealthGen)\n```\n\n::: {.cell-output-display}\n![](07_3_NHANES_sol_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nWhile the log transformation improved the distributions somewhat,\nthe data still does not appear to be normally distributed for\neach group. However, we do have a very large number of\nobservations per group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Count the number of observations per treatment\nNHANES |>\n  count(HealthGen)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"HealthGen\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Poor\",\"2\":\"184\"},{\"1\":\"Fair\",\"2\":\"934\"},{\"1\":\"Good\",\"2\":\"2803\"},{\"1\":\"Vgood\",\"2\":\"2367\"},{\"1\":\"Excellent\",\"2\":\"848\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nAs such, we may rely on the cental limit theorem.\nRemember, the cental limit theorem that when the number\nof observations is sufficiently large (i.e. >100), we\nwill assume that the distribution of the sample mean will\napproximate a normal distribution, even if the underlying\ndata is not normally distributed.\n\n## ANOVA model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(log(BPSys1) ~ HealthGen, NHANES)\nfit_anova <- anova(fit)\nfit_anova\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Sum Sq\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Mean Sq\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"4\",\"2\":\"1.908401\",\"3\":\"0.47710019\",\"4\":\"25.78773\",\"5\":\"2.993562e-21\",\"_rn_\":\"HealthGen\"},{\"1\":\"7131\",\"2\":\"131.931042\",\"3\":\"0.01850106\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nprint(paste(\"Not-rounded p-value:\", fit_anova$`Pr(>F)`[1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Not-rounded p-value: 2.99356182479473e-21\"\n```\n\n\n:::\n:::\n\n\nThe p-value of the ANOVA analysis is extremely significant\n(p-value = 2.994e-21),\nso we reject the null hypothesis that the mean\nsystolic blood pressure is equal for the different health groups.\nWe can say that the mean systolic blood pressure is significantly different\nbetween at least two health groups on the 5% significance level.\n\nBased on this analysis, we do not yet know between which particular\nbird types there is a significant difference. To study this, we will\nperfrom the Tuckey post-hoc analysis.\n\n## Post-hoc analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multcomp, quietly = TRUE)\nmcp <- glht(fit, linfct = mcp(HealthGen = \"Tukey\"))\nsummary(mcp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: lm(formula = log(BPSys1) ~ HealthGen, data = NHANES)\n\nLinear Hypotheses:\n                        Estimate Std. Error t value Pr(>|t|)    \nFair - Poor == 0       -0.015828   0.010971  -1.443  0.57592    \nGood - Poor == 0       -0.036762   0.010351  -3.551  0.00299 ** \nVgood - Poor == 0      -0.059415   0.010410  -5.708  < 0.001 ***\nExcellent - Poor == 0  -0.055476   0.011062  -5.015  < 0.001 ***\nGood - Fair == 0       -0.020934   0.005139  -4.074  < 0.001 ***\nVgood - Fair == 0      -0.043587   0.005256  -8.293  < 0.001 ***\nExcellent - Fair == 0  -0.039648   0.006452  -6.145  < 0.001 ***\nVgood - Good == 0      -0.022653   0.003797  -5.966  < 0.001 ***\nExcellent - Good == 0  -0.018714   0.005331  -3.511  0.00346 ** \nExcellent - Vgood == 0  0.003938   0.005444   0.723  0.94608    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(mcp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: lm(formula = log(BPSys1) ~ HealthGen, data = NHANES)\n\nQuantile = 2.6841\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                       Estimate  lwr       upr      \nFair - Poor == 0       -0.015828 -0.045274  0.013618\nGood - Poor == 0       -0.036762 -0.064545 -0.008978\nVgood - Poor == 0      -0.059415 -0.087356 -0.031474\nExcellent - Poor == 0  -0.055476 -0.085167 -0.025785\nGood - Fair == 0       -0.020934 -0.034727 -0.007140\nVgood - Fair == 0      -0.043587 -0.057694 -0.029479\nExcellent - Fair == 0  -0.039648 -0.056965 -0.022331\nVgood - Good == 0      -0.022653 -0.032844 -0.012462\nExcellent - Good == 0  -0.018714 -0.033023 -0.004406\nExcellent - Vgood == 0  0.003938 -0.010673  0.018550\n```\n\n\n:::\n:::\n\n\n## Conclusion\n\nWe have found an extremely significant dependence (p-value = 2.994e-21),\nbetween the mean systolic blood pressure and the health group\non the global 5% significance level.\n\nThe mean logarithm of systolic blood pressure in the self-reported health\ncategory `Poor` is significantly higher as compared three other groups:\n\n- the `Good` group (adjusted p-value = < 0.001, mean difference = -0.036762 mmHg, 95% CI [-0.034725; -0.007142])\n- the `Vgood` group (adjusted p-value = < 0.001, mean difference = -0.059415 mmHg, 95% CI [-0.087352; -0.031477])\n- the `Excellent` group (adjusted p-value = < 0.001, mean difference = -0.059415 mmHg, 95% CI [-0.085164; -0.025789])\n\nThe mean logarithm of  systolic blood pressure in the self-reported health\ncategory `Fair` is significantly higher as compared three other groups:\n\n- the `Good` group (adjusted p-value = 0.00317, mean difference = -0.020934  mmHg, 95% CI [-0.064542; -0.008982])\n- the `Vgood` group (adjusted p-value = < 0.001, mean difference = -0.043587 mmHg, 95% CI [-0.057692; -0.029481])\n- the `Excellent` group (adjusted p-value = < 0.001, mean difference = -0.039648 mmHg, 95% CI [-0.056963; -0.022333])\n\nThe mean logarithm of systolic blood pressure in the self-reported health\ncategory `Good` is significantly higher as compared two other groups:\n\n- the `Vgood` group (adjusted p-value = < 0.001, mean difference = -0.022653 mmHg, 95% CI [-0.032843; -0.012463])\n- the `Excellent` group (adjusted p-value = 0.00362, mean difference = -0.018714 mmHg, 95% CI [-0.033021; -0.004408])\n\nWe do not find enough evidence to claim a difference in systolic\nblood pressure levels between the other groups.\n\nNote that in order to interpret the outcomes on the original scale,\nwe should backtransform the outcomes with the `exp()` functions\n(interpretation on the geometric mean).\n",
    "supporting": [
      "07_3_NHANES_sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}