{
  "hash": "4183c1a6daddc93da56a8a274c292920",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercise 8.6: Blocking on the rat diet dataset - solution\"\nauthor: \"Lieven Clement, Jeroen Gilis and Milan Malfait\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\n---\n\n# Background\n\nResearchers are studying the impact of protein sources and protein levels in\nthe diet on the weight of rats. They feed the rats with diets of beef, cereal\nand pork and use a low and high protein level for each diet type.\nThe researchers can include 60 rats in the experiment. Prior to the experiment,\nthe rats were divided in 10 homogeneous groups of 6 rats based on\ncharacteristics such as initial weight, appetite, etc.\n\nWithin each group a rat is randomly assigned to a diet. The rats are fed during\na month and the weight gain in grams is recorded for each rat.\n\n# Experimental design\n\n- There are three explanatory variables in the experiment: the factor diet type\nwith three levels (beef, cereal and pork), factor protein level with levels\n(low and high) and a group blocking factor with 10 levels.\n\n- There are 6 treatments: beef-high, cereal-high, pork-high, beef-low,\ncereal-low, pork-low protein.\n\n- The rats are the experimental and observational units.\n\n- The weight gain is the response variable.\n\n- The experiment is a randomized complete block (RCB) design\n\nLoad libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n# Data import\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiet <- read.table(\"https://raw.githubusercontent.com/statOmics/PSLSData/main/dietRats.txt\",\n  header = TRUE\n)\nhead(diet)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"weightGain\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"protSource\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"protLevel\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"block\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"107\",\"2\":\"b\",\"3\":\"h\",\"4\":\"1\",\"_rn_\":\"1\"},{\"1\":\"96\",\"2\":\"c\",\"3\":\"h\",\"4\":\"1\",\"_rn_\":\"2\"},{\"1\":\"112\",\"2\":\"p\",\"3\":\"h\",\"4\":\"1\",\"_rn_\":\"3\"},{\"1\":\"83\",\"2\":\"b\",\"3\":\"l\",\"4\":\"1\",\"_rn_\":\"4\"},{\"1\":\"87\",\"2\":\"c\",\"3\":\"l\",\"4\":\"1\",\"_rn_\":\"5\"},{\"1\":\"90\",\"2\":\"p\",\"3\":\"l\",\"4\":\"1\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Tidy data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiet <- diet |>\n  ## Convert categorical levels to factors\n  mutate(\n    block = as.factor(block),\n    protSource = as.factor(protSource),\n    protLevel = as.factor(protLevel)\n  ) |>\n  ## Recode factors to make them more verbose\n  mutate(\n    protLevel = fct_recode(protLevel, high = \"h\", low = \"l\"),\n    protSource = fct_recode(protSource, beef = \"b\", cereal = \"c\", pork = \"p\")\n  ) |>\n  ## Set \"low\" as the reference level for `protLevel`\n  mutate(protLevel = fct_relevel(protLevel, \"low\"))\n\nhead(diet)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"weightGain\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"protSource\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"protLevel\"],\"name\":[3],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"block\"],\"name\":[4],\"type\":[\"fct\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"107\",\"2\":\"beef\",\"3\":\"high\",\"4\":\"1\",\"_rn_\":\"1\"},{\"1\":\"96\",\"2\":\"cereal\",\"3\":\"high\",\"4\":\"1\",\"_rn_\":\"2\"},{\"1\":\"112\",\"2\":\"pork\",\"3\":\"high\",\"4\":\"1\",\"_rn_\":\"3\"},{\"1\":\"83\",\"2\":\"beef\",\"3\":\"low\",\"4\":\"1\",\"_rn_\":\"4\"},{\"1\":\"87\",\"2\":\"cereal\",\"3\":\"low\",\"4\":\"1\",\"_rn_\":\"5\"},{\"1\":\"90\",\"2\":\"pork\",\"3\":\"low\",\"4\":\"1\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Data exploration\n\n- Boxplot of the weight gain against protein source, protein level with coloring according to block\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiet |>\n  ggplot(aes(x = protLevel, y = weightGain)) +\n  scale_fill_brewer(palette = \"RdGy\") +\n  theme_bw() +\n  geom_boxplot(outlier.shape = NA) +\n  geom_jitter(aes(color = block)) +\n  ggtitle(\"Weight gain dependence on protein source\") +\n  labs(x = \"Protein level\", y = \"Weight gain (g)\") +\n  stat_summary(\n    fun = mean, geom=\"point\",\n    shape=5, size=3, color=\"black\"\n  ) +\n  facet_wrap(vars(protSource))\n```\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n- Lineplot of the weight gain against protein source, protein level with coloring and grouping according to block\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiet |>\n  ggplot(aes(x = protLevel, y = weightGain, color = block)) +\n  scale_fill_brewer(palette = \"RdGy\") +\n  theme_bw() +\n  geom_line(aes(group = block)) +\n  geom_point() +\n  ggtitle(\"Weight gain dependence on protein source\") +\n  ylab(\"Weight gain (g)\") +\n  facet_wrap(vars(protSource))\n```\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n- An increase in the weight of the rats seems to depend on the protein source\nreceived in the diet.\n\n- The increase in the weight of the rats seems to depend on the level of protein\nreceived in the diet\n\n- There also seems to be an interaction effect between the protein level and the\nprotein source on the gain in weight of the rats. For the beef and the pork\ndiets the effect of high protein levels in the data seems to be much stronger\nthan in the cereal diet.\n\n- There is also a strong effect of the block. Blocking implies a randomisation\nrestriction, hence, we will have to include the block effect anyway.\n\n# Multivariate linear regression analysis\n\n## Assumptions\n\nList assumptions:\n\n1. The observations are independent\n2. Linearity between the response and predictor variable\n3. The residuals of the model must be normally distributed\n4. Homoscedasticity of the data\n\nThe first assumption is met if we correct for block in the model because the rats were randomized to the treatment within block. The other three assumptions can be assessed by\nfitting the linear model and calling the `plot()` function as follows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm1 <- lm(weightGain ~ block + protSource * protLevel, data = diet)\nplot(lm1)\n```\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-6-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-6-4.png){width=672}\n:::\n:::\n\n\nAll assumptions are met for this dataset.\n\n## Hypothesis testing\n\nWe here fit a linear model with a blocking factor for `block` and main and\ninteraction effects for protein source and protein level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weightGain ~ block + protSource * protLevel, data = diet)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-21.017  -5.183  -1.017   4.092  18.983 \n\nCoefficients:\n                               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                     88.3500     4.1728  21.173  < 2e-16 ***\nblock2                          -9.1667     4.8183  -1.902 0.063520 .  \nblock3                          -4.8333     4.8183  -1.003 0.321166    \nblock4                         -20.3333     4.8183  -4.220 0.000117 ***\nblock5                          -9.3333     4.8183  -1.937 0.059031 .  \nblock6                           0.6667     4.8183   0.138 0.890572    \nblock7                         -31.3333     4.8183  -6.503 5.58e-08 ***\nblock8                         -10.1667     4.8183  -2.110 0.040450 *  \nblock9                         -19.8333     4.8183  -4.116 0.000162 ***\nblock10                         -0.1667     4.8183  -0.035 0.972559    \nprotSourcecereal                 1.1000     3.7322   0.295 0.769556    \nprotSourcepork                   1.3000     3.7322   0.348 0.729226    \nprotLevelhigh                   20.0000     3.7322   5.359 2.76e-06 ***\nprotSourcecereal:protLevelhigh -18.2000     5.2782  -3.448 0.001236 ** \nprotSourcepork:protLevelhigh    -1.7000     5.2782  -0.322 0.748883    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.346 on 45 degrees of freedom\nMultiple R-squared:  0.7712,\tAdjusted R-squared:    0.7 \nF-statistic: 10.83 on 14 and 45 DF,  p-value: 3.726e-10\n```\n\n\n:::\n:::\n\n\n## Interpretation of the regression parameters\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ExploreModelMatrix)\nExploreModelMatrix::VisualizeDesign(diet, ~ block + protSource * protLevel)$plotlist\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`block = 1`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 10`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 2`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-8-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 3`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-8-4.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 4`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-8-5.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 5`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-8-6.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 6`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-8-7.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 7`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-8-8.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 8`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-8-9.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 9`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_6_rats_sol_files/figure-html/unnamed-chunk-8-10.png){width=672}\n:::\n:::\n\n\nThere are 3 levels for protein source, 2 levels for protein level and 10 levels\nfor the blocking variable. We will have one reference level for each respective\nvariable: beef, low, block 1. So we need 2, 1 and 9 dummy variables to introduce\nthe factors protein source, protein level and block in the linear model,\nrespectively.\n\nHence, we can write down the linear model as follows:\n\n$y_i=\\beta_0+\\beta_cx_{i,c} +\\beta_px_{i,p}+\\beta_hx_{i,h}+\\beta_{ch}x_{i,c}x_{i,h}+\\beta_{ph}x_{i,p}x_{i,h}+\\beta_{b2}x_{i,b2}+\\ldots+\\beta_{b10}x_{i,b10}+\\epsilon_{i}$\n\nwith:\n$y_i$ the observed weight gain for rat i,\n$x_{i,h}$ a dummy variable which is 1 if rat i receives a high protein diet\nand is 0 otherwise,\n$x_{i,c}$ a dummy variable which is 1 if rat i receives a cereal diet\nand is 0 otherwise,\n$x_{i,p}$ a dummy variable which is 1 if rat i receives a pork diet\nand is 0 otherwise and\n$x_{i,bk}$ is a dummy variable which is 1 if rat i belongs to block $bk$\nand is 0 otherwise, with $k \\in 2,\\ldots, 10$,\nand $\\epsilon_i$ an error term which is normally distributed with mean 0 and\nvariance $\\sigma^2$, i.e. $\\epsilon_i \\sim N(0,\\sigma^2)$.\n\n- Rats that are assigned to block $k$ and receive a beef based low protein diet have\n\ta covariate pattern $x_{i,h}=0$, $x_{i,c}=0$, $x_{i,p}=0$, $x_{i,bm}=0$ with $m\\neq k$ and $x_{i,bk}=1$.\n\tTheir mean weight gain is thus equal to $\\mu_{l,b,bk}=\\beta_0+\\beta_{bk}$\n\n- Rats that are assigned to block $k$ and receive a beef based high protein diet have\n\ta covariate pattern $x_{i,h}=1$, $x_{i,c}=0$, $x_{i,p}=0$, $x_{i,bm}=0$ with $m\\neq k$ and $x_{i,bk}=1$.\n\tTheir mean weight gain is thus equal to $\\mu_{h,b,bk}=\\beta_0+\\beta_h+\\beta_{bk}$\n\n- Rats that are assigned to block $k$ and receive a cereal based low protein diet have\n\ta covariate pattern $x_{i,h}=0$, $x_{i,c}=1$, $x_{i,p}=0$, $x_{i,bm}=0$ with $m\\neq k$ and $x_{i,bk}=1$.\n\tTheir mean weight gain is thus equal to $\\mu_{h,c,bk}=\\beta_0+\\beta_c+\\beta_{bk}$\n\n- Rats that are assigned to block $k$ and receive a cereal based heigh protein diet have\n\ta covariate pattern $x_{i,h}=1$, $x_{i,c}=1$, $x_{i,p}=0$, $x_{i,bm}=0$ with $m\\neq k$ and $x_{i,bk}=1$.\n\tTheir mean weight gain is thus equal to $\\mu_{h,c,bk}=\\beta_0+\\beta_h+\\beta_c+\\beta_{ch}+\\beta_{bk}$\n\n- Rats that are assigned to block $k$ and receive a pork based low protein diet have\n\ta covariate pattern $x_{i,h}=0$,  $x_{i,c}=0$, $x_{i,p}=1$, $x_{i,bm}=0$ with $m\\neq k$ and $x_{i,bk}=1$.\n\tTheir mean weight gain is thus equal to $\\mu_{l,p,bk}=\\beta_0+\\beta_p+\\beta_{bk}$\n\n- Rats that are assigned to block $k$ and receive a pork based heigh protein diet have\n\ta covariate pattern $x_{i,h}=1$, $x_{i,c}=0$, $x_{i,p}=1$, $x_{i,bm}=0$ with $m\\neq k$ and $x_{i,bk}=1$.\n\tThere mean weight gain is thus equal to $\\mu_{h,p,bk}=\\beta_0+\\beta_h+\\beta_p+\\beta_{ph}+\\beta_{bk}$\n\nWe can now relate this to the output of the `lm` function:\n\n- The intercept $\\beta_0$ is thus the average weight increase in the low beef\ndiet for rats in block 1.\n\n- The parameter $\\beta_c$: the average difference in weight gain between cereal-low and\nbeef-low diet is 1.1g.\n\n- The parameter $\\beta_p$: the average difference in weight gain between pork-low and\nbeef-low diet is 1.3g.\n\n- The parameter $\\beta_h$: the average difference in weight gain between beef-high and\nbeef-Low diet is 20g.\n\n- The parameter $\\beta_{ch}$ is the difference in the average weight gain difference\ndue to the high protein level as compared to the low protein level for cereal diets\nas compared to the weight gain difference that occurs due to the protein level\nin the reference class (here beef diet). Here this is negative,\ni.e. -18.2g, thus the weight gain\nfor the cereal protein source increases on average less between high and low protein diets\nthan in beef based diets.\n\n- The parameter $\\beta_{ph}$ is the difference in the average weight gain difference\ndue to the high protein level as compared to the low protein level for pork diets\nas compared to the weight gain difference that occurs due to the protein level\nin the reference class (here beef diet). Here this is negative,\ni.e. -1.7g, thus the weight gain\nfor the proc protein source increases on average less between high and low protein diets\nthan in beef based diets.\n\n## Testing the overall (combined) effect of diet\n\nBecause there are multiple factors with different levels in the model,\nwe can first assess the effect of the diet (protein Level, protein source\nand the interaction) by using anova. With this test we will assess the null\nhypothesis that the average weight gain in each treatment is equal: i.e. $H_0: \\mu_{b,l}=\\mu_{b,h}=\\mu_{c,h}=\\mu_{c,l}=\\mu_{p,h}=\\mu_{p,h}$ versus\nthe alternative hyptohesis $H_1:$ that at least two treatment means are\ndifferent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm0 <- lm(weightGain ~ block, data = diet)\nanova(lm0, lm1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"RSS\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sum of Sq\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"50\",\"2\":\"7728.833\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\",\"6\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"45\",\"2\":\"3134.150\",\"3\":\"5\",\"4\":\"4594.683\",\"5\":\"13.19406\",\"6\":\"6.308133e-08\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nWe can conclude that there is an extremely significant effect of the diet type\n(protein source and/or protein level and/or protein source-protein level\ninteraction) on the weight gain of rats (p << 0.001).\n\n## Assessing the interaction effect between protein source and protein level\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nAnova(lm1, type = \"III\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Sum Sq\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"31222.890\",\"2\":\"1\",\"3\":\"448.297002\",\"4\":\"4.955763e-25\",\"_rn_\":\"(Intercept)\"},{\"1\":\"5969.350\",\"2\":\"9\",\"3\":\"9.523076\",\"4\":\"6.083601e-08\",\"_rn_\":\"block\"},{\"1\":\"9.800\",\"2\":\"2\",\"3\":\"0.070354\",\"4\":\"9.321661e-01\",\"_rn_\":\"protSource\"},{\"1\":\"2000.000\",\"2\":\"1\",\"3\":\"28.715920\",\"4\":\"2.762595e-06\",\"_rn_\":\"protLevel\"},{\"1\":\"1010.633\",\"2\":\"2\",\"3\":\"7.255316\",\"4\":\"1.857393e-03\",\"_rn_\":\"protSource:protLevel\"},{\"1\":\"3134.150\",\"2\":\"45\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThere is a very significant interaction between the protein source and\nthe protein level (p = 2e-03). This indicates that the average weight increase due to\nthe protein level differs according to the protein source.\nHence, we cannot assess the effect of the protein source and/or protein level\nindependently because there effects of the protein source vary according to\nthe protein level.\n\n## Assessing specific contrasts\n\nImagine that we are interested in assessing if there is an effect of\n\n1. protein source in the low protein diets\n\t- $\\mu_{c,l}-\\mu_{b,l} = \\beta_c$\n\t- $\\mu_{p,l}-\\mu_{b,l} = \\beta_p$\n\t- $\\mu_{c,l}-\\mu_{p,l}= \\beta_c-\\beta_p$)\n\n\n2. protein source in high protein diets\n\t- $\\mu_{c,h}-\\mu_{b,h}=\\beta_c+\\beta_{ch}$\n\t- $\\mu_{p,h}-\\mu_{b,h}=\\beta_p+\\beta_{ph}$\n\t- $\\mu_{p,h}-\\mu_{c,h}=(\\beta_c+\\beta_{ch})-(\\beta_p+\\beta_{ph})$\n\n\n3. protein level for\n\t- beef diets ($\\mu_{b,h}-\\mu_{b,l}=\\beta_h$),\n\t- cereal diets  ($\\mu_{c,h}-\\mu_{c,l}=\\beta_h+\\beta_{ch}$) and\n\t- pork diets  ($\\mu_{p,h}-\\mu_{p,l}=\\beta_h+\\beta_{ph}$).\n\n\n4. If the effect of the protein level differs between\n\t- beef and cereal  $(\\mu_{c,h}-\\mu_{c,l}) - (\\mu_{b,h}-\\mu_{b,l})=\\beta_{ch}$\n\t- beef and pork $(\\mu_{p,h}-\\mu_{p,l}) - (\\mu_{c,h}-\\mu_{c,l})=\\beta_{ph}$ and\n\t- cereal and pork diets $(\\mu_{c,h}-\\mu_{c,l}) - (\\mu_{p,h}-\\mu_{p,l})=\\beta_{ch}-\\beta_{ph}$.\n\nThese effects of interest are so-called\n**contrasts, i.e. linear combinations of the parameters**.\n\nWe can define the contrasts and assess the significance of the contrasts with\nthe code below. The contrasts are given as input in the form of symbolic\ndescriptions to the `linfct` argument of the `glht` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multcomp)\nset.seed(75468) # to get reproducible results (small effect if removed)\nlm1MultComp <- glht(\n  model = lm1,\n  linfct = c(\n    \"protSourcecereal = 0\",\n    \"protSourcepork = 0\",\n    \"protSourcecereal- protSourcepork = 0\",\n    \"protSourcecereal + protSourcecereal:protLevelhigh = 0\",\n    \"protSourcepork + protSourcepork:protLevelhigh = 0\",\n    \"(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) = 0\",\n    \"protLevelhigh = 0\",\n    \"protLevelhigh +  protSourcecereal:protLevelhigh = 0\",\n    \"protLevelhigh +  protSourcepork:protLevelhigh = 0\",\n    \"protSourcecereal:protLevelhigh = 0\",\n    \"protSourcepork:protLevelhigh = 0\",\n    \"protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh = 0\"\n  )\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm1MultComp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nFit: lm(formula = weightGain ~ block + protSource * protLevel, data = diet)\n\nLinear Hypotheses:\n                                                                                                           Estimate\nprotSourcecereal == 0                                                                                         1.100\nprotSourcepork == 0                                                                                           1.300\nprotSourcecereal - protSourcepork == 0                                                                       -0.200\nprotSourcecereal + protSourcecereal:protLevelhigh == 0                                                      -17.100\nprotSourcepork + protSourcepork:protLevelhigh == 0                                                           -0.400\n(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0  -16.700\nprotLevelhigh == 0                                                                                           20.000\nprotLevelhigh + protSourcecereal:protLevelhigh == 0                                                           1.800\nprotLevelhigh + protSourcepork:protLevelhigh == 0                                                            18.300\nprotSourcecereal:protLevelhigh == 0                                                                         -18.200\nprotSourcepork:protLevelhigh == 0                                                                            -1.700\nprotSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                          -16.500\n                                                                                                           Std. Error\nprotSourcecereal == 0                                                                                           3.732\nprotSourcepork == 0                                                                                             3.732\nprotSourcecereal - protSourcepork == 0                                                                          3.732\nprotSourcecereal + protSourcecereal:protLevelhigh == 0                                                          3.732\nprotSourcepork + protSourcepork:protLevelhigh == 0                                                              3.732\n(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0      3.732\nprotLevelhigh == 0                                                                                              3.732\nprotLevelhigh + protSourcecereal:protLevelhigh == 0                                                             3.732\nprotLevelhigh + protSourcepork:protLevelhigh == 0                                                               3.732\nprotSourcecereal:protLevelhigh == 0                                                                             5.278\nprotSourcepork:protLevelhigh == 0                                                                               5.278\nprotSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                              5.278\n                                                                                                           t value\nprotSourcecereal == 0                                                                                        0.295\nprotSourcepork == 0                                                                                          0.348\nprotSourcecereal - protSourcepork == 0                                                                      -0.054\nprotSourcecereal + protSourcecereal:protLevelhigh == 0                                                      -4.582\nprotSourcepork + protSourcepork:protLevelhigh == 0                                                          -0.107\n(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0  -4.475\nprotLevelhigh == 0                                                                                           5.359\nprotLevelhigh + protSourcecereal:protLevelhigh == 0                                                          0.482\nprotLevelhigh + protSourcepork:protLevelhigh == 0                                                            4.903\nprotSourcecereal:protLevelhigh == 0                                                                         -3.448\nprotSourcepork:protLevelhigh == 0                                                                           -0.322\nprotSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                          -3.126\n                                                                                                           Pr(>|t|)\nprotSourcecereal == 0                                                                                        0.9995\nprotSourcepork == 0                                                                                          0.9989\nprotSourcecereal - protSourcepork == 0                                                                       1.0000\nprotSourcecereal + protSourcecereal:protLevelhigh == 0                                                       <0.001\nprotSourcepork + protSourcepork:protLevelhigh == 0                                                           1.0000\n(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0   <0.001\nprotLevelhigh == 0                                                                                           <0.001\nprotLevelhigh + protSourcecereal:protLevelhigh == 0                                                          0.9949\nprotLevelhigh + protSourcepork:protLevelhigh == 0                                                            <0.001\nprotSourcecereal:protLevelhigh == 0                                                                          0.0118\nprotSourcepork:protLevelhigh == 0                                                                            0.9993\nprotSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                           0.0265\n                                                                                                              \nprotSourcecereal == 0                                                                                         \nprotSourcepork == 0                                                                                           \nprotSourcecereal - protSourcepork == 0                                                                        \nprotSourcecereal + protSourcecereal:protLevelhigh == 0                                                     ***\nprotSourcepork + protSourcepork:protLevelhigh == 0                                                            \n(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0 ***\nprotLevelhigh == 0                                                                                         ***\nprotLevelhigh + protSourcecereal:protLevelhigh == 0                                                           \nprotLevelhigh + protSourcepork:protLevelhigh == 0                                                          ***\nprotSourcecereal:protLevelhigh == 0                                                                        *  \nprotSourcepork:protLevelhigh == 0                                                                             \nprotSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                         *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lm1MultComp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nFit: lm(formula = weightGain ~ block + protSource * protLevel, data = diet)\n\nQuantile = 2.8765\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                                                                                                           Estimate\nprotSourcecereal == 0                                                                                        1.1000\nprotSourcepork == 0                                                                                          1.3000\nprotSourcecereal - protSourcepork == 0                                                                      -0.2000\nprotSourcecereal + protSourcecereal:protLevelhigh == 0                                                     -17.1000\nprotSourcepork + protSourcepork:protLevelhigh == 0                                                          -0.4000\n(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0 -16.7000\nprotLevelhigh == 0                                                                                          20.0000\nprotLevelhigh + protSourcecereal:protLevelhigh == 0                                                          1.8000\nprotLevelhigh + protSourcepork:protLevelhigh == 0                                                           18.3000\nprotSourcecereal:protLevelhigh == 0                                                                        -18.2000\nprotSourcepork:protLevelhigh == 0                                                                           -1.7000\nprotSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                         -16.5000\n                                                                                                           lwr     \nprotSourcecereal == 0                                                                                       -9.6358\nprotSourcepork == 0                                                                                         -9.4358\nprotSourcecereal - protSourcepork == 0                                                                     -10.9358\nprotSourcecereal + protSourcecereal:protLevelhigh == 0                                                     -27.8358\nprotSourcepork + protSourcepork:protLevelhigh == 0                                                         -11.1358\n(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0 -27.4358\nprotLevelhigh == 0                                                                                           9.2642\nprotLevelhigh + protSourcecereal:protLevelhigh == 0                                                         -8.9358\nprotLevelhigh + protSourcepork:protLevelhigh == 0                                                            7.5642\nprotSourcecereal:protLevelhigh == 0                                                                        -33.3827\nprotSourcepork:protLevelhigh == 0                                                                          -16.8827\nprotSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                         -31.6827\n                                                                                                           upr     \nprotSourcecereal == 0                                                                                       11.8358\nprotSourcepork == 0                                                                                         12.0358\nprotSourcecereal - protSourcepork == 0                                                                      10.5358\nprotSourcecereal + protSourcecereal:protLevelhigh == 0                                                      -6.3642\nprotSourcepork + protSourcepork:protLevelhigh == 0                                                          10.3358\n(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0  -5.9642\nprotLevelhigh == 0                                                                                          30.7358\nprotLevelhigh + protSourcecereal:protLevelhigh == 0                                                         12.5358\nprotLevelhigh + protSourcepork:protLevelhigh == 0                                                           29.0358\nprotSourcecereal:protLevelhigh == 0                                                                         -3.0173\nprotSourcepork:protLevelhigh == 0                                                                           13.4827\nprotSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                          -1.3173\n```\n\n\n:::\n:::\n\n\nNote that the p-values and the confidence intervals are automatically corrected\nfor multiple testing.\n\n# Conclusion\n\n- There is an extremely significant effect of the type of protein diet on the\nweight gain of rats  (p<<1e-6). The interaction between protein type and protein\nsource is also very significant (p=0.0019).\n\n- The average weight gain does not vary significantly according to protein\nsource in the diets with low protein levels (all p>0.99).\n\n- The weight gain in the cereal diet at high protein concentration is on\naverage 17.1g and 16.7g g lower than in the high protein beef and pork diet,\nrespectively (95% CI [6.4, 27.8] and [6, 27.4]) and the differences are\nextremely significant (p<0.001). The average weight gains after meat based\ndiets at high protein levels, however, do not differ significantly\n(p>0.99).\n\n- We also discovered an extremely significant difference in weight gain\naccording to the protein level for beef and pork based diets (p<0.001).\nThe weight gain on average increases with 20g and 18.3g in the high protein\nlevel as compared to the low protein beef and pork diet, respectively\n(95%CI [9.3, 30.7] and [7.6, 29]). The protein level effect is not significant\nfor the cereal diet (p>0.99).\n\n- Finally significant interactions between protein level and protein source were\nfound (p<0.05), i.e. the increase in weight gain due to protein level in cereal\nbased diets was 18.2g and 16.5g lower than that of beef and pork based diets,\nrespectively (95% CI [3g,33.4g] and [1.3g,31.7g]). The average difference in\nincrease in weight gain due to protein level among the meat based diets was not\nsignificant (p>0.99).\n\nAll reported p-values and confidence intervals were corrected for multiple\ntesting\n",
    "supporting": [
      "08_6_rats_sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}