{
  "hash": "dcf8964970e6cd51c838a2f34815ba72",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercise 7.1: ANOVA on the lettuce dataset - solution\"\nauthor: \"Lieven Clement and Jeroen Gilis\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\n---\n\n# Background\n\nIn agriculture, it is important to have a high yield of crops. For lettuce\nplants, plants with many leaves are known to be preferred by the consumers.\n\nOne way to increase the number of leaves (or better, total\nleaf weight) is by using a fertilizer. Recently, there has been\na tendency to rely more on natural fertilizers, such as compost.\nNear Ghent, the institute of research for agriculture and fishery is testing\nnew, natural fertilization methods. One of these new fertilizers is called\nbiochar. Biochar is a residual product from pyrolysis, a process in which\nbiomass is burned under specific conditions (such as high pressure) in order\nto produce energy. Biochar is similar to charcoal, but has some very useful\nproperties, such as retaining water in the soil. It also has a positive\ninfluence on the soil microbiome.\n\n# The lettuce dataset\n\nThe researchers hypothesize that biochar, compost and\na combination of both biochar and compost can have a different influence\non the growth of lettuce plants. To this end, they grew up\nlettuce plants in a greenhouse. The pots were filled with\none of four soil types;\n\n1. Soil only (control)\n2. Soil supplemented with biochar (refoak)\n3. Soil supplemented with compost (compost)\n4. Soil supplemented with both biochar and compost (cobc)\n\nThe dataset `freshweight_lettuce.txt` contains the freshweight\n(in grams) for 28 lettuce plants (7 per condition). The researchers\nwant to use an ANOVA test to assess if the treatments have a different effect\non the growth of lettuce plants. If so, they will use a post-hoc test\n(Tuckey test) to discover which specific treatments have an effect.\n\nLoad the required libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ntheme_set(theme_bw()) # Change ggplot2 default theme\n\nlibrary(multcomp)\n```\n:::\n\n\n# Data import\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlettuce <- read_csv(\"https://raw.githubusercontent.com/statOmics/PSLSData/main/freshweight_lettuce.txt\")\n# Take a glimpse at the data\nglimpse(lettuce)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 28\nColumns: 3\n$ id          <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…\n$ treatment   <chr> \"control\", \"control\", \"control\", \"control\", \"control\", \"co…\n$ freshweight <dbl> 38, 34, 41, 43, 43, 29, 38, 59, 64, 57, 56, 50, 64, 62, 38…\n```\n\n\n:::\n:::\n\n\nFirst, we will set the `treatment` variable to a factor\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlettuce <- lettuce |>\n  mutate(\n    ## Convert treatment to factor\n    treatment = as.factor(treatment),\n    ## Relevels such that \"control\" is the reference\n    treatment = relevel(treatment, ref = \"control\")\n  )\n```\n:::\n\n\n# Data exploration\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Count the number of observations per treatment\nlettuce |>\n  count(treatment)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"treatment\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"control\",\"2\":\"7\"},{\"1\":\"cobc\",\"2\":\"7\"},{\"1\":\"compost\",\"2\":\"7\"},{\"1\":\"refoak\",\"2\":\"7\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNow let's make a boxplot displaying the freshweight of each treatment condition:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot <- lettuce |>\n  ggplot(aes(x = treatment, y = freshweight, fill = treatment)) +\n  scale_fill_brewer(palette = \"RdGy\") +\n  geom_boxplot(outlier.shape = NA) +\n  geom_jitter(width = 0.2) +\n  ggtitle(\"Boxplot of the freshweigth for each treatment condition\") +\n  ylab(\"freshweight (gram)\") +\n  stat_summary(\n    fun = mean, geom = \"point\",\n    shape = 5, size = 3, color = \"black\"\n  )\nboxplot\n```\n\n::: {.cell-output-display}\n![](07_1_lettuce_sol_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nNote that there are no clear outliers in the data.\nWe can see that the mean freshweight is very comparable\nbetween the control and refoak treatments and between the\ncompost and cobc treatments. We can also see that the mean\nfreshweight is much higher in the cobc and control treatments\nthan in the control and refoak treatments. But is this\nobserved difference significant?\n\n# ANOVA\n\nTo study if the observed difference between the\naverage freshweight values of the different treatment groups\nare significant, we may perform an ANOVA.\n\n## Formulate null and alternative hypotheses\n\nThe null hypothesis of ANOVA states that:\n$H0$: The mean freshweigth is equal between the different treatment groups.\n\nThe alternative hypothesis of ANOVA states that:\n$HA$: The mean freshweigth for at least one treatment group is different\nfrom the mean freshweight in at least one other treatment group.\n\n## Checking the assumptions for ANOVA\n\nBefore we may proceed with the analysis, we must make sure that all\nassumptions for ANOVA are met. ANOVA has three assumptions:\n\n1. The observations are independent of each other (in all groups)\n2. The data (freshweigth) must be normally distributed (in all groups)\n3. The variability within all groups is similar\n\n### Assumption of independence\n\nThe first assumption is met; we started of with 28 lettuce plants and\nwe randomly submitted them to one of four treatment conditions. There\nis no reason to believe that the plants display systematic differences\nbetween treatment groups, other than the actual treatment.\n\n### Assumption of normality\n\nFor the second assumption, we must check normality in each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lettuce, aes(sample = freshweight)) +\n  geom_qq() +\n  geom_qq_line(aes(col = treatment), show.legend = FALSE) +\n  scale_color_brewer(palette = \"Dark2\") +\n  facet_wrap(vars(treatment))\n```\n\n::: {.cell-output-display}\n![](07_1_lettuce_sol_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nAccording to these plots, the normality assumption is met\nfor each group. However, we need to be careful with relying on\nthese plots, as they are only based on 7 observations per group.\nIndeed, checking the assumptions of normality (and equal variances)\non such small datasets can be tricky. For instance, when\nsampling 7 datapoints from data that has an underlying distribution\nthat is not normally distributed, the small sample may be normally\ndistributed by chance. Equivalently, when sampling 7 datapoints\nfrom a normal distribution, the small sample may appear not normally\ndistributed. We can show this as follows.\n\nSimulate from uniform distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(5)\n\n## sample 7 observations from a uniform distribution, repeat 6 times\ndf <- data.frame(x = runif(7 * 6), rep = rep(1:6, each = 7))\nggplot(df, aes(sample = x)) +\n  geom_qq() +\n  geom_qq_line(col = \"darkorchid\") +\n  facet_wrap(vars(rep)) +\n  ggtitle(\"QQ plots for uniformly distributed data\")\n```\n\n::: {.cell-output-display}\n![](07_1_lettuce_sol_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nEven though the data originates from a uniform distribution, several\nsamples meet the normality requirements by chance.\n\nSample from normal distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(5)\n## sample 7 observations from a normal distribution, repeat 6 times\ndf <- data.frame(x = rnorm(7 * 6), rep = rep(1:6, each = 7))\nggplot(df, aes(sample = x)) +\n  geom_qq() +\n  geom_qq_line(col = \"dodgerblue\") +\n  facet_wrap(vars(rep)) +\n  ggtitle(\"QQ plots for normally distributed data\")\n```\n\n::: {.cell-output-display}\n![](07_1_lettuce_sol_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nEven though the data originates from a normal distribution, some deviations\ncan be observed due to random chance.\n\nAlternatively, we may generate a qq-plot of the residuals\nof a linear model. These residuals should be normally distributed\nif the data for each treatment condition is normally distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(freshweight ~ treatment, lettuce)\nplot(fit, which = 2, col = fit$model$treatment)\nlegend(\"bottomright\", levels(fit$model$treatment), text.col = 1:4)\n```\n\n::: {.cell-output-display}\n![](07_1_lettuce_sol_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe Q-Q plot of the residuals shows a slight skew to the left. Care should be\ntaken when interpreting the results for this dataset. Due to the sample size, a\nbetter alternative might be a non-parametric approach.\n\n\n### Assumption of equal variances\n\nWe can check the assumption of equal variance with a boxplot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot\n```\n\n::: {.cell-output-display}\n![](07_1_lettuce_sol_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nAs a measure of variability, we may take the height\nof each box. This is the interval between\nthe 25% and 75% quantile. Here we can see that this\ninterval, as well as the length of the whiskers, is\napproximately equal for most groups. However, the\nvariability of cobc does seem to be quite a bit larger\nthan the variability in the refoak group.\n\nWith this little observations per group, it is very\ndifficult to reliably assess the assumptions of normality and equal variances.\nIn this tutorial, we will assume that all assumptions are met.\n**In a later tutorial, \"Kruskal_lettuce_plants.Rmd\",**\n**we will see would happen if we decide to reject these assumptions.**\n\n## Modeling\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(freshweight ~ treatment, data = lettuce)\nfit_anova <- anova(fit)\nfit_anova\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Sum Sq\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Mean Sq\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"3\",\"2\":\"2732.1429\",\"3\":\"910.71429\",\"4\":\"34.01512\",\"5\":\"8.307623e-09\",\"_rn_\":\"treatment\"},{\"1\":\"24\",\"2\":\"642.5714\",\"3\":\"26.77381\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe p-value of the ANOVA analysis is extremely significant\n(p-value = 8.308e-09),\nso we reject the null hypothesis that the mean\nfreshweigth is equal for the different treatment groups.\nWe can say that the mean freshweigth is significantly different\nbetween at least two treatment groups on the 5% significance level.\n\nBased on this analysis, we do not yet know between which particular\ngroups there is a significant difference. To assess this, we will\nperfrom the Tuckey post-hoc analysis.\n\n## Post-hoc analysis\n\nWe will perform a post-hoc analysis to look at the difference\nin fresweigth between each pairwise comparison of treatment groups.\nImportantly, with this strategy, the p-values will be automatically\nadjusted for multiple testing.\n\nThe null hypothesis for each pairwise test is that\n$H0$ there is no difference in the average freshweight values between\nboth groups.\n\nThe alternative hypothesis for each pairwise test states that\n$HA$ there is indeed a difference in the average freshweight values\nbetween both groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcp <- glht(fit, linfct = mcp(treatment = \"Tukey\"))\nmcp_summary <- summary(mcp)\nmcp_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: lm(formula = freshweight ~ treatment, data = lettuce)\n\nLinear Hypotheses:\n                       Estimate Std. Error t value Pr(>|t|)    \ncobc - control == 0      16.143      2.766   5.837   <0.001 ***\ncompost - control == 0   20.857      2.766   7.541   <0.001 ***\nrefoak - control == 0    -1.857      2.766  -0.671    0.907    \ncompost - cobc == 0       4.714      2.766   1.704    0.343    \nrefoak - cobc == 0      -18.000      2.766  -6.508   <0.001 ***\nrefoak - compost == 0   -22.714      2.766  -8.213   <0.001 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n\n```{.r .cell-code}\n# We will also calculate the confidence interval on the mean differences.\nmcp_confint <- confint(mcp)\nmcp_confint\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: lm(formula = freshweight ~ treatment, data = lettuce)\n\nQuantile = 2.7597\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                       Estimate lwr      upr     \ncobc - control == 0     16.1429   8.5101  23.7757\ncompost - control == 0  20.8571  13.2243  28.4899\nrefoak - control == 0   -1.8571  -9.4899   5.7757\ncompost - cobc == 0      4.7143  -2.9185  12.3471\nrefoak - cobc == 0     -18.0000 -25.6328 -10.3672\nrefoak - compost == 0  -22.7143 -30.3471 -15.0815\n```\n\n\n:::\n:::\n\n\n## Conclusion\n\nWe have found an extremely significant dependence\n(p-value = 8.308\\times 10^{-9}),\nbetween the mean freshweigth and the treatment condition\non the global 5% significance level.\n\nThe mean freshweight of plants grown with compost is extremely\nsignificantly higher as compared to in control plants (Tuckey test,\nadjusted p-value < 0.0001, 20.9g higher, 95% CI: [13.2; 28.5])\nand as compared to refoak plants (Tuckey test, adjusted\np-value < 0.0001, 22.7g higher, 95% CI: [15.1; 30.3]).\n\nThe mean freshweight of plants grown with cobc is extremely\nsignificantly higher as compared to in control plants (Tuckey test,\nadjusted p-value < 0.0001, 16.1g higher, 95% CI: [8.5; 23.8])\nand as compared to refoak plants (Tuckey test, adjusted\np-value < 0.0001, 18.0g higher, 95% CI: [10.4; 25.6]).\n\nWe do not find enough evidence to claim a difference in mean\nfreshweight between refoak and control plants or between cobc\nand compost plants.\n\nWe may conclude that supplementing soil with compost or with\nboth compost and biochar will have a positive effect on the\nfreshweigth of lettuce plants.\n",
    "supporting": [
      "07_1_lettuce_sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}