{
  "hash": "38e1d2eae8dd6d5ff4f77ec0382da993",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"8. Multiple regression\"\nauthor: \"Lieven Clement\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html: default\n  pdf: default\n---\n\n\n<a rel=\"license\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png\" /></a>\n\n\n\n\n\n# Intro\n\n- Until now: one outcome $Y$ and a single  predictor $X$.\n- Often useful to use multiple predictors to model the response. e.g\n\n1. Association between X and Y is affected by confounder: Smoking and age by youngsters are confounded and they both affect the lung capacity\n2. Which group of variables is associated with a given outcome. E.g Habitat and human activity on the biodiversity of the rain forest. (Size, age, height of the wood $\\rightarrow$ assess all effects simultaneously.\n3. Prediction of outcome for individuals: use as many predictive information simultaneously. E.g prediction of risk on mortality is used on a daily basis in intensive care units to prioritise patient care.\n\n$\\rightarrow$ Extend simple linear regression to multiple predictors.\n\n---\n\n## Prostate cancer example\n\n- Prostate specific antigen (PSA) and a number of clinical variables for 97 males with radical prostatectomy.\n- Association of PSA by\n\n    - tumor volume (lcavol)\n    - prostate weight (lweight)\n    - age\n    - benign prostate hypertrophy  (lbph)\n    - seminal vesicle invasion (svi)\n    - capsular penetration (lcp)\n    - Gleason score (gleason)\n    - precentage gleason score 4/5 (pgg45)\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprostate <- read_csv(\"https://raw.githubusercontent.com/GTPB/PSLS20/master/data/prostate.csv\")\nprostate\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"lcavol\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"lweight\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"age\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"lbph\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"svi\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"lcp\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gleason\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"pgg45\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"lpsa\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"-0.579818495\",\"2\":\"2.769459\",\"3\":\"50\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"-0.4307829\"},{\"1\":\"-0.994252273\",\"2\":\"3.319626\",\"3\":\"58\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"-0.1625189\"},{\"1\":\"-0.510825624\",\"2\":\"2.691243\",\"3\":\"74\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"20\",\"9\":\"-0.1625189\"},{\"1\":\"-1.203972804\",\"2\":\"3.282789\",\"3\":\"58\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"-0.1625189\"},{\"1\":\"0.751416089\",\"2\":\"3.432373\",\"3\":\"62\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"0.3715636\"},{\"1\":\"-1.049822124\",\"2\":\"3.228826\",\"3\":\"50\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"0.7654678\"},{\"1\":\"0.737164066\",\"2\":\"3.473518\",\"3\":\"64\",\"4\":\"0.61518564\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"0.7654678\"},{\"1\":\"0.693147181\",\"2\":\"3.539509\",\"3\":\"58\",\"4\":\"1.53686722\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"0.8544153\"},{\"1\":\"-0.776528789\",\"2\":\"3.539509\",\"3\":\"47\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.0473190\"},{\"1\":\"0.223143551\",\"2\":\"3.244544\",\"3\":\"63\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.0473190\"},{\"1\":\"0.254642218\",\"2\":\"3.604138\",\"3\":\"65\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.2669476\"},{\"1\":\"-1.347073648\",\"2\":\"3.598681\",\"3\":\"63\",\"4\":\"1.26694760\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.2669476\"},{\"1\":\"1.613429934\",\"2\":\"3.022861\",\"3\":\"63\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-0.59783700\",\"7\":\"7\",\"8\":\"30\",\"9\":\"1.2669476\"},{\"1\":\"1.477048724\",\"2\":\"2.998229\",\"3\":\"67\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"5\",\"9\":\"1.3480731\"},{\"1\":\"1.205970807\",\"2\":\"3.442019\",\"3\":\"57\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-0.43078292\",\"7\":\"7\",\"8\":\"5\",\"9\":\"1.3987169\"},{\"1\":\"1.541159072\",\"2\":\"3.061052\",\"3\":\"66\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.4469190\"},{\"1\":\"-0.415515444\",\"2\":\"3.516013\",\"3\":\"70\",\"4\":\"1.24415459\",\"5\":\"healthy\",\"6\":\"-0.59783700\",\"7\":\"7\",\"8\":\"30\",\"9\":\"1.4701758\"},{\"1\":\"2.288486169\",\"2\":\"3.649359\",\"3\":\"66\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"0.37156356\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.4929041\"},{\"1\":\"-0.562118918\",\"2\":\"3.267666\",\"3\":\"41\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.5581446\"},{\"1\":\"0.182321557\",\"2\":\"3.825375\",\"3\":\"70\",\"4\":\"1.65822808\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.5993876\"},{\"1\":\"1.147402453\",\"2\":\"3.419365\",\"3\":\"59\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.6389967\"},{\"1\":\"2.059238834\",\"2\":\"3.501043\",\"3\":\"60\",\"4\":\"1.47476301\",\"5\":\"healthy\",\"6\":\"1.34807315\",\"7\":\"7\",\"8\":\"20\",\"9\":\"1.6582281\"},{\"1\":\"-0.544727175\",\"2\":\"3.375880\",\"3\":\"59\",\"4\":\"-0.79850770\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.6956156\"},{\"1\":\"1.781709133\",\"2\":\"3.451574\",\"3\":\"63\",\"4\":\"0.43825493\",\"5\":\"healthy\",\"6\":\"1.17865500\",\"7\":\"7\",\"8\":\"60\",\"9\":\"1.7137979\"},{\"1\":\"0.385262401\",\"2\":\"3.667400\",\"3\":\"69\",\"4\":\"1.59938758\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.7316555\"},{\"1\":\"1.446918983\",\"2\":\"3.124565\",\"3\":\"68\",\"4\":\"0.30010459\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.7664417\"},{\"1\":\"0.512823626\",\"2\":\"3.719651\",\"3\":\"65\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-0.79850770\",\"7\":\"7\",\"8\":\"70\",\"9\":\"1.8000583\"},{\"1\":\"-0.400477567\",\"2\":\"3.865979\",\"3\":\"67\",\"4\":\"1.81645208\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"20\",\"9\":\"1.8164521\"},{\"1\":\"1.040276712\",\"2\":\"3.128951\",\"3\":\"67\",\"4\":\"0.22314355\",\"5\":\"healthy\",\"6\":\"0.04879016\",\"7\":\"7\",\"8\":\"80\",\"9\":\"1.8484548\"},{\"1\":\"2.409644165\",\"2\":\"3.375880\",\"3\":\"65\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"1.61938824\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.8946169\"},{\"1\":\"0.285178942\",\"2\":\"4.090169\",\"3\":\"65\",\"4\":\"1.96290772\",\"5\":\"healthy\",\"6\":\"-0.79850770\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"1.9242487\"},{\"1\":\"0.182321557\",\"2\":\"6.107580\",\"3\":\"65\",\"4\":\"1.70474809\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.0082140\"},{\"1\":\"1.275362800\",\"2\":\"3.037354\",\"3\":\"71\",\"4\":\"1.26694760\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.0082140\"},{\"1\":\"0.009950331\",\"2\":\"3.267666\",\"3\":\"54\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.0215476\"},{\"1\":\"-0.010050336\",\"2\":\"3.216874\",\"3\":\"63\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-0.79850770\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.0476928\"},{\"1\":\"1.308332820\",\"2\":\"4.119850\",\"3\":\"64\",\"4\":\"2.17133681\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"5\",\"9\":\"2.0856721\"},{\"1\":\"1.423108334\",\"2\":\"3.657131\",\"3\":\"73\",\"4\":\"-0.57981850\",\"5\":\"healthy\",\"6\":\"1.65822808\",\"7\":\"8\",\"8\":\"15\",\"9\":\"2.1575593\"},{\"1\":\"0.457424847\",\"2\":\"2.374906\",\"3\":\"64\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"15\",\"9\":\"2.1916535\"},{\"1\":\"2.660958594\",\"2\":\"4.085136\",\"3\":\"68\",\"4\":\"1.37371558\",\"5\":\"invasion\",\"6\":\"1.83258146\",\"7\":\"7\",\"8\":\"35\",\"9\":\"2.2137539\"},{\"1\":\"0.797507196\",\"2\":\"3.013081\",\"3\":\"56\",\"4\":\"0.93609336\",\"5\":\"healthy\",\"6\":\"-0.16251893\",\"7\":\"7\",\"8\":\"5\",\"9\":\"2.2772673\"},{\"1\":\"0.620576488\",\"2\":\"3.141995\",\"3\":\"60\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"9\",\"8\":\"80\",\"9\":\"2.2975726\"},{\"1\":\"1.442201993\",\"2\":\"3.682610\",\"3\":\"68\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"10\",\"9\":\"2.3075726\"},{\"1\":\"0.582215620\",\"2\":\"3.865979\",\"3\":\"62\",\"4\":\"1.71379793\",\"5\":\"healthy\",\"6\":\"-0.43078292\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.3272777\"},{\"1\":\"1.771556762\",\"2\":\"3.896909\",\"3\":\"61\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"0.81093022\",\"7\":\"7\",\"8\":\"6\",\"9\":\"2.3749058\"},{\"1\":\"1.486139696\",\"2\":\"3.409496\",\"3\":\"66\",\"4\":\"1.74919986\",\"5\":\"healthy\",\"6\":\"-0.43078292\",\"7\":\"7\",\"8\":\"20\",\"9\":\"2.5217206\"},{\"1\":\"1.663926098\",\"2\":\"3.392829\",\"3\":\"61\",\"4\":\"0.61518564\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"15\",\"9\":\"2.5533438\"},{\"1\":\"2.727852828\",\"2\":\"3.995445\",\"3\":\"79\",\"4\":\"1.87946505\",\"5\":\"invasion\",\"6\":\"2.65675691\",\"7\":\"9\",\"8\":\"100\",\"9\":\"2.5687881\"},{\"1\":\"1.163150810\",\"2\":\"4.035125\",\"3\":\"68\",\"4\":\"1.71379793\",\"5\":\"healthy\",\"6\":\"-0.43078292\",\"7\":\"7\",\"8\":\"40\",\"9\":\"2.5687881\"},{\"1\":\"1.745715531\",\"2\":\"3.498022\",\"3\":\"43\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.5915164\"},{\"1\":\"1.220829921\",\"2\":\"3.568123\",\"3\":\"70\",\"4\":\"1.37371558\",\"5\":\"healthy\",\"6\":\"-0.79850770\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.5915164\"},{\"1\":\"1.091923301\",\"2\":\"3.993603\",\"3\":\"68\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"50\",\"9\":\"2.6567569\"},{\"1\":\"1.660131027\",\"2\":\"4.234831\",\"3\":\"64\",\"4\":\"2.07317193\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.6775910\"},{\"1\":\"0.512823626\",\"2\":\"3.633631\",\"3\":\"64\",\"4\":\"1.49290410\",\"5\":\"healthy\",\"6\":\"0.04879016\",\"7\":\"7\",\"8\":\"70\",\"9\":\"2.6844403\"},{\"1\":\"2.127040520\",\"2\":\"4.121473\",\"3\":\"68\",\"4\":\"1.76644166\",\"5\":\"healthy\",\"6\":\"1.44691898\",\"7\":\"7\",\"8\":\"40\",\"9\":\"2.6912431\"},{\"1\":\"3.153590358\",\"2\":\"3.516013\",\"3\":\"59\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"5\",\"9\":\"2.7047113\"},{\"1\":\"1.266947603\",\"2\":\"4.280132\",\"3\":\"66\",\"4\":\"2.12226154\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"15\",\"9\":\"2.7180005\"},{\"1\":\"0.974559640\",\"2\":\"2.865054\",\"3\":\"47\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"0.50077529\",\"7\":\"7\",\"8\":\"4\",\"9\":\"2.7880929\"},{\"1\":\"0.463734016\",\"2\":\"3.764682\",\"3\":\"49\",\"4\":\"1.42310833\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.7942279\"},{\"1\":\"0.542324291\",\"2\":\"4.178226\",\"3\":\"70\",\"4\":\"0.43825493\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"20\",\"9\":\"2.8063861\"},{\"1\":\"1.061256502\",\"2\":\"3.851211\",\"3\":\"61\",\"4\":\"1.29472717\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"40\",\"9\":\"2.8124102\"},{\"1\":\"0.457424847\",\"2\":\"4.524502\",\"3\":\"73\",\"4\":\"2.32630162\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.8419982\"},{\"1\":\"1.997417706\",\"2\":\"3.719651\",\"3\":\"63\",\"4\":\"1.61938824\",\"5\":\"invasion\",\"6\":\"1.90954250\",\"7\":\"7\",\"8\":\"40\",\"9\":\"2.8535925\"},{\"1\":\"2.775708850\",\"2\":\"3.524889\",\"3\":\"72\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"1.55814462\",\"7\":\"9\",\"8\":\"95\",\"9\":\"2.8535925\"},{\"1\":\"2.034705648\",\"2\":\"3.917011\",\"3\":\"66\",\"4\":\"2.00821403\",\"5\":\"invasion\",\"6\":\"2.11021320\",\"7\":\"7\",\"8\":\"60\",\"9\":\"2.8820035\"},{\"1\":\"2.073171929\",\"2\":\"3.623007\",\"3\":\"64\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.8820035\"},{\"1\":\"1.458615023\",\"2\":\"3.836221\",\"3\":\"61\",\"4\":\"1.32175584\",\"5\":\"healthy\",\"6\":\"-0.43078292\",\"7\":\"7\",\"8\":\"20\",\"9\":\"2.8875901\"},{\"1\":\"2.022871190\",\"2\":\"3.878466\",\"3\":\"68\",\"4\":\"1.78339122\",\"5\":\"healthy\",\"6\":\"1.32175584\",\"7\":\"7\",\"8\":\"70\",\"9\":\"2.9204698\"},{\"1\":\"2.198335072\",\"2\":\"4.050915\",\"3\":\"72\",\"4\":\"2.30757264\",\"5\":\"healthy\",\"6\":\"-0.43078292\",\"7\":\"7\",\"8\":\"10\",\"9\":\"2.9626924\"},{\"1\":\"-0.446287103\",\"2\":\"4.408547\",\"3\":\"69\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"2.9626924\"},{\"1\":\"1.193922468\",\"2\":\"4.780383\",\"3\":\"72\",\"4\":\"2.32630162\",\"5\":\"healthy\",\"6\":\"-0.79850770\",\"7\":\"7\",\"8\":\"5\",\"9\":\"2.9729753\"},{\"1\":\"1.864080131\",\"2\":\"3.593194\",\"3\":\"60\",\"4\":\"-1.38629436\",\"5\":\"invasion\",\"6\":\"1.32175584\",\"7\":\"7\",\"8\":\"60\",\"9\":\"3.0130809\"},{\"1\":\"1.160020917\",\"2\":\"3.341093\",\"3\":\"77\",\"4\":\"1.74919986\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"25\",\"9\":\"3.0373539\"},{\"1\":\"1.214912744\",\"2\":\"3.825375\",\"3\":\"69\",\"4\":\"-1.38629436\",\"5\":\"invasion\",\"6\":\"0.22314355\",\"7\":\"7\",\"8\":\"20\",\"9\":\"3.0563569\"},{\"1\":\"1.838961071\",\"2\":\"3.236716\",\"3\":\"60\",\"4\":\"0.43825493\",\"5\":\"invasion\",\"6\":\"1.17865500\",\"7\":\"9\",\"8\":\"90\",\"9\":\"3.0750055\"},{\"1\":\"2.999226163\",\"2\":\"3.849083\",\"3\":\"69\",\"4\":\"-1.38629436\",\"5\":\"invasion\",\"6\":\"1.90954250\",\"7\":\"7\",\"8\":\"20\",\"9\":\"3.2752562\"},{\"1\":\"3.141130476\",\"2\":\"3.263849\",\"3\":\"68\",\"4\":\"-0.05129329\",\"5\":\"invasion\",\"6\":\"2.42036813\",\"7\":\"7\",\"8\":\"50\",\"9\":\"3.3375474\"},{\"1\":\"2.010894999\",\"2\":\"4.433789\",\"3\":\"72\",\"4\":\"2.12226154\",\"5\":\"healthy\",\"6\":\"0.50077529\",\"7\":\"7\",\"8\":\"60\",\"9\":\"3.3928291\"},{\"1\":\"2.537657215\",\"2\":\"4.354784\",\"3\":\"78\",\"4\":\"2.32630162\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"10\",\"9\":\"3.4355988\"},{\"1\":\"2.648300197\",\"2\":\"3.582129\",\"3\":\"69\",\"4\":\"-1.38629436\",\"5\":\"invasion\",\"6\":\"2.58399755\",\"7\":\"7\",\"8\":\"70\",\"9\":\"3.4578927\"},{\"1\":\"2.779440197\",\"2\":\"3.823192\",\"3\":\"63\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"0.37156356\",\"7\":\"7\",\"8\":\"50\",\"9\":\"3.5130369\"},{\"1\":\"1.467874348\",\"2\":\"3.070376\",\"3\":\"66\",\"4\":\"0.55961579\",\"5\":\"healthy\",\"6\":\"0.22314355\",\"7\":\"7\",\"8\":\"40\",\"9\":\"3.5160131\"},{\"1\":\"2.513656063\",\"2\":\"3.473518\",\"3\":\"57\",\"4\":\"0.43825493\",\"5\":\"healthy\",\"6\":\"2.32727771\",\"7\":\"7\",\"8\":\"60\",\"9\":\"3.5307626\"},{\"1\":\"2.613006652\",\"2\":\"3.888754\",\"3\":\"77\",\"4\":\"-0.52763274\",\"5\":\"invasion\",\"6\":\"0.55961579\",\"7\":\"7\",\"8\":\"30\",\"9\":\"3.5652984\"},{\"1\":\"2.677590994\",\"2\":\"3.838376\",\"3\":\"65\",\"4\":\"1.11514159\",\"5\":\"healthy\",\"6\":\"1.74919986\",\"7\":\"9\",\"8\":\"70\",\"9\":\"3.5709402\"},{\"1\":\"1.562346305\",\"2\":\"3.709907\",\"3\":\"60\",\"4\":\"1.69561561\",\"5\":\"healthy\",\"6\":\"0.81093022\",\"7\":\"7\",\"8\":\"30\",\"9\":\"3.5876769\"},{\"1\":\"3.302849259\",\"2\":\"3.518980\",\"3\":\"64\",\"4\":\"-1.38629436\",\"5\":\"invasion\",\"6\":\"2.32727771\",\"7\":\"7\",\"8\":\"60\",\"9\":\"3.6309855\"},{\"1\":\"2.024193067\",\"2\":\"3.731699\",\"3\":\"58\",\"4\":\"1.63899671\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"3.6800909\"},{\"1\":\"1.731655545\",\"2\":\"3.369018\",\"3\":\"62\",\"4\":\"-1.38629436\",\"5\":\"invasion\",\"6\":\"0.30010459\",\"7\":\"7\",\"8\":\"30\",\"9\":\"3.7123518\"},{\"1\":\"2.807593831\",\"2\":\"4.718052\",\"3\":\"65\",\"4\":\"-1.38629436\",\"5\":\"invasion\",\"6\":\"2.46385324\",\"7\":\"7\",\"8\":\"60\",\"9\":\"3.9843437\"},{\"1\":\"1.562346305\",\"2\":\"3.695110\",\"3\":\"76\",\"4\":\"0.93609336\",\"5\":\"invasion\",\"6\":\"0.81093022\",\"7\":\"7\",\"8\":\"75\",\"9\":\"3.9936030\"},{\"1\":\"3.246490992\",\"2\":\"4.101817\",\"3\":\"68\",\"4\":\"-1.38629436\",\"5\":\"healthy\",\"6\":\"-1.38629436\",\"7\":\"6\",\"8\":\"healthy\",\"9\":\"4.0298060\"},{\"1\":\"2.532902848\",\"2\":\"3.677566\",\"3\":\"61\",\"4\":\"1.34807315\",\"5\":\"invasion\",\"6\":\"-1.38629436\",\"7\":\"7\",\"8\":\"15\",\"9\":\"4.1295508\"},{\"1\":\"2.830267834\",\"2\":\"3.876396\",\"3\":\"68\",\"4\":\"-1.38629436\",\"5\":\"invasion\",\"6\":\"1.32175584\",\"7\":\"7\",\"8\":\"60\",\"9\":\"4.3851468\"},{\"1\":\"3.821003607\",\"2\":\"3.896909\",\"3\":\"44\",\"4\":\"-1.38629436\",\"5\":\"invasion\",\"6\":\"2.16905370\",\"7\":\"7\",\"8\":\"40\",\"9\":\"4.6844434\"},{\"1\":\"2.907447359\",\"2\":\"3.396185\",\"3\":\"52\",\"4\":\"-1.38629436\",\"5\":\"invasion\",\"6\":\"2.46385324\",\"7\":\"7\",\"8\":\"10\",\"9\":\"5.1431245\"},{\"1\":\"2.882563575\",\"2\":\"3.773910\",\"3\":\"68\",\"4\":\"1.55814462\",\"5\":\"invasion\",\"6\":\"1.55814462\",\"7\":\"7\",\"8\":\"80\",\"9\":\"5.4775090\"},{\"1\":\"3.471966453\",\"2\":\"3.974998\",\"3\":\"68\",\"4\":\"0.43825493\",\"5\":\"invasion\",\"6\":\"2.90416508\",\"7\":\"7\",\"8\":\"20\",\"9\":\"5.5829322\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nprostate$svi <- as.factor(prostate$svi)\n```\n:::\n\n\n---\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n---\n\n# Additive  multiple linair model\n\nSeparate simple linair models, like\n\n$$E(Y|X_v)=\\alpha+\\beta_v X_v$$\n\n- Association between lpsa en 1 variabele e.g lcavol.\n- More accurate predictions by simultaneously accounting for multiple predictors\n- Estimate for parameter $\\beta_v$ does not only capture the effect of tumor volume.\n- $\\beta_v$ average difference for log-psa for patients that differ in 1 unit of the log tumor volume.\n- Even if lcavol is not associated with lpsa then patients with a higher tumor volume can have a higher lpsa because their semen vesicles are affected (svi status 1).\n$\\rightarrow$ confounding.\n- Compare patients with same svi status\n- Is posible in multiple linear model\n\n---\n\n## Statistical model\n\n- $p-1$ predictors $X_1,...,X_{p-1}$ and outcome $Y$ for $n$ subjecten.\n\n$$\nY_i =\\beta_0 + \\beta_1 X_{i1} + ... +\\beta_{p-1} X_{ip-1} + \\epsilon_i\n$$\n\n- $\\beta_0,\\beta_1,...,\\beta_{p-1}$ unknown parameters\n- $\\epsilon_i$ residuals that cannot be explained by predictors\n- Estimation by *least squares method*\n\n---\n\nModel allows to\n\n1. predict the expected outcome for subjects given their values $x_1,...,x_{p-1}$ for the predictor variables.\n$E[Y\\vert X_1=x_1, \\ldots X_{p-1}=x_{p-1}]=\\hat{\\beta}_0+\\hat{\\beta}_1x_1+...+\\hat{\\beta}_{p-1}x_{p-1}$.\n2. Does the average outcome differ between two groups of patients that differ by $\\delta$ units in predictor $X_j$ but have the same value for the remaining variables $\\{X_k,k=1,...,p,k\\ne j\\}$.\n$$\n\\begin{array}{l}\nE(Y|X_1=x_1,...,X_j=x_j+\\delta,...,X_{p-1}=x_{p-1}) \\\\\n\\quad\\quad - E(Y|X_1=x_1,...,X_j=x_j,...,X_{p-1}=x_{p-1}) \\\\\\\\\n\\quad =\\beta_0 + \\beta_1 x_1 + ... + \\beta_j(x_j+\\delta)+...+\\beta_{p-1} x_{p-1}\\\\\n\\quad\\quad- \\beta_0 - \\beta_1 x_1 - ... - \\beta_jx_j-...-\\beta_{p-1} x_{p-1} \\\\\\\\\n\\quad= \\beta_j\\delta\n\\end{array}\n$$\n\nInterpretation $\\beta_j$:\n\n- difference in mean outcome between subjects that differ in one unit of $X_j$, but have the same value for the remaining predictors in the model.\n\nor\n\n- Effect of predictor j corrected for the remaining predictors.  e.g. effect of cancer volume correct for prostate weight and the svi status.\n\n---\n\n### Prostate example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmV <- lm(lpsa ~ lcavol, prostate)\nsummary(lmV)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol, data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.67624 -0.41648  0.09859  0.50709  1.89672 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.50730    0.12194   12.36   <2e-16 ***\nlcavol       0.71932    0.06819   10.55   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7875 on 95 degrees of freedom\nMultiple R-squared:  0.5394,\tAdjusted R-squared:  0.5346 \nF-statistic: 111.3 on 1 and 95 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmVWS <- lm(lpsa ~ lcavol + lweight + svi, prostate)\nsummary(lmVWS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi, data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.72966 -0.45767  0.02814  0.46404  1.57012 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.26807    0.54350  -0.493  0.62301    \nlcavol       0.55164    0.07467   7.388  6.3e-11 ***\nlweight      0.50854    0.15017   3.386  0.00104 ** \nsviinvasion  0.66616    0.20978   3.176  0.00203 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7168 on 93 degrees of freedom\nMultiple R-squared:  0.6264,\tAdjusted R-squared:  0.6144 \nF-statistic: 51.99 on 3 and 93 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n---\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n---\n\n# Inference in multiple linear models\n\nIf data are representative than the least squares estimators for the intercept and slopes are unbiased.\n$$E[\\hat \\beta_j]=\\beta_j,\\quad j=0,\\ldots,p-1$$\n\n- Gain insight in the distribution of the parameter estimators so as to generalize the effect in the sample to the population.\n\n- Additional assumptions are needed for inference.\n\n1. *Linearity*\n\n2. *Independence*\n\n3. *Homoscedasticity* of *equal variance*\n4. *Normality*: residuals $\\epsilon_i$ are normally distributed.\n\nUnder these assumptions:\n$$\\epsilon_i \\sim N(0,\\sigma^2)$$\nand\n$$Y_i\\sim N(\\beta_0+\\beta_1 X_{i1}+\\ldots+\\beta_{p-1} X_{ip-1},\\sigma^2)$$\n\n---\n\n- Slopes are again more precise if the predictor values have a larger range.\n\n- Conditional variance ($\\sigma^2$) can again be estimated based on the *mean squared error* (MSE):\n\n$$\\hat\\sigma^2=MSE=\\frac{\\sum\\limits_{i=1}^n \\left(y_i-\\hat\\beta_0-\\hat\\beta_1 X_{i1}-\\ldots-\\hat\\beta_{p-1} X_{ip-1}\\right)^2}{n-p}=\\frac{\\sum\\limits_{i=1}^n e^2_i}{n-p}$$\n\nAgain hypothesis tests and confidence intervals by\n$$T_k=\\frac{\\hat{\\beta}_k-\\beta_k}{SE(\\hat{\\beta}_k)} \\text{ met } k=0, \\ldots, p-1$$\n\nIf all assumptions are satisfied than the statistics $T_k$ t-distributed with $n-p$ degrees of freedom.\n\n---\n\nWhen normality thus not hold, but lineariteit, independence and homoscedasticity are valid we can again adopt the CLT that states that statistic $T_k$ is approximately normally distributed in large samples.\n\n---\n\nWe can build confidence intervals on the slopes by:\n$$[\\hat\\beta_j - t_{n-p,\\alpha/2} \\text{SE}_{\\hat\\beta_j},\\hat\\beta_j + t_{n-p,\\alpha/2} \\text{SE}_{\\hat\\beta_j}]$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lmVWS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %    97.5 %\n(Intercept) -1.3473509 0.8112061\nlcavol       0.4033628 0.6999144\nlweight      0.2103288 0.8067430\nsviinvasion  0.2495824 1.0827342\n```\n\n\n:::\n:::\n\n\n---\n\nFormal hypothesis tests:\n$$H_0: \\beta_j=0$$\n$$H_1: \\beta_j\\neq0$$\n\nWith test statistic\n$$T=\\frac{\\hat{\\beta}_j-0}{SE(\\hat{\\beta}_j)}$$\nwhich follows a t-distribution with $n-p$ degrees of freedom under $H_0$\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lmVWS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi, data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.72966 -0.45767  0.02814  0.46404  1.57012 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.26807    0.54350  -0.493  0.62301    \nlcavol       0.55164    0.07467   7.388  6.3e-11 ***\nlweight      0.50854    0.15017   3.386  0.00104 ** \nsviinvasion  0.66616    0.20978   3.176  0.00203 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7168 on 93 degrees of freedom\nMultiple R-squared:  0.6264,\tAdjusted R-squared:  0.6144 \nF-statistic: 51.99 on 3 and 93 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n---\n\n## Assess the model assumptions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(lmVWS)\n```\n\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-8-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-8-4.png){width=672}\n:::\n:::\n\n\n---\n\n## The non additive multiple linear model\n### Interaction between two continuous variables\n\nThe previous model is additive because the contribution of the cancer volume on lpsa does not depend on the height of the prostate weight and the svi status.\n\nThe slope for lcavol does not depend on log prostate weight and svi.\n\n$$\n\\beta_0 + \\beta_v (x_{v}+\\delta_v) + \\beta_w x_{w} +\\beta_s x_{s} - \\beta_0 - \\beta_v x_{v} - \\beta_w x_{w} -\\beta_s x_s = \\beta_v \\delta_v\n$$\n\nThe svi status and the log-prostategewicht ($x_w$) do not influence the contribution of the log-tumor volume ($x_v$) to the average log-PSA and vice versa.\n\n---\n\n- It is however possible that the association of lpsa and lcavol depends on the prostate weight.\n- The average difference in lpsa for patients that differ in one unit of the log-tumor volume can for instance can be higher for patients wiht a high tumor weight then for those with a low tumor weight.\n- The effect of the tumor volume on the PSA depends on the prostate weight.\n\nTo model this **interactie** or **effect modification** we can add a product term of both variables to the model\n\n$$\nY_i = \\beta_0 + \\beta_v x_{iv} + \\beta_w x_{iw} +\\beta_s x_{is} + \\beta_{vw} x_{iv}x_{iw} +\\epsilon_i\n$$\n\nThis term quantifies the *interactie-effect* of predictors $x_v$ en $x_w$ on the mean outcome.\n\nTerms $\\beta_vx_{iv}$ and $\\beta_wx_{iw}$ are referred to as *main effects* of predictors $x_v$ and $x_w$.\n\n---\n\nThe difference in lpsa for patients that differ 1 unit in $X_v$ and have an equal log prostate weight and the same svi status now becomes:\n\n$$\n\\begin{array}{l}\nE(Y | X_v=x_v +1, X_w=x_w, X_s=x_s) - E(Y | X_v=x_v, X_w=x_w, X_s=x_s) \\\\\n\\quad = \\beta_0 + \\beta_v (x_{v}+1) + \\beta_w x_w +\\beta_s x_{s} + \\beta_{vw} (x_{v}+1) x_w - \\beta_0 - \\beta_v x_{v} - \\beta_w x_w -\\beta_s x_{s} - \\beta_{vw} (x_{v}) x_w \\\\\n\\quad = \\beta_v +  \\beta_{vw} x_w\n \\end{array}\n $$\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmVWS_IntVW <- lm(lpsa ~ lcavol + lweight + svi + lcavol:lweight, prostate)\nsummary(lmVWS_IntVW)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi + lcavol:lweight, \n    data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.65886 -0.44673  0.02082  0.50244  1.57457 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)   \n(Intercept)     -0.6430     0.7030  -0.915  0.36278   \nlcavol           1.0046     0.5427   1.851  0.06734 . \nlweight          0.6146     0.1961   3.134  0.00232 **\nsviinvasion      0.6859     0.2114   3.244  0.00164 **\nlcavol:lweight  -0.1246     0.1478  -0.843  0.40156   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7179 on 92 degrees of freedom\nMultiple R-squared:  0.6293,\tAdjusted R-squared:  0.6132 \nF-statistic: 39.05 on 4 and 92 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n---\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n---\n\n- Note that the interaction effect that is observed is not statistically significant (p=0.4).\n- The main effects that are involved in the interaction cannot be interpreted separately from one another.\n- We will therefore remove non-significant interaction terms from the model.\n- Upon removal of non-significant interaction terms the main effects can be interpreted.\n\n---\n\n## Interaction between a continuous variable and a factor variable\n\nInteraction between lcavol $\\leftrightarrow$ svi and lweight $\\leftrightarrow$ svi.\n\nThe model becomes\n\n$$Y=\\beta_0+\\beta_vX_v+\\beta_wX_w+\\beta_sX_s+\\beta_{vs}X_vX_s + \\beta_{ws}X_wX_s +\\epsilon$$\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmVWS_IntVS_WS <- lm(lpsa ~ lcavol + lweight + svi + svi:lcavol + svi:lweight, data = prostate)\nsummary(lmVWS_IntVS_WS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi + svi:lcavol + svi:lweight, \n    data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.50902 -0.44807  0.06455  0.45657  1.54354 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         -0.52642    0.56793  -0.927 0.356422    \nlcavol               0.54060    0.07821   6.912 6.38e-10 ***\nlweight              0.58292    0.15699   3.713 0.000353 ***\nsviinvasion          3.43653    1.93954   1.772 0.079771 .  \nlcavol:sviinvasion   0.13467    0.25550   0.527 0.599410    \nlweight:sviinvasion -0.82740    0.52224  -1.584 0.116592    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7147 on 91 degrees of freedom\nMultiple R-squared:  0.6367,\tAdjusted R-squared:  0.6167 \nF-statistic: 31.89 on 5 and 91 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n---\n\nBecause $X_S$ is a dummy variabele we obtain to distinct regression planes:\n\n1. Model for $X_s=0$: $$Y=\\beta_0+\\beta_vX_v+\\beta_wX_w + \\epsilon$$ where the main effects are the slope for lcavol and lweight\n2. and model for $X_s=1$:\n   $$\\begin{array}{lcl}\n   Y&=&\\beta_0+\\beta_vX_v+\\beta_s+\\beta_wX_w+\\beta_{vs}X_v + \\beta_{ws}X_w +\\epsilon\\\\\n  &=& (\\beta_0+\\beta_s)+(\\beta_v+\\beta_{vs})X_v+(\\beta_w+\\beta_{ws})X_w+\\epsilon\n  \\end{array}$$\nwith intercept $\\beta_0+\\beta_s$ and slopes $\\beta_v+\\beta_{vs}$ and $\\beta_w+\\beta_{ws}$\n\n---\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n---\n\n# ANOVA table\n\nThe total SSTot is again\n\n$$\n  \\text{SSTot} = \\sum_{i=1}^n (Y_i - \\bar{Y})^2.\n$$\n\nThe residual sum of squares remains similar\n$$\n  \\text{SSE} = \\sum_{i=1}^n (Y_i-\\hat{Y}_i)^2.\n$$\n\nAgain the total sum of squares can be decomposed in ,\n$$\n  \\text{SSTot} = \\text{SSR} + \\text{SSE} ,\n$$\nwith\n$$\n  \\text{SSR} = \\sum_{i=1}^n (\\hat{Y}_i-\\bar{Y})^2.\n$$\n\n---\n\nWe have following degrees of freedom and mean sum of squares:\n\n- SSTot has $n-1$ degrees of freedom and $\\text{SSTot}/(n-1)$ is an estimator for the total variance in $Y$ (marginal distribution of $Y$).\n- SSE has $n-p$ degrees of freedom and $\\text{MSE}=\\text{SSE}/(n-p)$ is an schatter for the residual variance of $Y$ given the predictores (i.e. an estimator for the residual variance $\\sigma^2$ of the error term $\\epsilon$).\n- SSR has $p-1$ degrees of freedom   and $\\text{MSR}=\\text{SSR}/(p-1)$ is the mean sum of squares of the regression.\n\nThe determination coefficients remains as before,  i.e.\n$$\n  R^2 = 1-\\frac{\\text{SSE}}{\\text{SSTot}} = \\frac{\\text{SSR}}{\\text{SSTot}}\n$$\nand is the fraction of the total variability that can be explained by the regression model.\n\nTeststatistic $F=\\text{MSR}/\\text{MSE}$ is under $H_0:\\beta_1=\\ldots=\\beta_{p-1}=0$ distributed by an F distribution: $F_{p-1;n-p}$.\n\n---\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi, data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.72966 -0.45767  0.02814  0.46404  1.57012 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.26807    0.54350  -0.493  0.62301    \nlcavol       0.55164    0.07467   7.388  6.3e-11 ***\nlweight      0.50854    0.15017   3.386  0.00104 ** \nsviinvasion  0.66616    0.20978   3.176  0.00203 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7168 on 93 degrees of freedom\nMultiple R-squared:  0.6264,\tAdjusted R-squared:  0.6144 \nF-statistic: 51.99 on 3 and 93 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n---\n\n## Additional sums of squares\n\n\nConsider 2 models for the predictors $x_1$ en $x_2$:\n$$\n  Y_i = \\beta_0+\\beta_1 x_{i1} + \\epsilon_i,\n$$\nwith $\\epsilon_i\\text{ iid } N(0,\\sigma_1^{2})$, and\n$$\nY_i = \\beta_0+\\beta_1 x_{i1}+\\beta_2 x_{i2} + \\epsilon_i,\n$$\nwith $\\epsilon_i\\text{ iid } N(0,\\sigma_2^{2})$.\n\nfor the first (gereduceerde) model we have decomposition\n\n$$\n  \\text{SSTot} = \\text{SSR}_1 + \\text{SSE}_1\n$$\nen for the second non-reduced model we have\n\n$$\n  \\text{SSTot} = \\text{SSR}_2 + \\text{SSE}_2\n$$\n(SSTot is of course the same because it only depends on the response and not of the models).\n\n---\n\n**Definition of additional sum of squares**\nThe *additional sum of squares* of predictor $x_2$ as compared to the model with only $x_1$ as predictor is given by\n$$\n  \\text{SSR}_{2\\mid 1} = \\text{SSE}_1-\\text{SSE}_2=\\text{SSR}_2-\\text{SSR}_1.\n$$\n\nNote that,  $\\text{SSE}_1-\\text{SSE}_2=\\text{SSR}_2-\\text{SSR}_1$ is triviaal is because of the decomposition of the total sum of squares.\n\nThe additional sum of squares $\\text{SSR}_{2\\mid 1}$ can simply be interpreted as the additional variability that can be explained by adding predictor $x_2$ to the model with predictor $x_1$.\n\nWith this sum of squares we can further decompose the total sum of squares\n$$\n  \\text{SSTot} = \\text{SSR}_1+ \\text{SSR}_{2\\mid 1} + \\text{SSE}.\n$$\nwhich follows directly from the definition $\\text{SSR}_{2\\mid 1}$.\n\n---\n\nExtension: ($s<p-1$)\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\cdots + \\beta_{s} x_{is} + \\epsilon_i\n$$\nwith $\\epsilon_i\\text{ iid }N(0,\\sigma_1^{2})$, and ($s< q\\leq p-1$)\n$$\nY_i = \\beta_0 + \\beta_1 x_{i1} + \\cdots + \\beta_{s} x_{is} + \\beta_{s+1} x_{is+1} + \\cdots \\beta_{q}x_{iq}+ \\epsilon_i\n$$\nwith $\\epsilon_i\\text{ iid } N(0,\\sigma_2^{2})$.\n\n\nThe **additional sum of squares** of predictor $x_{s+1}, \\ldots, x_q$ compared to a model with only predictors  $x_1,\\ldots, x_{s}$ is given by\n\n$$\n  \\text{SSR}_{s+1, \\ldots, q\\mid 1,\\ldots, s} = \\text{SSE}_1-\\text{SSE}_2=\\text{SSR}_2-\\text{SSR}_1.\n$$\n\n---\n\n### Type I Sums of Squares\nSuppose that $p-1$ predictors are considered, and suppose the following sequence of models ($s=2,\\ldots, p-1$)\n$$\nY_i = \\beta_0 + \\sum_{j=1}^{s} \\beta_j x_{ij} + \\epsilon_i\n$$\nwuth $\\epsilon_i\\text{ iid } N(0,\\sigma^{2})$.\n\n- The corresponding sum of squares are denoted as $\\text{SSR}_{s}$ and $\\text{SSE}_{s}$.\n- The sequence of models gives rise to the following sums of squares: $\\text{SSR}_{s\\mid 1,\\ldots, s-1}$.\n- The latter sum of squares is referred to as type I sums of squares. Note that they depend on the order in which the models were added to the model.\n\n---\n\nWe can show for model Model with $s=p-1$ that\n$$\n \\text{SSTot} = \\text{SSR}_1 + \\text{SSR}_{2\\mid 1} + \\text{SSR}_{3\\mid 1,2} + \\cdots + \\text{SSR}_{p-1\\mid 1,\\ldots, p-2} + \\text{SSE},\n$$\nwith $\\text{SSE}$ the residual sum of squares of the model with all $p-1$ predictors\n$$\n  \\text{SSR}_1 + \\text{SSR}_{2\\mid 1} + \\text{SSR}_{3\\mid 1,2} + \\cdots + \\text{SSR}_{p-1\\mid 1,\\ldots, p-2} = \\text{SSR}\n$$\nwith $\\text{SSR}$ the sum of squares of all  $p-1$ predictors.\n\n- The interpretation of each term depends on the order of the sequence of the regression models.\n\n---\n\n- Each type I SSR involves 1 predictor and has 1 degree of freedom (note that multiple dummies for a factor are typically removed together).\n- For each type I SSR term the mean sum of squares is defined by  $\\text{MSR}_{j\\mid 1,\\ldots, j-1}=\\text{SSR}_{j\\mid 1,\\ldots, j-1}/1$.\n- And teststatistic $F=\\text{MSR}_{j\\mid 1,\\ldots, j-1}/\\text{MSE}$ follows a $F_{1;n-(j+1)}$ distribution under  $H_0:\\beta_j=0$ with $s=j$.\n- These sums of squares are the default sum of squares in the anova function of R.\n\n---\n\n### Type III Sums of squares\n\n Type III sum of squares for predictor $x_j$ are given by the additional sum of squares\n$$\n  \\text{SSR}_{j \\mid 1,\\ldots, j-1,j+1,\\ldots, p-1} = \\text{SSE}_1-\\text{SSE}_2\n$$\n\n- $\\text{SSE}_2$ the sum of squares of the residuals of the model with all $p-1$ predictors.\n- $\\text{SSE}_1$ sum of squares of the residuals with all $p-1$ predictors, except for predictor $x_j$.\n\nThe type III sum of squares $\\text{SSR}_{j \\mid 1,\\ldots, j-1,j+1,\\ldots, p-1}$ quantify the contribution in the total variance of the outcome explained by $x_j$ that cannot be explained by the remaining $p-2$ predictors.\n\n---\n\nThe type III sum of squares has 1 degree of freedom because it involves 1 $\\beta$-parameter.\n\nFor each type III SSR term the mean sum of squares is defined by $\\text{MSR}_{j \\mid 1,\\ldots, j-1,j+1,\\ldots, p-1}=\\text{SSR}_{j \\mid 1,\\ldots, j-1,j+1,\\ldots, p-1}/1$.\n\nTeststatistiek $F=\\text{MSR}_{j \\mid 1,\\ldots, j-1,j+1,\\ldots, p-1}/\\text{MSE}$ is $F_{1;n-p}$ distributed under $H_0:\\beta_j=0$.\n\nWe can obtain these sums of squares using the `Anova` function from the `car` package.\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nAnova(lmVWS, type = 3)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Sum Sq\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0.1250021\",\"2\":\"1\",\"3\":\"0.2432815\",\"4\":\"6.230088e-01\",\"_rn_\":\"(Intercept)\"},{\"1\":\"28.0445759\",\"2\":\"1\",\"3\":\"54.5808864\",\"4\":\"6.303883e-11\",\"_rn_\":\"lcavol\"},{\"1\":\"5.8923334\",\"2\":\"1\",\"3\":\"11.4677711\",\"4\":\"1.039115e-03\",\"_rn_\":\"lweight\"},{\"1\":\"5.1813959\",\"2\":\"1\",\"3\":\"10.0841312\",\"4\":\"2.029035e-03\",\"_rn_\":\"svi\"},{\"1\":\"47.7849616\",\"2\":\"93\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe p-values are identical to those of two-sided t-tests\n\nNote, however, that all dummies for factors with multiple levels will be taken out of the model at once. So then the type III sum of squares will have as many degrees of freedom as the number of dummies and an omnibus test is performed for the effect of the factor.\n\n---\n\n# Diagnostics\n## Multicollinearity\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi, data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.72966 -0.45767  0.02814  0.46404  1.57012 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.26807    0.54350  -0.493  0.62301    \nlcavol       0.55164    0.07467   7.388  6.3e-11 ***\nlweight      0.50854    0.15017   3.386  0.00104 ** \nsviinvasion  0.66616    0.20978   3.176  0.00203 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7168 on 93 degrees of freedom\nMultiple R-squared:  0.6264,\tAdjusted R-squared:  0.6144 \nF-statistic: 51.99 on 3 and 93 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n---\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lpsa ~ lcavol + lweight + svi + lcavol:lweight, \n    data = prostate)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.65886 -0.44673  0.02082  0.50244  1.57457 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)   \n(Intercept)     -0.6430     0.7030  -0.915  0.36278   \nlcavol           1.0046     0.5427   1.851  0.06734 . \nlweight          0.6146     0.1961   3.134  0.00232 **\nsviinvasion      0.6859     0.2114   3.244  0.00164 **\nlcavol:lweight  -0.1246     0.1478  -0.843  0.40156   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7179 on 92 degrees of freedom\nMultiple R-squared:  0.6293,\tAdjusted R-squared:  0.6132 \nF-statistic: 39.05 on 4 and 92 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n---\n\n- Estimates are different from those in the additive model and the standard errors are much higher!\n\n- This is caused by the multicollinearity problem.\n\n- If 2 predictors are strongly correlated than they share a lot of information.\n\n- It is therefore difficult to estimate the individual contribution of each predictor on the outcome.\n\n- Least squares estimators become instable.\n\n- Standard errors become inflated.\n\n- As long as we only do predictions on the basis of the regression model without extrapolating beyond the range of the predictors observed in the sample multicolinearity is not problematic.\n\n- But for inference it is problematic.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(cbind(prostate$lcavol, prostate$lweight, prostate$lcavol * prostate$lweight))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]      [,2]      [,3]\n[1,] 1.0000000 0.1941283 0.9893127\n[2,] 0.1941283 1.0000000 0.2835608\n[3,] 0.9893127 0.2835608 1.0000000\n```\n\n\n:::\n:::\n\n\n- High correlation between log-tumor volume and interaction.\n- It is a known problem for higher order terms (interactions and quadratic terms)\n\n---\n\n- Detect multicollinearity based on the correlation matrix or scatterplot matrix is suboptimal.\n- In models with 3 or more predictors, say X1, X2, X3 we can have high multicollinearity while alle pairswise correlations between the predictors are low.\n- We also have multicollinearity if there is a high correlation between X1 and a linair combination of X2 and X3.\n\n---\n\n### Variance inflation factor (VIF)\n\nFor parameter $j$ in de regression model\n\n$$\\textrm{VIF}_j=\\left(1-R_j^2\\right)^{-1}$$\n\n- In this expression $R_j^2$ is the multiple determination coefficient of the linear regression of predictor j on the remaining predictors in the model.\n- VIF is 1 if predictor j is not linear associated with the remaining predictors in the model.\n- VIF is larger than 1 in all andere cases.\n- VIF is the factor with which the observed variance inflates as compared to a model for which all predictoren would be independend.\n- VIF > 10 $\\rightarrow$ strong multicollinearity.\n\n---\n\n### Body fat example\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n---\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Body_fat ~ Triceps + Thigh + Midarm, data = bodyfat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.7263 -1.6111  0.3923  1.4656  4.1277 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)  117.085     99.782   1.173    0.258\nTriceps        4.334      3.016   1.437    0.170\nThigh         -2.857      2.582  -1.106    0.285\nMidarm        -2.186      1.595  -1.370    0.190\n\nResidual standard error: 2.48 on 16 degrees of freedom\nMultiple R-squared:  0.8014,\tAdjusted R-squared:  0.7641 \nF-statistic: 21.52 on 3 and 16 DF,  p-value: 7.343e-06\n```\n\n\n:::\n:::\n\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(lmFat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Triceps    Thigh   Midarm \n708.8429 564.3434 104.6060 \n```\n\n\n:::\n:::\n\n\n---\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Midarm ~ Triceps + Thigh, data = bodyfat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.58200 -0.30625  0.02592  0.29526  0.56102 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 62.33083    1.23934   50.29   <2e-16 ***\nTriceps      1.88089    0.04498   41.82   <2e-16 ***\nThigh       -1.60850    0.04316  -37.26   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.377 on 17 degrees of freedom\nMultiple R-squared:  0.9904,\tAdjusted R-squared:  0.9893 \nF-statistic: 880.7 on 2 and 17 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n---\n\n\nWe evaluate the VIF in the prostate cancer example for the additive model and the model with interactie.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(lmVWS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  lcavol  lweight      svi \n1.447048 1.039188 1.409189 \n```\n\n\n:::\n\n```{.r .cell-code}\nvif(lmVWS_IntVW)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        lcavol        lweight            svi lcavol:lweight \n     76.193815       1.767121       1.426646      80.611657 \n```\n\n\n:::\n:::\n\n\n- Inflation in interaction terms often caused because main effect get another interpretation.\n\n---\n\n## Influential observations\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(112358)\nnobs <- 20\nsdy <- 1\nx <- seq(0, 1, length = nobs)\ny <- 10 + 5 * x + rnorm(nobs, sd = sdy)\nx1 <- c(x, 0.5)\ny1 <- c(y, 10 + 5 * 1.5 + rnorm(1, sd = sdy))\nx2 <- c(x, 1.5)\ny2 <- c(y, y1[21])\nx3 <- c(x, 1.5)\ny3 <- c(y, 11)\nplot(x, y, xlim = range(c(x1, x2, x3)), ylim = range(c(y1, y2, y3)))\npoints(c(x1[21], x2[21], x3[21]), c(y1[21], y2[21], y3[21]), pch = as.character(1:3), col = 2:4)\nabline(lm(y ~ x), lwd = 2)\nabline(lm(y1 ~ x1), col = 2, lty = 2, lwd = 2)\nabline(lm(y2 ~ x2), col = 3, lty = 3, lwd = 2)\nabline(lm(y3 ~ x3), col = 4, lty = 4, lwd = 2)\nlegend(\"topleft\", col = 1:4, lty = 1:4, legend = paste(\"lm\", c(\"\", as.character(1:3))), text.col = 1:4)\n```\n\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n---\n\n- It is not desirable that a single observation largely influences the result of a linear regression analysis\n\n- Diagnostics allow us to detect extreme observations.\n- *Studentized residuals* to spot outliers\n- *Leverage* to spot observations with extreem covariate pattern\n\n---\n\n### Cook's distance\n\n- A statistics to assess the influence the effect of a single observation on the regression analysis\n- Cook's distance for observation i is diagnostic measure for this particular observation on all all predictions or on *all* estimated parameters.\n\n$$D_i=\\frac{\\sum_{j=1}^n(\\hat{Y}_j-\\hat{Y}_{j(i)})^2}{p\\textrm{MSE}}$$\n\n- Observation $i$ has a large influence on the regression parameters and predictions if the  Cook's distance $D_i$ is large.\n- Extreme Cook's distance if it is larger than the 50% quantile of an $F_{p+1,n-(p+1)}$-distribution.\n\n---\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n---\n\n- Once we established that an observation is influential we can use *DFBETAS* to find the parameters for which the estimates are largely affected by the observation\n-  DFBETAS of observatie i is a diagnostic measure for *each model parameter separately*.\n$$\\textrm{DFBETAS}_{j(i)}=\\frac{\\hat{\\beta}_{j}-\\hat{\\beta}_{j(i)}}{\\textrm{SD}(\\hat{\\beta}_{j})}$$\n-  DFBETAS is extreme when it is larger than 1 in small to moderate datasets or exceeds $2/\\sqrt{n}$ in large datasets.\n\n---\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n---\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-26-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n---\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n# Constrasts\n\n- In more complex designs that are modelled using general linear models one often has to assess multiple hypotheses.\n- Moreover these hypotheses can typically not always be translated into a test on one parameter, but in a linear combination of model parameters.\n- A linear combination of model parameters is also referred to as a contrast.\n\n## NHANES example\n\n- Suppose that researchers want to assess the association between age and bloodpressure for American children.\n\n- Possibly this association will differ between boys and girls.\n\n- They want to assess following hypotheses:\n\n    - Is there an association between age and blood pressure for girls?\n    - Is there an association between age and blood pressure for boys?\n    - Is the association between age and blood pressure different for boys and girls?\n\n## Model\n\nWe fit a model for the average systolic blood pressure (`BPSysAve`) using age (in months), gender and the interaction between age and gender for children between 6 and 18 years from the NHANES study.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\nbpData <- NHANES |>\n  filter(\n      Age >=6 &\n      Age <= 18 &\n      !is.na(BPSysAve) &\n      !is.na(AgeMonths)\n  )\n\nmBp1 <- lm(BPSysAve ~ AgeMonths * Gender, bpData)\npar(mfrow = c(2, 2))\nplot(mBp1)\n```\n\n::: {.cell-output-display}\n![](08-MultipleRegression_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nAssumptions?\n\n- No deviations from Lineariteit\n- Assumption of homoscedasticity seems to be valid\n- Slight deviations from normality, indication for some tail to the right\n- Large dataset (n = 703) so we can adopt the CLT\n\n## Inference\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mBp1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = BPSysAve ~ AgeMonths * Gender, data = bpData)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-30.487  -5.871  -0.890   5.265  33.882 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           92.90682    2.29792  40.431  < 2e-16 ***\nAgeMonths              0.05943    0.01371   4.336 1.66e-05 ***\nGendermale           -11.35031    3.25237  -3.490 0.000514 ***\nAgeMonths:Gendermale   0.09294    0.01943   4.783 2.11e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.65 on 699 degrees of freedom\nMultiple R-squared:  0.1939,\tAdjusted R-squared:  0.1904 \nF-statistic: 56.04 on 3 and 699 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe research questions translate to following nullhypotheses:\n\n1. Association between blood pressure and age for girls? $$H_0: \\beta_\\text{AgeMonths} = 0 \\text{ vs } H_1: \\beta_\\text{AgeMonths} \\neq 0 $$\n\n2. Association between blood pressure and age for boys? $$H_0: \\beta_\\text{AgeMonths} + \\beta_\\text{AgeMonths:Gendermale} = 0 \\text{ vs } H_1: \\beta_\\text{AgeMonths} + \\beta_\\text{AgeMonths:Gendermale} \\neq 0 $$\n\n3. Is the association between blood pressure and age different for girls and boys?  $$H_0: \\beta_\\text{AgeMonths:Gendermale} = 0 \\text{ vs } H_1: \\beta_\\text{AgeMonths:Gendermale} \\neq 0 $$\n\n\n- We can assess hypotheses 1 and 3 immediately using the output of the model.\n- Hypotheses 2 is a linear combination of two parameters.\n- We also need multiple tests for assessing the association between the systolic blood pressure and Age.\n\nWe can again use an Anova approach.\n\n1.  We first assess the omnibus hypothesis that there is no association between age and blood pressure.\n\n$$ H_0: \\beta_\\text{AgeMonths} = \\beta_\\text{AgeMonths} + \\beta_\\text{AgeMonths:Gendermale} = \\beta_\\text{AgeMonths:Gendermale} = 0\n$$\n\n- which simplifies to assessing\n\n$$ H_0: \\beta_\\text{AgeMonths} = \\beta_\\text{AgeMonths:Gendermale} = 0\n$$\n\n- We can do this by comparing two models: the full model with an effect for Gender, AgeMonths and Gender x AgeMonths interaction against a reduced model with only Gender.\n\n2. If we can reject this hypothesis we can again do a posthoc analysis for each of the contrasts.\n\n\n### Omnibus test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmBp0 <- lm(BPSysAve ~ Gender, bpData)\nanova(mBp0, mBp1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"RSS\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sum of Sq\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"701\",\"2\":\"78239.43\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\",\"6\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"699\",\"2\":\"65094.59\",\"3\":\"2\",\"4\":\"13144.84\",\"5\":\"70.57608\",\"6\":\"1.206892e-28\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThere is an extremely significant association between the systolic blood pressure and Age ($p << 0.001$).\n\n### Posthoc tests\n\nFor the posthoc tests we will again build upon the `multcomp` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multcomp)\nbpPosthoc <- glht(mBp1, linfct = c(\n  \"AgeMonths = 0\",\n  \"AgeMonths + AgeMonths:Gendermale = 0\",\n  \"AgeMonths:Gendermale = 0\"\n))\nbpPosthoc |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nFit: lm(formula = BPSysAve ~ AgeMonths * Gender, data = bpData)\n\nLinear Hypotheses:\n                                      Estimate Std. Error t value Pr(>|t|)    \nAgeMonths == 0                         0.05943    0.01371   4.336 3.69e-05 ***\nAgeMonths + AgeMonths:Gendermale == 0  0.15237    0.01377  11.061  < 1e-05 ***\nAgeMonths:Gendermale == 0              0.09294    0.01943   4.783  < 1e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n\n```{.r .cell-code}\nbpPosthocCI <- bpPosthoc |> confint()\nbpPosthocCI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nFit: lm(formula = BPSysAve ~ AgeMonths * Gender, data = bpData)\n\nQuantile = 2.3215\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                                      Estimate lwr     upr    \nAgeMonths == 0                        0.05943  0.02761 0.09124\nAgeMonths + AgeMonths:Gendermale == 0 0.15237  0.12039 0.18434\nAgeMonths:Gendermale == 0             0.09294  0.04783 0.13805\n```\n\n\n:::\n:::\n\n\nNote that the glht function allows us to define the contrasts by explicitely defining the nullhypotheses using the names of the model parameters.\n\n## Conclusion\n\nWe can conclude that the association between age and blood pressure is extremely significant (p << 0.001).\n\nThe blood pressure for girls that differ in age is on average 0.059 mm Hg higher per month of age difference for the eldest girl (p << 0.001, 95% CI [0.028, 0.091].\n\nThe blood pressure for boys that differ in age is on average 0.152 mm Hg higher per month of age difference for the eldest boy  (p << 0.001, 95% CI [0.12, 0.184].\n\nThe average blood pressure difference between subjects that differ in age is on average  0.093 mm Hg/month higher for boys than for girls  (p << 0.001, 95% CI [0.048, 0.138]).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}