{
  "hash": "96c98465229888229ca329c30bbfce67",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercise 8.5: Blocking on the rat diet dataset - solution\"\nauthor: \"Lieven Clement, Jeroen Gilis and Milan Malfait\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\n---\n\n# Background\n\nResearchers are studying the impact of protein sources and protein levels in\nthe diet on the weight of rats. They feed the rats with diets of beef, cereal\nand pork and use a low and high protein level for each diet type.\nThe researchers can include 60 rats in the experiment. Prior to the experiment,\nthe rats were divided in 10 homogeneous groups of 6 rats based on\ncharacteristics such as initial weight, appetite, etc.\n\nWithin each group a rat is randomly assigned to a diet. The rats are fed during\na month and the weight gain in grams is recorded for each rat.\n\nThe researchers want to assess the effect of the type of diet and the protein\nlevel on the weight of the rats.\n\nIn this exercise we will perform the data exploration using all diets, but,\nto keep the data analysis simple we will only assess the beef and cereal diets.\n\n# Experimental design\n\n- There are three explanatory variables in the experiment: the factor diet type\nwith two levels (beef and cereal), factor protein level with levels\n(low and high) and a group blocking factor with 10 levels.\n\n- There are 6 treatments: beef-high, cereal-high, pork-high, beef-low,\ncereal-low, pork-low protein.\n\n- The rats are the experimental and observational units.\n\n- The weight gain is the response variable.\n\n- The experiment is a randomized complete block (RCB) design\n\nLoad libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n# Data import\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiet <- read.table(\"https://raw.githubusercontent.com/statOmics/PSLSData/main/dietRats.txt\",\n  header = TRUE\n)\nhead(diet)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"weightGain\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"protSource\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"protLevel\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"block\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"107\",\"2\":\"b\",\"3\":\"h\",\"4\":\"1\",\"_rn_\":\"1\"},{\"1\":\"96\",\"2\":\"c\",\"3\":\"h\",\"4\":\"1\",\"_rn_\":\"2\"},{\"1\":\"112\",\"2\":\"p\",\"3\":\"h\",\"4\":\"1\",\"_rn_\":\"3\"},{\"1\":\"83\",\"2\":\"b\",\"3\":\"l\",\"4\":\"1\",\"_rn_\":\"4\"},{\"1\":\"87\",\"2\":\"c\",\"3\":\"l\",\"4\":\"1\",\"_rn_\":\"5\"},{\"1\":\"90\",\"2\":\"p\",\"3\":\"l\",\"4\":\"1\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Tidy data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiet <- diet |>\n  ## Convert categorical levels to factors\n  mutate(\n    block = as.factor(block),\n    protSource = as.factor(protSource),\n    protLevel = as.factor(protLevel)\n  ) |>\n  ## Recode factors to make them more verbose\n  mutate(\n    protLevel = fct_recode(protLevel, high = \"h\", low = \"l\"),\n    protSource = fct_recode(protSource, beef = \"b\", cereal = \"c\", pork = \"p\")\n  ) |>\n  ## Set \"low\" as the reference level for `protLevel`\n  mutate(protLevel = fct_relevel(protLevel, \"low\"))\n\nhead(diet)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"weightGain\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"protSource\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"protLevel\"],\"name\":[3],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"block\"],\"name\":[4],\"type\":[\"fct\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"107\",\"2\":\"beef\",\"3\":\"high\",\"4\":\"1\",\"_rn_\":\"1\"},{\"1\":\"96\",\"2\":\"cereal\",\"3\":\"high\",\"4\":\"1\",\"_rn_\":\"2\"},{\"1\":\"112\",\"2\":\"pork\",\"3\":\"high\",\"4\":\"1\",\"_rn_\":\"3\"},{\"1\":\"83\",\"2\":\"beef\",\"3\":\"low\",\"4\":\"1\",\"_rn_\":\"4\"},{\"1\":\"87\",\"2\":\"cereal\",\"3\":\"low\",\"4\":\"1\",\"_rn_\":\"5\"},{\"1\":\"90\",\"2\":\"pork\",\"3\":\"low\",\"4\":\"1\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Data exploration\n\n- Boxplot of the weight gain against protein source, protein level with coloring according to block\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiet |>\n  ggplot(aes(x = protLevel, y = weightGain)) +\n  scale_fill_brewer(palette = \"RdGy\") +\n  theme_bw() +\n  geom_boxplot(outlier.shape = NA) +\n  geom_jitter(aes(color = block)) +\n  ggtitle(\"Weight gain dependence on protein source\") +\n  labs(x = \"Protein level\", y = \"Weight gain (g)\") +\n  stat_summary(\n    fun = mean, geom=\"point\",\n    shape=5, size=3, color=\"black\"\n  ) +\n  facet_wrap(vars(protSource))\n```\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n- Lineplot of the weight gain against protein source, protein level with coloring and grouping according to block\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiet |>\n  ggplot(aes(x = protLevel, y = weightGain, color = block)) +\n  scale_fill_brewer(palette = \"RdGy\") +\n  theme_bw() +\n  geom_line(aes(group = block)) +\n  geom_point() +\n  ggtitle(\"Weight gain dependence on protein source\") +\n  ylab(\"Weight gain (g)\") +\n  facet_wrap(vars(protSource))\n```\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n- An increase in the weight of the rats seems to depend on the protein source\nreceived in the diet.\n\n- The increase in the weight of the rats seems to depend on the level of protein\nreceived in the diet\n\n- There also seems to be an interaction effect between the protein level and the\nprotein source on the gain in weight of the rats. For the beef and the pork\ndiets the effect of high protein levels in the data seems to be much stronger\nthan in the cereal diet.\n\n- There is also a strong effect of the block. Blocking implies a randomisation\nrestriction, hence, we will have to include the block effect anyway.\n\n# Filter the data to only use the beef and cereal diet\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiet_bc <- diet |> filter(protSource != \"pork\")\n```\n:::\n\n\n# Multivariate linear regression analysis\n\n## Assumptions\n\nList assumptions:\n\n1. The observations are independent\n2. Linearity between the response and predictor variable\n3. The residuals of the model must be normally distributed\n4. Homoscedasticity of the data\n\nThe first assumption is met if we correct for block in the model because the\nrats were randomized to the treatment within block. The other three assumptions\ncan be assessed by fitting the linear model and calling the `plot()` function\nas follows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm1 <- lm(weightGain ~ block + protSource * protLevel, data = diet_bc)\nplot(lm1)\n```\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-7-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-7-4.png){width=672}\n:::\n:::\n\n\nAll assumptions are met for this dataset.\n\n## Hypothesis testing\n\nWe here fit a linear model with a blocking factor for `block` and main and\ninteraction effects for protein source and protein level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weightGain ~ block + protSource * protLevel, data = diet_bc)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-21.00  -6.25  -1.25   6.50  17.50 \n\nCoefficients:\n                               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      87.250      5.506  15.846 3.39e-15 ***\nblock2                          -11.750      6.830  -1.720 0.096797 .  \nblock3                           -3.750      6.830  -0.549 0.587467    \nblock4                          -19.000      6.830  -2.782 0.009735 ** \nblock5                           -9.000      6.830  -1.318 0.198650    \nblock6                            3.250      6.830   0.476 0.637999    \nblock7                          -30.250      6.830  -4.429 0.000141 ***\nblock8                           -8.250      6.830  -1.208 0.237536    \nblock9                          -16.750      6.830  -2.453 0.020933 *  \nblock10                           2.000      6.830   0.293 0.771883    \nprotSourcecereal                  1.100      4.319   0.255 0.800914    \nprotLevelhigh                    20.000      4.319   4.630 8.23e-05 ***\nprotSourcecereal:protLevelhigh  -18.200      6.109  -2.979 0.006043 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.659 on 27 degrees of freedom\nMultiple R-squared:  0.7252,\tAdjusted R-squared:  0.6031 \nF-statistic: 5.939 on 12 and 27 DF,  p-value: 6.122e-05\n```\n\n\n:::\n:::\n\n\n## Interpretation of the regression parameters\n\n\n::: {.cell}\n\n```{.r .cell-code}\nExploreModelMatrix::VisualizeDesign(diet_bc, ~ block + protSource * protLevel)$plotlist\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`block = 1`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 10`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 2`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-9-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 3`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-9-4.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 4`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-9-5.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 5`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-9-6.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 6`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-9-7.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 7`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-9-8.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 8`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-9-9.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`block = 9`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-9-10.png){width=672}\n:::\n:::\n\n\nThere are 3 levels for protein source, 2 levels for protein level and 10 levels\nfor the blocking variable. We will have one reference level for each respective\nvariable: beef, low, block 1. So we need 2, 1 and 9 dummy variables to introduce\nthe factors protein source, protein level and block in the linear model,\nrespectively.\n\nHence, we can write down the linear model as follows:\n\n$y_i=\\beta_0+\\beta_cx_{i,c} +\\beta_hx_{i,h}+\\beta_{ch}x_{i,c}x_{i,h}+\\beta_{b2}x_{i,b2}+\\ldots+\\beta_{b10}x_{i,b10}+\\epsilon_{i}$\n\nwith:\n$y_i$ the observed weight gain for rat i,\n$x_{i,h}$ a dummy variable which is 1 if rat i receives a high protein diet\nand is 0 otherwise,\n$x_{i,c}$ a dummy variable which is 1 if rat i receives a cereal diet\nand is 0 otherwise,\n$x_{i,bk}$ is a dummy variable which is 1 if rat i belongs to block $bk$\nand is 0 otherwise, with $k \\in 2,\\ldots, 10$,\nand $\\epsilon_i$ an error term which is normally distributed with mean 0 and\nvariance $\\sigma^2$, i.e. $\\epsilon_i \\sim N(0,\\sigma^2)$.\n\n- Rats that are assigned to block $k$ and receive a beef based low protein diet have\n\ta covariate pattern $x_{i,h}=0$, $x_{i,c}=0$, $x_{i,bm}=0$ with $m\\neq k$ and $x_{i,bk}=1$.\n\tTheir mean weight gain is thus equal to $\\mu_{l,b,bk}=\\beta_0+\\beta_{bk}$\n\n- Rats that are assigned to block $k$ and receive a beef based high protein diet have\n\ta covariate pattern $x_{i,h}=1$, $x_{i,c}=0$, $x_{i,bm}=0$ with $m\\neq k$ and $x_{i,bk}=1$.\n\tTheir mean weight gain is thus equal to $\\mu_{h,b,bk}=\\beta_0+\\beta_h+\\beta_{bk}$\n\n- Rats that are assigned to block $k$ and receive a cereal based low protein diet have\n\ta covariate pattern $x_{i,h}=0$, $x_{i,c}=1$, $x_{i,bm}=0$ with $m\\neq k$ and $x_{i,bk}=1$.\n\tTheir mean weight gain is thus equal to $\\mu_{h,c,bk}=\\beta_0+\\beta_c+\\beta_{bk}$\n\n- Rats that are assigned to block $k$ and receive a cereal based heigh protein diet have\n\ta covariate pattern $x_{i,h}=1$, $x_{i,c}=1$ $x_{i,bm}=0$ with $m\\neq k$ and $x_{i,bk}=1$.\n\tTheir mean weight gain is thus equal to $\\mu_{h,c,bk}=\\beta_0+\\beta_h+\\beta_c+\\beta_{ch}+\\beta_{bk}$\n\nWe can now relate this to the output of the `lm` function:\n\n- The intercept $\\beta_0$ is thus the average weight gain in the low beef\ndiet for rats in block 1.\n\n- The parameter $\\beta_c$: the average weight gain difference between cereal-low and\nbeef-low diet is 1.1g.\n\n- The parameter $\\beta_h$: the average weight gain difference between beef-high and\nbeef-Low diet is 20g.\n\n- The parameter $\\beta_{ch}$ is the difference in the average weight gain difference\ndue to the high protein level as compared to the low protein level for cereal diets\nas compared to the weight gain difference that occurs due to the protein level\nin the reference class (here beef diet). Here this is negative,\ni.e. -18.2g, thus the weight gain\nfor the cereal protein source increases on average less between high and\nlow protein diets than in beef based diets.\n\n## Testing the overall (combined) effect of diet\n\nBecause there are multiple factors with different levels in the model,\nwe can first assess the effect of the diet (protein Level, protein source\nand the interaction) by using anova. With this test we will assess the null\nhypothesis that the average weight gain in each treatment is equal: i.e. $H_0: \\mu_{b,l}=\\mu_{b,h}=\\mu_{c,h}=\\mu_{c,l}$ versus\nthe alternative hyptohesis $H_1:$ that at least two treatment means are\ndifferent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm0 <- lm(weightGain ~ block, data = diet_bc)\nanova(lm0, lm1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"RSS\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sum of Sq\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"30\",\"2\":\"5175.0\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\",\"6\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"27\",\"2\":\"2518.8\",\"3\":\"3\",\"4\":\"2656.2\",\"5\":\"9.490948\",\"6\":\"0.0001890084\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nWe can conclude that there is an very significant effect of the diet type\n(protein source and/or protein level and/or protein source-protein level\ninteraction) on the weight gain of rats (p = 2e-04).\n\n## Assessing the interaction effect between protein source and protein level\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = weightGain ~ block + protSource * protLevel, data = diet_bc)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-21.00  -6.25  -1.25   6.50  17.50 \n\nCoefficients:\n                               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      87.250      5.506  15.846 3.39e-15 ***\nblock2                          -11.750      6.830  -1.720 0.096797 .  \nblock3                           -3.750      6.830  -0.549 0.587467    \nblock4                          -19.000      6.830  -2.782 0.009735 ** \nblock5                           -9.000      6.830  -1.318 0.198650    \nblock6                            3.250      6.830   0.476 0.637999    \nblock7                          -30.250      6.830  -4.429 0.000141 ***\nblock8                           -8.250      6.830  -1.208 0.237536    \nblock9                          -16.750      6.830  -2.453 0.020933 *  \nblock10                           2.000      6.830   0.293 0.771883    \nprotSourcecereal                  1.100      4.319   0.255 0.800914    \nprotLevelhigh                    20.000      4.319   4.630 8.23e-05 ***\nprotSourcecereal:protLevelhigh  -18.200      6.109  -2.979 0.006043 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.659 on 27 degrees of freedom\nMultiple R-squared:  0.7252,\tAdjusted R-squared:  0.6031 \nF-statistic: 5.939 on 12 and 27 DF,  p-value: 6.122e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nAnova(lm1, type = \"III\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Sum Sq\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"23423.27\",\"2\":\"1\",\"3\":\"251.08316231\",\"4\":\"3.387443e-15\",\"_rn_\":\"(Intercept)\"},{\"1\":\"3992.60\",\"2\":\"9\",\"3\":\"4.75535970\",\"4\":\"7.545657e-04\",\"_rn_\":\"block\"},{\"1\":\"6.05\",\"2\":\"1\",\"3\":\"0.06485231\",\"4\":\"8.009145e-01\",\"_rn_\":\"protSource\"},{\"1\":\"2000.00\",\"2\":\"1\",\"3\":\"21.43878037\",\"4\":\"8.227801e-05\",\"_rn_\":\"protLevel\"},{\"1\":\"828.10\",\"2\":\"1\",\"3\":\"8.87672701\",\"4\":\"6.043197e-03\",\"_rn_\":\"protSource:protLevel\"},{\"1\":\"2518.80\",\"2\":\"27\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThere is a very significant interaction between the protein source and\nthe protein level. This indicates that the average weight increase due to\nthe protein level differs according to the protein source.\nHence, we cannot assess the effect of the protein source and/or protein level\nindependently because there effects of the protein source vary according to\nthe protein level.\n\n## Assessing specific contrasts\n\nImagine that we are interested in assessing if there is an effect of\n\n1. protein source in the low protein diets\n\t- $\\mu_{c,l}-\\mu_{b,l} = \\beta_c$\n\n\n2. protein source in high protein diets\n\t- $\\mu_{c,h}-\\mu_{b,h}=\\beta_c+\\beta_{ch}$\n\n3. protein level for beef diets ($\\mu_{b,h}-\\mu_{b,l}=\\beta_h$), and\ncereal diets  ($\\mu_{c,h}-\\mu_{c,l}=\\beta_h+\\beta_{ch}$)\n\n4. if the effect of the protein level differs between\n\t- beef and cereal  $(\\mu_{c,h}-\\mu_{c,l}) - (\\mu_{b,h}-\\mu_{b,l})=\\beta_{ch}$\n\nThese effects of interest are so-called\n**contrasts, i.e. linear combinations of the parameters**.\n\nWe can define the contrasts and assess the significance of the contrasts with\nthe code below. The contrasts are given as input in the form of symbolic\ndescriptions to the `linfct` argument of the `glht` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multcomp)\nset.seed(75468) # to get reproducible results (small effect if removed)\nlm1MultComp <- glht(\n  model = lm1,\n  linfct = c(\n    \"protSourcecereal = 0\",\n    \"protSourcecereal + protSourcecereal:protLevelhigh = 0\",\n    \"protLevelhigh = 0\",\n    \"protLevelhigh +  protSourcecereal:protLevelhigh = 0\",\n    \"protSourcecereal:protLevelhigh = 0\"\n  )\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm1MultComp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nFit: lm(formula = weightGain ~ block + protSource * protLevel, data = diet_bc)\n\nLinear Hypotheses:\n                                                       Estimate Std. Error\nprotSourcecereal == 0                                     1.100      4.319\nprotSourcecereal + protSourcecereal:protLevelhigh == 0  -17.100      4.319\nprotLevelhigh == 0                                       20.000      4.319\nprotLevelhigh + protSourcecereal:protLevelhigh == 0       1.800      4.319\nprotSourcecereal:protLevelhigh == 0                     -18.200      6.109\n                                                       t value Pr(>|t|)    \nprotSourcecereal == 0                                    0.255  0.99235    \nprotSourcecereal + protSourcecereal:protLevelhigh == 0  -3.959  0.00211 ** \nprotLevelhigh == 0                                       4.630  < 0.001 ***\nprotLevelhigh + protSourcecereal:protLevelhigh == 0      0.417  0.96838    \nprotSourcecereal:protLevelhigh == 0                     -2.979  0.02351 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lm1MultComp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nFit: lm(formula = weightGain ~ block + protSource * protLevel, data = diet_bc)\n\nQuantile = 2.6386\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n                                                       Estimate lwr     \nprotSourcecereal == 0                                    1.1000 -10.2975\nprotSourcecereal + protSourcecereal:protLevelhigh == 0 -17.1000 -28.4975\nprotLevelhigh == 0                                      20.0000   8.6025\nprotLevelhigh + protSourcecereal:protLevelhigh == 0      1.8000  -9.5975\nprotSourcecereal:protLevelhigh == 0                    -18.2000 -34.3185\n                                                       upr     \nprotSourcecereal == 0                                   12.4975\nprotSourcecereal + protSourcecereal:protLevelhigh == 0  -5.7025\nprotLevelhigh == 0                                      31.3975\nprotLevelhigh + protSourcecereal:protLevelhigh == 0     13.1975\nprotSourcecereal:protLevelhigh == 0                     -2.0815\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(lm1MultComp)\n```\n\n::: {.cell-output-display}\n![](08_5_rats_sol_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nNote that the p-values and the confidence intervals are automatically corrected\nfor multiple testing.\n\n# Conclusion\n\n- There is an extremely significant effect of the type of protein diet on the\nweight gain of rats  (p<<1e-3).\n\n- The average weight gain does not vary significantly according to protein\nsource in the diets with low protein levels (p = 0.99).\n\n- The weight gain in the cereal diet at high protein concentration is on\naverage 17.1g lower than in the high protein beef diet (95% CI [5.7, 28.5]) and the difference is\nvery significant (p = format(summary(lm1MultComp)$test$pvalues[names(summary(lm1MultComp)$test$tstat)==\"protSourcecereal + protSourcecereal:protLevelhigh\"],digits=1)).\n\n- We also discovered an extremely significant difference in weight gain\naccording to the protein level for beef based diets (p<<0.001).\nThe weight gain on average increases with 20g in the high protein\nlevel as compared to the low protein beef diet\n(95%CI [8.6, 31.4]).\nThe protein level effect is not significant\nfor the cereal diet (0.97).\n\n- Finally there is a significant interaction between protein level and protein source (p = 0.023), i.e. the increase in weight gain due to protein level in beef\nbased diets was 18.2g than that in the cerial diet (95% CI [2.1, 34.3]).\n\nAll reported p-values and confidence intervals were corrected for multiple\ntesting\n",
    "supporting": [
      "08_5_rats_sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}