{
  "hash": "d80ef5414e41697d76c3c40ef2a5c9e2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Analysis of prostacyclin experiment\nauthor: Lieven Clement\n---\n\n# Background\n\nResearchers study the effect of arachidonic acid on prostacyclin level in blood plasma. They use 3 different doses of arachidonic acid: low (10 units), medium (25 units) and high dose (50 units) and measure the prostacycline levels in blood plasma using an elisa fluorescence measurement. Treatments are randomly assigned to rats and every rat originates from a different litter and is grown in a separate cage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n# Experimental design\n\n- There is one explanatory variable: the factor dose\n- There are three treatments: low, medium and high dose of arachidonic acid\n- The effect of the treatments is assessed on the response variable prostacyclin level in blood plasma\n- The rats are the experimental and observational units\n- The experiment is a completely randomized design (CRD)\n- Researchers are interested to assess if there is an effect of the arachidonic acid dose on the prostacyclin level and when there is an effect, they want to asssess for which dose levels significantly different effects occur.\n\n# Data\n\nThe data can be found in a table of Voorbeeld 5.23 in the bachelor cours of statistics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprostacyclin <- data.frame(\n\tprostac=c(19.2, 10.8, 33.6, 11.9, 15.9, 33.3, 81.1, 36.7, 58.0, 60.8, 50.6, 69.4, 30.8, 27.6, 13.2, 38.8, 37.0, 38.3, 65.2, 66.4, 63.2, 49.9, 89.5, 60.5, 102.9, 57.1, 76.7, 70.5, 66.4, 76.3, 83.1, 61.7, 101.5, 86.2, 115.9, 102.1),\n\tdose=factor(c(rep(10,12),rep(25,12),rep(50,12))))\n```\n:::\n\n\n# Analysis\n\nOne-way anova to assess if there is an effect of the treatment. Tukey post-hoc test to assess pairwise differences between the treatment.\n\n## One-way anova\n\n### Data exploration\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprostacyclin |>\n  ggplot(aes(x=dose, y=prostac)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\")\n```\n\n::: {.cell-output-display}\n![](07_prostacyclin_example_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\nprostacyclin |>\n  ggplot(aes(sample=prostac)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_grid(cols = vars(dose))\n```\n\n::: {.cell-output-display}\n![](07_prostacyclin_example_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n:::\n\n\n- The boxplots show that the data are homoscedastic\n- The qq-plot show no severe deviations from normality\n\n### Anova\n\n- H0: On average there is no effect of the arachidonic acid treatment on the prostacyclin level in blood serum of rats\n- H1: The average prostacyclin level in blood serum of rats is different for at least two arachidonic dose levels\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'car'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:purrr':\n\n    some\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(multcomp)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: mvtnorm\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: survival\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: TH.data\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: MASS\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'MASS'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    select\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'TH.data'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:MASS':\n\n    geyser\n```\n\n\n:::\n\n```{.r .cell-code}\nlm1 <- lm(prostac~dose,data=prostacyclin)\nAnova(lm1,type=3)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Sum Sq\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"19304.14\",\"2\":\"1\",\"3\":\"42.52984\",\"4\":\"2.096323e-07\",\"_rn_\":\"(Intercept)\"},{\"1\":\"12657.93\",\"2\":\"2\",\"3\":\"13.94364\",\"4\":\"4.081242e-05\",\"_rn_\":\"dose\"},{\"1\":\"14978.58\",\"2\":\"33\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nThere is an extremely significant effect of arachidonic acid on the average prostacyclin blood concentration in rats (p<0.001).\n\n### Post-hoc\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntukey <- glht(lm1,linfct=mcp(dose=\"Tukey\"))\nsummary(tukey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: lm(formula = prostac ~ dose, data = prostacyclin)\n\nLinear Hypotheses:\n             Estimate Std. Error t value Pr(>|t|)    \n25 - 10 == 0    8.258      8.698   0.949 0.613379    \n50 - 10 == 0   43.258      8.698   4.974  < 1e-04 ***\n50 - 25 == 0   35.000      8.698   4.024 0.000858 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(tukey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Confidence Intervals\n\nMultiple Comparisons of Means: Tukey Contrasts\n\n\nFit: lm(formula = prostac ~ dose, data = prostacyclin)\n\nQuantile = 2.4532\n95% family-wise confidence level\n \n\nLinear Hypotheses:\n             Estimate lwr      upr     \n25 - 10 == 0   8.2583 -13.0789  29.5956\n50 - 10 == 0  43.2583  21.9211  64.5956\n50 - 25 == 0  35.0000  13.6628  56.3372\n```\n\n\n:::\n:::\n\n\nThe average prostacyclin concentration is higher in the high dose group than in the low and moderate dose group (both p-values are smaller than p<0.001).\nThe average concentration in the high dose group is 43.3 ng/ml (95% CI [21.9, 64.6]) and 35 ng/ml (95% CI [13.7, 56.3]) higher than in the low and moderate dose group, respectively (both p<0.001).\nThe difference in average prostacyclin concentration between the moderate and low dose group is not significant (p=0.61, 95% CI on average difference [-13.1, 29.6] ng/ml).\n\n# Conclusion\n\nThere is an extremely significant effect of arachidonic acid on the average prostacyclin blood concentration in rats (p<0.001).\nThe average concentration in the high dose group is 43.3 ng/ml (95% CI [21.9, 64.6]) and 35 ng/ml (95% CI [13.7, 56.3]) higher than in the low and moderate dose group, respectively (both p<0.001).\nThe difference in average prostacyclin concentration between the moderate and low dose group is not significant (p=0.61, 95% CI on average difference [-13.1, 29.6] ng/ml).\n",
    "supporting": [
      "07_prostacyclin_example_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}