{
  "hash": "a14ea19ef29b72fc00509628ebc2f3af",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercise 4.1: Exploring the NHANES dataset\"\nauthor: \"Lieven Clement, Jeroen Gilis and Milan Malfait\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\n---\n\n# Aims of this exercise\n\nIn this exercise, you will learn howto:\n\n- import data into R\n- tidy and wrangle data\n- explore and visualize data\n\nby following and interpreting the code of this worked out R/Rmarkdown example.\n\n# The NHANES dataset\n\nThe National Health and Nutrition Examination Survey (NHANES)\ncontains data that has been collected since 1960. For this exercise,\nwe will make use of the data that were collected between 2009 and\n2012, for 10.000 U.S. civilians. The dataset contains a large number of\nphysical, demographic, nutritional and life-style-related parameters.\n\nBefore we can actually start working with data, we will need to learn how to\nimport the required datasets into our R session.\n\n# Data Import  with the `readr` R package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\nLet's try reading in some data. We will begin by\nreading in the `NHANES.csv` dataset.\n\nNote that we don't need to download the dataset manually; `read_csv()` (or its base equivalent\n`read.csv()`) can take a URL as input and read in the data directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES <- read_csv(\"https://raw.githubusercontent.com/statOmics/PSLSData/main/NHANES.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 10000 Columns: 76\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (31): SurveyYr, Gender, AgeDecade, Race1, Race3, Education, MaritalStatu...\ndbl (45): ID, Age, AgeMonths, HHIncomeMid, Poverty, HomeRooms, Weight, Lengt...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(NHANES) ## take a look at the first 6 rows of the dataset\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"ID\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SurveyYr\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Gender\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Age\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AgeDecade\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"AgeMonths\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Race1\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Race3\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Education\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"MaritalStatus\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HHIncome\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HHIncomeMid\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Poverty\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HomeRooms\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HomeOwn\"],\"name\":[15],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Work\"],\"name\":[16],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Weight\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Length\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HeadCirc\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Height\"],\"name\":[20],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BMI\"],\"name\":[21],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BMICatUnder20yrs\"],\"name\":[22],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"BMI_WHO\"],\"name\":[23],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Pulse\"],\"name\":[24],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPSysAve\"],\"name\":[25],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPDiaAve\"],\"name\":[26],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPSys1\"],\"name\":[27],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPDia1\"],\"name\":[28],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPSys2\"],\"name\":[29],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPDia2\"],\"name\":[30],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPSys3\"],\"name\":[31],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPDia3\"],\"name\":[32],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Testosterone\"],\"name\":[33],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"DirectChol\"],\"name\":[34],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"TotChol\"],\"name\":[35],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"UrineVol1\"],\"name\":[36],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"UrineFlow1\"],\"name\":[37],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"UrineVol2\"],\"name\":[38],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"UrineFlow2\"],\"name\":[39],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Diabetes\"],\"name\":[40],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"DiabetesAge\"],\"name\":[41],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HealthGen\"],\"name\":[42],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"DaysPhysHlthBad\"],\"name\":[43],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"DaysMentHlthBad\"],\"name\":[44],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LittleInterest\"],\"name\":[45],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Depressed\"],\"name\":[46],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"nPregnancies\"],\"name\":[47],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"nBabies\"],\"name\":[48],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Age1stBaby\"],\"name\":[49],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SleepHrsNight\"],\"name\":[50],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SleepTrouble\"],\"name\":[51],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"PhysActive\"],\"name\":[52],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"PhysActiveDays\"],\"name\":[53],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"TVHrsDay\"],\"name\":[54],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"CompHrsDay\"],\"name\":[55],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"TVHrsDayChild\"],\"name\":[56],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CompHrsDayChild\"],\"name\":[57],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Alcohol12PlusYr\"],\"name\":[58],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"AlcoholDay\"],\"name\":[59],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AlcoholYear\"],\"name\":[60],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SmokeNow\"],\"name\":[61],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Smoke100\"],\"name\":[62],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Smoke100n\"],\"name\":[63],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"SmokeAge\"],\"name\":[64],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Marijuana\"],\"name\":[65],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"AgeFirstMarij\"],\"name\":[66],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"RegularMarij\"],\"name\":[67],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"AgeRegMarij\"],\"name\":[68],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HardDrugs\"],\"name\":[69],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"SexEver\"],\"name\":[70],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"SexAge\"],\"name\":[71],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SexNumPartnLife\"],\"name\":[72],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SexNumPartYear\"],\"name\":[73],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SameSex\"],\"name\":[74],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"SexOrientation\"],\"name\":[75],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"PregnantNow\"],\"name\":[76],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"51624\",\"2\":\"2009_10\",\"3\":\"male\",\"4\":\"34\",\"5\":\"30-39\",\"6\":\"409\",\"7\":\"White\",\"8\":\"NA\",\"9\":\"High School\",\"10\":\"Married\",\"11\":\"25000-34999\",\"12\":\"30000\",\"13\":\"1.36\",\"14\":\"6\",\"15\":\"Own\",\"16\":\"NotWorking\",\"17\":\"87.4\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"164.7\",\"21\":\"32.22\",\"22\":\"NA\",\"23\":\"30.0_plus\",\"24\":\"70\",\"25\":\"113\",\"26\":\"85\",\"27\":\"114\",\"28\":\"88\",\"29\":\"114\",\"30\":\"88\",\"31\":\"112\",\"32\":\"82\",\"33\":\"NA\",\"34\":\"1.29\",\"35\":\"3.49\",\"36\":\"352\",\"37\":\"NA\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"15\",\"45\":\"Most\",\"46\":\"Several\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"4\",\"51\":\"Yes\",\"52\":\"No\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"NA\",\"60\":\"0\",\"61\":\"No\",\"62\":\"Yes\",\"63\":\"Smoker\",\"64\":\"18\",\"65\":\"Yes\",\"66\":\"17\",\"67\":\"No\",\"68\":\"NA\",\"69\":\"Yes\",\"70\":\"Yes\",\"71\":\"16\",\"72\":\"8\",\"73\":\"1\",\"74\":\"No\",\"75\":\"Heterosexual\",\"76\":\"NA\"},{\"1\":\"51624\",\"2\":\"2009_10\",\"3\":\"male\",\"4\":\"34\",\"5\":\"30-39\",\"6\":\"409\",\"7\":\"White\",\"8\":\"NA\",\"9\":\"High School\",\"10\":\"Married\",\"11\":\"25000-34999\",\"12\":\"30000\",\"13\":\"1.36\",\"14\":\"6\",\"15\":\"Own\",\"16\":\"NotWorking\",\"17\":\"87.4\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"164.7\",\"21\":\"32.22\",\"22\":\"NA\",\"23\":\"30.0_plus\",\"24\":\"70\",\"25\":\"113\",\"26\":\"85\",\"27\":\"114\",\"28\":\"88\",\"29\":\"114\",\"30\":\"88\",\"31\":\"112\",\"32\":\"82\",\"33\":\"NA\",\"34\":\"1.29\",\"35\":\"3.49\",\"36\":\"352\",\"37\":\"NA\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"15\",\"45\":\"Most\",\"46\":\"Several\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"4\",\"51\":\"Yes\",\"52\":\"No\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"NA\",\"60\":\"0\",\"61\":\"No\",\"62\":\"Yes\",\"63\":\"Smoker\",\"64\":\"18\",\"65\":\"Yes\",\"66\":\"17\",\"67\":\"No\",\"68\":\"NA\",\"69\":\"Yes\",\"70\":\"Yes\",\"71\":\"16\",\"72\":\"8\",\"73\":\"1\",\"74\":\"No\",\"75\":\"Heterosexual\",\"76\":\"NA\"},{\"1\":\"51624\",\"2\":\"2009_10\",\"3\":\"male\",\"4\":\"34\",\"5\":\"30-39\",\"6\":\"409\",\"7\":\"White\",\"8\":\"NA\",\"9\":\"High School\",\"10\":\"Married\",\"11\":\"25000-34999\",\"12\":\"30000\",\"13\":\"1.36\",\"14\":\"6\",\"15\":\"Own\",\"16\":\"NotWorking\",\"17\":\"87.4\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"164.7\",\"21\":\"32.22\",\"22\":\"NA\",\"23\":\"30.0_plus\",\"24\":\"70\",\"25\":\"113\",\"26\":\"85\",\"27\":\"114\",\"28\":\"88\",\"29\":\"114\",\"30\":\"88\",\"31\":\"112\",\"32\":\"82\",\"33\":\"NA\",\"34\":\"1.29\",\"35\":\"3.49\",\"36\":\"352\",\"37\":\"NA\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"15\",\"45\":\"Most\",\"46\":\"Several\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"4\",\"51\":\"Yes\",\"52\":\"No\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"NA\",\"60\":\"0\",\"61\":\"No\",\"62\":\"Yes\",\"63\":\"Smoker\",\"64\":\"18\",\"65\":\"Yes\",\"66\":\"17\",\"67\":\"No\",\"68\":\"NA\",\"69\":\"Yes\",\"70\":\"Yes\",\"71\":\"16\",\"72\":\"8\",\"73\":\"1\",\"74\":\"No\",\"75\":\"Heterosexual\",\"76\":\"NA\"},{\"1\":\"51625\",\"2\":\"2009_10\",\"3\":\"male\",\"4\":\"4\",\"5\":\"0-9\",\"6\":\"49\",\"7\":\"Other\",\"8\":\"NA\",\"9\":\"NA\",\"10\":\"NA\",\"11\":\"20000-24999\",\"12\":\"22500\",\"13\":\"1.07\",\"14\":\"9\",\"15\":\"Own\",\"16\":\"NA\",\"17\":\"17.0\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"105.4\",\"21\":\"15.30\",\"22\":\"NA\",\"23\":\"12.0_18.5\",\"24\":\"NA\",\"25\":\"NA\",\"26\":\"NA\",\"27\":\"NA\",\"28\":\"NA\",\"29\":\"NA\",\"30\":\"NA\",\"31\":\"NA\",\"32\":\"NA\",\"33\":\"NA\",\"34\":\"NA\",\"35\":\"NA\",\"36\":\"NA\",\"37\":\"NA\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"NA\",\"43\":\"NA\",\"44\":\"NA\",\"45\":\"NA\",\"46\":\"NA\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"NA\",\"51\":\"NA\",\"52\":\"NA\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"4\",\"57\":\"1\",\"58\":\"NA\",\"59\":\"NA\",\"60\":\"NA\",\"61\":\"NA\",\"62\":\"NA\",\"63\":\"NA\",\"64\":\"NA\",\"65\":\"NA\",\"66\":\"NA\",\"67\":\"NA\",\"68\":\"NA\",\"69\":\"NA\",\"70\":\"NA\",\"71\":\"NA\",\"72\":\"NA\",\"73\":\"NA\",\"74\":\"NA\",\"75\":\"NA\",\"76\":\"NA\"},{\"1\":\"51630\",\"2\":\"2009_10\",\"3\":\"female\",\"4\":\"49\",\"5\":\"40-49\",\"6\":\"596\",\"7\":\"White\",\"8\":\"NA\",\"9\":\"Some College\",\"10\":\"LivePartner\",\"11\":\"35000-44999\",\"12\":\"40000\",\"13\":\"1.91\",\"14\":\"5\",\"15\":\"Rent\",\"16\":\"NotWorking\",\"17\":\"86.7\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"168.4\",\"21\":\"30.57\",\"22\":\"NA\",\"23\":\"30.0_plus\",\"24\":\"86\",\"25\":\"112\",\"26\":\"75\",\"27\":\"118\",\"28\":\"82\",\"29\":\"108\",\"30\":\"74\",\"31\":\"116\",\"32\":\"76\",\"33\":\"NA\",\"34\":\"1.16\",\"35\":\"6.70\",\"36\":\"77\",\"37\":\"0.094\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"10\",\"45\":\"Several\",\"46\":\"Several\",\"47\":\"2\",\"48\":\"2\",\"49\":\"27\",\"50\":\"8\",\"51\":\"Yes\",\"52\":\"No\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"2\",\"60\":\"20\",\"61\":\"Yes\",\"62\":\"Yes\",\"63\":\"Smoker\",\"64\":\"38\",\"65\":\"Yes\",\"66\":\"18\",\"67\":\"No\",\"68\":\"NA\",\"69\":\"Yes\",\"70\":\"Yes\",\"71\":\"12\",\"72\":\"10\",\"73\":\"1\",\"74\":\"Yes\",\"75\":\"Heterosexual\",\"76\":\"NA\"},{\"1\":\"51638\",\"2\":\"2009_10\",\"3\":\"male\",\"4\":\"9\",\"5\":\"0-9\",\"6\":\"115\",\"7\":\"White\",\"8\":\"NA\",\"9\":\"NA\",\"10\":\"NA\",\"11\":\"75000-99999\",\"12\":\"87500\",\"13\":\"1.84\",\"14\":\"6\",\"15\":\"Rent\",\"16\":\"NA\",\"17\":\"29.8\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"133.1\",\"21\":\"16.82\",\"22\":\"NA\",\"23\":\"12.0_18.5\",\"24\":\"82\",\"25\":\"86\",\"26\":\"47\",\"27\":\"84\",\"28\":\"50\",\"29\":\"84\",\"30\":\"50\",\"31\":\"88\",\"32\":\"44\",\"33\":\"NA\",\"34\":\"1.34\",\"35\":\"4.86\",\"36\":\"123\",\"37\":\"1.538\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"NA\",\"43\":\"NA\",\"44\":\"NA\",\"45\":\"NA\",\"46\":\"NA\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"NA\",\"51\":\"NA\",\"52\":\"NA\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"5\",\"57\":\"0\",\"58\":\"NA\",\"59\":\"NA\",\"60\":\"NA\",\"61\":\"NA\",\"62\":\"NA\",\"63\":\"NA\",\"64\":\"NA\",\"65\":\"NA\",\"66\":\"NA\",\"67\":\"NA\",\"68\":\"NA\",\"69\":\"NA\",\"70\":\"NA\",\"71\":\"NA\",\"72\":\"NA\",\"73\":\"NA\",\"74\":\"NA\",\"75\":\"NA\",\"76\":\"NA\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail(NHANES) ## take a look at the last rows of the dataset\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"ID\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SurveyYr\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Gender\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Age\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AgeDecade\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"AgeMonths\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Race1\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Race3\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Education\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"MaritalStatus\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HHIncome\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"HHIncomeMid\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Poverty\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HomeRooms\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HomeOwn\"],\"name\":[15],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Work\"],\"name\":[16],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Weight\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Length\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HeadCirc\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Height\"],\"name\":[20],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BMI\"],\"name\":[21],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BMICatUnder20yrs\"],\"name\":[22],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"BMI_WHO\"],\"name\":[23],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Pulse\"],\"name\":[24],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPSysAve\"],\"name\":[25],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPDiaAve\"],\"name\":[26],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPSys1\"],\"name\":[27],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPDia1\"],\"name\":[28],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPSys2\"],\"name\":[29],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPDia2\"],\"name\":[30],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPSys3\"],\"name\":[31],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPDia3\"],\"name\":[32],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Testosterone\"],\"name\":[33],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"DirectChol\"],\"name\":[34],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"TotChol\"],\"name\":[35],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"UrineVol1\"],\"name\":[36],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"UrineFlow1\"],\"name\":[37],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"UrineVol2\"],\"name\":[38],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"UrineFlow2\"],\"name\":[39],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Diabetes\"],\"name\":[40],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"DiabetesAge\"],\"name\":[41],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HealthGen\"],\"name\":[42],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"DaysPhysHlthBad\"],\"name\":[43],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"DaysMentHlthBad\"],\"name\":[44],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LittleInterest\"],\"name\":[45],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Depressed\"],\"name\":[46],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"nPregnancies\"],\"name\":[47],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"nBabies\"],\"name\":[48],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Age1stBaby\"],\"name\":[49],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SleepHrsNight\"],\"name\":[50],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SleepTrouble\"],\"name\":[51],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"PhysActive\"],\"name\":[52],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"PhysActiveDays\"],\"name\":[53],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"TVHrsDay\"],\"name\":[54],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"CompHrsDay\"],\"name\":[55],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"TVHrsDayChild\"],\"name\":[56],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CompHrsDayChild\"],\"name\":[57],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Alcohol12PlusYr\"],\"name\":[58],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"AlcoholDay\"],\"name\":[59],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AlcoholYear\"],\"name\":[60],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SmokeNow\"],\"name\":[61],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Smoke100\"],\"name\":[62],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Smoke100n\"],\"name\":[63],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"SmokeAge\"],\"name\":[64],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Marijuana\"],\"name\":[65],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"AgeFirstMarij\"],\"name\":[66],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"RegularMarij\"],\"name\":[67],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"AgeRegMarij\"],\"name\":[68],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HardDrugs\"],\"name\":[69],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"SexEver\"],\"name\":[70],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"SexAge\"],\"name\":[71],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SexNumPartnLife\"],\"name\":[72],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SexNumPartYear\"],\"name\":[73],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SameSex\"],\"name\":[74],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"SexOrientation\"],\"name\":[75],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"PregnantNow\"],\"name\":[76],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"71909\",\"2\":\"2011_12\",\"3\":\"male\",\"4\":\"28\",\"5\":\"20-29\",\"6\":\"NA\",\"7\":\"Mexican\",\"8\":\"Mexican\",\"9\":\"9 - 11th Grade\",\"10\":\"NeverMarried\",\"11\":\"5000-9999\",\"12\":\"7500\",\"13\":\"0.46\",\"14\":\"3\",\"15\":\"Rent\",\"16\":\"Working\",\"17\":\"92.3\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"177.3\",\"21\":\"29.4\",\"22\":\"NA\",\"23\":\"25.0_to_29.9\",\"24\":\"68\",\"25\":\"124\",\"26\":\"65\",\"27\":\"124\",\"28\":\"62\",\"29\":\"126\",\"30\":\"64\",\"31\":\"122\",\"32\":\"66\",\"33\":\"490.43\",\"34\":\"1.22\",\"35\":\"3.90\",\"36\":\"97\",\"37\":\"0.942\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"NA\",\"43\":\"NA\",\"44\":\"NA\",\"45\":\"NA\",\"46\":\"NA\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"6\",\"51\":\"No\",\"52\":\"Yes\",\"53\":\"NA\",\"54\":\"1_hr\",\"55\":\"2_hr\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"NA\",\"59\":\"NA\",\"60\":\"NA\",\"61\":\"Yes\",\"62\":\"Yes\",\"63\":\"Smoker\",\"64\":\"18\",\"65\":\"NA\",\"66\":\"NA\",\"67\":\"NA\",\"68\":\"NA\",\"69\":\"NA\",\"70\":\"NA\",\"71\":\"NA\",\"72\":\"NA\",\"73\":\"NA\",\"74\":\"NA\",\"75\":\"NA\",\"76\":\"NA\"},{\"1\":\"71909\",\"2\":\"2011_12\",\"3\":\"male\",\"4\":\"28\",\"5\":\"20-29\",\"6\":\"NA\",\"7\":\"Mexican\",\"8\":\"Mexican\",\"9\":\"9 - 11th Grade\",\"10\":\"NeverMarried\",\"11\":\"5000-9999\",\"12\":\"7500\",\"13\":\"0.46\",\"14\":\"3\",\"15\":\"Rent\",\"16\":\"Working\",\"17\":\"92.3\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"177.3\",\"21\":\"29.4\",\"22\":\"NA\",\"23\":\"25.0_to_29.9\",\"24\":\"68\",\"25\":\"124\",\"26\":\"65\",\"27\":\"124\",\"28\":\"62\",\"29\":\"126\",\"30\":\"64\",\"31\":\"122\",\"32\":\"66\",\"33\":\"490.43\",\"34\":\"1.22\",\"35\":\"3.90\",\"36\":\"97\",\"37\":\"0.942\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"NA\",\"43\":\"NA\",\"44\":\"NA\",\"45\":\"NA\",\"46\":\"NA\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"6\",\"51\":\"No\",\"52\":\"Yes\",\"53\":\"NA\",\"54\":\"1_hr\",\"55\":\"2_hr\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"NA\",\"59\":\"NA\",\"60\":\"NA\",\"61\":\"Yes\",\"62\":\"Yes\",\"63\":\"Smoker\",\"64\":\"18\",\"65\":\"NA\",\"66\":\"NA\",\"67\":\"NA\",\"68\":\"NA\",\"69\":\"NA\",\"70\":\"NA\",\"71\":\"NA\",\"72\":\"NA\",\"73\":\"NA\",\"74\":\"NA\",\"75\":\"NA\",\"76\":\"NA\"},{\"1\":\"71910\",\"2\":\"2011_12\",\"3\":\"female\",\"4\":\"0\",\"5\":\"0-9\",\"6\":\"5\",\"7\":\"White\",\"8\":\"White\",\"9\":\"NA\",\"10\":\"NA\",\"11\":\"75000-99999\",\"12\":\"87500\",\"13\":\"3.37\",\"14\":\"10\",\"15\":\"Own\",\"16\":\"NA\",\"17\":\"6.7\",\"18\":\"67.6\",\"19\":\"42.2\",\"20\":\"NA\",\"21\":\"NA\",\"22\":\"NA\",\"23\":\"NA\",\"24\":\"NA\",\"25\":\"NA\",\"26\":\"NA\",\"27\":\"NA\",\"28\":\"NA\",\"29\":\"NA\",\"30\":\"NA\",\"31\":\"NA\",\"32\":\"NA\",\"33\":\"NA\",\"34\":\"NA\",\"35\":\"NA\",\"36\":\"NA\",\"37\":\"NA\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"NA\",\"41\":\"NA\",\"42\":\"NA\",\"43\":\"NA\",\"44\":\"NA\",\"45\":\"NA\",\"46\":\"NA\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"NA\",\"51\":\"NA\",\"52\":\"NA\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"NA\",\"59\":\"NA\",\"60\":\"NA\",\"61\":\"NA\",\"62\":\"NA\",\"63\":\"NA\",\"64\":\"NA\",\"65\":\"NA\",\"66\":\"NA\",\"67\":\"NA\",\"68\":\"NA\",\"69\":\"NA\",\"70\":\"NA\",\"71\":\"NA\",\"72\":\"NA\",\"73\":\"NA\",\"74\":\"NA\",\"75\":\"NA\",\"76\":\"NA\"},{\"1\":\"71911\",\"2\":\"2011_12\",\"3\":\"male\",\"4\":\"27\",\"5\":\"20-29\",\"6\":\"NA\",\"7\":\"Mexican\",\"8\":\"Mexican\",\"9\":\"College Grad\",\"10\":\"Married\",\"11\":\"75000-99999\",\"12\":\"87500\",\"13\":\"3.25\",\"14\":\"10\",\"15\":\"Own\",\"16\":\"Working\",\"17\":\"96.7\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"175.8\",\"21\":\"31.3\",\"22\":\"NA\",\"23\":\"30.0_plus\",\"24\":\"74\",\"25\":\"133\",\"26\":\"74\",\"27\":\"122\",\"28\":\"76\",\"29\":\"132\",\"30\":\"82\",\"31\":\"134\",\"32\":\"66\",\"33\":\"509.00\",\"34\":\"1.06\",\"35\":\"5.72\",\"36\":\"63\",\"37\":\"0.600\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"2\",\"45\":\"None\",\"46\":\"None\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"6\",\"51\":\"No\",\"52\":\"No\",\"53\":\"3\",\"54\":\"1_hr\",\"55\":\"0_to_1_hr\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"5\",\"60\":\"4\",\"61\":\"NA\",\"62\":\"No\",\"63\":\"Non-Smoker\",\"64\":\"NA\",\"65\":\"Yes\",\"66\":\"22\",\"67\":\"No\",\"68\":\"NA\",\"69\":\"No\",\"70\":\"Yes\",\"71\":\"21\",\"72\":\"1\",\"73\":\"1\",\"74\":\"No\",\"75\":\"Heterosexual\",\"76\":\"NA\"},{\"1\":\"71915\",\"2\":\"2011_12\",\"3\":\"male\",\"4\":\"60\",\"5\":\"60-69\",\"6\":\"NA\",\"7\":\"White\",\"8\":\"White\",\"9\":\"College Grad\",\"10\":\"NeverMarried\",\"11\":\"65000-74999\",\"12\":\"70000\",\"13\":\"5.00\",\"14\":\"4\",\"15\":\"Own\",\"16\":\"Working\",\"17\":\"78.4\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"168.8\",\"21\":\"27.5\",\"22\":\"NA\",\"23\":\"25.0_to_29.9\",\"24\":\"76\",\"25\":\"147\",\"26\":\"73\",\"27\":\"150\",\"28\":\"72\",\"29\":\"148\",\"30\":\"74\",\"31\":\"146\",\"32\":\"72\",\"33\":\"505.13\",\"34\":\"0.93\",\"35\":\"4.94\",\"36\":\"218\",\"37\":\"1.253\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"Yes\",\"41\":\"56\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"2\",\"45\":\"None\",\"46\":\"None\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"6\",\"51\":\"No\",\"52\":\"No\",\"53\":\"1\",\"54\":\"2_hr\",\"55\":\"1_hr\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"NA\",\"60\":\"0\",\"61\":\"NA\",\"62\":\"No\",\"63\":\"Non-Smoker\",\"64\":\"NA\",\"65\":\"NA\",\"66\":\"NA\",\"67\":\"NA\",\"68\":\"NA\",\"69\":\"No\",\"70\":\"Yes\",\"71\":\"19\",\"72\":\"2\",\"73\":\"NA\",\"74\":\"No\",\"75\":\"NA\",\"76\":\"NA\"},{\"1\":\"71915\",\"2\":\"2011_12\",\"3\":\"male\",\"4\":\"60\",\"5\":\"60-69\",\"6\":\"NA\",\"7\":\"White\",\"8\":\"White\",\"9\":\"College Grad\",\"10\":\"NeverMarried\",\"11\":\"65000-74999\",\"12\":\"70000\",\"13\":\"5.00\",\"14\":\"4\",\"15\":\"Own\",\"16\":\"Working\",\"17\":\"78.4\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"168.8\",\"21\":\"27.5\",\"22\":\"NA\",\"23\":\"25.0_to_29.9\",\"24\":\"76\",\"25\":\"147\",\"26\":\"73\",\"27\":\"150\",\"28\":\"72\",\"29\":\"148\",\"30\":\"74\",\"31\":\"146\",\"32\":\"72\",\"33\":\"505.13\",\"34\":\"0.93\",\"35\":\"4.94\",\"36\":\"218\",\"37\":\"1.253\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"Yes\",\"41\":\"56\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"2\",\"45\":\"None\",\"46\":\"None\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"6\",\"51\":\"No\",\"52\":\"No\",\"53\":\"NA\",\"54\":\"2_hr\",\"55\":\"1_hr\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"NA\",\"60\":\"0\",\"61\":\"NA\",\"62\":\"No\",\"63\":\"Non-Smoker\",\"64\":\"NA\",\"65\":\"NA\",\"66\":\"NA\",\"67\":\"NA\",\"68\":\"NA\",\"69\":\"No\",\"70\":\"Yes\",\"71\":\"19\",\"72\":\"2\",\"73\":\"NA\",\"74\":\"No\",\"75\":\"NA\",\"76\":\"NA\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n # display a select set of variable and subjects\nNHANES[c(1, 4, 5, 6, 7, 8), c(\"ID\", \"Gender\", \"Age\", \"Race1\", \"Weight\", \"Height\", \"BMI\", \"BPSysAve\")]\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"ID\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Gender\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Age\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Race1\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Weight\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Height\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BMI\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BPSysAve\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"51624\",\"2\":\"male\",\"3\":\"34\",\"4\":\"White\",\"5\":\"87.4\",\"6\":\"164.7\",\"7\":\"32.22\",\"8\":\"113\"},{\"1\":\"51625\",\"2\":\"male\",\"3\":\"4\",\"4\":\"Other\",\"5\":\"17.0\",\"6\":\"105.4\",\"7\":\"15.30\",\"8\":\"NA\"},{\"1\":\"51630\",\"2\":\"female\",\"3\":\"49\",\"4\":\"White\",\"5\":\"86.7\",\"6\":\"168.4\",\"7\":\"30.57\",\"8\":\"112\"},{\"1\":\"51638\",\"2\":\"male\",\"3\":\"9\",\"4\":\"White\",\"5\":\"29.8\",\"6\":\"133.1\",\"7\":\"16.82\",\"8\":\"86\"},{\"1\":\"51646\",\"2\":\"male\",\"3\":\"8\",\"4\":\"White\",\"5\":\"35.2\",\"6\":\"130.6\",\"7\":\"20.64\",\"8\":\"107\"},{\"1\":\"51647\",\"2\":\"female\",\"3\":\"45\",\"4\":\"White\",\"5\":\"75.7\",\"6\":\"166.7\",\"7\":\"27.24\",\"8\":\"118\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Take a `glimpse()` at your data {-}\n\nThe `glimpse()` function allows us to (obviously) take\na first, informative glimpse at our data. The function\nis part of the `dplyr` package, which we will explore in much\nmore detail below!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(NHANES[, 1:10])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,000\nColumns: 10\n$ ID            <dbl> 51624, 51624, 51624, 51625, 51630, 51638, 51646, 51647, …\n$ SurveyYr      <chr> \"2009_10\", \"2009_10\", \"2009_10\", \"2009_10\", \"2009_10\", \"…\n$ Gender        <chr> \"male\", \"male\", \"male\", \"male\", \"female\", \"male\", \"male\"…\n$ Age           <dbl> 34, 34, 34, 4, 49, 9, 8, 45, 45, 45, 66, 58, 54, 10, 58,…\n$ AgeDecade     <chr> \"30-39\", \"30-39\", \"30-39\", \"0-9\", \"40-49\", \"0-9\", \"0-9\",…\n$ AgeMonths     <dbl> 409, 409, 409, 49, 596, 115, 101, 541, 541, 541, 795, 70…\n$ Race1         <chr> \"White\", \"White\", \"White\", \"Other\", \"White\", \"White\", \"W…\n$ Race3         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ Education     <chr> \"High School\", \"High School\", \"High School\", NA, \"Some C…\n$ MaritalStatus <chr> \"Married\", \"Married\", \"Married\", NA, \"LivePartner\", NA, …\n```\n\n\n:::\n\n```{.r .cell-code}\n# or glimpse(NHANES) to see all the variables in the dataset\n```\n:::\n\n\n# Data Tidying\n\n**Important**:\nIf you are not familiar yet with the concepts of tidy data,\nhave a look at the [*tidyverse preliminary*](./extra1_preliminary_tidyverse.html) first!\n\nIf we consider our `NHANES` dataframe, we see it is already in\na tidy format, as;\n\n* Each variable forms a column.\n* Each observation forms a row.\n* Each type of observational unit forms a table.\n\nEach row contains all of the information on\na single subject (US civilian) in the study.\n\nIn te next tutorial, we will work with a dataset on the\neffects of sugar intake  on the blood glucose level of patients. This will not be\na _tidy_ dataset. As such, the details of tidying data\nwith tidyverse will be described there\n\n# Data wrangling with `dplyr`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n:::\n\n\nThe `dplyr` package provides us with a large set of functions for handeling our data. We refer to\nthe [*preliminary*](./extra1_preliminary_tidyverse.html) file for a more detailed description of\nthese functions.\n\nThe most important `dplyr` functions to remember are:\n\n|`dplyr` verbs | Description |\n|:---|:-------------------------------------------------------------------|\n| `select()` | select columns  |\n| `filter()` | filter rows |\n| `arrange()` | re-order or arrange rows |\n| `mutate()` | create new columns |\n| `summarize()` | summarize values |\n| `group_by()` | allows for group operations in the \"split-apply-combine\" concept |\n\n## The pipe\n\nIn addition, R has a built-in [pipe operator](https://r4ds.had.co.nz/pipes.html#pipes)\n`|>` to use the output of one function as an input to the next\nfunction. Instead of nesting functions (reading from the inside to the outside), piping can improve\nreadability by allowing to write function calls from left to right or top to bottom.\n\nFor example, the following nested expression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoo(bar(baz(x)))\n```\n:::\n\n\nCould be rewritten as\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx |>\n  baz() |>\n  bar() |>\n  foo()\n```\n:::\n\n\nNote that the pipe should only be used when it *improves* readability! It's a purely esthetic tool\nand does not change anyting to how the functions are evaluated.\n\nNote that the above example could also be rewritten using *intermediate steps*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx1 <- baz(x)\nx2 <- bar(x1)\nx3 <- foo(x2)\n```\n:::\n\n\nWhich in some cases might actually be more appropriate (for example when you need to debug the code\nor reuse the intermediate results) but has the downside of having to name each intermediate object.\n\nIn short, be conscious about when it's appropriate to use the pipe and don't just blindly use it\neverywhere. **Ask yourself whether it really improves the readability of your code.**\n\n## Select and filter\n\nHere we will demonstrate the `dplyr` functionalities with\na couple of small examples.\n\nLet's say we want to investigate how many subjects are\n\n1. men that\n\n2. are older than 18 years old,\n\n3. are taller than 150 cm, and\n\n4. have weight of less than 80kg\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  ## (Optional) select the colums of interest\n  select(c(\"Gender\", \"Age\", \"Weight\", \"Height\")) |>\n  ## filter observations (rows) based on the required values\n  filter(\n    Gender == \"male\",\n    Age > 18,\n    Height > 150,\n    Weight < 80\n  ) |>\n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1286\n```\n\n\n:::\n:::\n\n\nFiltering the dataset based on thee three filtering criteria\nretain 3.601 subjects. Note that the the `select` step wasn't\nstrictly necessary, but since we could answer the question\nbased on only these 4 colums, there is no need to retain the\nthe rest of the data (if this is the only question).\n\n## Arrange\n\nNext question; within the `Race1` category of `Hispanics`, select\n`men` that are `not married` and display the first five by\ndescending height`\n\n**Hint**: use the `desc()` function inside of\n`arrange()` to order rows in a descending order.\nUse the base R function `head` to display the first\nfive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  select(c(\"Race1\", \"Gender\", \"MaritalStatus\", \"Height\")) |>\n  filter(MaritalStatus != \"Married\", Race1 == \"Hispanic\", Gender == \"male\") |>\n  arrange(desc(Height)) |>\n  head(n = 5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Race1\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Gender\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"MaritalStatus\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Height\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"197.2\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"189.5\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"181.9\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"180.6\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"180.3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nWe have successfully combined three of the main `dplyr`\nfunctionalities. Let's try to explore another one!\n\n## Mutate\n\nAssume that we don't trust the BMI values in our dataset\nand we decide to calculate them ourselves. BMI is typically\ncalculated by taking a person's weigth (in kg) and dividing\nit by the its height (in m) squared. Based on this rule,\ngenerate a new column, `BMI_self`, for the subset of the\nNHANES dataset that we obtained from the previous question.\nTo create new columns, we will use the `mutate()` function\nin `dplyr`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  select(c(\"Race1\", \"Gender\", \"MaritalStatus\", \"Height\", \"Weight\", \"BMI\")) |>\n  filter(MaritalStatus != \"Married\", Race1 == \"Hispanic\", Gender == \"male\") |>\n  mutate(BMI_self = Weight / (Height / 100)**2)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Race1\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Gender\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"MaritalStatus\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Height\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Weight\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BMI\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BMI_self\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"177.1\",\"5\":\"113.9\",\"6\":\"36.32\",\"7\":\"36.31505\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"177.1\",\"5\":\"113.9\",\"6\":\"36.32\",\"7\":\"36.31505\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"189.5\",\"5\":\"124.7\",\"6\":\"34.73\",\"7\":\"34.72546\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"175.6\",\"5\":\"160.6\",\"6\":\"52.08\",\"7\":\"52.08306\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"164.1\",\"5\":\"88.2\",\"6\":\"32.75\",\"7\":\"32.75303\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"164.1\",\"5\":\"88.2\",\"6\":\"32.75\",\"7\":\"32.75303\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"161.7\",\"5\":\"78.5\",\"6\":\"30.02\",\"7\":\"30.02269\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"173.1\",\"5\":\"95.4\",\"6\":\"31.84\",\"7\":\"31.83862\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"179.2\",\"5\":\"92.8\",\"6\":\"28.90\",\"7\":\"28.89828\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"179.2\",\"5\":\"92.8\",\"6\":\"28.90\",\"7\":\"28.89828\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Separated\",\"4\":\"176.5\",\"5\":\"92.5\",\"6\":\"29.69\",\"7\":\"29.69288\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"170.1\",\"5\":\"71.2\",\"6\":\"24.61\",\"7\":\"24.60772\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"170.1\",\"5\":\"71.2\",\"6\":\"24.61\",\"7\":\"24.60772\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"172.0\",\"5\":\"92.6\",\"6\":\"31.30\",\"7\":\"31.30070\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"172.9\",\"5\":\"69.8\",\"6\":\"23.35\",\"7\":\"23.34885\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"180.3\",\"5\":\"115.9\",\"6\":\"35.65\",\"7\":\"35.65266\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"180.3\",\"5\":\"115.9\",\"6\":\"35.65\",\"7\":\"35.65266\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Separated\",\"4\":\"168.3\",\"5\":\"113.7\",\"6\":\"40.14\",\"7\":\"40.14137\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"179.6\",\"5\":\"95.3\",\"6\":\"29.54\",\"7\":\"29.54474\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"175.6\",\"5\":\"82.1\",\"6\":\"26.63\",\"7\":\"26.62528\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"162.8\",\"5\":\"70.0\",\"6\":\"26.41\",\"7\":\"26.41127\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"164.8\",\"5\":\"94.7\",\"6\":\"34.87\",\"7\":\"34.86868\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"178.2\",\"5\":\"75.4\",\"6\":\"23.74\",\"7\":\"23.74411\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"168.9\",\"5\":\"79.9\",\"6\":\"28.01\",\"7\":\"28.00835\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"171.0\",\"5\":\"79.3\",\"6\":\"27.12\",\"7\":\"27.11946\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"171.0\",\"5\":\"79.3\",\"6\":\"27.12\",\"7\":\"27.11946\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"175.4\",\"5\":\"90.8\",\"6\":\"29.51\",\"7\":\"29.51390\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Widowed\",\"4\":\"163.4\",\"5\":\"85.0\",\"6\":\"31.84\",\"7\":\"31.83573\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Widowed\",\"4\":\"163.4\",\"5\":\"85.0\",\"6\":\"31.84\",\"7\":\"31.83573\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Widowed\",\"4\":\"169.3\",\"5\":\"94.2\",\"6\":\"32.87\",\"7\":\"32.86525\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"163.1\",\"5\":\"66.7\",\"6\":\"25.07\",\"7\":\"25.07367\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"179.3\",\"5\":\"75.6\",\"6\":\"23.52\",\"7\":\"23.51588\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"180.6\",\"5\":\"84.6\",\"6\":\"25.94\",\"7\":\"25.93790\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Separated\",\"4\":\"177.2\",\"5\":\"92.7\",\"6\":\"29.52\",\"7\":\"29.52244\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"172.3\",\"5\":\"77.0\",\"6\":\"25.94\",\"7\":\"25.93703\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"179.5\",\"5\":\"79.3\",\"6\":\"24.61\",\"7\":\"24.61185\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"174.1\",\"5\":\"84.9\",\"6\":\"28.01\",\"7\":\"28.00981\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"174.8\",\"5\":\"78.3\",\"6\":\"25.63\",\"7\":\"25.62589\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"153.2\",\"5\":\"61.5\",\"6\":\"26.20\",\"7\":\"26.20340\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"177.1\",\"5\":\"70.8\",\"6\":\"22.57\",\"7\":\"22.57336\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"174.0\",\"5\":\"77.9\",\"6\":\"25.73\",\"7\":\"25.72995\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"168.4\",\"5\":\"77.7\",\"6\":\"27.40\",\"7\":\"27.39913\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Separated\",\"4\":\"172.6\",\"5\":\"68.8\",\"6\":\"23.09\",\"7\":\"23.09441\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"164.4\",\"5\":\"77.0\",\"6\":\"28.50\",\"7\":\"28.48965\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"172.6\",\"5\":\"90.6\",\"6\":\"30.40\",\"7\":\"30.41211\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"169.0\",\"5\":\"84.1\",\"6\":\"29.40\",\"7\":\"29.44575\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"172.3\",\"5\":\"82.3\",\"6\":\"27.70\",\"7\":\"27.72230\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"167.2\",\"5\":\"82.7\",\"6\":\"29.60\",\"7\":\"29.58237\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"167.2\",\"5\":\"82.7\",\"6\":\"29.60\",\"7\":\"29.58237\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"177.1\",\"5\":\"105.0\",\"6\":\"33.50\",\"7\":\"33.47744\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"177.1\",\"5\":\"105.0\",\"6\":\"33.50\",\"7\":\"33.47744\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"177.1\",\"5\":\"105.0\",\"6\":\"33.50\",\"7\":\"33.47744\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"164.2\",\"5\":\"78.0\",\"6\":\"28.90\",\"7\":\"28.92999\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"165.6\",\"5\":\"81.0\",\"6\":\"29.50\",\"7\":\"29.53686\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"165.6\",\"5\":\"81.0\",\"6\":\"29.50\",\"7\":\"29.53686\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"176.4\",\"5\":\"94.2\",\"6\":\"30.30\",\"7\":\"30.27288\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"177.2\",\"5\":\"111.3\",\"6\":\"35.40\",\"7\":\"35.44604\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Separated\",\"4\":\"175.6\",\"5\":\"130.0\",\"6\":\"42.20\",\"7\":\"42.15939\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"170.4\",\"5\":\"82.2\",\"6\":\"28.30\",\"7\":\"28.30953\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"181.9\",\"5\":\"101.2\",\"6\":\"30.60\",\"7\":\"30.58547\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"171.0\",\"5\":\"68.9\",\"6\":\"23.60\",\"7\":\"23.56281\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"171.0\",\"5\":\"68.9\",\"6\":\"23.60\",\"7\":\"23.56281\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"197.2\",\"5\":\"77.1\",\"6\":\"19.80\",\"7\":\"19.82625\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"170.7\",\"5\":\"98.9\",\"6\":\"33.90\",\"7\":\"33.94136\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"170.7\",\"5\":\"98.9\",\"6\":\"33.90\",\"7\":\"33.94136\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"170.7\",\"5\":\"98.9\",\"6\":\"33.90\",\"7\":\"33.94136\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"170.7\",\"5\":\"98.9\",\"6\":\"33.90\",\"7\":\"33.94136\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"170.5\",\"5\":\"84.3\",\"6\":\"29.00\",\"7\":\"28.99872\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"173.2\",\"5\":\"91.9\",\"6\":\"30.60\",\"7\":\"30.63513\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"167.4\",\"5\":\"64.9\",\"6\":\"23.20\",\"7\":\"23.15975\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"180.3\",\"5\":\"106.0\",\"6\":\"32.60\",\"7\":\"32.60727\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Separated\",\"4\":\"174.1\",\"5\":\"100.3\",\"6\":\"33.10\",\"7\":\"33.09050\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"168.5\",\"5\":\"68.1\",\"6\":\"24.00\",\"7\":\"23.98542\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"168.5\",\"5\":\"68.1\",\"6\":\"24.00\",\"7\":\"23.98542\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"160.6\",\"5\":\"56.7\",\"6\":\"22.00\",\"7\":\"21.98325\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Separated\",\"4\":\"166.6\",\"5\":\"95.2\",\"6\":\"34.30\",\"7\":\"34.29943\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Widowed\",\"4\":\"161.8\",\"5\":\"69.1\",\"6\":\"26.40\",\"7\":\"26.39496\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"169.1\",\"5\":\"99.9\",\"6\":\"34.90\",\"7\":\"34.93641\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"172.7\",\"5\":\"62.4\",\"6\":\"20.90\",\"7\":\"20.92184\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"172.7\",\"5\":\"62.4\",\"6\":\"20.90\",\"7\":\"20.92184\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"170.4\",\"5\":\"82.8\",\"6\":\"28.50\",\"7\":\"28.51617\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"171.1\",\"5\":\"76.3\",\"6\":\"26.10\",\"7\":\"26.06301\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"160.3\",\"5\":\"65.1\",\"6\":\"25.30\",\"7\":\"25.33459\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"160.3\",\"5\":\"65.1\",\"6\":\"25.30\",\"7\":\"25.33459\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"160.5\",\"5\":\"65.8\",\"6\":\"25.50\",\"7\":\"25.54323\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"160.6\",\"5\":\"77.2\",\"6\":\"29.90\",\"7\":\"29.93134\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"160.6\",\"5\":\"77.2\",\"6\":\"29.90\",\"7\":\"29.93134\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Separated\",\"4\":\"164.4\",\"5\":\"73.0\",\"6\":\"27.00\",\"7\":\"27.00967\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Separated\",\"4\":\"164.4\",\"5\":\"73.0\",\"6\":\"27.00\",\"7\":\"27.00967\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"172.9\",\"5\":\"84.9\",\"6\":\"28.40\",\"7\":\"28.39996\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Divorced\",\"4\":\"172.9\",\"5\":\"84.9\",\"6\":\"28.40\",\"7\":\"28.39996\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"180.1\",\"5\":\"79.0\",\"6\":\"24.40\",\"7\":\"24.35565\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"180.1\",\"5\":\"79.0\",\"6\":\"24.40\",\"7\":\"24.35565\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Widowed\",\"4\":\"170.5\",\"5\":\"87.8\",\"6\":\"30.20\",\"7\":\"30.20270\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"Separated\",\"4\":\"173.2\",\"5\":\"82.6\",\"6\":\"27.50\",\"7\":\"27.53495\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"171.7\",\"5\":\"99.0\",\"6\":\"33.60\",\"7\":\"33.58108\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"171.7\",\"5\":\"99.0\",\"6\":\"33.60\",\"7\":\"33.58108\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"171.7\",\"5\":\"99.0\",\"6\":\"33.60\",\"7\":\"33.58108\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"171.1\",\"5\":\"83.0\",\"6\":\"28.40\",\"7\":\"28.35163\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"175.7\",\"5\":\"65.3\",\"6\":\"21.20\",\"7\":\"21.15289\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"175.7\",\"5\":\"65.3\",\"6\":\"21.20\",\"7\":\"21.15289\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"175.7\",\"5\":\"65.3\",\"6\":\"21.20\",\"7\":\"21.15289\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"160.8\",\"5\":\"67.2\",\"6\":\"26.00\",\"7\":\"25.98946\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"LivePartner\",\"4\":\"166.6\",\"5\":\"63.3\",\"6\":\"22.80\",\"7\":\"22.80624\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"177.1\",\"5\":\"94.6\",\"6\":\"30.20\",\"7\":\"30.16157\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"162.7\",\"5\":\"56.3\",\"6\":\"21.30\",\"7\":\"21.26833\"},{\"1\":\"Hispanic\",\"2\":\"male\",\"3\":\"NeverMarried\",\"4\":\"162.7\",\"5\":\"56.3\",\"6\":\"21.30\",\"7\":\"21.26833\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNote that now we need to include the _Weight_ and _BMI_\ncolumns in the `select` statement, because we need that\ninput for the `mutate` function. Good news: It turns out\nthat the BMI column in the original dataset was computed\ncorrectly after all! But now we are interested in the\nmean value of the BMI_Self column. This requires a fifth\n`dplyr` function: `summarise()`.\n\n## Summarise\n\nGiven the filtering of the question above, compute the mean\nvalue of the `BMI_self` column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  select(c(\"Race1\", \"Gender\", \"MaritalStatus\", \"Height\", \"Weight\", \"BMI\")) |>\n  filter(MaritalStatus != \"Married\", Race1 == \"Hispanic\", Gender == \"male\") |>\n  mutate(BMI_self = Weight / (Height / 100)**2) |>\n  summarise(avg_BMI_self = mean(BMI_self, na.rm = TRUE))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"avg_BMI_self\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"28.81668\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n## the additional argument na.rm = TRUE makes sure to remove missing\n## values for the purpose of calculating the mean\n```\n:::\n\n\nFor this particular subset of the data, we find an\naverage BMI value of $28.59 kg/m^2$\n\nThere are many other summary statistics you could consider such `sd()`, `min()`, `median()`,\n`max()`, `sum()`, `n()` (returns the length of vector), `first()` (returns first value in vector),\n`last()` (returns last value in vector) and `n_distinct()` (number of distinct values in vector).\nWe will elaborate on these functions later.\n\nNote that choosing the most informative summary statistic is very important! This can be shown with\nthe following example;\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figures/Figure_partners.png){width=446}\n:::\n:::\n\n\nIn this study, men and woman were asked about their\n\"ideal number of partners desired over 30 years\".\nWhile almost all subjects desired a number between 0 and 50,\nthree male subjects selected a number above 100.\nThese three _outliers_ in the data can have a large impact on\nthe data analysis, especially when we work with summary\nstatistics that are sensitive to these outliers.\n\nWhen we look at the _mean_, for instance, we see that on average\nwoman desire 2.8 partners, while men desire 64.3 partners on average,\nsuggesting a large discrepancy between male and female desires.\n\nHowever, if look at a more _robust_ summary statistic such as\nthe _median_, we see that the result is 1 for both men and woman.\nIt is clear that the mean value was completely distorted by the\nthree outliers in the data.\n\nAnother example of a more robust summary statistic is\nthe _geometric mean_.\n\n## Group\n\nWe already combine 5 very important functions.\nHere, we will add a final one: `group_by()`.\n\nThe `group_by()` verb is and incredibly powerful\nfunction in `dplyr`. It allows us, for example,\nto calculate summarisy statistics for different\ngroups of observations.\n\nIf we take our example from above, let's say\nwe want to split the data frame by some variable\n(e.g. `MaritalStatus`), apply a function (`mean`)\nto a column (e.g. BMI_self) of the individual\ndata frames  and then combine the output back into\na summary data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  select(c(\"Race1\", \"Gender\", \"MaritalStatus\", \"Height\", \"Weight\", \"BMI\")) |>\n  filter(MaritalStatus != \"Married\", Race1 == \"Hispanic\", Gender == \"male\") |>\n  mutate(BMI_self = Weight / (Height / 100)**2) |>\n  group_by(MaritalStatus) |> ##  group the subjects by their marital status\n  summarise(avg_BMI_self = mean(BMI_self, na.rm = TRUE)) ## calculate the mean BMI_self value of each group\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"MaritalStatus\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"avg_BMI_self\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Divorced\",\"2\":\"28.42817\"},{\"1\":\"LivePartner\",\"2\":\"28.97381\"},{\"1\":\"NeverMarried\",\"2\":\"28.13185\"},{\"1\":\"Separated\",\"2\":\"31.35547\"},{\"1\":\"Widowed\",\"2\":\"30.62687\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nWe have successfully combined six of the most important\n`dplyr` functionalities!\n\nNow that we have all the required functions for importing, tidying and wrangling\ndata in place, we will learn how to visualize our data with the ggplot2 package.\n\n# Data Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n```\n:::\n\n\nAs you might have have already seen, there are many functions\navailable in base R that can create plots (e.g. `plot()`, `boxplot()`).\nOthers include: `hist()`, `qqplot()`, etc.\nThese functions are great because they come with a basic installation\nof R and can be quite powerful when you need a quick visualization\nof something when you are exploring data.\n\nWe are choosing to introduce `ggplot2` because, in our\nopinion, it's one of the simplest ways for beginners to\ncreate relatively complicated plots that are intuitive\nand aesthetically pleasing.\n\n## Univariate statistics\n\nIn univariate statistics, we focus on a single variable\nof interest. Here, we will show different ways to visualize\nthe `BMI` variable from the NHANES dataset. Importantly,\ndifferent types of visualizations will provide us with\ndifferent types of information!\n\nHere we will visualize the same data using\na histogram and a boxplot.\n\n### Histogram\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  head(NHANES, n = 100) |>\n  ggplot(aes(x = BMI)) +\n  geom_histogram(na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04_1_NHANES_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nThe information that can be obtained from this histogram\nis similar to that of the dotplot. Here, we can read immediately\n(i.e. without counting) that the BMI interval [29.5, 30.0[\ncontains 4 subjects. Again, the histogram does not provide us with\ninformation on the mean/median values of the data, but on\nits entire distribution.\n\nHistograms are typically useful to visualize data from experiments with large sample sizes. It is not useful to make histograms when the sample size is below 20 observations.\n\n### Boxplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2) ## to make the horizontal position of the jitter non-random\n\nNHANES |>\n  head(NHANES, n = 100) |>\n  ggplot(aes(x = \"\", y = BMI)) +\n  geom_boxplot(outlier.shape = NA, na.rm = TRUE) +\n  geom_jitter(width = 0.2, na.rm = TRUE) +\n  stat_summary(\n    geom = \"text\", fun = quantile,\n    aes(label = sprintf(\"%1.1f\", ..y..)),\n    position = position_nudge(x = 0.5), size = 4.5,\n    na.rm = TRUE\n  ) +\n  annotate(\"text\", x = c(1.5, 1.5, 1.5, 1.5, 1.5, 1.05, 1.05), y = c(12.5, 19, 24.5, 28.5, 45, 18, 35), label = c(\"(minimum)\", \"(25%)\", \"(median)\", \"(75%)\", \"(maximum)\", \"whisker\", \"whisker\"), size = 3)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The dot-dot notation (`..y..`) was deprecated in ggplot2 3.4.0.\nℹ Please use `after_stat(y)` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04_1_NHANES_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nArguably, the boxplot is the most informative default\nvisualization strategy. First, it provides us with\nsimilar insights to the shape of the distribution as\nthe histogram. Second, It clearly displays several useful\nsummary statistics such as the median, the interquartile\nrange, whiskers and outliers. Third, with the geom_jitter\nfunctionality we can also project each individual value\nof the dataset on the plot.\n\nThe latter is useful if you have small to medium sized datasets.\nIt allows you to visualize the raw data!\nThis however becomes cluttered for large experiments because they involve too many datapoints (>100).\n\nThe only disadvantage of the boxplot as compared to the histogram is that we cannot see (from the figure)\nhow many subjects have a BMI value within a certain interval.\n\n## Bivariate statistics\n\nIn bivariate statistics, the goal is to study two variables,\nincluding the relationship between both variables.\n\nIn terms of visualizations, the scatterplot is the baseline\nmethod for displaying two variables.\n\n### Create scatter plots using `geom_point()`\n\nFor the NHANES dataset, we can for instance look\nat the relationship between a person's height and weigth\nvalues.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- NHANES |>\n  ggplot(aes(x = Height, y = Weight))\np + geom_point(na.rm = TRUE) +\n  xlab(\"Height (cm)\") +\n  ylab(\"Weight (kg)\")\n```\n\n::: {.cell-output-display}\n![](04_1_NHANES_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nWe used the `xlab()` and `ylab()` functions\nin `ggplot2` to specify the x-axis and y-axis\nlabels. Note that NA values were automatically\nremove by the geom_point function.\n\nggplot2 also has a very broad panel of aesthetic features\nfor improving your plot. One very basic feature is that we\ncan give colors to the ggplot object. For instance, we can\ngive different colors to the dots in the previous\nscatterplot based on a subject's gender.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  ggplot(aes(x = Height, y = Weight, color = Gender)) +\n  geom_point(na.rm = TRUE) +\n  xlab(\"Height (cm)\") +\n  ylab(\"Weight (kg)\")\n```\n\n::: {.cell-output-display}\n![](04_1_NHANES_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n# Combining dplyr and ggplot2\n\nNote that the previous functions from the dplyr\npackage can be easily combined with ggplot through\nthe concept of pipes |>.\n\nFor instance, we could make the same scatterplot as above,\nbut only for white, married adults.\n\nIn addition, we here also show some convenient ggplot features;\n1. Setting the colors manually\n2. Set to have a white background\n3. Set a (main) title for the plot\n4. Pick a different shape for the dots in the scatterplot\n5. Manually set the limits of the x- and y-axes\n\nNote that this a only the tip of the iceberg of the\nthe ggplot functionalities!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  filter(Age >= 18, Race1 == \"White\", MaritalStatus == \"Married\") |> ## select the required data\n  ggplot(aes(x = Height, y = Weight, color = Gender)) +\n  geom_point(shape = 17, size = 1, na.rm = TRUE) + ## set to a different shape (triangle) and size\n  ggtitle(\"Height versus Weight\") + ## for the main title\n  xlab(\"Height (cm)\") +\n  ylab(\"Weight (kg)\") +\n  xlim(0, 220) + ## set limit of x-axis\n  ylim(0, 220) + ## set limit of y-axis\n  scale_color_manual(values = c(\"red\", \"blue\")) + ## manually set colors\n  theme_bw() ## set white background\n```\n\n::: {.cell-output-display}\n![](04_1_NHANES_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nNext to scatterplots, we have a large number of other\ntypes of plots at our disposal. Importantly, some plots\nwill be more informative than others, depending on the\nresearch question. Therefore, choosing the plot that is\nmost informative is crucial. We show this with a more\nelaborate example later (`captopril` exercise).\n\n# Final example\n\n## Goal\n\nSet up a reference interval for the systolic blood\npressure in the NHANES dataset.\n\n## Background\n\nThe captopril dataset, which we will explore and analyse later,\nholds information on  15 patients that have increased blood pressure\nvalues.\n\nBefore we may conduct such an experiment, we first need to know\nwhich values should be considered _increased_ and which ones should be\nconsidered _normal_. To find an interval for values that are normal,\nwe can set up a reference interval. To set up this interval, we will\nuse the NHANES dataset. The `BPSysAve` column holds data on the systolic\nblood pressure. To select healthy subjects, we will need to subset the\ndata.\n\n## Analysis\n\nFirst, we will plot the data for all subjects for which we have all\nthe required data and that are between 40 and 65 years old.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## histogram of BPSysAve for subjects wit age between 40 and 65 years old\nNHANES |>\n  filter(!is.na(Race1), !is.na(Smoke100n), !is.na(BMI_WHO), !is.na(Age), !is.na(HardDrugs), !is.na(HealthGen), !is.na(Gender), !is.na(AlcoholYear), !is.na(BPSysAve), !is.na(SleepTrouble)) |> ## retains 4660 subjects with the required data\n  filter(between(Age, 40, 65)) |> ## filter the subjects on age, retains 2522 subjects\n  distinct(ID, .keep_all = TRUE) |> ## removes duplicated IDs, retains 1467 subjects\n  ggplot(aes(x = BPSysAve)) +\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04_1_NHANES_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nAn important requirement of calculating reference intervals is\nthat the data is normally distributed. this is clearly not the\ncase; the data has a long right tail, which is quite common\nin biological data (in this easier to have extreme values on the\nright-hand side than on the left-hand size, which is additionally\nbounded by zero for most biological variables).\n\nBy selecting only _healthy_ subjects, we expect the data to be\ndistributed more normally. We define _healthy_ as being a non-smoker,\nwithout a history of diabetes, hard drugs or sleeping trouble, with a\ngeneral health that is not considered poor and that has a BMI between\n18.5 and 29.9.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## histogram of BPSysAve for HEALTHY subjects wit age between 40 and 65 years old\nNHANES |>\n  filter(!is.na(Race1), !is.na(Smoke100n), !is.na(BMI_WHO), !is.na(Age), !is.na(HardDrugs), !is.na(HealthGen), !is.na(Gender), !is.na(AlcoholYear), !is.na(BPSysAve), !is.na(SleepTrouble)) |> ## retains 4660 subjects with the required data\n  filter(between(Age, 40, 65)) |> ## filter the subjects on age, retains 2522 subjects\n  distinct(ID, .keep_all = TRUE) |> ## removes duplicated IDs, retains 1467 subjects\n  filter(Smoke100n == \"Non-Smoker\", Diabetes == \"No\", HardDrugs == \"No\", HealthGen != \"Poor\", SleepTrouble == \"No\", BMI_WHO %in% c(\"18.5_to_24.9\", \"25.0_to_29.9\")) |> ## filter to have only healthy subjects, based on multiple health criteria. Retains 275 subjects.\n  ggplot(aes(x = BPSysAve)) +\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04_1_NHANES_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nNow the data seems to be approximately normal on sight (we will later show how to\nassess data normality more formally). From this subset, we may calculate the\nreference interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## to get the 95% reference interval for the healthy group;\nsummary_NHANES <- NHANES |>\n  filter(!is.na(Race1), !is.na(Smoke100n), !is.na(BMI_WHO), !is.na(Age), !is.na(HardDrugs), !is.na(HealthGen), !is.na(Gender), !is.na(AlcoholYear), !is.na(BPSys1), !is.na(BPSys2), !is.na(BPSys3), !is.na(SleepTrouble)) |> ## retains 4660 subjects with the required data\n  filter(between(Age, 40, 65)) |> ## filter the subjects on age, retains 2522 subjects\n  distinct(ID, .keep_all = TRUE) |> ## removes duplicated IDs, retains 1467 subjects\n  filter(Smoke100n == \"Non-Smoker\", Diabetes == \"No\", HardDrugs == \"No\", HealthGen != \"Poor\", SleepTrouble == \"No\", BMI_WHO %in% c(\"18.5_to_24.9\", \"25.0_to_29.9\")) |> ## filter to have only healthy subjects, based on multiple health criteria. Retains 275 subjects.\n  Rmisc::summarySE(measurevar = \"BPSysAve\") # calculate the summary statistics\n\npaste(\"Mean value:\", summary_NHANES$BPSysAve)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Mean value: 119.018181818182\"\n```\n\n\n:::\n\n```{.r .cell-code}\npaste(\"Standard deviation:\", summary_NHANES$sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Standard deviation: 13.9763759348907\"\n```\n\n\n:::\n\n```{.r .cell-code}\npaste0(\"Reference interval: [\", summary_NHANES$BPSysAve - 2 * summary_NHANES$sd, \";\", summary_NHANES$BPSysAve + 2 * summary_NHANES$sd, \"]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Reference interval: [91.0654299484005;146.970933687963]\"\n```\n\n\n:::\n:::\n\n\nThe systolic blood pressure for healthy subjects is distributed\nsymmetrically, and in a later tutorial we will show that these values\napproximately follow a normal distribution. We have calculated the\nmean and standard deviation of blood pressure values in this healthy\nsubset, which allows us to set up the (95%) reference interval, for\nwhat we can consider to be _normal_ blood pressure values. Any of the\nlater patients who's values do not fall within this interval, we can\nconsider _abnormal_.\n\nThe `mean` blood pressure value of the healthy subset is 119 mmHg, with\na `standard deviation` of 14 mmHg. When we replace the population average\nand population standard deviation with these estimates, we obtain a\n`95% reference interval` of [91;147] mmHg.\n\nNote that in the literature a value 140 mmHg for the systolic blood\npressure is typically considered to be the upper limit of _normality_.\n",
    "supporting": [
      "04_1_NHANES_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}