{
  "hash": "681c9cb28d8f59652a829ecada62e0c1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercise 9.1: Non-parametric statistics on the shrimps dataset - solution\"\nauthor: \"Lieven Clement and Jeroen Gilis\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\n---\n\n# The shrimps dataset\n\nDataset on the accumulation of PCBs (Polychlorinated biphenyls)\nin the adipose tissue of shrimps. PCBs are often present in coolants, and are\nknow to accumulate easily in the adipose tissue of shrimps. In this experiment,\ntwo groups of 18 samples (each 100 grams) of shrimps each were cultivated\nin different conditions, one control condition and one condition\nwhere the medium was poluted with PCBs. Note that the PCB concentrations were\nmeasured in pg/g adipose tissue.\n\n# Goal\n\nThe research question is; is there an effect of the\ngrowth condition on the PCB concentration in the adipose\ntissue of shrimps?\n\nLoad libraries:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n# Import the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshrimps <- read_tsv(\n  \"https://raw.githubusercontent.com/statOmics/PSLSData/main/shrimps.txt\"\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 36 Columns: 2\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \"\\t\"\ndbl (2): PCB.conc, group\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(shrimps)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 36\nColumns: 2\n$ PCB.conc <dbl> 29.7, 24.5, 97.7, 39.1, 22.6, 32.4, 27.7, 100.1, 40.1, 23.3, …\n$ group    <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2…\n```\n\n\n:::\n:::\n\n\n# Data tidying\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshrimps <- shrimps |>\n  mutate(group = as.factor(group))\n```\n:::\n\n\n# Data exploration\n\nThe first step is to explore the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshrimps |>\n  count(group)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"group\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"18\"},{\"1\":\"2\",\"2\":\"18\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nVisualize the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshrimps |>\n  ggplot(aes(x = group, y = PCB.conc, fill = group)) +\n  scale_fill_manual(values = c(\"darkorchid\", \"olivedrab\")) +\n  theme_bw() +\n  geom_boxplot(outlier.shape = NA) +\n  geom_jitter(width = 0.2) +\n  ggtitle(\"Boxplot of the PCB concentrations in two groups of shrimps\") +\n  ylab(\"PCB concentration (pg/g)\") +\n  stat_summary(\n    fun = mean, geom = \"point\",\n    shape = 5, size = 3, color = \"black\",\n  )\n```\n\n::: {.cell-output-display}\n![](09_1_shrimps_sol_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nWe can see that for group 1 we have four very clear outliers\nin the data. These values were double-checked (i.e for\ntyping errors), but there was no reason found to believe\nthat these values are incorrect.\n\n# Analysis\n\nA good way for\ntesting the research hypothesis is to perform an unpaired\ntwo-sample t-test to find out whether there is a significant\ndifference in the mean PCB concentrations between both groups\nof samples. Before we can do this, we must check if all the\nrequired assumptions are met.\n\n## Assumptions\n\n1. The observations are independent of each other (in both groups)\n2. The data (PCB.conc) must be normally distributed (in both groups)\n3. The variance is equal in the two groups.\n\nThe first assumption is met, as we randomly selected shrimps and\nsubmitted them to one of two growth conditions. No underlying\ncorrelation patterns are expected.\n\nWe can check the second assumption with a QQ-plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshrimps |>\n  ggplot(aes(sample = PCB.conc)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_grid(~ group)\n```\n\n::: {.cell-output-display}\n![](09_1_shrimps_sol_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nWe clearly see that we have strong deviations from\nnormality. Many datapoints do not lie near the quantile-quantile\nline. As such, we may conclude that our data are not normally distributed.\nIn addition, the boxplots suggest that the\nvariability differs between the two groups.\n\nAs such, we are not allowed to perform the t-test.\nGiven the location of the outliers transformation will not help, so we will resort to non-parametric\ntests, i.e. to the Wilcoxon rank-sum test.\n\n## Wilcoxon rank-sum test\n\nThe Wilcoxon rank-sum test (or the Mann-Whitney U test) is an important\nnon-parametric data analysis method. In rank-based tests, the data\n$Y_i$ are first transformed to its ranked equivalent\n\\[ R_i=R(Y_i) = \\#\\{Y_j: Y_j\\leq Y_i; j=1,\\ldots, n\\}. \\]\n\nRanks are very robust to outliers. For instance, it does not\nmatter if the highest value in an hypothetical dataset has a\nvalue of 10 or 100; it will keep the same rank (highest rank).\n\nNote, that there might be ties in the data, e.g., if\ntwo samples of shrimps have an equal concentration of PCBs.\nIn this case, the Wilcoxon rank-sum test will compute\nmid-ranks, which are calculated as follows;\n\\[R(Y_i) = \\frac{\\sum\\limits_{\\forall j : Y_j=Y_i}R(Y_j)}{\\#{\\forall j:Y_j=Y_i}}  \\]\ni.e., the midrank is equal to the mean of the ranks of equal\nobservations.\n\nAfter computing the ranks and midranks, the Wilcoxon test will\ncompare the mean rank between both treatment groups:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox_res <- wilcox.test(PCB.conc ~ group, data = shrimps)\nwilcox_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  PCB.conc by group\nW = 88, p-value = 0.01871\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nWe find that the test is significant on the 5%\nsignificance level (p = 0.01871). The value W=88\ncould be calculated manually as the Mann-Withney statistic\nthat counts how many times a value from group 1 is larger or equal than values of group 2.\n\n### Interpretation\n\nThe interpretation of the Wilcoxon rank-sum test is\nslightly more challenging than that of a t-test.\nSince we are no longer interpreting differences in the distributions between the groups in terms of the average differences but in in terms of the\n*probabilistic index*.\n\nThe null hypothesis of the Wilcoxon test states that\nthe distributions\nare equal for both groups:\n\n\\[ H_0: f_1 = f_2 \\]\n\nIn words: the distribution of PCB concentrations in\nshrimps are equal for both treatment conditions.\n\nagainst the alternative hypothesis that\n\n\\[ H_1: P(Y_{1} \\geq Y_{2}) \\ne 1/2 \\]\n\nIn words: The probability that a random observation of a\nPCB concentration derived from shrimps that\nwas grown in the control condition *is larger than or equal to*\nthan a random observation of a PCB concentration\nderived from a shrimps that was grown in\nthe other condition *is not equal to 50%*.\n\nWe can estimate this probability based on the observed test statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn1 <- n2 <- 18 # 18 observations in each group\nWObs <- wilcox_res$statistic # get the observed test statistic\nWObs / (n1 * n2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        W \n0.2716049 \n```\n\n\n:::\n:::\n\n\nWe can see that the point estimate of this probability\nis 27.2%.\n\nWe can interpret it as follows;\n\nThere is a probability of 27.2% that the PCB concentration in a random\nshrimp that was grown in the control condition is\ngreater than or equal to the PCB concentration in a random\nshrimp that was grown in the treatment condition. This probability is significantly different from 50% on the 5% significance level (p = 0.01871).\n",
    "supporting": [
      "09_1_shrimps_sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}