<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lieven Clement, Jeroen Gilis and Milan Malfait">

<title>Exercise 8.6: Blocking on the rat diet dataset - solution – PSLS26 - Practical Statistics for the Life Sciences</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-f79c7fb6db380d32be398468f2fb58cf.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-af4279ef3f227b0aa017c658565fcb03.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">PSLS26 - Practical Statistics for the Life Sciences</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-topics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-easel" role="img">
</i> 
 <span class="menu-text">Topics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-topics">    
        <li>
    <a class="dropdown-item" href="./01-intro.html">
 <span class="dropdown-text">1. Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02-concepts.html">
 <span class="dropdown-text">2. Concepts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-experimentalDesign.html">
 <span class="dropdown-text">3. Experimental Design I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-dataExploration.html">
 <span class="dropdown-text">4. Data Exploration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05-statisticalInference.html">
 <span class="dropdown-text">5.1 Statistical Inference 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05-statisticalInference-twosampleT.html">
 <span class="dropdown-text">5.2 Statistical Inference 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./06-linearRegression.html">
 <span class="dropdown-text">6. Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07-Anova.html">
 <span class="dropdown-text">7. Analysis of Variance</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08-MultipleRegression.html">
 <span class="dropdown-text">8. Multiple Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08-MultipleRegression-SpecificDesigns.html">
 <span class="dropdown-text">8.2 Multiple Regression: Factorial Designs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08-experimentalDesign2.html">
 <span class="dropdown-text">8.3. Experimental Design II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08-experimentalDesign3.html">
 <span class="dropdown-text">8.4. Experimental Design III</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09-NonparametericStatistics-WilcoxonMannWithney.html">
 <span class="dropdown-text">9.1. Nonparametric Statistics 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09-NonparametericStatistics-KruskalWallis.html">
 <span class="dropdown-text">9.2. Nonparametric Statistics 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./10-categoricalDataAnalysis.html">
 <span class="dropdown-text">10. Categorical Data Analysis</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-laptop" role="img">
</i> 
 <span class="menu-text">Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-exercises">    
        <li>
    <a class="dropdown-item" href="./04_exercises.html">
 <span class="dropdown-text">4. Data Exploration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_exercises.html">
 <span class="dropdown-text">5. Statistical inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./06_exercises.html">
 <span class="dropdown-text">6. Simple linear regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./07_exercises.html">
 <span class="dropdown-text">7. ANOVA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./08_exercises.html">
 <span class="dropdown-text">8. Multiple linear regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./09_exercises.html">
 <span class="dropdown-text">9. Non-parametric statistics</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="http://statomics.github.io/"> 
<span class="menu-text">statOmics</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background"><span class="header-section-number">1</span> Background</a></li>
  <li><a href="#experimental-design" id="toc-experimental-design" class="nav-link" data-scroll-target="#experimental-design"><span class="header-section-number">2</span> Experimental design</a></li>
  <li><a href="#data-import" id="toc-data-import" class="nav-link" data-scroll-target="#data-import"><span class="header-section-number">3</span> Data import</a></li>
  <li><a href="#tidy-data" id="toc-tidy-data" class="nav-link" data-scroll-target="#tidy-data"><span class="header-section-number">4</span> Tidy data</a></li>
  <li><a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration"><span class="header-section-number">5</span> Data exploration</a></li>
  <li><a href="#multivariate-linear-regression-analysis" id="toc-multivariate-linear-regression-analysis" class="nav-link" data-scroll-target="#multivariate-linear-regression-analysis"><span class="header-section-number">6</span> Multivariate linear regression analysis</a>
  <ul class="collapse">
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">6.1</span> Assumptions</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing"><span class="header-section-number">6.2</span> Hypothesis testing</a></li>
  <li><a href="#interpretation-of-the-regression-parameters" id="toc-interpretation-of-the-regression-parameters" class="nav-link" data-scroll-target="#interpretation-of-the-regression-parameters"><span class="header-section-number">6.3</span> Interpretation of the regression parameters</a></li>
  <li><a href="#testing-the-overall-combined-effect-of-diet" id="toc-testing-the-overall-combined-effect-of-diet" class="nav-link" data-scroll-target="#testing-the-overall-combined-effect-of-diet"><span class="header-section-number">6.4</span> Testing the overall (combined) effect of diet</a></li>
  <li><a href="#assessing-the-interaction-effect-between-protein-source-and-protein-level" id="toc-assessing-the-interaction-effect-between-protein-source-and-protein-level" class="nav-link" data-scroll-target="#assessing-the-interaction-effect-between-protein-source-and-protein-level"><span class="header-section-number">6.5</span> Assessing the interaction effect between protein source and protein level</a></li>
  <li><a href="#assessing-specific-contrasts" id="toc-assessing-specific-contrasts" class="nav-link" data-scroll-target="#assessing-specific-contrasts"><span class="header-section-number">6.6</span> Assessing specific contrasts</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">7</span> Conclusion</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Exercise 8.6: Blocking on the rat diet dataset - solution</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">statOmics, Ghent University (https://statomics.github.io)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lieven Clement, Jeroen Gilis and Milan Malfait </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="background" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Background</h1>
<p>Researchers are studying the impact of protein sources and protein levels in the diet on the weight of rats. They feed the rats with diets of beef, cereal and pork and use a low and high protein level for each diet type. The researchers can include 60 rats in the experiment. Prior to the experiment, the rats were divided in 10 homogeneous groups of 6 rats based on characteristics such as initial weight, appetite, etc.</p>
<p>Within each group a rat is randomly assigned to a diet. The rats are fed during a month and the weight gain in grams is recorded for each rat.</p>
</section>
<section id="experimental-design" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Experimental design</h1>
<ul>
<li><p>There are three explanatory variables in the experiment: the factor diet type with three levels (beef, cereal and pork), factor protein level with levels (low and high) and a group blocking factor with 10 levels.</p></li>
<li><p>There are 6 treatments: beef-high, cereal-high, pork-high, beef-low, cereal-low, pork-low protein.</p></li>
<li><p>The rats are the experimental and observational units.</p></li>
<li><p>The weight gain is the response variable.</p></li>
<li><p>The experiment is a randomized complete block (RCB) design</p></li>
</ul>
<p>Load libraries</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="data-import" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data import</h1>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>diet <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"https://raw.githubusercontent.com/statOmics/PSLSData/main/dietRats.txt"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">header =</span> <span class="cn">TRUE</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diet)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["weightGain"],"name":[1],"type":["int"],"align":["right"]},{"label":["protSource"],"name":[2],"type":["chr"],"align":["left"]},{"label":["protLevel"],"name":[3],"type":["chr"],"align":["left"]},{"label":["block"],"name":[4],"type":["int"],"align":["right"]}],"data":[{"1":"107","2":"b","3":"h","4":"1","_rn_":"1"},{"1":"96","2":"c","3":"h","4":"1","_rn_":"2"},{"1":"112","2":"p","3":"h","4":"1","_rn_":"3"},{"1":"83","2":"b","3":"l","4":"1","_rn_":"4"},{"1":"87","2":"c","3":"l","4":"1","_rn_":"5"},{"1":"90","2":"p","3":"l","4":"1","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</section>
<section id="tidy-data" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Tidy data</h1>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>diet <span class="ot">&lt;-</span> diet <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Convert categorical levels to factors</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">block =</span> <span class="fu">as.factor</span>(block),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">protSource =</span> <span class="fu">as.factor</span>(protSource),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">protLevel =</span> <span class="fu">as.factor</span>(protLevel)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Recode factors to make them more verbose</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">protLevel =</span> <span class="fu">fct_recode</span>(protLevel, <span class="at">high =</span> <span class="st">"h"</span>, <span class="at">low =</span> <span class="st">"l"</span>),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">protSource =</span> <span class="fu">fct_recode</span>(protSource, <span class="at">beef =</span> <span class="st">"b"</span>, <span class="at">cereal =</span> <span class="st">"c"</span>, <span class="at">pork =</span> <span class="st">"p"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Set "low" as the reference level for `protLevel`</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">protLevel =</span> <span class="fu">fct_relevel</span>(protLevel, <span class="st">"low"</span>))</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diet)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["weightGain"],"name":[1],"type":["int"],"align":["right"]},{"label":["protSource"],"name":[2],"type":["fct"],"align":["left"]},{"label":["protLevel"],"name":[3],"type":["fct"],"align":["left"]},{"label":["block"],"name":[4],"type":["fct"],"align":["left"]}],"data":[{"1":"107","2":"beef","3":"high","4":"1","_rn_":"1"},{"1":"96","2":"cereal","3":"high","4":"1","_rn_":"2"},{"1":"112","2":"pork","3":"high","4":"1","_rn_":"3"},{"1":"83","2":"beef","3":"low","4":"1","_rn_":"4"},{"1":"87","2":"cereal","3":"low","4":"1","_rn_":"5"},{"1":"90","2":"pork","3":"low","4":"1","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</section>
<section id="data-exploration" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Data exploration</h1>
<ul>
<li>Boxplot of the weight gain against protein source, protein level with coloring according to block</li>
</ul>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>diet <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> protLevel, <span class="at">y =</span> weightGain)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"RdGy"</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">color =</span> block)) <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Weight gain dependence on protein source"</span>) <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Protein level"</span>, <span class="at">y =</span> <span class="st">"Weight gain (g)"</span>) <span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> mean, <span class="at">geom=</span><span class="st">"point"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">shape=</span><span class="dv">5</span>, <span class="at">size=</span><span class="dv">3</span>, <span class="at">color=</span><span class="st">"black"</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(protSource))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Lineplot of the weight gain against protein source, protein level with coloring and grouping according to block</li>
</ul>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>diet <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> protLevel, <span class="at">y =</span> weightGain, <span class="at">color =</span> block)) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"RdGy"</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> block)) <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Weight gain dependence on protein source"</span>) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Weight gain (g)"</span>) <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(protSource))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>An increase in the weight of the rats seems to depend on the protein source received in the diet.</p></li>
<li><p>The increase in the weight of the rats seems to depend on the level of protein received in the diet</p></li>
<li><p>There also seems to be an interaction effect between the protein level and the protein source on the gain in weight of the rats. For the beef and the pork diets the effect of high protein levels in the data seems to be much stronger than in the cereal diet.</p></li>
<li><p>There is also a strong effect of the block. Blocking implies a randomisation restriction, hence, we will have to include the block effect anyway.</p></li>
</ul>
</section>
<section id="multivariate-linear-regression-analysis" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Multivariate linear regression analysis</h1>
<section id="assumptions" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="assumptions"><span class="header-section-number">6.1</span> Assumptions</h2>
<p>List assumptions:</p>
<ol type="1">
<li>The observations are independent</li>
<li>Linearity between the response and predictor variable</li>
<li>The residuals of the model must be normally distributed</li>
<li>Homoscedasticity of the data</li>
</ol>
<p>The first assumption is met if we correct for block in the model because the rats were randomized to the treatment within block. The other three assumptions can be assessed by fitting the linear model and calling the <code>plot()</code> function as follows.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(weightGain <span class="sc">~</span> block <span class="sc">+</span> protSource <span class="sc">*</span> protLevel, <span class="at">data =</span> diet)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-6-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-6-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>All assumptions are met for this dataset.</p>
</section>
<section id="hypothesis-testing" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="hypothesis-testing"><span class="header-section-number">6.2</span> Hypothesis testing</h2>
<p>We here fit a linear model with a blocking factor for <code>block</code> and main and interaction effects for protein source and protein level.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weightGain ~ block + protSource * protLevel, data = diet)

Residuals:
    Min      1Q  Median      3Q     Max 
-21.017  -5.183  -1.017   4.092  18.983 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     88.3500     4.1728  21.173  &lt; 2e-16 ***
block2                          -9.1667     4.8183  -1.902 0.063520 .  
block3                          -4.8333     4.8183  -1.003 0.321166    
block4                         -20.3333     4.8183  -4.220 0.000117 ***
block5                          -9.3333     4.8183  -1.937 0.059031 .  
block6                           0.6667     4.8183   0.138 0.890572    
block7                         -31.3333     4.8183  -6.503 5.58e-08 ***
block8                         -10.1667     4.8183  -2.110 0.040450 *  
block9                         -19.8333     4.8183  -4.116 0.000162 ***
block10                         -0.1667     4.8183  -0.035 0.972559    
protSourcecereal                 1.1000     3.7322   0.295 0.769556    
protSourcepork                   1.3000     3.7322   0.348 0.729226    
protLevelhigh                   20.0000     3.7322   5.359 2.76e-06 ***
protSourcecereal:protLevelhigh -18.2000     5.2782  -3.448 0.001236 ** 
protSourcepork:protLevelhigh    -1.7000     5.2782  -0.322 0.748883    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.346 on 45 degrees of freedom
Multiple R-squared:  0.7712,    Adjusted R-squared:    0.7 
F-statistic: 10.83 on 14 and 45 DF,  p-value: 3.726e-10</code></pre>
</div>
</div>
</section>
<section id="interpretation-of-the-regression-parameters" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="interpretation-of-the-regression-parameters"><span class="header-section-number">6.3</span> Interpretation of the regression parameters</h2>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ExploreModelMatrix)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>ExploreModelMatrix<span class="sc">::</span><span class="fu">VisualizeDesign</span>(diet, <span class="sc">~</span> block <span class="sc">+</span> protSource <span class="sc">*</span> protLevel)<span class="sc">$</span>plotlist</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$`block = 1`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$`block = 10`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$`block = 2`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$`block = 3`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-8-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$`block = 4`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-8-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$`block = 5`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-8-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$`block = 6`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-8-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$`block = 7`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-8-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$`block = 8`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-8-9.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$`block = 9`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08_6_rats_sol_files/figure-html/unnamed-chunk-8-10.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are 3 levels for protein source, 2 levels for protein level and 10 levels for the blocking variable. We will have one reference level for each respective variable: beef, low, block 1. So we need 2, 1 and 9 dummy variables to introduce the factors protein source, protein level and block in the linear model, respectively.</p>
<p>Hence, we can write down the linear model as follows:</p>
<p><span class="math inline">\(y_i=\beta_0+\beta_cx_{i,c} +\beta_px_{i,p}+\beta_hx_{i,h}+\beta_{ch}x_{i,c}x_{i,h}+\beta_{ph}x_{i,p}x_{i,h}+\beta_{b2}x_{i,b2}+\ldots+\beta_{b10}x_{i,b10}+\epsilon_{i}\)</span></p>
<p>with: <span class="math inline">\(y_i\)</span> the observed weight gain for rat i, <span class="math inline">\(x_{i,h}\)</span> a dummy variable which is 1 if rat i receives a high protein diet and is 0 otherwise, <span class="math inline">\(x_{i,c}\)</span> a dummy variable which is 1 if rat i receives a cereal diet and is 0 otherwise, <span class="math inline">\(x_{i,p}\)</span> a dummy variable which is 1 if rat i receives a pork diet and is 0 otherwise and <span class="math inline">\(x_{i,bk}\)</span> is a dummy variable which is 1 if rat i belongs to block <span class="math inline">\(bk\)</span> and is 0 otherwise, with <span class="math inline">\(k \in 2,\ldots, 10\)</span>, and <span class="math inline">\(\epsilon_i\)</span> an error term which is normally distributed with mean 0 and variance <span class="math inline">\(\sigma^2\)</span>, i.e.&nbsp;<span class="math inline">\(\epsilon_i \sim N(0,\sigma^2)\)</span>.</p>
<ul>
<li><p>Rats that are assigned to block <span class="math inline">\(k\)</span> and receive a beef based low protein diet have a covariate pattern <span class="math inline">\(x_{i,h}=0\)</span>, <span class="math inline">\(x_{i,c}=0\)</span>, <span class="math inline">\(x_{i,p}=0\)</span>, <span class="math inline">\(x_{i,bm}=0\)</span> with <span class="math inline">\(m\neq k\)</span> and <span class="math inline">\(x_{i,bk}=1\)</span>. Their mean weight gain is thus equal to <span class="math inline">\(\mu_{l,b,bk}=\beta_0+\beta_{bk}\)</span></p></li>
<li><p>Rats that are assigned to block <span class="math inline">\(k\)</span> and receive a beef based high protein diet have a covariate pattern <span class="math inline">\(x_{i,h}=1\)</span>, <span class="math inline">\(x_{i,c}=0\)</span>, <span class="math inline">\(x_{i,p}=0\)</span>, <span class="math inline">\(x_{i,bm}=0\)</span> with <span class="math inline">\(m\neq k\)</span> and <span class="math inline">\(x_{i,bk}=1\)</span>. Their mean weight gain is thus equal to <span class="math inline">\(\mu_{h,b,bk}=\beta_0+\beta_h+\beta_{bk}\)</span></p></li>
<li><p>Rats that are assigned to block <span class="math inline">\(k\)</span> and receive a cereal based low protein diet have a covariate pattern <span class="math inline">\(x_{i,h}=0\)</span>, <span class="math inline">\(x_{i,c}=1\)</span>, <span class="math inline">\(x_{i,p}=0\)</span>, <span class="math inline">\(x_{i,bm}=0\)</span> with <span class="math inline">\(m\neq k\)</span> and <span class="math inline">\(x_{i,bk}=1\)</span>. Their mean weight gain is thus equal to <span class="math inline">\(\mu_{h,c,bk}=\beta_0+\beta_c+\beta_{bk}\)</span></p></li>
<li><p>Rats that are assigned to block <span class="math inline">\(k\)</span> and receive a cereal based heigh protein diet have a covariate pattern <span class="math inline">\(x_{i,h}=1\)</span>, <span class="math inline">\(x_{i,c}=1\)</span>, <span class="math inline">\(x_{i,p}=0\)</span>, <span class="math inline">\(x_{i,bm}=0\)</span> with <span class="math inline">\(m\neq k\)</span> and <span class="math inline">\(x_{i,bk}=1\)</span>. Their mean weight gain is thus equal to <span class="math inline">\(\mu_{h,c,bk}=\beta_0+\beta_h+\beta_c+\beta_{ch}+\beta_{bk}\)</span></p></li>
<li><p>Rats that are assigned to block <span class="math inline">\(k\)</span> and receive a pork based low protein diet have a covariate pattern <span class="math inline">\(x_{i,h}=0\)</span>, <span class="math inline">\(x_{i,c}=0\)</span>, <span class="math inline">\(x_{i,p}=1\)</span>, <span class="math inline">\(x_{i,bm}=0\)</span> with <span class="math inline">\(m\neq k\)</span> and <span class="math inline">\(x_{i,bk}=1\)</span>. Their mean weight gain is thus equal to <span class="math inline">\(\mu_{l,p,bk}=\beta_0+\beta_p+\beta_{bk}\)</span></p></li>
<li><p>Rats that are assigned to block <span class="math inline">\(k\)</span> and receive a pork based heigh protein diet have a covariate pattern <span class="math inline">\(x_{i,h}=1\)</span>, <span class="math inline">\(x_{i,c}=0\)</span>, <span class="math inline">\(x_{i,p}=1\)</span>, <span class="math inline">\(x_{i,bm}=0\)</span> with <span class="math inline">\(m\neq k\)</span> and <span class="math inline">\(x_{i,bk}=1\)</span>. There mean weight gain is thus equal to <span class="math inline">\(\mu_{h,p,bk}=\beta_0+\beta_h+\beta_p+\beta_{ph}+\beta_{bk}\)</span></p></li>
</ul>
<p>We can now relate this to the output of the <code>lm</code> function:</p>
<ul>
<li><p>The intercept <span class="math inline">\(\beta_0\)</span> is thus the average weight increase in the low beef diet for rats in block 1.</p></li>
<li><p>The parameter <span class="math inline">\(\beta_c\)</span>: the average difference in weight gain between cereal-low and beef-low diet is 1.1g.</p></li>
<li><p>The parameter <span class="math inline">\(\beta_p\)</span>: the average difference in weight gain between pork-low and beef-low diet is 1.3g.</p></li>
<li><p>The parameter <span class="math inline">\(\beta_h\)</span>: the average difference in weight gain between beef-high and beef-Low diet is 20g.</p></li>
<li><p>The parameter <span class="math inline">\(\beta_{ch}\)</span> is the difference in the average weight gain difference due to the high protein level as compared to the low protein level for cereal diets as compared to the weight gain difference that occurs due to the protein level in the reference class (here beef diet). Here this is negative, i.e.&nbsp;-18.2g, thus the weight gain for the cereal protein source increases on average less between high and low protein diets than in beef based diets.</p></li>
<li><p>The parameter <span class="math inline">\(\beta_{ph}\)</span> is the difference in the average weight gain difference due to the high protein level as compared to the low protein level for pork diets as compared to the weight gain difference that occurs due to the protein level in the reference class (here beef diet). Here this is negative, i.e.&nbsp;-1.7g, thus the weight gain for the proc protein source increases on average less between high and low protein diets than in beef based diets.</p></li>
</ul>
</section>
<section id="testing-the-overall-combined-effect-of-diet" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="testing-the-overall-combined-effect-of-diet"><span class="header-section-number">6.4</span> Testing the overall (combined) effect of diet</h2>
<p>Because there are multiple factors with different levels in the model, we can first assess the effect of the diet (protein Level, protein source and the interaction) by using anova. With this test we will assess the null hypothesis that the average weight gain in each treatment is equal: i.e.&nbsp;<span class="math inline">\(H_0: \mu_{b,l}=\mu_{b,h}=\mu_{c,h}=\mu_{c,l}=\mu_{p,h}=\mu_{p,h}\)</span> versus the alternative hyptohesis <span class="math inline">\(H_1:\)</span> that at least two treatment means are different.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>lm0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(weightGain <span class="sc">~</span> block, <span class="at">data =</span> diet)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lm0, lm1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Res.Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["RSS"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Sum of Sq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["F"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"50","2":"7728.833","3":"NA","4":"NA","5":"NA","6":"NA","_rn_":"1"},{"1":"45","2":"3134.150","3":"5","4":"4594.683","5":"13.19406","6":"6.308133e-08","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>We can conclude that there is an extremely significant effect of the diet type (protein source and/or protein level and/or protein source-protein level interaction) on the weight gain of rats (p &lt;&lt; 0.001).</p>
</section>
<section id="assessing-the-interaction-effect-between-protein-source-and-protein-level" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="assessing-the-interaction-effect-between-protein-source-and-protein-level"><span class="header-section-number">6.5</span> Assessing the interaction effect between protein source and protein level</h2>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(lm1, <span class="at">type =</span> <span class="st">"III"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Sum Sq"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"31222.890","2":"1","3":"448.297002","4":"4.955763e-25","_rn_":"(Intercept)"},{"1":"5969.350","2":"9","3":"9.523076","4":"6.083601e-08","_rn_":"block"},{"1":"9.800","2":"2","3":"0.070354","4":"9.321661e-01","_rn_":"protSource"},{"1":"2000.000","2":"1","3":"28.715920","4":"2.762595e-06","_rn_":"protLevel"},{"1":"1010.633","2":"2","3":"7.255316","4":"1.857393e-03","_rn_":"protSource:protLevel"},{"1":"3134.150","2":"45","3":"NA","4":"NA","_rn_":"Residuals"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>There is a very significant interaction between the protein source and the protein level (p = 2e-03). This indicates that the average weight increase due to the protein level differs according to the protein source. Hence, we cannot assess the effect of the protein source and/or protein level independently because there effects of the protein source vary according to the protein level.</p>
</section>
<section id="assessing-specific-contrasts" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="assessing-specific-contrasts"><span class="header-section-number">6.6</span> Assessing specific contrasts</h2>
<p>Imagine that we are interested in assessing if there is an effect of</p>
<ol type="1">
<li>protein source in the low protein diets
<ul>
<li><span class="math inline">\(\mu_{c,l}-\mu_{b,l} = \beta_c\)</span></li>
<li><span class="math inline">\(\mu_{p,l}-\mu_{b,l} = \beta_p\)</span></li>
<li><span class="math inline">\(\mu_{c,l}-\mu_{p,l}= \beta_c-\beta_p\)</span>)</li>
</ul></li>
<li>protein source in high protein diets
<ul>
<li><span class="math inline">\(\mu_{c,h}-\mu_{b,h}=\beta_c+\beta_{ch}\)</span></li>
<li><span class="math inline">\(\mu_{p,h}-\mu_{b,h}=\beta_p+\beta_{ph}\)</span></li>
<li><span class="math inline">\(\mu_{p,h}-\mu_{c,h}=(\beta_c+\beta_{ch})-(\beta_p+\beta_{ph})\)</span></li>
</ul></li>
<li>protein level for
<ul>
<li>beef diets (<span class="math inline">\(\mu_{b,h}-\mu_{b,l}=\beta_h\)</span>),</li>
<li>cereal diets (<span class="math inline">\(\mu_{c,h}-\mu_{c,l}=\beta_h+\beta_{ch}\)</span>) and</li>
<li>pork diets (<span class="math inline">\(\mu_{p,h}-\mu_{p,l}=\beta_h+\beta_{ph}\)</span>).</li>
</ul></li>
<li>If the effect of the protein level differs between
<ul>
<li>beef and cereal <span class="math inline">\((\mu_{c,h}-\mu_{c,l}) - (\mu_{b,h}-\mu_{b,l})=\beta_{ch}\)</span></li>
<li>beef and pork <span class="math inline">\((\mu_{p,h}-\mu_{p,l}) - (\mu_{c,h}-\mu_{c,l})=\beta_{ph}\)</span> and</li>
<li>cereal and pork diets <span class="math inline">\((\mu_{c,h}-\mu_{c,l}) - (\mu_{p,h}-\mu_{p,l})=\beta_{ch}-\beta_{ph}\)</span>.</li>
</ul></li>
</ol>
<p>These effects of interest are so-called <strong>contrasts, i.e.&nbsp;linear combinations of the parameters</strong>.</p>
<p>We can define the contrasts and assess the significance of the contrasts with the code below. The contrasts are given as input in the form of symbolic descriptions to the <code>linfct</code> argument of the <code>glht</code> function.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">75468</span>) <span class="co"># to get reproducible results (small effect if removed)</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>lm1MultComp <span class="ot">&lt;-</span> <span class="fu">glht</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> lm1,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">linfct =</span> <span class="fu">c</span>(</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcecereal = 0"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcepork = 0"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcecereal- protSourcepork = 0"</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcecereal + protSourcecereal:protLevelhigh = 0"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcepork + protSourcepork:protLevelhigh = 0"</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) = 0"</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protLevelhigh = 0"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protLevelhigh +  protSourcecereal:protLevelhigh = 0"</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protLevelhigh +  protSourcepork:protLevelhigh = 0"</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcecereal:protLevelhigh = 0"</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcepork:protLevelhigh = 0"</span>,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh = 0"</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1MultComp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Fit: lm(formula = weightGain ~ block + protSource * protLevel, data = diet)

Linear Hypotheses:
                                                                                                           Estimate
protSourcecereal == 0                                                                                         1.100
protSourcepork == 0                                                                                           1.300
protSourcecereal - protSourcepork == 0                                                                       -0.200
protSourcecereal + protSourcecereal:protLevelhigh == 0                                                      -17.100
protSourcepork + protSourcepork:protLevelhigh == 0                                                           -0.400
(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0  -16.700
protLevelhigh == 0                                                                                           20.000
protLevelhigh + protSourcecereal:protLevelhigh == 0                                                           1.800
protLevelhigh + protSourcepork:protLevelhigh == 0                                                            18.300
protSourcecereal:protLevelhigh == 0                                                                         -18.200
protSourcepork:protLevelhigh == 0                                                                            -1.700
protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                          -16.500
                                                                                                           Std. Error
protSourcecereal == 0                                                                                           3.732
protSourcepork == 0                                                                                             3.732
protSourcecereal - protSourcepork == 0                                                                          3.732
protSourcecereal + protSourcecereal:protLevelhigh == 0                                                          3.732
protSourcepork + protSourcepork:protLevelhigh == 0                                                              3.732
(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0      3.732
protLevelhigh == 0                                                                                              3.732
protLevelhigh + protSourcecereal:protLevelhigh == 0                                                             3.732
protLevelhigh + protSourcepork:protLevelhigh == 0                                                               3.732
protSourcecereal:protLevelhigh == 0                                                                             5.278
protSourcepork:protLevelhigh == 0                                                                               5.278
protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                              5.278
                                                                                                           t value
protSourcecereal == 0                                                                                        0.295
protSourcepork == 0                                                                                          0.348
protSourcecereal - protSourcepork == 0                                                                      -0.054
protSourcecereal + protSourcecereal:protLevelhigh == 0                                                      -4.582
protSourcepork + protSourcepork:protLevelhigh == 0                                                          -0.107
(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0  -4.475
protLevelhigh == 0                                                                                           5.359
protLevelhigh + protSourcecereal:protLevelhigh == 0                                                          0.482
protLevelhigh + protSourcepork:protLevelhigh == 0                                                            4.903
protSourcecereal:protLevelhigh == 0                                                                         -3.448
protSourcepork:protLevelhigh == 0                                                                           -0.322
protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                          -3.126
                                                                                                           Pr(&gt;|t|)
protSourcecereal == 0                                                                                        0.9995
protSourcepork == 0                                                                                          0.9989
protSourcecereal - protSourcepork == 0                                                                       1.0000
protSourcecereal + protSourcecereal:protLevelhigh == 0                                                       &lt;0.001
protSourcepork + protSourcepork:protLevelhigh == 0                                                           1.0000
(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0   &lt;0.001
protLevelhigh == 0                                                                                           &lt;0.001
protLevelhigh + protSourcecereal:protLevelhigh == 0                                                          0.9949
protLevelhigh + protSourcepork:protLevelhigh == 0                                                            &lt;0.001
protSourcecereal:protLevelhigh == 0                                                                          0.0118
protSourcepork:protLevelhigh == 0                                                                            0.9993
protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                           0.0265
                                                                                                              
protSourcecereal == 0                                                                                         
protSourcepork == 0                                                                                           
protSourcecereal - protSourcepork == 0                                                                        
protSourcecereal + protSourcecereal:protLevelhigh == 0                                                     ***
protSourcepork + protSourcepork:protLevelhigh == 0                                                            
(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0 ***
protLevelhigh == 0                                                                                         ***
protLevelhigh + protSourcecereal:protLevelhigh == 0                                                           
protLevelhigh + protSourcepork:protLevelhigh == 0                                                          ***
protSourcecereal:protLevelhigh == 0                                                                        *  
protSourcepork:protLevelhigh == 0                                                                             
protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                         *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lm1MultComp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Confidence Intervals

Fit: lm(formula = weightGain ~ block + protSource * protLevel, data = diet)

Quantile = 2.8765
95% family-wise confidence level
 

Linear Hypotheses:
                                                                                                           Estimate
protSourcecereal == 0                                                                                        1.1000
protSourcepork == 0                                                                                          1.3000
protSourcecereal - protSourcepork == 0                                                                      -0.2000
protSourcecereal + protSourcecereal:protLevelhigh == 0                                                     -17.1000
protSourcepork + protSourcepork:protLevelhigh == 0                                                          -0.4000
(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0 -16.7000
protLevelhigh == 0                                                                                          20.0000
protLevelhigh + protSourcecereal:protLevelhigh == 0                                                          1.8000
protLevelhigh + protSourcepork:protLevelhigh == 0                                                           18.3000
protSourcecereal:protLevelhigh == 0                                                                        -18.2000
protSourcepork:protLevelhigh == 0                                                                           -1.7000
protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                         -16.5000
                                                                                                           lwr     
protSourcecereal == 0                                                                                       -9.6358
protSourcepork == 0                                                                                         -9.4358
protSourcecereal - protSourcepork == 0                                                                     -10.9358
protSourcecereal + protSourcecereal:protLevelhigh == 0                                                     -27.8358
protSourcepork + protSourcepork:protLevelhigh == 0                                                         -11.1358
(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0 -27.4358
protLevelhigh == 0                                                                                           9.2642
protLevelhigh + protSourcecereal:protLevelhigh == 0                                                         -8.9358
protLevelhigh + protSourcepork:protLevelhigh == 0                                                            7.5642
protSourcecereal:protLevelhigh == 0                                                                        -33.3827
protSourcepork:protLevelhigh == 0                                                                          -16.8827
protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                         -31.6827
                                                                                                           upr     
protSourcecereal == 0                                                                                       11.8358
protSourcepork == 0                                                                                         12.0358
protSourcecereal - protSourcepork == 0                                                                      10.5358
protSourcecereal + protSourcecereal:protLevelhigh == 0                                                      -6.3642
protSourcepork + protSourcepork:protLevelhigh == 0                                                          10.3358
(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) == 0  -5.9642
protLevelhigh == 0                                                                                          30.7358
protLevelhigh + protSourcecereal:protLevelhigh == 0                                                         12.5358
protLevelhigh + protSourcepork:protLevelhigh == 0                                                           29.0358
protSourcecereal:protLevelhigh == 0                                                                         -3.0173
protSourcepork:protLevelhigh == 0                                                                           13.4827
protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh == 0                                          -1.3173</code></pre>
</div>
</div>
<p>Note that the p-values and the confidence intervals are automatically corrected for multiple testing.</p>
</section>
</section>
<section id="conclusion" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusion</h1>
<ul>
<li><p>There is an extremely significant effect of the type of protein diet on the weight gain of rats (p&lt;&lt;1e-6). The interaction between protein type and protein source is also very significant (p=0.0019).</p></li>
<li><p>The average weight gain does not vary significantly according to protein source in the diets with low protein levels (all p&gt;0.99).</p></li>
<li><p>The weight gain in the cereal diet at high protein concentration is on average 17.1g and 16.7g g lower than in the high protein beef and pork diet, respectively (95% CI [6.4, 27.8] and [6, 27.4]) and the differences are extremely significant (p&lt;0.001). The average weight gains after meat based diets at high protein levels, however, do not differ significantly (p&gt;0.99).</p></li>
<li><p>We also discovered an extremely significant difference in weight gain according to the protein level for beef and pork based diets (p&lt;0.001). The weight gain on average increases with 20g and 18.3g in the high protein level as compared to the low protein beef and pork diet, respectively (95%CI [9.3, 30.7] and [7.6, 29]). The protein level effect is not significant for the cereal diet (p&gt;0.99).</p></li>
<li><p>Finally significant interactions between protein level and protein source were found (p&lt;0.05), i.e.&nbsp;the increase in weight gain due to protein level in cereal based diets was 18.2g and 16.5g lower than that of beef and pork based diets, respectively (95% CI [3g,33.4g] and [1.3g,31.7g]). The average difference in increase in weight gain due to protein level among the meat based diets was not significant (p&gt;0.99).</p></li>
</ul>
<p>All reported p-values and confidence intervals were corrected for multiple testing</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Exercise 8.6: Blocking on the rat diet dataset - solution"</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Lieven Clement, Jeroen Gilis and Milan Malfait"</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "statOmics, Ghent University (https://statomics.github.io)"</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu"># Background</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>Researchers are studying the impact of protein sources and protein levels in</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>the diet on the weight of rats. They feed the rats with diets of beef, cereal</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>and pork and use a low and high protein level for each diet type.</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>The researchers can include 60 rats in the experiment. Prior to the experiment,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>the rats were divided in 10 homogeneous groups of 6 rats based on</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>characteristics such as initial weight, appetite, etc.</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>Within each group a rat is randomly assigned to a diet. The rats are fed during</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>a month and the weight gain in grams is recorded for each rat.</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="fu"># Experimental design</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>There are three explanatory variables in the experiment: the factor diet type</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>with three levels (beef, cereal and pork), factor protein level with levels</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>(low and high) and a group blocking factor with 10 levels.</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>There are 6 treatments: beef-high, cereal-high, pork-high, beef-low,</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>cereal-low, pork-low protein.</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The rats are the experimental and observational units.</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The weight gain is the response variable.</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The experiment is a randomized complete block (RCB) design</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>Load libraries</span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, message=FALSE, warning=FALSE}</span></span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-39"><a href="#cb27-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-40"><a href="#cb27-40" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data import</span></span>
<span id="cb27-41"><a href="#cb27-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-44"><a href="#cb27-44" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb27-45"><a href="#cb27-45" aria-hidden="true" tabindex="-1"></a>diet <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"https://raw.githubusercontent.com/statOmics/PSLSData/main/dietRats.txt"</span>,</span>
<span id="cb27-46"><a href="#cb27-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">header =</span> <span class="cn">TRUE</span></span>
<span id="cb27-47"><a href="#cb27-47" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-48"><a href="#cb27-48" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diet)</span>
<span id="cb27-49"><a href="#cb27-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-50"><a href="#cb27-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-51"><a href="#cb27-51" aria-hidden="true" tabindex="-1"></a><span class="fu"># Tidy data</span></span>
<span id="cb27-52"><a href="#cb27-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-55"><a href="#cb27-55" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb27-56"><a href="#cb27-56" aria-hidden="true" tabindex="-1"></a>diet <span class="ot">&lt;-</span> diet <span class="sc">|&gt;</span></span>
<span id="cb27-57"><a href="#cb27-57" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Convert categorical levels to factors</span></span>
<span id="cb27-58"><a href="#cb27-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-59"><a href="#cb27-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">block =</span> <span class="fu">as.factor</span>(block),</span>
<span id="cb27-60"><a href="#cb27-60" aria-hidden="true" tabindex="-1"></a>    <span class="at">protSource =</span> <span class="fu">as.factor</span>(protSource),</span>
<span id="cb27-61"><a href="#cb27-61" aria-hidden="true" tabindex="-1"></a>    <span class="at">protLevel =</span> <span class="fu">as.factor</span>(protLevel)</span>
<span id="cb27-62"><a href="#cb27-62" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb27-63"><a href="#cb27-63" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Recode factors to make them more verbose</span></span>
<span id="cb27-64"><a href="#cb27-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-65"><a href="#cb27-65" aria-hidden="true" tabindex="-1"></a>    <span class="at">protLevel =</span> <span class="fu">fct_recode</span>(protLevel, <span class="at">high =</span> <span class="st">"h"</span>, <span class="at">low =</span> <span class="st">"l"</span>),</span>
<span id="cb27-66"><a href="#cb27-66" aria-hidden="true" tabindex="-1"></a>    <span class="at">protSource =</span> <span class="fu">fct_recode</span>(protSource, <span class="at">beef =</span> <span class="st">"b"</span>, <span class="at">cereal =</span> <span class="st">"c"</span>, <span class="at">pork =</span> <span class="st">"p"</span>)</span>
<span id="cb27-67"><a href="#cb27-67" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb27-68"><a href="#cb27-68" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Set "low" as the reference level for `protLevel`</span></span>
<span id="cb27-69"><a href="#cb27-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">protLevel =</span> <span class="fu">fct_relevel</span>(protLevel, <span class="st">"low"</span>))</span>
<span id="cb27-70"><a href="#cb27-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-71"><a href="#cb27-71" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diet)</span>
<span id="cb27-72"><a href="#cb27-72" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-73"><a href="#cb27-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-74"><a href="#cb27-74" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data exploration</span></span>
<span id="cb27-75"><a href="#cb27-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-76"><a href="#cb27-76" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Boxplot of the weight gain against protein source, protein level with coloring according to block</span>
<span id="cb27-77"><a href="#cb27-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-80"><a href="#cb27-80" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb27-81"><a href="#cb27-81" aria-hidden="true" tabindex="-1"></a>diet <span class="sc">|&gt;</span></span>
<span id="cb27-82"><a href="#cb27-82" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> protLevel, <span class="at">y =</span> weightGain)) <span class="sc">+</span></span>
<span id="cb27-83"><a href="#cb27-83" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"RdGy"</span>) <span class="sc">+</span></span>
<span id="cb27-84"><a href="#cb27-84" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb27-85"><a href="#cb27-85" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb27-86"><a href="#cb27-86" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">color =</span> block)) <span class="sc">+</span></span>
<span id="cb27-87"><a href="#cb27-87" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Weight gain dependence on protein source"</span>) <span class="sc">+</span></span>
<span id="cb27-88"><a href="#cb27-88" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Protein level"</span>, <span class="at">y =</span> <span class="st">"Weight gain (g)"</span>) <span class="sc">+</span></span>
<span id="cb27-89"><a href="#cb27-89" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(</span>
<span id="cb27-90"><a href="#cb27-90" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> mean, <span class="at">geom=</span><span class="st">"point"</span>,</span>
<span id="cb27-91"><a href="#cb27-91" aria-hidden="true" tabindex="-1"></a>    <span class="at">shape=</span><span class="dv">5</span>, <span class="at">size=</span><span class="dv">3</span>, <span class="at">color=</span><span class="st">"black"</span></span>
<span id="cb27-92"><a href="#cb27-92" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb27-93"><a href="#cb27-93" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(protSource))</span>
<span id="cb27-94"><a href="#cb27-94" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-95"><a href="#cb27-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-96"><a href="#cb27-96" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Lineplot of the weight gain against protein source, protein level with coloring and grouping according to block</span>
<span id="cb27-97"><a href="#cb27-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-100"><a href="#cb27-100" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb27-101"><a href="#cb27-101" aria-hidden="true" tabindex="-1"></a>diet <span class="sc">|&gt;</span></span>
<span id="cb27-102"><a href="#cb27-102" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> protLevel, <span class="at">y =</span> weightGain, <span class="at">color =</span> block)) <span class="sc">+</span></span>
<span id="cb27-103"><a href="#cb27-103" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"RdGy"</span>) <span class="sc">+</span></span>
<span id="cb27-104"><a href="#cb27-104" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb27-105"><a href="#cb27-105" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> block)) <span class="sc">+</span></span>
<span id="cb27-106"><a href="#cb27-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-107"><a href="#cb27-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Weight gain dependence on protein source"</span>) <span class="sc">+</span></span>
<span id="cb27-108"><a href="#cb27-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Weight gain (g)"</span>) <span class="sc">+</span></span>
<span id="cb27-109"><a href="#cb27-109" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(protSource))</span>
<span id="cb27-110"><a href="#cb27-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-111"><a href="#cb27-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-112"><a href="#cb27-112" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>An increase in the weight of the rats seems to depend on the protein source</span>
<span id="cb27-113"><a href="#cb27-113" aria-hidden="true" tabindex="-1"></a>received in the diet.</span>
<span id="cb27-114"><a href="#cb27-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-115"><a href="#cb27-115" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The increase in the weight of the rats seems to depend on the level of protein</span>
<span id="cb27-116"><a href="#cb27-116" aria-hidden="true" tabindex="-1"></a>received in the diet</span>
<span id="cb27-117"><a href="#cb27-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-118"><a href="#cb27-118" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>There also seems to be an interaction effect between the protein level and the</span>
<span id="cb27-119"><a href="#cb27-119" aria-hidden="true" tabindex="-1"></a>protein source on the gain in weight of the rats. For the beef and the pork</span>
<span id="cb27-120"><a href="#cb27-120" aria-hidden="true" tabindex="-1"></a>diets the effect of high protein levels in the data seems to be much stronger</span>
<span id="cb27-121"><a href="#cb27-121" aria-hidden="true" tabindex="-1"></a>than in the cereal diet.</span>
<span id="cb27-122"><a href="#cb27-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-123"><a href="#cb27-123" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>There is also a strong effect of the block. Blocking implies a randomisation</span>
<span id="cb27-124"><a href="#cb27-124" aria-hidden="true" tabindex="-1"></a>restriction, hence, we will have to include the block effect anyway.</span>
<span id="cb27-125"><a href="#cb27-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-126"><a href="#cb27-126" aria-hidden="true" tabindex="-1"></a><span class="fu"># Multivariate linear regression analysis</span></span>
<span id="cb27-127"><a href="#cb27-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-128"><a href="#cb27-128" aria-hidden="true" tabindex="-1"></a><span class="fu">## Assumptions</span></span>
<span id="cb27-129"><a href="#cb27-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-130"><a href="#cb27-130" aria-hidden="true" tabindex="-1"></a>List assumptions:</span>
<span id="cb27-131"><a href="#cb27-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-132"><a href="#cb27-132" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>The observations are independent</span>
<span id="cb27-133"><a href="#cb27-133" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Linearity between the response and predictor variable</span>
<span id="cb27-134"><a href="#cb27-134" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>The residuals of the model must be normally distributed</span>
<span id="cb27-135"><a href="#cb27-135" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Homoscedasticity of the data</span>
<span id="cb27-136"><a href="#cb27-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-137"><a href="#cb27-137" aria-hidden="true" tabindex="-1"></a>The first assumption is met if we correct for block in the model because the rats were randomized to the treatment within block. The other three assumptions can be assessed by</span>
<span id="cb27-138"><a href="#cb27-138" aria-hidden="true" tabindex="-1"></a>fitting the linear model and calling the <span class="in">`plot()`</span> function as follows.</span>
<span id="cb27-139"><a href="#cb27-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-142"><a href="#cb27-142" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb27-143"><a href="#cb27-143" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(weightGain <span class="sc">~</span> block <span class="sc">+</span> protSource <span class="sc">*</span> protLevel, <span class="at">data =</span> diet)</span>
<span id="cb27-144"><a href="#cb27-144" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm1)</span>
<span id="cb27-145"><a href="#cb27-145" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-146"><a href="#cb27-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-147"><a href="#cb27-147" aria-hidden="true" tabindex="-1"></a>All assumptions are met for this dataset.</span>
<span id="cb27-148"><a href="#cb27-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-149"><a href="#cb27-149" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis testing</span></span>
<span id="cb27-150"><a href="#cb27-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-151"><a href="#cb27-151" aria-hidden="true" tabindex="-1"></a>We here fit a linear model with a blocking factor for <span class="in">`block`</span> and main and</span>
<span id="cb27-152"><a href="#cb27-152" aria-hidden="true" tabindex="-1"></a>interaction effects for protein source and protein level.</span>
<span id="cb27-153"><a href="#cb27-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-156"><a href="#cb27-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb27-157"><a href="#cb27-157" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span>
<span id="cb27-158"><a href="#cb27-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-159"><a href="#cb27-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-160"><a href="#cb27-160" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpretation of the regression parameters</span></span>
<span id="cb27-161"><a href="#cb27-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-164"><a href="#cb27-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb27-165"><a href="#cb27-165" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ExploreModelMatrix)</span>
<span id="cb27-166"><a href="#cb27-166" aria-hidden="true" tabindex="-1"></a>ExploreModelMatrix<span class="sc">::</span><span class="fu">VisualizeDesign</span>(diet, <span class="sc">~</span> block <span class="sc">+</span> protSource <span class="sc">*</span> protLevel)<span class="sc">$</span>plotlist</span>
<span id="cb27-167"><a href="#cb27-167" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-168"><a href="#cb27-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-169"><a href="#cb27-169" aria-hidden="true" tabindex="-1"></a>There are 3 levels for protein source, 2 levels for protein level and 10 levels</span>
<span id="cb27-170"><a href="#cb27-170" aria-hidden="true" tabindex="-1"></a>for the blocking variable. We will have one reference level for each respective</span>
<span id="cb27-171"><a href="#cb27-171" aria-hidden="true" tabindex="-1"></a>variable: beef, low, block 1. So we need 2, 1 and 9 dummy variables to introduce</span>
<span id="cb27-172"><a href="#cb27-172" aria-hidden="true" tabindex="-1"></a>the factors protein source, protein level and block in the linear model,</span>
<span id="cb27-173"><a href="#cb27-173" aria-hidden="true" tabindex="-1"></a>respectively.</span>
<span id="cb27-174"><a href="#cb27-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-175"><a href="#cb27-175" aria-hidden="true" tabindex="-1"></a>Hence, we can write down the linear model as follows:</span>
<span id="cb27-176"><a href="#cb27-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-177"><a href="#cb27-177" aria-hidden="true" tabindex="-1"></a>$y_i=\beta_0+\beta_cx_{i,c} +\beta_px_{i,p}+\beta_hx_{i,h}+\beta_{ch}x_{i,c}x_{i,h}+\beta_{ph}x_{i,p}x_{i,h}+\beta_{b2}x_{i,b2}+\ldots+\beta_{b10}x_{i,b10}+\epsilon_{i}$</span>
<span id="cb27-178"><a href="#cb27-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-179"><a href="#cb27-179" aria-hidden="true" tabindex="-1"></a>with:</span>
<span id="cb27-180"><a href="#cb27-180" aria-hidden="true" tabindex="-1"></a>$y_i$ the observed weight gain for rat i,</span>
<span id="cb27-181"><a href="#cb27-181" aria-hidden="true" tabindex="-1"></a>$x_{i,h}$ a dummy variable which is 1 if rat i receives a high protein diet</span>
<span id="cb27-182"><a href="#cb27-182" aria-hidden="true" tabindex="-1"></a>and is 0 otherwise,</span>
<span id="cb27-183"><a href="#cb27-183" aria-hidden="true" tabindex="-1"></a>$x_{i,c}$ a dummy variable which is 1 if rat i receives a cereal diet</span>
<span id="cb27-184"><a href="#cb27-184" aria-hidden="true" tabindex="-1"></a>and is 0 otherwise,</span>
<span id="cb27-185"><a href="#cb27-185" aria-hidden="true" tabindex="-1"></a>$x_{i,p}$ a dummy variable which is 1 if rat i receives a pork diet</span>
<span id="cb27-186"><a href="#cb27-186" aria-hidden="true" tabindex="-1"></a>and is 0 otherwise and</span>
<span id="cb27-187"><a href="#cb27-187" aria-hidden="true" tabindex="-1"></a>$x_{i,bk}$ is a dummy variable which is 1 if rat i belongs to block $bk$</span>
<span id="cb27-188"><a href="#cb27-188" aria-hidden="true" tabindex="-1"></a>and is 0 otherwise, with $k \in 2,\ldots, 10$,</span>
<span id="cb27-189"><a href="#cb27-189" aria-hidden="true" tabindex="-1"></a>and $\epsilon_i$ an error term which is normally distributed with mean 0 and</span>
<span id="cb27-190"><a href="#cb27-190" aria-hidden="true" tabindex="-1"></a>variance $\sigma^2$, i.e. $\epsilon_i \sim N(0,\sigma^2)$.</span>
<span id="cb27-191"><a href="#cb27-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-192"><a href="#cb27-192" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rats that are assigned to block $k$ and receive a beef based low protein diet have</span>
<span id="cb27-193"><a href="#cb27-193" aria-hidden="true" tabindex="-1"></a>    a covariate pattern $x_{i,h}=0$, $x_{i,c}=0$, $x_{i,p}=0$, $x_{i,bm}=0$ with $m\neq k$ and $x_{i,bk}=1$.</span>
<span id="cb27-194"><a href="#cb27-194" aria-hidden="true" tabindex="-1"></a>    Their mean weight gain is thus equal to $\mu_{l,b,bk}=\beta_0+\beta_{bk}$</span>
<span id="cb27-195"><a href="#cb27-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-196"><a href="#cb27-196" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rats that are assigned to block $k$ and receive a beef based high protein diet have</span>
<span id="cb27-197"><a href="#cb27-197" aria-hidden="true" tabindex="-1"></a>    a covariate pattern $x_{i,h}=1$, $x_{i,c}=0$, $x_{i,p}=0$, $x_{i,bm}=0$ with $m\neq k$ and $x_{i,bk}=1$.</span>
<span id="cb27-198"><a href="#cb27-198" aria-hidden="true" tabindex="-1"></a>    Their mean weight gain is thus equal to $\mu_{h,b,bk}=\beta_0+\beta_h+\beta_{bk}$</span>
<span id="cb27-199"><a href="#cb27-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-200"><a href="#cb27-200" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rats that are assigned to block $k$ and receive a cereal based low protein diet have</span>
<span id="cb27-201"><a href="#cb27-201" aria-hidden="true" tabindex="-1"></a>    a covariate pattern $x_{i,h}=0$, $x_{i,c}=1$, $x_{i,p}=0$, $x_{i,bm}=0$ with $m\neq k$ and $x_{i,bk}=1$.</span>
<span id="cb27-202"><a href="#cb27-202" aria-hidden="true" tabindex="-1"></a>    Their mean weight gain is thus equal to $\mu_{h,c,bk}=\beta_0+\beta_c+\beta_{bk}$</span>
<span id="cb27-203"><a href="#cb27-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-204"><a href="#cb27-204" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rats that are assigned to block $k$ and receive a cereal based heigh protein diet have</span>
<span id="cb27-205"><a href="#cb27-205" aria-hidden="true" tabindex="-1"></a>    a covariate pattern $x_{i,h}=1$, $x_{i,c}=1$, $x_{i,p}=0$, $x_{i,bm}=0$ with $m\neq k$ and $x_{i,bk}=1$.</span>
<span id="cb27-206"><a href="#cb27-206" aria-hidden="true" tabindex="-1"></a>    Their mean weight gain is thus equal to $\mu_{h,c,bk}=\beta_0+\beta_h+\beta_c+\beta_{ch}+\beta_{bk}$</span>
<span id="cb27-207"><a href="#cb27-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-208"><a href="#cb27-208" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rats that are assigned to block $k$ and receive a pork based low protein diet have</span>
<span id="cb27-209"><a href="#cb27-209" aria-hidden="true" tabindex="-1"></a>    a covariate pattern $x_{i,h}=0$,  $x_{i,c}=0$, $x_{i,p}=1$, $x_{i,bm}=0$ with $m\neq k$ and $x_{i,bk}=1$.</span>
<span id="cb27-210"><a href="#cb27-210" aria-hidden="true" tabindex="-1"></a>    Their mean weight gain is thus equal to $\mu_{l,p,bk}=\beta_0+\beta_p+\beta_{bk}$</span>
<span id="cb27-211"><a href="#cb27-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-212"><a href="#cb27-212" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rats that are assigned to block $k$ and receive a pork based heigh protein diet have</span>
<span id="cb27-213"><a href="#cb27-213" aria-hidden="true" tabindex="-1"></a>    a covariate pattern $x_{i,h}=1$, $x_{i,c}=0$, $x_{i,p}=1$, $x_{i,bm}=0$ with $m\neq k$ and $x_{i,bk}=1$.</span>
<span id="cb27-214"><a href="#cb27-214" aria-hidden="true" tabindex="-1"></a>    There mean weight gain is thus equal to $\mu_{h,p,bk}=\beta_0+\beta_h+\beta_p+\beta_{ph}+\beta_{bk}$</span>
<span id="cb27-215"><a href="#cb27-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-216"><a href="#cb27-216" aria-hidden="true" tabindex="-1"></a>We can now relate this to the output of the <span class="in">`lm`</span> function:</span>
<span id="cb27-217"><a href="#cb27-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-218"><a href="#cb27-218" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The intercept $\beta_0$ is thus the average weight increase in the low beef</span>
<span id="cb27-219"><a href="#cb27-219" aria-hidden="true" tabindex="-1"></a>diet for rats in block 1.</span>
<span id="cb27-220"><a href="#cb27-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-221"><a href="#cb27-221" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The parameter $\beta_c$: the average difference in weight gain between cereal-low and</span>
<span id="cb27-222"><a href="#cb27-222" aria-hidden="true" tabindex="-1"></a>beef-low diet is <span class="in">`r lm1$coef["protSourcecereal"]`</span>g.</span>
<span id="cb27-223"><a href="#cb27-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-224"><a href="#cb27-224" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The parameter $\beta_p$: the average difference in weight gain between pork-low and</span>
<span id="cb27-225"><a href="#cb27-225" aria-hidden="true" tabindex="-1"></a>beef-low diet is <span class="in">`r lm1$coef["protSourcepork"]`</span>g.</span>
<span id="cb27-226"><a href="#cb27-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-227"><a href="#cb27-227" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The parameter $\beta_h$: the average difference in weight gain between beef-high and</span>
<span id="cb27-228"><a href="#cb27-228" aria-hidden="true" tabindex="-1"></a>beef-Low diet is <span class="in">`r lm1$coef["protLevelhigh"]`</span>g.</span>
<span id="cb27-229"><a href="#cb27-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-230"><a href="#cb27-230" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The parameter $\beta_{ch}$ is the difference in the average weight gain difference</span>
<span id="cb27-231"><a href="#cb27-231" aria-hidden="true" tabindex="-1"></a>due to the high protein level as compared to the low protein level for cereal diets</span>
<span id="cb27-232"><a href="#cb27-232" aria-hidden="true" tabindex="-1"></a>as compared to the weight gain difference that occurs due to the protein level</span>
<span id="cb27-233"><a href="#cb27-233" aria-hidden="true" tabindex="-1"></a>in the reference class (here beef diet). Here this is negative,</span>
<span id="cb27-234"><a href="#cb27-234" aria-hidden="true" tabindex="-1"></a>i.e. <span class="in">`r lm1$coef["protSourcecereal:protLevelhigh"]`</span>g, thus the weight gain</span>
<span id="cb27-235"><a href="#cb27-235" aria-hidden="true" tabindex="-1"></a>for the cereal protein source increases on average less between high and low protein diets</span>
<span id="cb27-236"><a href="#cb27-236" aria-hidden="true" tabindex="-1"></a>than in beef based diets.</span>
<span id="cb27-237"><a href="#cb27-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-238"><a href="#cb27-238" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The parameter $\beta_{ph}$ is the difference in the average weight gain difference</span>
<span id="cb27-239"><a href="#cb27-239" aria-hidden="true" tabindex="-1"></a>due to the high protein level as compared to the low protein level for pork diets</span>
<span id="cb27-240"><a href="#cb27-240" aria-hidden="true" tabindex="-1"></a>as compared to the weight gain difference that occurs due to the protein level</span>
<span id="cb27-241"><a href="#cb27-241" aria-hidden="true" tabindex="-1"></a>in the reference class (here beef diet). Here this is negative,</span>
<span id="cb27-242"><a href="#cb27-242" aria-hidden="true" tabindex="-1"></a>i.e. <span class="in">`r lm1$coef["protSourcepork:protLevelhigh"]`</span>g, thus the weight gain</span>
<span id="cb27-243"><a href="#cb27-243" aria-hidden="true" tabindex="-1"></a>for the proc protein source increases on average less between high and low protein diets</span>
<span id="cb27-244"><a href="#cb27-244" aria-hidden="true" tabindex="-1"></a>than in beef based diets.</span>
<span id="cb27-245"><a href="#cb27-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-246"><a href="#cb27-246" aria-hidden="true" tabindex="-1"></a><span class="fu">## Testing the overall (combined) effect of diet</span></span>
<span id="cb27-247"><a href="#cb27-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-248"><a href="#cb27-248" aria-hidden="true" tabindex="-1"></a>Because there are multiple factors with different levels in the model,</span>
<span id="cb27-249"><a href="#cb27-249" aria-hidden="true" tabindex="-1"></a>we can first assess the effect of the diet (protein Level, protein source</span>
<span id="cb27-250"><a href="#cb27-250" aria-hidden="true" tabindex="-1"></a>and the interaction) by using anova. With this test we will assess the null</span>
<span id="cb27-251"><a href="#cb27-251" aria-hidden="true" tabindex="-1"></a>hypothesis that the average weight gain in each treatment is equal: i.e. $H_0: \mu_{b,l}=\mu_{b,h}=\mu_{c,h}=\mu_{c,l}=\mu_{p,h}=\mu_{p,h}$ versus</span>
<span id="cb27-252"><a href="#cb27-252" aria-hidden="true" tabindex="-1"></a>the alternative hyptohesis $H_1:$ that at least two treatment means are</span>
<span id="cb27-253"><a href="#cb27-253" aria-hidden="true" tabindex="-1"></a>different.</span>
<span id="cb27-254"><a href="#cb27-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-257"><a href="#cb27-257" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb27-258"><a href="#cb27-258" aria-hidden="true" tabindex="-1"></a>lm0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(weightGain <span class="sc">~</span> block, <span class="at">data =</span> diet)</span>
<span id="cb27-259"><a href="#cb27-259" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lm0, lm1)</span>
<span id="cb27-260"><a href="#cb27-260" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-261"><a href="#cb27-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-262"><a href="#cb27-262" aria-hidden="true" tabindex="-1"></a>We can conclude that there is an extremely significant effect of the diet type</span>
<span id="cb27-263"><a href="#cb27-263" aria-hidden="true" tabindex="-1"></a>(protein source and/or protein level and/or protein source-protein level</span>
<span id="cb27-264"><a href="#cb27-264" aria-hidden="true" tabindex="-1"></a>interaction) on the weight gain of rats (p &lt;&lt; 0.001).</span>
<span id="cb27-265"><a href="#cb27-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-266"><a href="#cb27-266" aria-hidden="true" tabindex="-1"></a><span class="fu">## Assessing the interaction effect between protein source and protein level</span></span>
<span id="cb27-267"><a href="#cb27-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-268"><a href="#cb27-268" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, message=FALSE, warning=FALSE}</span></span>
<span id="cb27-269"><a href="#cb27-269" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb27-270"><a href="#cb27-270" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(lm1, <span class="at">type =</span> <span class="st">"III"</span>)</span>
<span id="cb27-271"><a href="#cb27-271" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-272"><a href="#cb27-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-273"><a href="#cb27-273" aria-hidden="true" tabindex="-1"></a>There is a very significant interaction between the protein source and</span>
<span id="cb27-274"><a href="#cb27-274" aria-hidden="true" tabindex="-1"></a>the protein level (p = <span class="in">`r format(Anova(lm1, type=3)$"Pr(&gt;F)",digits=1)[5]`</span>). This indicates that the average weight increase due to</span>
<span id="cb27-275"><a href="#cb27-275" aria-hidden="true" tabindex="-1"></a>the protein level differs according to the protein source.</span>
<span id="cb27-276"><a href="#cb27-276" aria-hidden="true" tabindex="-1"></a>Hence, we cannot assess the effect of the protein source and/or protein level</span>
<span id="cb27-277"><a href="#cb27-277" aria-hidden="true" tabindex="-1"></a>independently because there effects of the protein source vary according to</span>
<span id="cb27-278"><a href="#cb27-278" aria-hidden="true" tabindex="-1"></a>the protein level.</span>
<span id="cb27-279"><a href="#cb27-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-280"><a href="#cb27-280" aria-hidden="true" tabindex="-1"></a><span class="fu">## Assessing specific contrasts</span></span>
<span id="cb27-281"><a href="#cb27-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-282"><a href="#cb27-282" aria-hidden="true" tabindex="-1"></a>Imagine that we are interested in assessing if there is an effect of</span>
<span id="cb27-283"><a href="#cb27-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-284"><a href="#cb27-284" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>protein source in the low protein diets</span>
<span id="cb27-285"><a href="#cb27-285" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>$\mu_{c,l}-\mu_{b,l} = \beta_c$</span>
<span id="cb27-286"><a href="#cb27-286" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>$\mu_{p,l}-\mu_{b,l} = \beta_p$</span>
<span id="cb27-287"><a href="#cb27-287" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>$\mu_{c,l}-\mu_{p,l}= \beta_c-\beta_p$)</span>
<span id="cb27-288"><a href="#cb27-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-289"><a href="#cb27-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-290"><a href="#cb27-290" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>protein source in high protein diets</span>
<span id="cb27-291"><a href="#cb27-291" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>$\mu_{c,h}-\mu_{b,h}=\beta_c+\beta_{ch}$</span>
<span id="cb27-292"><a href="#cb27-292" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>$\mu_{p,h}-\mu_{b,h}=\beta_p+\beta_{ph}$</span>
<span id="cb27-293"><a href="#cb27-293" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>$\mu_{p,h}-\mu_{c,h}=(\beta_c+\beta_{ch})-(\beta_p+\beta_{ph})$</span>
<span id="cb27-294"><a href="#cb27-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-295"><a href="#cb27-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-296"><a href="#cb27-296" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>protein level for</span>
<span id="cb27-297"><a href="#cb27-297" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>beef diets ($\mu_{b,h}-\mu_{b,l}=\beta_h$),</span>
<span id="cb27-298"><a href="#cb27-298" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>cereal diets  ($\mu_{c,h}-\mu_{c,l}=\beta_h+\beta_{ch}$) and</span>
<span id="cb27-299"><a href="#cb27-299" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>pork diets  ($\mu_{p,h}-\mu_{p,l}=\beta_h+\beta_{ph}$).</span>
<span id="cb27-300"><a href="#cb27-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-301"><a href="#cb27-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-302"><a href="#cb27-302" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>If the effect of the protein level differs between</span>
<span id="cb27-303"><a href="#cb27-303" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>beef and cereal  $(\mu_{c,h}-\mu_{c,l}) - (\mu_{b,h}-\mu_{b,l})=\beta_{ch}$</span>
<span id="cb27-304"><a href="#cb27-304" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>beef and pork $(\mu_{p,h}-\mu_{p,l}) - (\mu_{c,h}-\mu_{c,l})=\beta_{ph}$ and</span>
<span id="cb27-305"><a href="#cb27-305" aria-hidden="true" tabindex="-1"></a><span class="ss">    - </span>cereal and pork diets $(\mu_{c,h}-\mu_{c,l}) - (\mu_{p,h}-\mu_{p,l})=\beta_{ch}-\beta_{ph}$.</span>
<span id="cb27-306"><a href="#cb27-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-307"><a href="#cb27-307" aria-hidden="true" tabindex="-1"></a>These effects of interest are so-called</span>
<span id="cb27-308"><a href="#cb27-308" aria-hidden="true" tabindex="-1"></a>**contrasts, i.e. linear combinations of the parameters**.</span>
<span id="cb27-309"><a href="#cb27-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-310"><a href="#cb27-310" aria-hidden="true" tabindex="-1"></a>We can define the contrasts and assess the significance of the contrasts with</span>
<span id="cb27-311"><a href="#cb27-311" aria-hidden="true" tabindex="-1"></a>the code below. The contrasts are given as input in the form of symbolic</span>
<span id="cb27-312"><a href="#cb27-312" aria-hidden="true" tabindex="-1"></a>descriptions to the <span class="in">`linfct`</span> argument of the <span class="in">`glht`</span> function.</span>
<span id="cb27-313"><a href="#cb27-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-314"><a href="#cb27-314" aria-hidden="true" tabindex="-1"></a><span class="in">```{r,message=FALSE, warning=FALSE}</span></span>
<span id="cb27-315"><a href="#cb27-315" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb27-316"><a href="#cb27-316" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">75468</span>) <span class="co"># to get reproducible results (small effect if removed)</span></span>
<span id="cb27-317"><a href="#cb27-317" aria-hidden="true" tabindex="-1"></a>lm1MultComp <span class="ot">&lt;-</span> <span class="fu">glht</span>(</span>
<span id="cb27-318"><a href="#cb27-318" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> lm1,</span>
<span id="cb27-319"><a href="#cb27-319" aria-hidden="true" tabindex="-1"></a>  <span class="at">linfct =</span> <span class="fu">c</span>(</span>
<span id="cb27-320"><a href="#cb27-320" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcecereal = 0"</span>,</span>
<span id="cb27-321"><a href="#cb27-321" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcepork = 0"</span>,</span>
<span id="cb27-322"><a href="#cb27-322" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcecereal- protSourcepork = 0"</span>,</span>
<span id="cb27-323"><a href="#cb27-323" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcecereal + protSourcecereal:protLevelhigh = 0"</span>,</span>
<span id="cb27-324"><a href="#cb27-324" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcepork + protSourcepork:protLevelhigh = 0"</span>,</span>
<span id="cb27-325"><a href="#cb27-325" aria-hidden="true" tabindex="-1"></a>    <span class="st">"(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh) = 0"</span>,</span>
<span id="cb27-326"><a href="#cb27-326" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protLevelhigh = 0"</span>,</span>
<span id="cb27-327"><a href="#cb27-327" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protLevelhigh +  protSourcecereal:protLevelhigh = 0"</span>,</span>
<span id="cb27-328"><a href="#cb27-328" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protLevelhigh +  protSourcepork:protLevelhigh = 0"</span>,</span>
<span id="cb27-329"><a href="#cb27-329" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcecereal:protLevelhigh = 0"</span>,</span>
<span id="cb27-330"><a href="#cb27-330" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcepork:protLevelhigh = 0"</span>,</span>
<span id="cb27-331"><a href="#cb27-331" aria-hidden="true" tabindex="-1"></a>    <span class="st">"protSourcecereal:protLevelhigh - protSourcepork:protLevelhigh = 0"</span></span>
<span id="cb27-332"><a href="#cb27-332" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb27-333"><a href="#cb27-333" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-334"><a href="#cb27-334" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-335"><a href="#cb27-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-338"><a href="#cb27-338" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb27-339"><a href="#cb27-339" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1MultComp)</span>
<span id="cb27-340"><a href="#cb27-340" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-341"><a href="#cb27-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-344"><a href="#cb27-344" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb27-345"><a href="#cb27-345" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lm1MultComp)</span>
<span id="cb27-346"><a href="#cb27-346" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb27-347"><a href="#cb27-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-348"><a href="#cb27-348" aria-hidden="true" tabindex="-1"></a>Note that the p-values and the confidence intervals are automatically corrected</span>
<span id="cb27-349"><a href="#cb27-349" aria-hidden="true" tabindex="-1"></a>for multiple testing.</span>
<span id="cb27-350"><a href="#cb27-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-351"><a href="#cb27-351" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusion</span></span>
<span id="cb27-352"><a href="#cb27-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-353"><a href="#cb27-353" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>There is an extremely significant effect of the type of protein diet on the</span>
<span id="cb27-354"><a href="#cb27-354" aria-hidden="true" tabindex="-1"></a>weight gain of rats  (p&lt;&lt;1e-6). The interaction between protein type and protein</span>
<span id="cb27-355"><a href="#cb27-355" aria-hidden="true" tabindex="-1"></a>source is also very significant (p=<span class="in">`r round(Anova(lm1,type=3)$Pr[5],4)`</span>).</span>
<span id="cb27-356"><a href="#cb27-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-357"><a href="#cb27-357" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The average weight gain does not vary significantly according to protein</span>
<span id="cb27-358"><a href="#cb27-358" aria-hidden="true" tabindex="-1"></a>source in the diets with low protein levels (all p&gt;0.99).</span>
<span id="cb27-359"><a href="#cb27-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-360"><a href="#cb27-360" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The weight gain in the cereal diet at high protein concentration is on</span>
<span id="cb27-361"><a href="#cb27-361" aria-hidden="true" tabindex="-1"></a>average <span class="in">`r confint(lm1MultComp)$confint["protSourcecereal + protSourcecereal:protLevelhigh",1] |&gt; abs() |&gt; round(1)`</span>g and <span class="in">`r confint(lm1MultComp)$confint["(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh)",1] |&gt; abs() |&gt; round(1)`</span>g g lower than in the high protein beef and pork diet,</span>
<span id="cb27-362"><a href="#cb27-362" aria-hidden="true" tabindex="-1"></a>respectively (95% CI <span class="co">[</span><span class="ot">`r confint(lm1MultComp)$confint["protSourcecereal + protSourcecereal:protLevelhigh",-1] |&gt; abs() |&gt; round(1) |&gt; sort()`</span><span class="co">]</span> and <span class="co">[</span><span class="ot">`r confint(lm1MultComp)$confint["(protSourcecereal + protSourcecereal:protLevelhigh) - (protSourcepork + protSourcepork:protLevelhigh)",-1] |&gt; abs() |&gt; round(1) |&gt; sort()`</span><span class="co">]</span>) and the differences are</span>
<span id="cb27-363"><a href="#cb27-363" aria-hidden="true" tabindex="-1"></a>extremely significant (p&lt;0.001). The average weight gains after meat based</span>
<span id="cb27-364"><a href="#cb27-364" aria-hidden="true" tabindex="-1"></a>diets at high protein levels, however, do not differ significantly</span>
<span id="cb27-365"><a href="#cb27-365" aria-hidden="true" tabindex="-1"></a>(p&gt;0.99).</span>
<span id="cb27-366"><a href="#cb27-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-367"><a href="#cb27-367" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>We also discovered an extremely significant difference in weight gain</span>
<span id="cb27-368"><a href="#cb27-368" aria-hidden="true" tabindex="-1"></a>according to the protein level for beef and pork based diets (p&lt;0.001).</span>
<span id="cb27-369"><a href="#cb27-369" aria-hidden="true" tabindex="-1"></a>The weight gain on average increases with <span class="in">`r round(confint(lm1MultComp)$confint["protLevelhigh",1],1)`</span>g and <span class="in">`r round(confint(lm1MultComp)$confint["protLevelhigh + protSourcepork:protLevelhigh",1],1)`</span>g in the high protein</span>
<span id="cb27-370"><a href="#cb27-370" aria-hidden="true" tabindex="-1"></a>level as compared to the low protein beef and pork diet, respectively</span>
<span id="cb27-371"><a href="#cb27-371" aria-hidden="true" tabindex="-1"></a>(95%CI <span class="co">[</span><span class="ot">`r round(confint(lm1MultComp)$confint["protLevelhigh",-1],1)`</span><span class="co">]</span> and <span class="co">[</span><span class="ot">`r round(confint(lm1MultComp)$confint["protLevelhigh + protSourcepork:protLevelhigh",-1],1)`</span><span class="co">]</span>). The protein level effect is not significant</span>
<span id="cb27-372"><a href="#cb27-372" aria-hidden="true" tabindex="-1"></a>for the cereal diet (p&gt;0.99).</span>
<span id="cb27-373"><a href="#cb27-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-374"><a href="#cb27-374" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Finally significant interactions between protein level and protein source were</span>
<span id="cb27-375"><a href="#cb27-375" aria-hidden="true" tabindex="-1"></a>found (p&lt;0.05), i.e. the increase in weight gain due to protein level in cereal</span>
<span id="cb27-376"><a href="#cb27-376" aria-hidden="true" tabindex="-1"></a>based diets was 18.2g and 16.5g lower than that of beef and pork based diets,</span>
<span id="cb27-377"><a href="#cb27-377" aria-hidden="true" tabindex="-1"></a>respectively (95% CI <span class="co">[</span><span class="ot">3g,33.4g</span><span class="co">]</span> and <span class="co">[</span><span class="ot">1.3g,31.7g</span><span class="co">]</span>). The average difference in</span>
<span id="cb27-378"><a href="#cb27-378" aria-hidden="true" tabindex="-1"></a>increase in weight gain due to protein level among the meat based diets was not</span>
<span id="cb27-379"><a href="#cb27-379" aria-hidden="true" tabindex="-1"></a>significant (p&gt;0.99).</span>
<span id="cb27-380"><a href="#cb27-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-381"><a href="#cb27-381" aria-hidden="true" tabindex="-1"></a>All reported p-values and confidence intervals were corrected for multiple</span>
<span id="cb27-382"><a href="#cb27-382" aria-hidden="true" tabindex="-1"></a>testing</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>