{
  "hash": "e5026a304b4e2d9950f8353d65cecc87",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"1. Introduction: Why do we need statistics\"\nauthor: \"Lieven Clement\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html: default\n  pdf: default\n---\n\n\n\n# Motivation\n<a rel=\"license\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png\" /></a>\n\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/SCw65jjaXPw?si=m2w_NqDgjgC9kbf9\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\n\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/PAJL2078O20?si=ZO2BnEhboX6F53x5\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\n\n![](./figures/wpGraph.jpeg)\n\n- We live in a big data era\n- Data on location, clicks, e-commerce, social media ...\n- Life Sciences: measure expression of thousands of genes, proteins, ... for each subject or even individual cells\n- Data driven journalism\n- ...\n\nStatistics is the science to learn from empirical data.\n\nStatistical literacy is key to interpret results from scientific publications.\n\n# Learning objectives \n\n1. In this introduction you will familiarize yourself with three important tasks of statistics \n\n  - Experimental design\n  - Data Exploration\n  - Estimation and statistical inference \n\n2. You understand how the data, the estimated mean, standard deviation and conclusions of a statistical data analysis can change from experiment to experiment \n\n3. You have notice on how \n\n  - statistical tests can control for false positives \n  - the power to pick up an effect depends on the sample size \n\n4. You can explain the importance of using a good control \n\n5. You can explain what confounding is\n\n# Smelly armpit example\n\n- Smelly armpits are not caused by sweat itself. The smell is caused by specific micro-organisms belonging to the group of *Corynebacterium spp.* that metabolise sweat.\nAnother group of abundant bacteria are the *Staphylococcus spp.*, these bacteria do not metabolise sweat in smelly compounds.\n\n- The CMET-groep at Ghent University does research on transplanting the armpit microbiome to save people with smelly armpits.\n\n- Proposed Therapy:\n  \t1. Remove armpit-microbiome with antibiotics\n    2. Influence armpit microbiome with microbial  transplant (https://youtu.be/9RIFyqLXdVw)\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-1-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n- Experiment:\n\n    - 20 subjects with smelly armpits are attributed to one of two treatment groups\n    - placebo (only antibiotics)\n    - transplant (antibiotics followed by microbial transplant).\n    - The microbiome is sampled 6 weeks upon the treatment.\n    - The relative abundance of *Staphylococcus spp.* on *Corynebacterium spp.* + *Staphylococcus spp.* in the microbiome is measured via DGGE (*Denaturing Gradient Gel Electrophoresis*).\n\n---\n\n## Import the data\n\n::: {.cell}\n\n```{.r .cell-code}\nread_lines(\"https://raw.githubusercontent.com/GTPB/PSLS20/master/data/armpit.csv\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"trt,rel\"                       \"placebo,54.99207606973059\"    \n [3] \"placebo,31.84466019417476\"     \"placebo,41.09947643979057\"    \n [5] \"placebo,59.52063914780293\"     \"placebo,63.573407202216075\"   \n [7] \"placebo,41.48648648648649\"     \"placebo,30.44041450777202\"    \n [9] \"placebo,42.95676429567643\"     \"placebo,41.7391304347826\"     \n[11] \"placebo,33.896515311510036\"    \"transplant,57.218124341412015\"\n[13] \"transplant,72.50900360144058\"  \"transplant,61.89258312020461\" \n[15] \"transplant,56.690140845070424\" \"transplant,76\"                \n[17] \"transplant,71.7357910906298\"   \"transplant,57.757296466973884\"\n[19] \"transplant,65.1219512195122\"   \"transplant,67.53424657534246\" \n[21] \"transplant,77.55359394703657\" \n```\n\n\n:::\n:::\n\n\nThe file is comma separated and in tidy format\n\n\n::: {.cell}\n\n```{.r .cell-code}\nap <- read_csv(\"https://raw.githubusercontent.com/GTPB/PSLS20/master/data/armpit.csv\")\nap\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"trt\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"rel\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"placebo\",\"2\":\"54.99208\"},{\"1\":\"placebo\",\"2\":\"31.84466\"},{\"1\":\"placebo\",\"2\":\"41.09948\"},{\"1\":\"placebo\",\"2\":\"59.52064\"},{\"1\":\"placebo\",\"2\":\"63.57341\"},{\"1\":\"placebo\",\"2\":\"41.48649\"},{\"1\":\"placebo\",\"2\":\"30.44041\"},{\"1\":\"placebo\",\"2\":\"42.95676\"},{\"1\":\"placebo\",\"2\":\"41.73913\"},{\"1\":\"placebo\",\"2\":\"33.89652\"},{\"1\":\"transplant\",\"2\":\"57.21812\"},{\"1\":\"transplant\",\"2\":\"72.50900\"},{\"1\":\"transplant\",\"2\":\"61.89258\"},{\"1\":\"transplant\",\"2\":\"56.69014\"},{\"1\":\"transplant\",\"2\":\"76.00000\"},{\"1\":\"transplant\",\"2\":\"71.73579\"},{\"1\":\"transplant\",\"2\":\"57.75730\"},{\"1\":\"transplant\",\"2\":\"65.12195\"},{\"1\":\"transplant\",\"2\":\"67.53425\"},{\"1\":\"transplant\",\"2\":\"77.55359\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n---\n\n## Data Exploration and Descriptive Statistics\n\n- Data exploration is extremely important to get insight in the data.\n- It is often underrated and overlooked.\n\n### Descriptive statistics\n\nWe first summarize the data and calculate the mean, standard deviation, number of observations and standard error and store the result in an object apRelSum via `apRelSum<-`\n\n1. We pipe the `ap` dataframe to the group_by function to group the data by treatment trt `group_by(trt)`\n2. We pipe the result to the `summarize` function to summarize the \"rel\" variable and calculate the mean, standard deviation and the number of observations\n3. We pipe the result to the `mutate` function to make a new variable in the data frame `se` for which we calculate the standard error\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\napRelSum <- ap |>\n  group_by(trt) |>\n  summarize(\n    mean = mean(rel, na.rm = TRUE),\n    sd = sd(rel, na.rm = TRUE),\n    n = n()\n  ) |>\n  mutate(se = sd / sqrt(n))\n\napRelSum\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"trt\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"mean\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"n\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"se\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"placebo\",\"2\":\"44.15496\",\"3\":\"11.543251\",\"4\":\"10\",\"5\":\"3.650297\"},{\"1\":\"transplant\",\"2\":\"66.40127\",\"3\":\"7.880176\",\"4\":\"10\",\"5\":\"2.491930\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n---\n\n### Plots\n\nWe will use ggplot2 to make our plots.\nWith the ggplot2 library we can easily build plots by adding layers.\n\n#### barplot\n\n1. We pipe our summarized data to the `ggplot` function and we select the treatment variable trt and the variable mean for plotting `aes(x=trt,y=mean)`\n\n2. We make a barplot based on this data using the `geom_bar` function. The statistic is `stat=\"identity\"` because the bar height should be equal the value for the mean of the relative abundance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napRelSum |>\n  ggplot(aes(x = trt, y = mean)) +\n  geom_bar(stat = \"identity\")\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n- Is this plot informative??\n\n---\n\nWe will now add standard errors to the plot\nusing `geom_errorbar` function and specify the minimum and maximum value for of the error bar, the width command is used to set the width of the error bar smaller than the width of the bar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napRelSum |>\n  ggplot(aes(x = trt, y = mean)) +\n  geom_bar(stat = \"identity\") +\n  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = .2)\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n- Is this plot informative??\n\n---\n\n#### boxplots\n\nI consider barplots to be bad plots\n\n- They are not informative\n- They just visualize a two point summary of the data. It is better to do this in a table\n- They use a lot of space (e.g. from zero up to the minimum relative abundance) where no data are present.\n\nIt is better to get a view on the distribution of the data. We can use a boxplot for this purpose.\nWe first explain what a boxplot.\n\n---\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n---\n\nWe will now make a boxplot for the ap data\n\n1. We pipe the `ap` dataframe to the ggplot command\n2. We select the data with the command `ggplot(aes(x=trt,y=rel))`\n3. We add a boxplot with the command `geom_boxplot()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nap |>\n  ggplot(aes(x = trt, y = rel)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n---\n\n- Note, that we do not have so many observations.\n\n- It is always better to show the data as raw as possible!\n\nWe will now add the raw data to the plot.\n\n- Note that we set the outlier.shape=NA in the geom_boxplot function because because we will add all raw data anyway.\n- We add the raw data using `geom_point(position=\"jitter\")`, with the argument position='jitter' we will add some random noise to the x coordinate so that we can see all data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nap |>\n  ggplot(aes(x = trt, y = rel)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\")\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThis is an informative plot!\n\n---\n\n- We observed an effect of the transplantation on the relatieve abundantie of Staphylococcus.\n\n- Is that effect large enough to conclude that the treatment works?\n\n---\n\n## Estimation and statistical inference\n\n- Induction: With statistical inference we can generalize what we observe in the sample towards the population.\n\n- The price that we have to pay: uncertainty on our conclusions!\n\n---\n\n- With data we cannot prove that the treatment works\n\n- Falsification principle of Popper: With data we can only  reject a hypothesis or theory.\n\n- With stats we can thus not prove that the treatment works.\n\n- But stats will allow us to falcify the opposite hypothesis: how much evidence is there in the data against the assumption that there is no effect of the treatment?\n\n- With stats we can calculate how likely it is to draw a random sample (when you would repeat the experiment) with a mean difference in relative abundance between transplant and placebo group that is at least as large as what we observed in our sample when there would be no effect of the treatment.\n\n- This probability is called a p-value.\n\n- If p is very small, it is very unlikely to observe a sample like ours by random change when there would be no effect of the treatment.\n\n- We typically compare p with 5%. If there is no effect of the treatment we will thus tolerate a probability of 5% on a false positive conclusion.\n\n- To calculate p we will have to model the data using  statistical models.\n\n---\n\nIn chapter 5 we will learn that we can use a two-sample t-test to generalise what we observe in the microbiome dataset towards the population.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(rel ~ trt, data = ap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  rel by trt\nt = -5.0334, df = 15.892, p-value = 0.0001249\nalternative hypothesis: true difference in means between group placebo and group transplant is not equal to 0\n95 percent confidence interval:\n -31.62100 -12.87163\nsample estimates:\n   mean in group placebo mean in group transplant \n                44.15496                 66.40127 \n```\n\n\n:::\n:::\n\n\nConclusion:\n\nWe can conclude that the relative abundance of Staphylococcus in the microbiome of individuals with smelly armpits  is 22.2% higher upon the transplant than upon the placebo treatment (p < 0.001).\n\n---\n\n## Some concepts\n\nWhat are the consequences of using a sample and randomisation?\n\n- Random sampling is closely related to the concept of the population or the scope of the study.\n\n- Based on a sample of subjects, the researchers want to come to conclusions that hold for\n\n    - all kinds of people\n    - only male students\n\n- Scope of the study should be well specified before the start of the study.\n\n- For the statistical analysis to be valid, it is required that the subjects are selected completely at random from the population to which we want to generalize our conclusions.\n\n- Selecting completely at random from a population implies:\n    - all subjects in the population should have the same probability of being selected in the sample,\n    - the selection of a subject in the sample should be independent from the selection of the other subjects in the sample.\n\n- The sample is thus supposed to be representative for the population, but still it is random.\n\n- What does this imply?\n\n---\n\n# Sample to sample variability\n\n- To understand that a sample is random, we would have to be able to repeat the same experiment many times (`repeated sampling`).\n\n- This would give us insight in how the data change from sample to sample.\n\n- To illustrate this we will make use of a very large study.\n\n- From that study, we will repeatedly draw small samples to understand how the data and statistics change from sample to sample. In other words, to assess what the variability is between samples.\n\n---\n\nNational Health And Nutrition Examination Study (NHANES)\n\n  - Since 1960 individuals of all ages are interviewed in their homes every year.\n  - The health examination component of the survey is conducted in a mobile examination centre (MEC).\n  - We will use this large study to select random subjects from the American population.\n  - This will help us to understand how the results of an analysis and the conclusions vary from sample to sample.\n  - The data of this study can be found in the R package `NHANES`.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\nhead(NHANES)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"ID\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SurveyYr\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Gender\"],\"name\":[3],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Age\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"AgeDecade\"],\"name\":[5],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"AgeMonths\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Race1\"],\"name\":[7],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Race3\"],\"name\":[8],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Education\"],\"name\":[9],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"MaritalStatus\"],\"name\":[10],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"HHIncome\"],\"name\":[11],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"HHIncomeMid\"],\"name\":[12],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Poverty\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HomeRooms\"],\"name\":[14],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"HomeOwn\"],\"name\":[15],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Work\"],\"name\":[16],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Weight\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Length\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"HeadCirc\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Height\"],\"name\":[20],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BMI\"],\"name\":[21],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"BMICatUnder20yrs\"],\"name\":[22],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"BMI_WHO\"],\"name\":[23],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Pulse\"],\"name\":[24],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"BPSysAve\"],\"name\":[25],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"BPDiaAve\"],\"name\":[26],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"BPSys1\"],\"name\":[27],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"BPDia1\"],\"name\":[28],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"BPSys2\"],\"name\":[29],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"BPDia2\"],\"name\":[30],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"BPSys3\"],\"name\":[31],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"BPDia3\"],\"name\":[32],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Testosterone\"],\"name\":[33],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"DirectChol\"],\"name\":[34],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"TotChol\"],\"name\":[35],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"UrineVol1\"],\"name\":[36],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"UrineFlow1\"],\"name\":[37],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"UrineVol2\"],\"name\":[38],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"UrineFlow2\"],\"name\":[39],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Diabetes\"],\"name\":[40],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"DiabetesAge\"],\"name\":[41],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"HealthGen\"],\"name\":[42],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"DaysPhysHlthBad\"],\"name\":[43],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"DaysMentHlthBad\"],\"name\":[44],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"LittleInterest\"],\"name\":[45],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Depressed\"],\"name\":[46],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"nPregnancies\"],\"name\":[47],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"nBabies\"],\"name\":[48],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Age1stBaby\"],\"name\":[49],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SleepHrsNight\"],\"name\":[50],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SleepTrouble\"],\"name\":[51],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"PhysActive\"],\"name\":[52],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"PhysActiveDays\"],\"name\":[53],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"TVHrsDay\"],\"name\":[54],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"CompHrsDay\"],\"name\":[55],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"TVHrsDayChild\"],\"name\":[56],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"CompHrsDayChild\"],\"name\":[57],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Alcohol12PlusYr\"],\"name\":[58],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"AlcoholDay\"],\"name\":[59],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"AlcoholYear\"],\"name\":[60],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SmokeNow\"],\"name\":[61],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Smoke100\"],\"name\":[62],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Smoke100n\"],\"name\":[63],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"SmokeAge\"],\"name\":[64],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Marijuana\"],\"name\":[65],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"AgeFirstMarij\"],\"name\":[66],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"RegularMarij\"],\"name\":[67],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"AgeRegMarij\"],\"name\":[68],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"HardDrugs\"],\"name\":[69],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"SexEver\"],\"name\":[70],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"SexAge\"],\"name\":[71],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SexNumPartnLife\"],\"name\":[72],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SexNumPartYear\"],\"name\":[73],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"SameSex\"],\"name\":[74],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"SexOrientation\"],\"name\":[75],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"PregnantNow\"],\"name\":[76],\"type\":[\"fct\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"51624\",\"2\":\"2009_10\",\"3\":\"male\",\"4\":\"34\",\"5\":\"30-39\",\"6\":\"409\",\"7\":\"White\",\"8\":\"NA\",\"9\":\"High School\",\"10\":\"Married\",\"11\":\"25000-34999\",\"12\":\"30000\",\"13\":\"1.36\",\"14\":\"6\",\"15\":\"Own\",\"16\":\"NotWorking\",\"17\":\"87.4\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"164.7\",\"21\":\"32.22\",\"22\":\"NA\",\"23\":\"30.0_plus\",\"24\":\"70\",\"25\":\"113\",\"26\":\"85\",\"27\":\"114\",\"28\":\"88\",\"29\":\"114\",\"30\":\"88\",\"31\":\"112\",\"32\":\"82\",\"33\":\"NA\",\"34\":\"1.29\",\"35\":\"3.49\",\"36\":\"352\",\"37\":\"NA\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"15\",\"45\":\"Most\",\"46\":\"Several\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"4\",\"51\":\"Yes\",\"52\":\"No\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"NA\",\"60\":\"0\",\"61\":\"No\",\"62\":\"Yes\",\"63\":\"Smoker\",\"64\":\"18\",\"65\":\"Yes\",\"66\":\"17\",\"67\":\"No\",\"68\":\"NA\",\"69\":\"Yes\",\"70\":\"Yes\",\"71\":\"16\",\"72\":\"8\",\"73\":\"1\",\"74\":\"No\",\"75\":\"Heterosexual\",\"76\":\"NA\"},{\"1\":\"51624\",\"2\":\"2009_10\",\"3\":\"male\",\"4\":\"34\",\"5\":\"30-39\",\"6\":\"409\",\"7\":\"White\",\"8\":\"NA\",\"9\":\"High School\",\"10\":\"Married\",\"11\":\"25000-34999\",\"12\":\"30000\",\"13\":\"1.36\",\"14\":\"6\",\"15\":\"Own\",\"16\":\"NotWorking\",\"17\":\"87.4\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"164.7\",\"21\":\"32.22\",\"22\":\"NA\",\"23\":\"30.0_plus\",\"24\":\"70\",\"25\":\"113\",\"26\":\"85\",\"27\":\"114\",\"28\":\"88\",\"29\":\"114\",\"30\":\"88\",\"31\":\"112\",\"32\":\"82\",\"33\":\"NA\",\"34\":\"1.29\",\"35\":\"3.49\",\"36\":\"352\",\"37\":\"NA\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"15\",\"45\":\"Most\",\"46\":\"Several\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"4\",\"51\":\"Yes\",\"52\":\"No\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"NA\",\"60\":\"0\",\"61\":\"No\",\"62\":\"Yes\",\"63\":\"Smoker\",\"64\":\"18\",\"65\":\"Yes\",\"66\":\"17\",\"67\":\"No\",\"68\":\"NA\",\"69\":\"Yes\",\"70\":\"Yes\",\"71\":\"16\",\"72\":\"8\",\"73\":\"1\",\"74\":\"No\",\"75\":\"Heterosexual\",\"76\":\"NA\"},{\"1\":\"51624\",\"2\":\"2009_10\",\"3\":\"male\",\"4\":\"34\",\"5\":\"30-39\",\"6\":\"409\",\"7\":\"White\",\"8\":\"NA\",\"9\":\"High School\",\"10\":\"Married\",\"11\":\"25000-34999\",\"12\":\"30000\",\"13\":\"1.36\",\"14\":\"6\",\"15\":\"Own\",\"16\":\"NotWorking\",\"17\":\"87.4\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"164.7\",\"21\":\"32.22\",\"22\":\"NA\",\"23\":\"30.0_plus\",\"24\":\"70\",\"25\":\"113\",\"26\":\"85\",\"27\":\"114\",\"28\":\"88\",\"29\":\"114\",\"30\":\"88\",\"31\":\"112\",\"32\":\"82\",\"33\":\"NA\",\"34\":\"1.29\",\"35\":\"3.49\",\"36\":\"352\",\"37\":\"NA\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"15\",\"45\":\"Most\",\"46\":\"Several\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"4\",\"51\":\"Yes\",\"52\":\"No\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"NA\",\"60\":\"0\",\"61\":\"No\",\"62\":\"Yes\",\"63\":\"Smoker\",\"64\":\"18\",\"65\":\"Yes\",\"66\":\"17\",\"67\":\"No\",\"68\":\"NA\",\"69\":\"Yes\",\"70\":\"Yes\",\"71\":\"16\",\"72\":\"8\",\"73\":\"1\",\"74\":\"No\",\"75\":\"Heterosexual\",\"76\":\"NA\"},{\"1\":\"51625\",\"2\":\"2009_10\",\"3\":\"male\",\"4\":\"4\",\"5\":\"0-9\",\"6\":\"49\",\"7\":\"Other\",\"8\":\"NA\",\"9\":\"NA\",\"10\":\"NA\",\"11\":\"20000-24999\",\"12\":\"22500\",\"13\":\"1.07\",\"14\":\"9\",\"15\":\"Own\",\"16\":\"NA\",\"17\":\"17.0\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"105.4\",\"21\":\"15.30\",\"22\":\"NA\",\"23\":\"12.0_18.5\",\"24\":\"NA\",\"25\":\"NA\",\"26\":\"NA\",\"27\":\"NA\",\"28\":\"NA\",\"29\":\"NA\",\"30\":\"NA\",\"31\":\"NA\",\"32\":\"NA\",\"33\":\"NA\",\"34\":\"NA\",\"35\":\"NA\",\"36\":\"NA\",\"37\":\"NA\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"NA\",\"43\":\"NA\",\"44\":\"NA\",\"45\":\"NA\",\"46\":\"NA\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"NA\",\"51\":\"NA\",\"52\":\"NA\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"4\",\"57\":\"1\",\"58\":\"NA\",\"59\":\"NA\",\"60\":\"NA\",\"61\":\"NA\",\"62\":\"NA\",\"63\":\"NA\",\"64\":\"NA\",\"65\":\"NA\",\"66\":\"NA\",\"67\":\"NA\",\"68\":\"NA\",\"69\":\"NA\",\"70\":\"NA\",\"71\":\"NA\",\"72\":\"NA\",\"73\":\"NA\",\"74\":\"NA\",\"75\":\"NA\",\"76\":\"NA\"},{\"1\":\"51630\",\"2\":\"2009_10\",\"3\":\"female\",\"4\":\"49\",\"5\":\"40-49\",\"6\":\"596\",\"7\":\"White\",\"8\":\"NA\",\"9\":\"Some College\",\"10\":\"LivePartner\",\"11\":\"35000-44999\",\"12\":\"40000\",\"13\":\"1.91\",\"14\":\"5\",\"15\":\"Rent\",\"16\":\"NotWorking\",\"17\":\"86.7\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"168.4\",\"21\":\"30.57\",\"22\":\"NA\",\"23\":\"30.0_plus\",\"24\":\"86\",\"25\":\"112\",\"26\":\"75\",\"27\":\"118\",\"28\":\"82\",\"29\":\"108\",\"30\":\"74\",\"31\":\"116\",\"32\":\"76\",\"33\":\"NA\",\"34\":\"1.16\",\"35\":\"6.70\",\"36\":\"77\",\"37\":\"0.094\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"Good\",\"43\":\"0\",\"44\":\"10\",\"45\":\"Several\",\"46\":\"Several\",\"47\":\"2\",\"48\":\"2\",\"49\":\"27\",\"50\":\"8\",\"51\":\"Yes\",\"52\":\"No\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"NA\",\"57\":\"NA\",\"58\":\"Yes\",\"59\":\"2\",\"60\":\"20\",\"61\":\"Yes\",\"62\":\"Yes\",\"63\":\"Smoker\",\"64\":\"38\",\"65\":\"Yes\",\"66\":\"18\",\"67\":\"No\",\"68\":\"NA\",\"69\":\"Yes\",\"70\":\"Yes\",\"71\":\"12\",\"72\":\"10\",\"73\":\"1\",\"74\":\"Yes\",\"75\":\"Heterosexual\",\"76\":\"NA\"},{\"1\":\"51638\",\"2\":\"2009_10\",\"3\":\"male\",\"4\":\"9\",\"5\":\"0-9\",\"6\":\"115\",\"7\":\"White\",\"8\":\"NA\",\"9\":\"NA\",\"10\":\"NA\",\"11\":\"75000-99999\",\"12\":\"87500\",\"13\":\"1.84\",\"14\":\"6\",\"15\":\"Rent\",\"16\":\"NA\",\"17\":\"29.8\",\"18\":\"NA\",\"19\":\"NA\",\"20\":\"133.1\",\"21\":\"16.82\",\"22\":\"NA\",\"23\":\"12.0_18.5\",\"24\":\"82\",\"25\":\"86\",\"26\":\"47\",\"27\":\"84\",\"28\":\"50\",\"29\":\"84\",\"30\":\"50\",\"31\":\"88\",\"32\":\"44\",\"33\":\"NA\",\"34\":\"1.34\",\"35\":\"4.86\",\"36\":\"123\",\"37\":\"1.538\",\"38\":\"NA\",\"39\":\"NA\",\"40\":\"No\",\"41\":\"NA\",\"42\":\"NA\",\"43\":\"NA\",\"44\":\"NA\",\"45\":\"NA\",\"46\":\"NA\",\"47\":\"NA\",\"48\":\"NA\",\"49\":\"NA\",\"50\":\"NA\",\"51\":\"NA\",\"52\":\"NA\",\"53\":\"NA\",\"54\":\"NA\",\"55\":\"NA\",\"56\":\"5\",\"57\":\"0\",\"58\":\"NA\",\"59\":\"NA\",\"60\":\"NA\",\"61\":\"NA\",\"62\":\"NA\",\"63\":\"NA\",\"64\":\"NA\",\"65\":\"NA\",\"66\":\"NA\",\"67\":\"NA\",\"68\":\"NA\",\"69\":\"NA\",\"70\":\"NA\",\"71\":\"NA\",\"72\":\"NA\",\"73\":\"NA\",\"74\":\"NA\",\"75\":\"NA\",\"76\":\"NA\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nglimpse(NHANES)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10,000\nColumns: 76\n$ ID               <int> 51624, 51624, 51624, 51625, 51630, 51638, 51646, 5164…\n$ SurveyYr         <fct> 2009_10, 2009_10, 2009_10, 2009_10, 2009_10, 2009_10,…\n$ Gender           <fct> male, male, male, male, female, male, male, female, f…\n$ Age              <int> 34, 34, 34, 4, 49, 9, 8, 45, 45, 45, 66, 58, 54, 10, …\n$ AgeDecade        <fct>  30-39,  30-39,  30-39,  0-9,  40-49,  0-9,  0-9,  40…\n$ AgeMonths        <int> 409, 409, 409, 49, 596, 115, 101, 541, 541, 541, 795,…\n$ Race1            <fct> White, White, White, Other, White, White, White, Whit…\n$ Race3            <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ Education        <fct> High School, High School, High School, NA, Some Colle…\n$ MaritalStatus    <fct> Married, Married, Married, NA, LivePartner, NA, NA, M…\n$ HHIncome         <fct> 25000-34999, 25000-34999, 25000-34999, 20000-24999, 3…\n$ HHIncomeMid      <int> 30000, 30000, 30000, 22500, 40000, 87500, 60000, 8750…\n$ Poverty          <dbl> 1.36, 1.36, 1.36, 1.07, 1.91, 1.84, 2.33, 5.00, 5.00,…\n$ HomeRooms        <int> 6, 6, 6, 9, 5, 6, 7, 6, 6, 6, 5, 10, 6, 10, 10, 4, 3,…\n$ HomeOwn          <fct> Own, Own, Own, Own, Rent, Rent, Own, Own, Own, Own, O…\n$ Work             <fct> NotWorking, NotWorking, NotWorking, NA, NotWorking, N…\n$ Weight           <dbl> 87.4, 87.4, 87.4, 17.0, 86.7, 29.8, 35.2, 75.7, 75.7,…\n$ Length           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ HeadCirc         <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ Height           <dbl> 164.7, 164.7, 164.7, 105.4, 168.4, 133.1, 130.6, 166.…\n$ BMI              <dbl> 32.22, 32.22, 32.22, 15.30, 30.57, 16.82, 20.64, 27.2…\n$ BMICatUnder20yrs <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ BMI_WHO          <fct> 30.0_plus, 30.0_plus, 30.0_plus, 12.0_18.5, 30.0_plus…\n$ Pulse            <int> 70, 70, 70, NA, 86, 82, 72, 62, 62, 62, 60, 62, 76, 8…\n$ BPSysAve         <int> 113, 113, 113, NA, 112, 86, 107, 118, 118, 118, 111, …\n$ BPDiaAve         <int> 85, 85, 85, NA, 75, 47, 37, 64, 64, 64, 63, 74, 85, 6…\n$ BPSys1           <int> 114, 114, 114, NA, 118, 84, 114, 106, 106, 106, 124, …\n$ BPDia1           <int> 88, 88, 88, NA, 82, 50, 46, 62, 62, 62, 64, 76, 86, 6…\n$ BPSys2           <int> 114, 114, 114, NA, 108, 84, 108, 118, 118, 118, 108, …\n$ BPDia2           <int> 88, 88, 88, NA, 74, 50, 36, 68, 68, 68, 62, 72, 88, 6…\n$ BPSys3           <int> 112, 112, 112, NA, 116, 88, 106, 118, 118, 118, 114, …\n$ BPDia3           <int> 82, 82, 82, NA, 76, 44, 38, 60, 60, 60, 64, 76, 82, 7…\n$ Testosterone     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ DirectChol       <dbl> 1.29, 1.29, 1.29, NA, 1.16, 1.34, 1.55, 2.12, 2.12, 2…\n$ TotChol          <dbl> 3.49, 3.49, 3.49, NA, 6.70, 4.86, 4.09, 5.82, 5.82, 5…\n$ UrineVol1        <int> 352, 352, 352, NA, 77, 123, 238, 106, 106, 106, 113, …\n$ UrineFlow1       <dbl> NA, NA, NA, NA, 0.094, 1.538, 1.322, 1.116, 1.116, 1.…\n$ UrineVol2        <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ UrineFlow2       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ Diabetes         <fct> No, No, No, No, No, No, No, No, No, No, No, No, No, N…\n$ DiabetesAge      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ HealthGen        <fct> Good, Good, Good, NA, Good, NA, NA, Vgood, Vgood, Vgo…\n$ DaysPhysHlthBad  <int> 0, 0, 0, NA, 0, NA, NA, 0, 0, 0, 10, 0, 4, NA, NA, 0,…\n$ DaysMentHlthBad  <int> 15, 15, 15, NA, 10, NA, NA, 3, 3, 3, 0, 0, 0, NA, NA,…\n$ LittleInterest   <fct> Most, Most, Most, NA, Several, NA, NA, None, None, No…\n$ Depressed        <fct> Several, Several, Several, NA, Several, NA, NA, None,…\n$ nPregnancies     <int> NA, NA, NA, NA, 2, NA, NA, 1, 1, 1, NA, NA, NA, NA, N…\n$ nBabies          <int> NA, NA, NA, NA, 2, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ Age1stBaby       <int> NA, NA, NA, NA, 27, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ SleepHrsNight    <int> 4, 4, 4, NA, 8, NA, NA, 8, 8, 8, 7, 5, 4, NA, 5, 7, N…\n$ SleepTrouble     <fct> Yes, Yes, Yes, NA, Yes, NA, NA, No, No, No, No, No, Y…\n$ PhysActive       <fct> No, No, No, NA, No, NA, NA, Yes, Yes, Yes, Yes, Yes, …\n$ PhysActiveDays   <int> NA, NA, NA, NA, NA, NA, NA, 5, 5, 5, 7, 5, 1, NA, 2, …\n$ TVHrsDay         <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ CompHrsDay       <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ TVHrsDayChild    <int> NA, NA, NA, 4, NA, 5, 1, NA, NA, NA, NA, NA, NA, 4, N…\n$ CompHrsDayChild  <int> NA, NA, NA, 1, NA, 0, 6, NA, NA, NA, NA, NA, NA, 3, N…\n$ Alcohol12PlusYr  <fct> Yes, Yes, Yes, NA, Yes, NA, NA, Yes, Yes, Yes, Yes, Y…\n$ AlcoholDay       <int> NA, NA, NA, NA, 2, NA, NA, 3, 3, 3, 1, 2, 6, NA, NA, …\n$ AlcoholYear      <int> 0, 0, 0, NA, 20, NA, NA, 52, 52, 52, 100, 104, 364, N…\n$ SmokeNow         <fct> No, No, No, NA, Yes, NA, NA, NA, NA, NA, No, NA, NA, …\n$ Smoke100         <fct> Yes, Yes, Yes, NA, Yes, NA, NA, No, No, No, Yes, No, …\n$ Smoke100n        <fct> Smoker, Smoker, Smoker, NA, Smoker, NA, NA, Non-Smoke…\n$ SmokeAge         <int> 18, 18, 18, NA, 38, NA, NA, NA, NA, NA, 13, NA, NA, N…\n$ Marijuana        <fct> Yes, Yes, Yes, NA, Yes, NA, NA, Yes, Yes, Yes, NA, Ye…\n$ AgeFirstMarij    <int> 17, 17, 17, NA, 18, NA, NA, 13, 13, 13, NA, 19, 15, N…\n$ RegularMarij     <fct> No, No, No, NA, No, NA, NA, No, No, No, NA, Yes, Yes,…\n$ AgeRegMarij      <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 20, 15, N…\n$ HardDrugs        <fct> Yes, Yes, Yes, NA, Yes, NA, NA, No, No, No, No, Yes, …\n$ SexEver          <fct> Yes, Yes, Yes, NA, Yes, NA, NA, Yes, Yes, Yes, Yes, Y…\n$ SexAge           <int> 16, 16, 16, NA, 12, NA, NA, 13, 13, 13, 17, 22, 12, N…\n$ SexNumPartnLife  <int> 8, 8, 8, NA, 10, NA, NA, 20, 20, 20, 15, 7, 100, NA, …\n$ SexNumPartYear   <int> 1, 1, 1, NA, 1, NA, NA, 0, 0, 0, NA, 1, 1, NA, NA, 1,…\n$ SameSex          <fct> No, No, No, NA, Yes, NA, NA, Yes, Yes, Yes, No, No, N…\n$ SexOrientation   <fct> Heterosexual, Heterosexual, Heterosexual, NA, Heteros…\n$ PregnantNow      <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n```\n\n\n:::\n:::\n\n\n---\n\n## Data exploration\n\nResearch question: how does the height of adult men and women differ?\n\n1. We pipe the dataset to the function `filter` to filter the data according to age.\n2. We plot the height measurements.\n    - We select the data with the command `ggplot(aes(x=Height))`\n    - We add a histogram with the command `geom_histogram()`\n    - We make two vertical panels using the command `facet_grid(Gender~.)`\n    - We customize the label of the x-axis with the `xlab` command.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  filter(Age >= 18 & !is.na(Height)) |>\n  ggplot(aes(x = Height)) +\n  geom_histogram() +\n  facet_grid(Gender ~ .) +\n  xlab(\"Height (cm)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n---\n\nWe see that the data are now more or less symmetrically distributed and bell shaped.\nThis will allow us to further summarize the data by using two statistics: the mean and the standard deviation, which is a measure for the spread of the data around the mean.\n\n---\n\nWe will now create a subset of the data that we will use to illustrate how the data in small samples can vary from sample to sample.\n\n  1. We filter on age and remove subjects with missing values (NA, Not Available).\n  2. We only select Gender and Height so that the dataset does not contain unnecessary variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnhanesSub <- NHANES |>\n  filter(Age >= 18 & !is.na(Height)) |>\n  select(c(\"Gender\", \"Height\"))\n```\n:::\n\n\n---\n\nWe will calculate the mean and the standard deviation for the height for males and females in the large dataset.\nSo we group the data by gender (variable Gender).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHeightSum <- nhanesSub |>\n  group_by(Gender) |>\n  summarize_at(\"Height\",\n    list(mean = mean, sd = sd)\n  )\n\nknitr::kable(\n  HeightSum |>\n    mutate_if(is.numeric, round, digits = 1)\n)\n```\n\n::: {.cell-output-display}\n\n\n|Gender |  mean|  sd|\n|:------|-----:|---:|\n|female | 162.1| 7.3|\n|male   | 175.9| 7.5|\n\n\n:::\n:::\n\n\nBoth distributions:\n\n- seem to follow a normal distribution\n- with the same variance\n\n$\\rightarrow$ so they only differ in mean.\n\n- Research question: \"Is there a difference in height between males and females?\"\n- can be translated to 1 characteristic: the average difference in height\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHeightSum$mean[1] - HeightSum$mean[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -13.81445\n```\n\n\n:::\n:::\n\n\nOn average, adult American women are 13.8 cm shorter than men.\n\n---\n\n## Experiment\n\n- Suppose that we have no access to the measurements of the NHANES study.\n\n- We would then have to set up an experiment to take measurements in males and females.\n\n- Suppose that we have a budget to take measurements of 5 males and 5 females.\n\n- We would then randomly select 5 males and 5 females above 18 years old from the American population.\n\n- We can simulate this experiment by randomly selecting 5 females and 5 males from the NHANES study.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1023)\nnSamp <- 5\nfem <- nhanesSub |>\n  filter(Gender == \"female\") |>\n  sample_n(size = 5)\n\nmal <- nhanesSub |>\n  filter(Gender == \"male\") |>\n  sample_n(size = 5)\n\nsamp1 <- rbind(fem, mal)\n\nsamp1\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Gender\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Height\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"164.0\"},{\"1\":\"female\",\"2\":\"160.1\"},{\"1\":\"female\",\"2\":\"159.0\"},{\"1\":\"female\",\"2\":\"154.1\"},{\"1\":\"female\",\"2\":\"156.4\"},{\"1\":\"male\",\"2\":\"169.6\"},{\"1\":\"male\",\"2\":\"182.9\"},{\"1\":\"male\",\"2\":\"182.6\"},{\"1\":\"male\",\"2\":\"184.6\"},{\"1\":\"male\",\"2\":\"169.7\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n---\n\nData exploration\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamp1 |>\n  ggplot(aes(x = Height)) +\n  geom_histogram() +\n  facet_grid(Gender ~ .) +\n  xlab(\"Height (cm)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\nHeightSumExp1 <- samp1 |>\n  group_by(Gender) |>\n  summarize_at(\"Height\",\n    list(mean = mean, sd = sd)\n  )\nHeightSumExp1\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Gender\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"mean\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"158.72\",\"3\":\"3.761250\"},{\"1\":\"male\",\"2\":\"177.88\",\"3\":\"7.551622\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nA histogram is not very useful when we only have so few data points.\n\n---\n\nA boxplot is better:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n## Repeat the experiment\n\nIf we repeat the experiment, we select other people and we obtain different results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1024)\nfem <- nhanesSub |>\n  filter(Gender == \"female\") |>\n  sample_n(size = 5)\n\nmal <- nhanesSub |>\n  filter(Gender == \"male\") |>\n  sample_n(size = 5)\n\nsamp2 <- rbind(fem, mal)\n\nHeightSumExp2 <- samp2 |>\n  group_by(Gender) |>\n  summarize_at(\"Height\",\n    list(mean = mean, sd = sd)\n  )\nHeightSumExp2\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Gender\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"mean\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"166.26\",\"3\":\"9.891562\"},{\"1\":\"male\",\"2\":\"170.46\",\"3\":\"8.239721\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsamp2 |>\n  ggplot(aes(x = Gender, y = Height)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\") +\n  geom_point(\n    aes(x = 1, y = HeightSumExp2$mean[1]),\n    size = 3,\n    pch = 17,\n    color = \"darkred\"\n  ) +\n  geom_point(\n    aes(x = 2, y = HeightSumExp2$mean[2]),\n    size = 3,\n    pch = 17,\n    color = \"darkred\"\n  ) +\n  ylab(\"Height (cm)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n## Repeat the experiment again\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseed <- 88605\nset.seed(seed)\nfem <- nhanesSub |>\n  filter(Gender == \"female\") |>\n  sample_n(size = 5)\n\nmal <- nhanesSub |>\n  filter(Gender == \"male\") |>\n  sample_n(size = 5)\n\nsamp3 <- rbind(fem, mal)\n\nHeightSumExp3 <- samp3 |>\n  group_by(Gender) |>\n  summarize_at(\"Height\",\n    list(mean = mean, sd = sd)\n  )\nHeightSumExp3\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Gender\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"mean\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"female\",\"2\":\"172.60\",\"3\":\"1.973575\"},{\"1\":\"male\",\"2\":\"167.78\",\"3\":\"2.837605\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsamp3 |>\n  ggplot(aes(x = Gender, y = Height)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_point(position = \"jitter\") +\n  geom_point(\n    aes(x = 1, y = HeightSumExp3$mean[1]),\n    size = 3,\n    pch = 17,\n    color = \"darkred\"\n  ) +\n  geom_point(\n    aes(x = 2, y = HeightSumExp3$mean[2]),\n    size = 3,\n    pch = 17,\n    color = \"darkred\"\n  ) +\n  ylab(\"Height (cm)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n### Repeat the experiment many times\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(15152)\n# Number of simulations and sample size per group\nnSim <- 10000\nnSamp <- 5\n\n# We filter the data in advance so that we do not have to repeat this every time\nfem <- nhanesSub |>\n  filter(Gender == \"female\")\n\nmal <- nhanesSub |>\n  filter(Gender == \"male\")\n\n# Simulation study\n# To be able to use fast functions, we first draw nSim samples and calculate everything afterwards.\n\nfemSamps <- malSamps <- matrix(NA, nrow = nSamp, ncol = nSim)\nfor (i in 1:nSim)\n{\n  femSamps[, i] <- sample(fem$Height, nSamp)\n  malSamps[, i] <- sample(mal$Height, nSamp)\n}\n\nres <- data.frame(\n  difference = colMeans(femSamps) - colMeans(malSamps)\n)\n\nres |>\n  ggplot(aes(y = difference)) +\n  geom_boxplot() +\n  ylab(\"Average difference (cm)\") +\n  xlab(\"\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n### Effect of increasing the sample size\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(15142)\n# Number of simulations and sample size per group\nnSim <- 10000\nnSamp <- 25\n\n# We filter the data in advance so that we do not have to repeat this every time\nfem <- nhanesSub |>\n  filter(Gender == \"female\")\n\nmal <- nhanesSub |>\n  filter(Gender == \"male\")\n\n# Simulation study\n# To be able to use fast functions, we first draw nSim samples and calculate everything afterwards.\n\nfemSamps <- malSamps <- matrix(NA, nrow = nSamp, ncol = nSim)\nfor (i in 1:nSim)\n{\n  femSamps[, i] <- sample(fem$Height, nSamp)\n  malSamps[, i] <- sample(mal$Height, nSamp)\n}\n\nres2 <- data.frame(\n  difference = colMeans(femSamps) - colMeans(malSamps)\n)\n\nres2$ng <- 25\nres$ng <- 5\n\nrbind(res, res2) |>\n  ggplot(aes(y = difference)) +\n  geom_boxplot() +\n  ylab(\"Average difference (cm)\") +\n  xlab(\"\") +\n  theme_minimal() +\n  facet_wrap(~ng)\n```\n\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n## Summary\n\n- We randomly selected different subjects in every sample.\n\n- As a result, the height measurements differ from sample to sample.\n\n- So do the estimated means and standard deviations.\n\n$\\rightarrow$ Consequently, our conclusions are also uncertain and can change from sample to sample.\n\n$\\rightarrow$ With statistics, we can control the probability of drawing wrong conclusions.\n\n- We also saw that we can estimate the true difference more precisely if we increase the sample size.\n\n$\\rightarrow$ The design of an experiment will thus determine how easily we can pick up the true difference with the sample.\n\n---\n\n# Salk Study\n\n- In 1916, the US experienced the first large epidemic of polio.\n- John Salk developed a vaccine with promising results in the lab in the early fifties.\n- In 1954, the National Foundation\nfor Infantile Paralysis (NFIP) has setup a large study to assess the effectiveness of the Salk vaccine.\n- Suppose that the NFIP would have vaccinated a large number of children in 1954 and would have observed that the polio incidence in 1954 was lower than in 1953. Could they have concluded that the vaccine was effective?\n\n---\n\n## NFIP Study\n\n### Design\n\n- Large simultaneous study with cases, vaccinated children, and controls,  non-vaccinated children.\n- All schools in districts with high polio incidence\n- Cases: children with consent for vaccination from second grade of primary school.\n- Controls: children from  first and third grade.\n\n### Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnfip <- data.frame(group = c(\"cases\", \"control\", \"noConcent\"), grade = c(\"g2\", \"g1g3\", \"g2\"), vaccin = c(\"yes\", \"no\", \"no\"), total = c(221998, 725173, 123605), polio = c(54, 391, 56))\nnfip$noPolio <- nfip$total - nfip$polio\nknitr::kable(nfip)\n```\n\n::: {.cell-output-display}\n\n\n|group     |grade |vaccin |  total| polio| noPolio|\n|:---------|:-----|:------|------:|-----:|-------:|\n|cases     |g2    |yes    | 221998|    54|  221944|\n|control   |g1g3  |no     | 725173|   391|  724782|\n|noConcent |g2    |no     | 123605|    56|  123549|\n\n\n:::\n:::\n\n\nCompare polio incidence?\n\n\n::: {.cell}\n\n:::\n\n\nWhat can we conclude?\n\n---\n\n## Confounding\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=50%}\n:::\n:::\n\n\n\n- We observe a lower polio (P) incidence for children for who no consent was given than for the children in the control group.\n\n- Consent for vaccination (V) was associated with the socio-economic status (S).\n\n- Children of lower socio-economic status were more resistant to the disease.\n\n- The groups of cases and controls are not comparable:\n    - difference in age,\n    - difference in socio-economic status and\n    - difference in susceptible for disease.\n\n---\n\n## Salk Study\n\n### Design\n\nA new study was conducted: Randomized double blind study\n\n  - Children are assigned at random to the control or case treatment arm after consent was given by the parents.\n  - Control: vaccination with placebo\n  - Treatment: vaccination with vaccine\n  - double blinding:\n    - parents did not know if their child was vaccinated or received the placebo\n    - care-giver/researchers did not know if the child was vaccinated  or received placebo\n\n---\n\n### Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalk <- data.frame(group = c(\"cases\", \"control\", \"noConcent\"), treatment = c(\"vaccine\", \"placebo\", \"none\"), total = c(\n  200745,\n  201229, 338778\n), polio = c(57, 142, 157))\nsalk$noPolio <- salk$total - salk$polio\nsalk$incidencePM <- round(salk$polio / salk$total * 1e6, 0)\nknitr::kable(salk)\n```\n\n::: {.cell-output-display}\n\n\n|group     |treatment |  total| polio| noPolio| incidencePM|\n|:---------|:---------|------:|-----:|-------:|-----------:|\n|cases     |vaccine   | 200745|    57|  200688|         284|\n|control   |placebo   | 201229|   142|  201087|         706|\n|noConcent |none      | 338778|   157|  338621|         463|\n\n\n:::\n:::\n\n\n- We observe a much larger effect now that the cases and the controls are comparable, incidence of 284  and 706 per million, respectively.\n\n- The polio incidence for children with no consent remains similar,  and 463 per million in the NFIP and Salk study, respectively.\n\n---\n\n# Role of Statistics in the Life Sciences\n\n- We have seen that\n    - it is important to carefully specify the scope of the study before the experiment,\n    - the sample size matters,\n    - we should be aware of confounding, and\n    - a proper control is required.\n\n$\\rightarrow$ Good experimental design is crucial!\n\n- We also observed that there is variability in the population and because we can only sample a small part of the population our results and conclusions are subjected to uncertainty.\n\n- Statistics is the science on\n    1. collecting (experimental design),\n    2. exploring (data exploration) and\n    3. learning from data and to generalize what we observe in the sample towards the population while quantifying, controlling and reporting variability and uncertainty (statistical modelling and statistical inference).\n\n- Therefore, statistics plays an important role in almost all sciences (e.g. column \"points of significance\" in Nature Methods. http://blogs.nature.com/methagora/2013/08/giving_statistics_the_attention_it_deserves.html)\n\n---\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01-intro_files/figure-html/pop2Samp2Pop-1.png){fig-align='center' width=80%}\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}