{
  "hash": "a09bf6d5cf1cc6a300233d4ebb708a3c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exeercise 6.2: Linear regression on the FEV dataset - solution\"\nauthor: \"Lieven Clement and Jeroen Gilis\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\n---\n\nAs an exercise on linear regression, we will analyse the FEV dataset.\n\n# The FEV dataset\n\nThe FEV, which is an acronym for forced expiratory volume,\nis a measure of how much air a person can exhale (in liters)\nduring a forced breath. In this dataset, the FEV of 606 children,\nbetween the ages of 6 and 17, were measured. The dataset\nalso provides additional information on these children:\ntheir `age`, their `height`, their `gender` and, most\nimportantly, whether the child is a smoker or a non-smoker.\n\nThe overarching goal of this experiment was to find out if\nsmoking has an effect on the FEV of children.\n\n# Load the required libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n# Import data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfev <- read_tsv(\"https://raw.githubusercontent.com/statOmics/PSLSData/main/fev.txt\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 606 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \"\\t\"\nchr (1): gender\ndbl (4): age, fev, height, smoking\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(fev)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"age\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"fev\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"height\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gender\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"smoking\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"9\",\"2\":\"1.708\",\"3\":\"57.0\",\"4\":\"f\",\"5\":\"0\"},{\"1\":\"8\",\"2\":\"1.724\",\"3\":\"67.5\",\"4\":\"f\",\"5\":\"0\"},{\"1\":\"7\",\"2\":\"1.720\",\"3\":\"54.5\",\"4\":\"f\",\"5\":\"0\"},{\"1\":\"9\",\"2\":\"1.558\",\"3\":\"53.0\",\"4\":\"m\",\"5\":\"0\"},{\"1\":\"9\",\"2\":\"1.895\",\"3\":\"57.0\",\"4\":\"m\",\"5\":\"0\"},{\"1\":\"8\",\"2\":\"2.336\",\"3\":\"61.0\",\"4\":\"f\",\"5\":\"0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThere are a few things in the formatting of the\ndata that can be improved upon:\n\n1. Both the `gender` and `smoking` can be transformed to\nfactors.\n\n2. The `height` variable is written in inches. Assuming that\nthis audience is mainly European, inches are hard to\ninterpret. Let's add a new column, `height_cm`, with the values\nconverted to centimeter using the `mutate` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfev <- fev |>\n  mutate(gender = as.factor(gender)) |>\n  mutate(smoking = as.factor(smoking)) |>\n  mutate(height_cm = height * 2.54)\n\nhead(fev)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"age\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"fev\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"height\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gender\"],\"name\":[4],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"smoking\"],\"name\":[5],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"height_cm\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"9\",\"2\":\"1.708\",\"3\":\"57.0\",\"4\":\"f\",\"5\":\"0\",\"6\":\"144.78\"},{\"1\":\"8\",\"2\":\"1.724\",\"3\":\"67.5\",\"4\":\"f\",\"5\":\"0\",\"6\":\"171.45\"},{\"1\":\"7\",\"2\":\"1.720\",\"3\":\"54.5\",\"4\":\"f\",\"5\":\"0\",\"6\":\"138.43\"},{\"1\":\"9\",\"2\":\"1.558\",\"3\":\"53.0\",\"4\":\"m\",\"5\":\"0\",\"6\":\"134.62\"},{\"1\":\"9\",\"2\":\"1.895\",\"3\":\"57.0\",\"4\":\"m\",\"5\":\"0\",\"6\":\"144.78\"},{\"1\":\"8\",\"2\":\"2.336\",\"3\":\"61.0\",\"4\":\"f\",\"5\":\"0\",\"6\":\"154.94\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Data Exploration\n\nNow, let's make a first explorative boxplot, showing\nonly the FEV for both smoking categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfev |>\n  ggplot(aes(x = smoking, y = fev, fill = smoking)) +\n  scale_fill_manual(values = c(\"dimgrey\", \"firebrick\")) +\n  theme_bw() +\n  geom_boxplot(outlier.shape = NA) +\n  geom_jitter(width = 0.2, size = 0.1) +\n  ggtitle(\"Boxplot of FEV versus smoking\") +\n  ylab(\"fev (l)\") +\n  xlab(\"smoking status\")\n```\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nDid you expect these results?\n\nIt appears that children that smoke have a higher\nmedian FEV than children that do not smoke.\nShould we change legislations worldwide and make\nsmoking obligatory for children?\n\nMaybe there is something else going on in the data.\nNow, we will generate a similar plot, but we will\nstratify the data based on age (age as factor).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfev |>\n  ggplot(aes(\n    x = age,\n    y = fev,\n    color = smoking,\n    pch = smoking\n  )) +\n  facet_grid(cols = vars(smoking)) +\n  theme_bw() +\n  scale_color_manual(values = c(\"dimgrey\", \"firebrick\")) +\n  geom_point(fill = \"white\") +\n  ggtitle(\"Boxplot of FEV versus smoking, stratified on age\") +\n  ylab(\"fev (l)\") +\n  xlab(\"smoking status\")\n```\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThis plot seems to already give us a more\nplausible picture. First, it seems that we do not have\nany smoking children of ages 6, 7 or 8. Second, when\nlooking at the results per age \"category\", it seems\nno longer the case that smokers have a much higher FEV\nthan non-smokers; for the higher ages, the contrary\nseems true.\n\nThis shows that taking into account confounders\n(in this case) is crucial! If we simply analyse the dataset based on\nthe smoking status and FEV values only, our inference might\nbe incorrect.\n\nCan we provide an even better visualization of the data, taking\ninto account more useful explanatory variables with respect\nto the FEV?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfev |>\n  ggplot(aes(\n    x = age,\n    y = fev,\n    color = smoking,\n    pch = smoking\n  )) +\n  facet_grid(cols = vars(smoking), rows = vars(gender)) +\n  theme_bw() +\n  scale_color_manual(values = c(\"dimgrey\", \"firebrick\")) +\n  geom_point(fill = \"white\") +\n  ggtitle(\"Boxplot of FEV versus smoking, stratified on age\") +\n  ylab(\"fev (l)\") +\n  xlab(\"smoking status\")\n```\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis plot holds one extra level of information, the gender\nof the child. Especially for higher ages, the median FEV\nis higher for males as compared to females.\n\nThe only source of information that is lacking is `height`.\nTo look at the effect of height, we could simply make a\nscatterplot displaying the FEV in function of a child's\nheight (in cm). Additionally, we could color the dots based\non gender.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfev |>\n  ggplot(aes(x = height_cm, y = fev, color = gender)) +\n  geom_point() +\n  scale_color_manual(values = c(\"darkorchid\", \"olivedrab4\")) +\n  theme_bw() +\n  ggtitle(\"Boxplot of FEV versus height\") +\n  ylab(\"fev (l)\") +\n  xlab(\"height (cm)\")\n```\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThere is a clear relationship between height and FEV.\nIn addition, we see that for the large height values\n(>175cm), we mainly find male subjects.\n\n# Linear regression analysis\n\n## Assumptions of linear regression\n\nList the assumptions:\n\n1. The observations are independent\n2. Linearity between the response and predictor variable\n3. The residues of the model must be normally distributed\n4. Homoscedasticity of the data\n\nThe subjects are sampled randomly from the population and can be assumed to be\nindependent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(fev ~ smoking, data = fev)\n\n## display the diagnostic plots of the model\nplot(model)\n```\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-8-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-8-4.png){width=672}\n:::\n:::\n\n\nWe have four diagnostic plots:\n\n### Linearity with the Residuals vs fitted plot\n\n- predictor of predictions $\\hat\\beta_0+\\hat\\beta_1 x$ on $X$-axis\n- *residuals* on $Y$-as\n$$e_i=y_i-\\hat{g}(x_i)=y_i-\\hat\\beta_0-\\hat\\beta_1\\times x_i,$$\nHowever, because smoking is a factor, the predictor variable $x$ in the model is\na dummy variable that can only take two values (0: non-smoking or 1: smoking).\n\n### Normal Q-Q\n\n- QQ-plot of the residuals $e_i$.\n\nThe residuals of the linear regression model should be normally\ndistributed. Based on the second diagnostic plot, the normality\nassumption is not met.\n\n### Homoscedasticity\n\n- Square-root of the absolute value of standardized residuals\nin function of the fitted values\n\nTo meet the third assumption of linear regression, the variance\non the _Square-root of the absolute value of standardized residuals_\nmust be similar over the entire range of fitted values.\n\nHowever, because smoking is a factor the predictor variable $x$ in the model is\na dummy variable that can only take two values (0: non-smoking or 1: smoking).\nSo it is better to check this assumption using boxplots. In the data exploration\nwe noticed that there is no big difference in the IQR range between smokers and\nnon smokers.\n\n## Log transformation\n\nThe normality assumption was not met. One possible way resolve this is by\nrelying on the central limit theorem; given the large number of observations in\nthis dataset, we would still be allowed to perform that assume normality.\nAnother option is to try a log-transformation of the data. In this example,\nlog-transforming the data makes perfect sense; we can then interpret difference\nin terms of log transformed fold changes, which is sensible for volume data.\n\nHere, we fit the log-linear model and generate diagnostic plots in order to\nassess the assumptions for linear regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog.model <- lm(fev |> log2() ~ smoking, data = fev)\nplot(log.model)\n```\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-9-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06_2_FEV_sol_files/figure-html/unnamed-chunk-9-4.png){width=672}\n:::\n:::\n\n\nUpon log-transformation, all the required assumption are met.\n\nLook at the output of the log-linear model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(log.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log2(fev) ~ smoking, data = fev)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.11108 -0.28248  0.00693  0.28172  1.20290 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.33141    0.01833  72.649  < 2e-16 ***\nsmoking1     0.32592    0.05776   5.642 2.58e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4278 on 604 degrees of freedom\nMultiple R-squared:  0.05007,\tAdjusted R-squared:  0.0485 \nF-statistic: 31.84 on 1 and 604 DF,  p-value: 2.582e-08\n```\n\n\n:::\n:::\n\n\nCompute the 95% confidence interval on the model parameters:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(log.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %    97.5 %\n(Intercept) 1.2954196 1.3674032\nsmoking1    0.2124768 0.4393616\n```\n\n\n:::\n:::\n\n\n# Conclusion\n\n## Interpretation on the log scale\n\nCurrently, all the outcomes should be interpreted on the log-scale.\nIndeed, since we are now modelling  _the $\\log_{2}$ FEV_\n\nWe may interpret the output as follows:\n\n- The slope:\n\nSmoking pupils on average have a log$_{2}$ FEV that is on average\n0.33 higher than non-smoking pupils (95% CI [0.21, 0.44]).\nThis difference is extremely significant on the 5% significance level (p << 0.001).\n\n- The intercept:\n\nThe average log$_{2}$ of FEV for children that\ndo not smoke is 0.33 (95% CI [1.3, 1.37]).\n\n## Interpretation on the original scale\n\nThe interpretation the log-scale is quite difficult. However, if we backtransform we get an interpretation in terms of geometric means and fold changes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2^(log.model$coefficients)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)    smoking1 \n   2.516487    1.253463 \n```\n\n\n:::\n:::\n\n\nand of their confidence intervals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2^(confint(log.model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               2.5 %   97.5 %\n(Intercept) 2.454484 2.580058\nsmoking1    1.158676 1.356004\n```\n\n\n:::\n:::\n\n\nNow, we can interpret the results in terms of the geometric mean:\n\n- The slope:\n\nThe geometric mean of the forced expiratory volume is a factor\n1.25 larger for smoking\npupil than for non-smoking pupil\n(95% CI [1.16, 1.36]).\nThis difference is extremely significant (p << 0.001).\n\nNote that we can also interpret as follows because the factor is between 1\nand 2.\n\nThe the forced expiratory volume is on average\n25% larger for\nsmoking pupils than for non-smoking pupils\n(95% CI [16, 36]).\n\n**NOTE THAT THE CONCLUSION IS WRONG BECAUSE THE TWO GROUPS OF PUPILS ARE NOT**\n**COMPARABLE. THERE IS CONFOUNDING!**\n\nIndeed, the FEV study is an observational study: smoking pupils are on average\nolder than non-smoking pupils and age is associated with both the smoking\nbehavior and long capacity. If we do not account for age the age effect is\npartially captured in the estimated effect for smoking!\n\n- The intercept:\n\nThe geometric mean of the forced experatory volume for non-smoking pupils\nis  2.52l\n(95% CI [2.45, 2.58]l).\nThis value is extermely significantly larger than 1l (p <<< 0.001). Note, that\nthe statistical test on the intercept is typically not reported.\n\n\nIn the tutorial of multiple regression, we will revisit this exercise and do\nan analysis where we correct for this confounder. More specifically, we will\nthere study  the association between smoking and FEV while accounting for\ndifferences in the age, height and gender of the children.\n",
    "supporting": [
      "06_2_FEV_sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}