{
  "hash": "0b1e203ebc35af15669222a01f30910c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"6. Simple linear regression\"\nauthor: \"Lieven Clement\"\nsubtitle: \"statOmics, Ghent University (https://statomics.github.io)\"\nformat:\n  html: default\n  pdf: default\n---\n\n<a rel=\"license\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png\" /></a>\n\n\n\n\n# Breast cancer dataset\n\n\n- Subset of study https://doi.org/10.1093/jnci/djj052\n\n- 32 breast cancer patients with estrogen recepter positieve tumor that had tamoxifen chemotherapy. Variabels:\n\n    - grade: histological grade of tumor (grade 1 vs 3),\n    - node: lymph node status  (0: not affected, 1: lymph nodes affected and removed),\n    - size: tumor size in cm,\n    - ESR1 and S100A8 gene expression in tumor biopsy (microarray technology)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca <- read_csv(\"https://raw.githubusercontent.com/GTPB/PSLS20/master/data/breastcancer.csv\")\nbrca\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"sample_name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"filename\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"treatment\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"er\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"grade\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"node\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"size\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"age\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"ESR1\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"S100A8\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"OXFT_209\",\"2\":\"gsm65344.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"1\",\"7\":\"2.5\",\"8\":\"66\",\"9\":\"1939.1990\",\"10\":\"207.19682\"},{\"1\":\"OXFT_1769\",\"2\":\"gsm65345.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"3.5\",\"8\":\"86\",\"9\":\"2751.9521\",\"10\":\"36.98611\"},{\"1\":\"OXFT_2093\",\"2\":\"gsm65347.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"2.2\",\"8\":\"74\",\"9\":\"379.1951\",\"10\":\"2364.18306\"},{\"1\":\"OXFT_1770\",\"2\":\"gsm65348.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"1.7\",\"8\":\"69\",\"9\":\"2531.7473\",\"10\":\"23.61504\"},{\"1\":\"OXFT_1342\",\"2\":\"gsm65350.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"2.5\",\"8\":\"62\",\"9\":\"141.0508\",\"10\":\"3218.74109\"},{\"1\":\"OXFT_2338\",\"2\":\"gsm65352.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"1\",\"7\":\"1.4\",\"8\":\"63\",\"9\":\"1495.4213\",\"10\":\"107.56868\"},{\"1\":\"OXFT_2341\",\"2\":\"gsm65353.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"3.3\",\"8\":\"76\",\"9\":\"3405.7294\",\"10\":\"13.99662\"},{\"1\":\"OXFT_1902\",\"2\":\"gsm65354.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"2.4\",\"8\":\"61\",\"9\":\"2812.8034\",\"10\":\"68.38262\"},{\"1\":\"OXFT_1982\",\"2\":\"gsm65355.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"0\",\"7\":\"1.7\",\"8\":\"62\",\"9\":\"949.9327\",\"10\":\"74.18828\"},{\"1\":\"OXFT_5210\",\"2\":\"gsm65356.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"3.5\",\"8\":\"65\",\"9\":\"1052.9142\",\"10\":\"182.32133\"},{\"1\":\"OXFT_2027\",\"2\":\"gsm65357.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"1.4\",\"8\":\"63\",\"9\":\"1838.7705\",\"10\":\"27.51279\"},{\"1\":\"OXFT_1133\",\"2\":\"gsm65358.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"0\",\"7\":\"2.0\",\"8\":\"70\",\"9\":\"3707.8010\",\"10\":\"26.70991\"},{\"1\":\"OXFT_1441\",\"2\":\"gsm65359.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"3.2\",\"8\":\"78\",\"9\":\"2240.4095\",\"10\":\"26.28934\"},{\"1\":\"OXFT_1432\",\"2\":\"gsm65360.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"0\",\"7\":\"2.0\",\"8\":\"71\",\"9\":\"2698.5507\",\"10\":\"56.30524\"},{\"1\":\"OXFT_1125\",\"2\":\"gsm65361.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"0\",\"7\":\"1.6\",\"8\":\"68\",\"9\":\"2459.7793\",\"10\":\"14.17095\"},{\"1\":\"OXFT_1070\",\"2\":\"gsm65362.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"0\",\"7\":\"0.2\",\"8\":\"45\",\"9\":\"689.2472\",\"10\":\"282.68343\"},{\"1\":\"OXFT_700\",\"2\":\"gsm65363.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"0\",\"7\":\"3.5\",\"8\":\"57\",\"9\":\"2625.8917\",\"10\":\"18.67950\"},{\"1\":\"OXFT_742\",\"2\":\"gsm65364.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"1\",\"7\":\"1.7\",\"8\":\"67\",\"9\":\"1665.5595\",\"10\":\"18.11686\"},{\"1\":\"OXFT_738\",\"2\":\"gsm65365.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"1.8\",\"8\":\"74\",\"9\":\"3336.0416\",\"10\":\"26.00373\"},{\"1\":\"OXFT_669\",\"2\":\"gsm65366.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"4.0\",\"8\":\"60\",\"9\":\"3057.5784\",\"10\":\"22.59829\"},{\"1\":\"OXFT_3597\",\"2\":\"gsm65367.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"1.1\",\"8\":\"60\",\"9\":\"164.2995\",\"10\":\"6225.02863\"},{\"1\":\"OXFT_638\",\"2\":\"gsm65368.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"2.3\",\"8\":\"63\",\"9\":\"2909.6771\",\"10\":\"78.53095\"},{\"1\":\"OXFT_2188\",\"2\":\"gsm65369.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"3.3\",\"8\":\"69\",\"9\":\"1925.8788\",\"10\":\"82.15699\"},{\"1\":\"OXFT_2069\",\"2\":\"gsm65370.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"1\",\"7\":\"2.3\",\"8\":\"66\",\"9\":\"1864.3941\",\"10\":\"65.50852\"},{\"1\":\"OXFT_596\",\"2\":\"gsm65371.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"3.0\",\"8\":\"66\",\"9\":\"3037.2311\",\"10\":\"21.68372\"},{\"1\":\"OXFT_619\",\"2\":\"gsm65372.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"1.9\",\"8\":\"49\",\"9\":\"1449.9249\",\"10\":\"27.11254\"},{\"1\":\"OXFT_680\",\"2\":\"gsm65373.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"4.5\",\"8\":\"61\",\"9\":\"3967.2038\",\"10\":\"26.73890\"},{\"1\":\"OXFT_443\",\"2\":\"gsm65374.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"0\",\"7\":\"2.1\",\"8\":\"45\",\"9\":\"396.0846\",\"10\":\"219.23261\"},{\"1\":\"OXFT_1579\",\"2\":\"gsm65376.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"0\",\"7\":\"2.0\",\"8\":\"40\",\"9\":\"976.9015\",\"10\":\"116.66995\"},{\"1\":\"OXFT_4904\",\"2\":\"gsm65377.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\",\"7\":\"5.0\",\"8\":\"69\",\"9\":\"2036.9399\",\"10\":\"102.14641\"},{\"1\":\"OXFT_511\",\"2\":\"gsm65378.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"3\",\"6\":\"1\",\"7\":\"5.5\",\"8\":\"64\",\"9\":\"1004.3520\",\"10\":\"294.16364\"},{\"1\":\"OXFT_736\",\"2\":\"gsm65379.cel.gz\",\"3\":\"tamoxifen\",\"4\":\"1\",\"5\":\"1\",\"6\":\"0\",\"7\":\"1.4\",\"8\":\"48\",\"9\":\"2163.5382\",\"10\":\"45.28436\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n- For didactical reasons we first remove 3 outliers in the S100A8 expression data.\n- Later in the lecture we will show how to properly deal with all data.\n\n\n\n::: {.cell layout-align=\"center\" warnings='false'}\n\n```{.r .cell-code}\nbrca |> ggplot(aes(x = \"\", y = S100A8)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GGally)\nbrcaSubset <- brca |> filter(S100A8 < 2000)\nbrcaSubset[, -(1:4)] |> ggpairs()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Association between ESR1 and S100A8 expression\n\n- ESR1 in $\\pm$ 75% of breast cancer tumors.\n\n    - Expression of ER gene positive for treatment: tumor responds to hormone therapy\n    - Tamoxifen interacts with ER and modulates gene expression.\n\n- Proteins of S100 family often dysregulated in cancer\n\n- S100A8 expression represses immune systeem in tumor en creates an environment of inflamation that promotes tumor growth.\n\n- Assess association between ESR1 and S100A8 expression.\n\n1. pipe dataset to ggplot\n2. select data `ggplot(aes(x=ESR1,y=S100A8))`\n3. add points `geom_point()`\n4. add smooth line `geom_smooth()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbrcaSubset |>\n  ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrcaSubset |>\n  select(\"ESR1\",\"S100A8\") |>\n  cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             ESR1     S100A8\nESR1    1.0000000 -0.6854281\nS100A8 -0.6854281  1.0000000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrcaSubset |> \n  select(\"ESR1\",\"S100A8\") |> \n  cor(method=\"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             ESR1     S100A8\nESR1    1.0000000 -0.6428571\nS100A8 -0.6428571  1.0000000\n```\n\n\n:::\n:::\n\n\n# Lineair Regression\n\n- Statistical method to assess association between two variables $(X_i, Y_i)$, measured on each subject $i = 1, ..., n$.\n\n- Gene expression example\n\n    - Response Y : S100A8 expression\n    - Predictor X: ESR1 expression\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbrcaSubset |>\n  ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_smooth(se = FALSE, col = \"grey\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Model\n\n- For fixed $X$, $Y$ does not necessarly has the same value\n\n$$\\text{observation = signal + noise}$$\n\n$$Y_i=g(X_i)+\\epsilon_i$$\n- We define $g(x)$ als the expected outcome for subjects with $X_i=x$\n\n$$E[Y_i|X_i=x]=g(x)$$\n\nHence, $\\epsilon_i$ is on average 0 for subjects with same  $X_i$:\n$$E[\\epsilon_i|X_i]=0$$\n\n## Lineair regression\n\n- To obtain *accurate* and *interpretable* results one often choose $g(x)$ to be a linear function with unknown parameter.\n\n$$E(Y|X=x)=\\beta_0 + \\beta_1 x$$\n\nunknown **intercept** $\\beta_0$ and\n**slope** $\\beta_1$.\n\n- Lineair model imposes an *assumption* on the distribution of $X$ and $Y$, which can be invalid.\n\n- *Efficient data-analysis*: because it uses all observations to learn on the expected outcome for $X=x$.\n\n\n## Use\n\n- *Prediction*: when $Y$ is unknown but $X$ is known we can predict $Y$ using\n\n$$E(Y|X=x)=\\beta_0 + \\beta_1 x$$\n\n- *Association*: biological relation between variable $X$ and response $Y$\n- *Intercept:* $E(Y|X=0)=\\beta_0$\n\\vspace{10pt}\n- *Slope*:\n\\begin{eqnarray*}\nE(Y|X=x+\\delta)-E(Y|X=x)&=&\\beta_0 + \\beta_1 (x+\\delta) -\\beta_0-\\beta_1 x\\\\\n&=& \\beta_1\\delta\n\\end{eqnarray*}\n\n$\\beta_1=$ difference in mean outcome for subjects that differ in one unit of the predictor  $X$.\n\n# Parameter estimation\n\n- Least squares\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbrcaSubset |>\n  ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_smooth(se = FALSE, col = \"grey\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n- Parameters $\\beta_0$ en $\\beta_1$ are unknown.\n\n- Estimate them using sample\n\n- Best fitting line\n\n    - Point on regression line for a given $x_i$: $(x_i, \\beta_0 + \\beta_1 x_i)$ as close as possible $(x_i, y_i)$\n    - Choose $\\beta_0$ and $\\beta_1$ so that the sum between predicted and observed points becomes as small as possible.\n\n$$SSE=\\sum_{i=1}^n (y_i-\\beta_0-\\beta_1 x_i)^2=\\sum_{i=1}^n e_i^2$$\n\nwith residuals $e_i$ the vertical distances from the observations to the fitted regression line\n\n## Estimators that minimise SSE\n\n$$\\hat{\\beta_1}= \\frac{\\sum\\limits_{i=1}^n (y_i-\\bar y)(x_i-\\bar x)}{\\sum\\limits_{i=1}^n (x_i-\\bar x_i)^2}=\\frac{\\mbox{cor}(x,y)s_y}{s_x} $$\n\n$$\\hat{\\beta_0}=\\bar y - \\hat{\\beta}_1 \\bar x $$\n\nNote, that the slope of the least squares fit is proportional to the correlation between the response and the predictor.\n\nFitted model allows to:\n\n  - predict the response for subjects with a given value $x$ for the predictor:\n$$\\text{E} [ Y | X = x]=\\hat{\\beta}_0+\\hat{\\beta}_1x$$\n\n  - Assess how the mean response differs between two groups of subjects that differ $\\delta$ units in the predictor:\n\n$$\\text{E}\\left[Y|X=x+\\delta\\right]-\\text{E}\\left[Y|X=x\\right]= \\hat{\\beta}_1\\delta$$\n\n### Breast cancer example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm1 <- lm(S100A8 ~ ESR1, brcaSubset)\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = S100A8 ~ ESR1, data = brcaSubset)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-95.43 -34.81  -6.79  34.23 145.21 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 208.47145   28.57207   7.296 7.56e-08 ***\nESR1         -0.05926    0.01212  -4.891 4.08e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 59.91 on 27 degrees of freedom\nMultiple R-squared:  0.4698,\tAdjusted R-squared:  0.4502 \nF-statistic: 23.93 on 1 and 27 DF,  p-value: 4.078e-05\n```\n\n\n:::\n:::\n\n\n$$E(Y|X=x)=208.47-0.059 x$$\n\n- Expected S100A8 expression is on average  59 units lower for patients with ESR1 expression level that is 1000 units higher\n\n- Expected S100A8 expression level for patients with an ESR1 expression level of 2000:\n\n$$208.47-0.059\\times 2000=89.94$$\n\n- Expected S100A8 expression level for patients with an ESR1 expression level of 4000:\n\n$$208.47-0.059\\times 4000=-28.58$$\n- Be careful when you extrapolate! (We can only assess the assumption of linearity within the range of the data).\n\n# Statistical inference\n\nTo draw conclusions based on the regression model\n\n$$E(Y|X)=\\beta_0+\\beta_1 X$$\nwe need to know\n\n- How the least squares parameter estimators vary from sample to sample, and\n- how they deviate under the null hypothesis that there is no association between predictor and response\n- Requires a statistical model\n\n- Model the distribution of $Y$ given $X$ explicitly: f_{Y|X}(y)\n\n## Modelling distribution of Y?\n\n1. Besides *Linearity* we need additional assumptions!\n2. *Independence*: Observations $(X_1,Y_1), ...,  (X_n,Y_n)$ are made for n independent subjects (is required to estimate the variance)\n3. *Homoscedasticity* or *equal variances*: observations vary with equal mean around the regression line\n    - Residuals $\\epsilon_i$ have equal variance for each $X_i=x$\n    - $\\text{var}(Y\\vert X=x) = \\sigma^2$ for each $X=x$\n    - $\\sigma$ is referred to as the *residual standard deviation*\n4. *Normality*: the residuals $\\epsilon_i$ are normally distributed\n\n![](https://raw.githubusercontent.com/GTPB/PSLS20/gh-pages/assets/figs/RegModel3.png){width=100%}\n\n\n- Given 2, 3 and 4\n$$\\epsilon_i \\text{ i.i.d.} N(0,\\sigma^2).$$\n- Together with 1 this implies:\n$$Y_i\\vert X_i\\sim N(\\beta_0+\\beta_1 X_i,\\sigma^2),$$\n\n- We can show that given these assumption\n$$\\sigma^2_{\\hat{\\beta}_0}=\\frac{\\sum\\limits_{i=1}^n X^2_i}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2} \\times\\frac{\\sigma^2}{n} \\text{ en } \\sigma^2_{\\hat{\\beta}_1}=\\frac{\\sigma^2}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2}$$\n- and the parameter estimators are also normally distributed\n$$\\hat\\beta_0 \\sim N\\left(\\beta_0,\\sigma^2_{\\hat \\beta_0}\\right) \\text{ en } \\hat\\beta_1 \\sim N\\left(\\beta_1,\\sigma^2_{\\hat \\beta_1}\\right)$$\n\n## High spread of $X$ improves the precision\n\n$$\\sigma^2_{\\hat{\\beta}_1}=\\frac{\\sigma^2}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2}$$\n\n![](https://raw.githubusercontent.com/GTPB/PSLS20/gh-pages/assets/figs/spread.png){ width=100% }\n\n- Conditional variance ($\\sigma^2$) is unknown\n- Estimate using *mean squared error* (MSE)\n$$\\hat\\sigma^2=MSE=\\frac{\\sum\\limits_{i=1}^n \\left(y_i-\\hat\\beta_0-\\hat\\beta_1\\times x_i\\right)^2}{n-2}=\\frac{\\sum\\limits_{i=1}^n e^2_i}{n-2}.$$\n- This estimator is based on independence (assumption 2) and equality of the variance (assumption 3).\n- Devide by $n-2$\n\nUpon the estimation of $\\sigma^2$ we obtain following standard errors:\n\n$$\\text{SE}_{\\hat{\\beta}_0}=\\hat\\sigma_{\\hat{\\beta}_0}=\\sqrt{\\frac{\\sum\\limits_{i=1}^n X^2_i}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2} \\times\\frac{\\text{MSE}}{n}} \\text{ en } \\text{SE}_{\\hat{\\beta}_1}=\\hat\\sigma_{\\hat{\\beta}_1}=\\sqrt{\\frac{\\text{MSE}}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2}}$$\n\n- Again we can construct tests and confidence intervals using\n$$T=\\frac{\\hat{\\beta}_k-\\beta_k}{SE(\\hat{\\beta}_k)} \\text{ with } k=1,2.$$\n\n- If all assumptions are valid $T$ follows t-verdeling with n-2 degrees of freedom.\n\\vspace{15pt}\n- If no normality, but independence, linearity, equality of mean and large dataset\n\n$$\\rightarrow \\text{Central Limit theorem}$$\n\n\n### Breast cancer example\n\n- Negative association between S100A8 and ESR1 gene expression.\n\n- Generalize effect in sample to population using the confidence interval on the mean:\n$$[\\hat\\beta_1 - t_{n-2,\\alpha/2} \\text{SE}_{\\hat\\beta_1},\\hat\\beta_1 + t_{n-2,\\alpha/2} \\text{SE}_{\\hat\\beta_1}]$$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   2.5 %       97.5 %\n(Intercept) 149.84639096 267.09649989\nESR1         -0.08412397  -0.03440378\n```\n\n\n:::\n:::\n\n\n- Negative association is significant on 5% significance level.\n\n\n## Hypothesis test\n\n- Translate the research question to assess the association between the S100A8 and ESR1 gene expression to parameters in the model.\n\n- Under the null hypothesis of the absence of an association in the expression of both genes:\n$$H_0: \\beta_1=0$$\n\n- Under the alternative hypothesis, there is an association between the expression of both genes :\n$$H_1: \\beta_1\\neq0$$\n\\vspace{15pt}\n- Test statistic\n$$T=\\frac{\\hat{\\beta}_1-0}{SE(\\hat{\\beta}_k)}$$\n\\vspace{15pt}\n- Under $H_0$ the statistics follows a t-distribution with n-2 degrees of freedom.\n\n### BRCA dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = S100A8 ~ ESR1, data = brcaSubset)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-95.43 -34.81  -6.79  34.23 145.21 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 208.47145   28.57207   7.296 7.56e-08 ***\nESR1         -0.05926    0.01212  -4.891 4.08e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 59.91 on 27 degrees of freedom\nMultiple R-squared:  0.4698,\tAdjusted R-squared:  0.4502 \nF-statistic: 23.93 on 1 and 27 DF,  p-value: 4.078e-05\n```\n\n\n:::\n:::\n\n\n\n- The association between the S100A8 and ESR1 expression is extremely significant  (p<<0.001).\n- But, we first have to check all assumptions!\n- Otherwise the conclusions based on the statistical test and the CI can be incorrect.\n\n# Assess assumptions\n\n- Independence: design\n- Linearity: inference is useless if the association is not linear\n- Homoscedasticity: inference/p-value is incorrect if data are heteroscedastic\n- Normality: inference/p-value is incorrect if data are not normally distributed in small samples\n\n\n## Linearity\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbrcaSubset |>\n  ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_smooth(se = FALSE, col = \"grey\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n### Residual analysis\n\n- Assumption of linearity is typically assessed using *residual plot*. (Especially if the lineair model has multiple covariates, later chapters)\n- predictor of predictions $\\hat\\beta_0+\\hat\\beta_1 x$ on $X$-axis\n- *residuals* on $Y$-as\n$$e_i=y_i-\\hat{g}(x_i)=y_i-\\hat\\beta_0-\\hat\\beta_1\\times x_i,$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(lm1)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-13-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-13-4.png){width=672}\n:::\n:::\n\n\n## Homoscedasticity (equal variances)\n\n- Residuals and squared residuals cary information on the residual variability\n\n- Association with predictors $\\rightarrow$ indication of heteroscedasticity.\n- Scatterplot of $e_i$ vs $x_i$ or predictions $\\hat \\beta_0+ \\hat \\beta_1 x_i$.\n- Scatterplot van standardized residual versus $x_i$ or predictions.\n\n## Normality\n\n- If the sample size is large the estimators are normally distributed even if the observations are not normally distributed: central limit theorem\n- How many observations? $\\rightarrow$ depends on shape and magnitude of deviations\n- Assumption: Data are Normally distributed conditional on X:\n$$Y_i\\vert X_i\\sim N(\\beta_0+\\beta_1X_i,\\sigma^2)$$\n- QQ-plot of response Y is misleading and useless: distribution of $Y_i$ are different because they have a different conditional mean!\n\n- QQ-plot of the residuals $e_i$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(lm1, which = 2)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n# Invalid assumptions\n\n- Transformation of predictor does not change distribution of Y for given X:\n\n    - not useful to obtain homoscedasticity or Normal distribution\n    - useful for linearity when normality and homoscedasticity are valid\n    - Often inclusion of higher order terms: $X^2$, $X^3$, ...\n    $$Y_i=\\beta_0+\\beta_1X_i+\\beta_2X_i^2+ ... + \\epsilon_i$$\n\n\n- Transformation of response Y can be useful to obtain normality and homoscedasticity\n\n-  $\\sqrt(Y)$, $\\log(Y)$, 1/Y, ...\n\n\n## Breast cancer example\n\nProblems with\n\n- heteroscedasticity\n- possibly deviations from normality (skewed to the right)\n- negative concentration predictions are theoretically impossible\n- non-linearity\n\nThis is often the case for concentration and intensity measurements\n\n- These are often log-normal distributed (normal distribution upon log-transformatie)\n- We also observed a kind of exponential relation with the smoother\n- In gene expression literature often $\\log_2$ transformation is adopted\n- gene-expression on log scale: differences on log scale are fold changes on original scale!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca |> ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca |> ggplot(aes(x = ESR1 |> log2(), y = S100A8 |> log2())) +\n  geom_point() +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm2 <- lm(S100A8 |> log2() ~ ESR1 |> log2(), brca)\nplot(lm2)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-18-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-18-4.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log2(S100A8) ~ log2(ESR1), data = brca)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.94279 -0.66537  0.08124  0.68468  1.92714 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   23.401      1.603   14.60 3.57e-15 ***\nlog2(ESR1)    -1.615      0.150  -10.76 8.07e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.026 on 30 degrees of freedom\nMultiple R-squared:  0.7942,\tAdjusted R-squared:  0.7874 \nF-statistic: 115.8 on 1 and 30 DF,  p-value: 8.07e-12\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %    97.5 %\n(Intercept) 20.128645 26.674023\nlog2(ESR1)  -1.921047 -1.308185\n```\n\n\n:::\n:::\n\n\n\n### Interpretation 1\n\nA patient with an ESR1 expression that is one unit on $\\log_2$ scale higher than that of another patient on average has a $\\log_2$ expression for S100A8 that is 1.61 units lower (95% CI [-1.92,-1.31]).\n\n$$\\log_2 \\hat\\mu_1=23.401  -1.615 \\times \\text{logESR}_1,\\text{ } \\log_2 \\hat\\mu_2=23.401  -1.615 \\times \\text{logESR}_2 $$\n$$\\log_2 \\hat\\mu_2-\\log_2 \\hat\\mu_1=  -1.615 (\\log_2 \\text{ESR}_2-\\log_2 \\text{ESR}_1) = -1.615 \\times 1 = -1.615$$\n\n### Interpretation 2\n\nModel on log-scale: upon back-transformation we obtain geometric means\n\n\\begin{eqnarray*}\n\\sum\\limits_{i=1}^n \\frac{\\log x_i}{n}&=&\\frac{\\log x_1 + \\ldots + \\log x_n}{n}\\\\\\\\\n&\\stackrel{(1)}{=}&\\frac{\\log(x_1 \\times \\ldots \\times x_n)}{n}=\\frac{\\log\\left(\\prod\\limits_{i=1}^n x_i\\right)}{n}\\\\\\\\\n&\\stackrel{(2)}{=}&\\log \\left(\\sqrt[\\leftroot{-1}\\uproot{2}\\scriptstyle n]{\\prod\\limits_{i=1}^n x_i}\\right)\n\\end{eqnarray*}\n\n- Population mean $\\mu$ is estimated as a geometric mean\n- Logarithmic transformation is monotone: we can backtransform confidence intervals on log-scale!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2^lm2$coef[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2(ESR1) \n 0.3265519 \n```\n\n\n:::\n\n```{.r .cell-code}\n2^-lm2$coef[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog2(ESR1) \n    3.0623 \n```\n\n\n:::\n\n```{.r .cell-code}\n2^-confint(lm2)[2, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   2.5 %   97.5 % \n3.786977 2.476298 \n```\n\n\n:::\n:::\n\n\nA patient with an ESR1 expression that is 2 times the expression of that of another patient will on average have an  S100A8 expression that is 3.06 times lower (95\\% CI [2.48,3.79]).\n\n\n$$\\log_2 \\hat\\mu_1=23.401  -1.615 \\times \\text{logESR}_1,\\text{ } \\log_2 \\hat\\mu_2=23.401  -1.615 \\times \\text{logESR}_2 $$\n$$\\log_2 \\hat\\mu_2-\\log_2 \\hat\\mu_1=  -1.615 (\\log_2 \\text{ESR}_2-\\log_2 \\text{ESR}_1) $$\n$$\\log_2 \\left[\\frac{\\hat\\mu_2}{\\hat\\mu_1}\\right]=  -1.615 \\log_2\\left[\\frac{ \\text{ESR}_2}{\\text{ESR}_1}\\right] $$\n$$\\frac{\\hat\\mu_2}{\\hat\\mu_1}=\\left[\\frac{ \\text{ESR}_2}{\\text{ESR}_1}\\right]^{-1.615}=2^ {-1.615} =0.326$$\nor\n$$\\frac{\\hat\\mu_1}{\\hat\\mu_2}=2^{1.615} =3.06$$\n\n\n### Interpretation 3\n\nA patient with an ESR1 expression that is 1\\% higher than that of another patient will on average have  an expression-level for S100A8 gen  that is approximately -1.61% lower (95\\% CI [-1.92,-1.31])%.\n\n$$\\log_2 \\hat\\mu_1=23.401  -1.615 \\times \\text{logESR}_1,\\text{ } \\log_2 \\hat\\mu_2=23.401  -1.615 \\times \\text{logESR}_2 $$\n$$\\log_2 \\hat\\mu_2-\\log_2 \\hat\\mu_1=  -1.615 (\\log_2 \\text{ESR}_2-\\log_2 \\text{ESR}_1) $$\n$$\\log_2 \\left[\\frac{\\hat\\mu_2}{\\hat\\mu_1}\\right]=  -1.615 \\log_2\\left[\\frac{ \\text{ESR}_2}{\\text{ESR}_1}\\right] $$\n$$\\frac{\\hat\\mu_2}{\\hat\\mu_1}=\\left[\\frac{ \\text{ESR}_2}{\\text{ESR}_1}\\right]^{-1.615}=1.01^ {-1.615} =0.984 \\approx -1.6\\%$$\n\nThis is valid for low to moderate values of $\\beta_1$:\n$$-10<\\beta_1<10 \\rightarrow 1.01^{\\beta_1} -1 \\approx \\frac{\\beta_1}{100}.$$\n\n\n## Inference on the mean outcome\n\n- A regression model can also be used for prediction\n- Inference on average outcome for a given value of $X=x$, i.e.\n$$\\hat{g}(x)= \\hat{\\beta}_0 + \\hat{\\beta}_1 x$$\n- $\\hat{g}(x)$ is an estimator of the conditional mean $E[Y\\vert X=x]$\n- Parameter estimators are Normally distributed and unbiased $\\rightarrow$ estimator $\\hat{g}(x)$ is also Normally distributed and unbiased.\n\n$$\\text{SE}_{\\hat{g}(x)}=\\sqrt{MSE\\left\\{\\frac{1}{n}+\\frac{(x-\\bar X)^2}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2}\\right\\}}.$$\n\n$$T=\\frac{\\hat{g}(x)-g(x)}{SE_{\\hat{g}(x)}}\\sim t_{n-2}$$\n\n- Mean response and confidence intervals for the mean response in R via de `predict(.)` functie.\n- `newdata` argument: predictor values (x-values) at which we want to calculate the mean response\n- `interval=\"confidence\"` argument to obtain CI.\n- Without newdata argument we perform predictions for all predictor values in the dataset used to fit the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- 140:4000\ng <- predict(lm2, newdata = data.frame(ESR1 = grid), interval = \"confidence\")\nhead(g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 11.89028 10.76082 13.01974\n2 11.87370 10.74721 13.00019\n3 11.85724 10.73370 12.98078\n4 11.84089 10.72028 12.96151\n5 11.82466 10.70696 12.94237\n6 11.80854 10.69372 12.92336\n```\n\n\n:::\n:::\n\n\nNote, that we do not have to transform the new data that we specified for the ESR1 expression because we fitted the model with a call to the `lm` function and specified the transformation within the lm formula using the pipe command!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca |> ggplot(aes(x = ESR1 |> log2(), y = S100A8 |> log2())) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n## Back-transformation\n\n::: {.cell}\n\n```{.r .cell-code}\nnewdata <- data.frame(cbind(grid, 2^g))\nbrca |> ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_line(aes(x = grid, y = fit), newdata) +\n  geom_line(aes(x = grid, y = lwr), newdata, color = \"grey\") +\n  geom_line(aes(x = grid, y = upr), newdata, color = \"grey\")\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n# Prediction-intervals\n\n- We can also make a prediction for the location of a new observation that would be collected in a new experiment for a patient with a particular value for their ESR1 expression\n\n- It is important to notice that this experiment still has to be conducted. So we want to predict the non-observed individual expression value for a novel patient.\n\n- For a novel independent observation $Y^*$\n$$\n  Y^* = g(x) + \\epsilon^*\n$$\nwith $\\epsilon^*\\sim N(0,\\sigma^2)$ and $\\epsilon^*$ independent of the observations in the sample $Y_1,\\ldots, Y_n$.\n\n- We predict a new log-S100A8 for a patient with a known log2-ESR1 expression level x\n\n$$\n  \\hat{y}(x)=\\hat{\\beta}_0+\\hat{\\beta}_1 \\times x\n$$\n\n- The estimated mean outcome and prediction for a new observation are equal.\n\n- But, their sample distributions are different!\n\n    - Uncertainty on the estimated mean outcome  $\\leftarrow$ uncertainty on estimated model parameters $\\hat\\beta_0$ en $\\hat\\beta_1$.\n    - Uncertainty on new observation $ $\\leftarrow$ *uncertainty on estimated mean* and  *additional uncertainty* because the new observation will deviate around the mean!\n\n\n$$\\text{SE}_{\\hat{Y}(x)}=\\sqrt{\\hat\\sigma^2+\\hat\\sigma^2_{\\hat{g}(x)}}=\\sqrt{MSE\\left\\{1+\\frac{1}{n}+\\frac{(x-\\bar X)^2}{\\sum\\limits_{i=1}^n (X_i-\\bar X)^2}\\right\\}}.$$\n\n$$\\frac{\\hat{Y}(x)-Y}{\\text{SE}_{\\hat{Y}(x)}}\\sim t_{n-2}$$\n\n- Note, that a **prediction-interval** (PI) is an improved version of a reference-interval when the model parameters are unknown: Uncertainty on model parameters +  t-distribution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- predict(lm2, newdata = data.frame(ESR1 = grid), interval = \"prediction\")\nhead(p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 11.89028 9.510524 14.27004\n2 11.87370 9.495354 14.25205\n3 11.85724 9.480288 14.23419\n4 11.84089 9.465324 14.21646\n5 11.82466 9.450461 14.19886\n6 11.80854 9.435698 14.18138\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreddata <- data.frame(cbind(grid = grid |> log2(), p))\nbrca |> ggplot(aes(x = ESR1 |> log2(), y = S100A8 |> log2())) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  geom_line(aes(x = grid, y = lwr), preddata, color = \"blue\") +\n  geom_line(aes(x = grid, y = upr), preddata, color = \"blue\")\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreddata <- data.frame(cbind(grid, 2^p))\nbrca |> ggplot(aes(x = ESR1, y = S100A8)) +\n  geom_point() +\n  geom_line(aes(x = grid, y = fit), newdata) +\n  geom_line(aes(x = grid, y = lwr), newdata, color = \"grey\") +\n  geom_line(aes(x = grid, y = upr), newdata, color = \"grey\") +\n  geom_line(aes(x = grid, y = lwr), preddata, color = \"blue\") +\n  geom_line(aes(x = grid, y = upr), preddata, color = \"blue\")\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n## NHANES example\n\n\n- Replace reference interval for cholesterol level from chapter 2 by prediction-interval.\n\n- Reference interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(NHANES)\nfem <- NHANES |> filter(Gender == \"female\" & !is.na(DirectChol))\n\nexp(fem$DirectChol |> log() |> mean() + c(-1, 1) * qnorm(0.975) * (fem$DirectChol |> log() |> sd()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8361311 2.4397130\n```\n\n\n:::\n:::\n\n\n- prediction interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmChol <- lm(DirectChol |> log2() ~ 1, data = fem)\npredInt <- predict(lmChol, interval = \"prediction\", newdata = data.frame(noPred = 1))\nround(2^predInt, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   fit  lwr  upr\n1 1.43 0.84 2.44\n```\n\n\n:::\n:::\n\n\n\nNote, that the prediction interval is almost similar to the reference interval for the large sample. Indeed we could estimate the parameters very precise.\n\nWe will do the same thing for the small sample size of 10 patients.\n\n- Reference interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nfem10 <- NHANES |>\n  filter(Gender == \"female\" & !is.na(DirectChol)) |>\n  sample_n(size = 10)\n\n2^(fem10$DirectChol |> log2() |> mean() + c(-1, 1) * qnorm(0.975) * (fem10$DirectChol |> log2() |> sd()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8976012 2.2571645\n```\n\n\n:::\n:::\n\n\n- Prediction interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmChol10 <- lm(DirectChol |> log2() ~ 1, data = fem10)\npredInt10 <- predict(lmChol10, interval = \"prediction\", newdata = data.frame(noPred = 1))\nround(2^predInt10, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   fit  lwr  upr\n1 1.42 0.81 2.49\n```\n\n\n:::\n:::\n\n\n- Note, that the PI now captures uncertainty in parameter estimators (mean and standard error).\nAnd that the interval becomes much wider! This is particularly important here for the upper limit because we back-transformed the data!\n\n- The interval is almost as wide as the one based on the large sample.\n\n- In small samples it is very important to account for this additional uncertainty.\n\n\n# Sum of squares and Anova-table\n## Total sum of squares\n$$\\text{SSTot} = \\sum_{i=1}^n (Y_i-\\bar{Y})^2.$$\n\n- SStot can be used to estimate the variance of the **marginal distribution** of the response $f(Y)$.\n\n- In this chapter we focused on the **conditional distribution** $f(Y\\vert X=x)$.\n\n- We known that MSE is a good estimate of the variance of the conditional distribution of  $Y\\vert X=x$.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Sum of squares of the regression SSR\n\n$$\\text{SSR} = \\sum_{i=1}^n (\\hat{Y}_i - \\bar{Y})^2 = \\sum_{i=1}^n (\\hat{g}(x_i) - \\bar{Y})^2.$$\n\n- Is a measure for the deviation of the predictions on the regression line and the marginal mean of the response.\n\n- Another interpretation: difference between two models\n\n    - Estimated model $\\hat{g}(x)=\\hat\\beta_0+\\hat\\beta_1x$\n    - Estimated model without predictor (only intercept): $\\hat{g}(x)=\\hat{\\beta}_0$ $\\rightarrow$ $\\hat{\\beta}_0$ will be equal to $\\bar{Y}$.\n\n- SSR measures the size of the effect of the predictor\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Sum of Squares of the Error\n\n$$ \\text{SSE} = \\sum_{i=1}^n (Y_i-\\hat{Y}_i )^2 = \\sum_{i=1}^n \\left\\{Y_i-\\hat{g}\\left(x_i\\right)\\right\\}^2.$$\n\n- The smaller SSE the better the fit.\n\n\n- Least squares method!\n\n---\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWe can show that SST can be decomposed in\n\\begin{eqnarray*}\n  \\text{SSTot}\n    &=&  \\sum_{i=1}^n (Y_i-\\bar{Y})^2 \\\\\n    &=&  \\sum_{i=1}^n (Y_i-\\hat{Y}_i+\\hat{Y}_i-\\bar{Y})^2 \\\\\n    &=&  \\sum_{i=1}^n (Y_i-\\hat{Y}_i)^2+\\sum_{i=1}^n(\\hat{Y}_i-\\bar{Y})^2 \\\\\n    &=&  \\text{SSE }+\\text{SSR}\n  \\end{eqnarray*}\n\n-  Total variability in the data (SSTot) is partially explained by the predictor (SSR).\n- Variability that we cannot explain with the regression model is the residual variability (SSE).\n\n\n## Determination coefficient\n\n$$ R^2 = 1-\\frac{\\text{SSE}}{\\text{SSTot}}=\\frac{\\text{SSR}}{\\text{SSTot}}.$$\n\n- *Fraction of total variability of the sample outcomes explained by the model*.\n\n- Large $R^2$ indicates that the model has the potential to make good predictions  (small SSE).\n\n- Not very indicative for p-value of the test $H_0:\\beta_1=0$ vs $H_1:\\beta_1\\neq0$.\n\n  - p-value is largely determined by SSE and sample size $n$, but not by SSTot.\n  - $R^2$ is determined by SSE and SSTot but not by sample size $n$.\n- Model with low $R^2$ is still useful to study associations as long as the association is modelled correctly!\n\n### Breast cancer example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log2(S100A8) ~ log2(ESR1), data = brca)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.94279 -0.66537  0.08124  0.68468  1.92714 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   23.401      1.603   14.60 3.57e-15 ***\nlog2(ESR1)    -1.615      0.150  -10.76 8.07e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.026 on 30 degrees of freedom\nMultiple R-squared:  0.7942,\tAdjusted R-squared:  0.7874 \nF-statistic: 115.8 on 1 and 30 DF,  p-value: 8.07e-12\n```\n\n\n:::\n:::\n\n\n## F-Test in simple linear model\n\n- Sum of squares are the bases for $F$-tests\n$$  F  = \\frac{\\text{MSR}}{\\text{MSE}}$$\n\nwith  $\\text{MSR} = \\frac{\\text{SSR}}{1} \\text{ and } \\text{MSE} = \\frac{\\text{SSE}}{n-2}.$\n\n- MSR mean sum of squares of the regression,\n\n- denominators 1 en $n-2$ are the degrees of freedom of SSR and SSE.\n\n- Under $H_0: \\beta_1=0$\n$$H_0:F = \\frac{\\text{MSR}}{\\text{MSE}} \\sim F_{1,n-2},$$\n- F-test is always two-sided! $H_1:\\beta_1\\neq 0$\n$$  p = P_0\\left[F\\geq f\\right]=1-F_F(f;1,n-2)$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log2(S100A8) ~ log2(ESR1), data = brca)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.94279 -0.66537  0.08124  0.68468  1.92714 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   23.401      1.603   14.60 3.57e-15 ***\nlog2(ESR1)    -1.615      0.150  -10.76 8.07e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.026 on 30 degrees of freedom\nMultiple R-squared:  0.7942,\tAdjusted R-squared:  0.7874 \nF-statistic: 115.8 on 1 and 30 DF,  p-value: 8.07e-12\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n\n## Anova Table\n\n\n| |Df|Sum Sq|Mean Sq|F value|Pr(>F)|\n|---|---|---|---|---|---|\n|Regression|degrees of freedom SSR|SSR|MSR|f-statistic|p-value|\n|Error|degrees of freedom SSE|SSE|MSE| | |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(lm2)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Sum Sq\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Mean Sq\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"121.81364\",\"3\":\"121.813644\",\"4\":\"115.7978\",\"5\":\"8.070269e-12\",\"_rn_\":\"log2(ESR1)\"},{\"1\":\"30\",\"2\":\"31.55854\",\"3\":\"1.051951\",\"4\":\"NA\",\"5\":\"NA\",\"_rn_\":\"Residuals\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n# Dummy variables\n\n- Linear regression model  can also be used to compare two group means.\n- brca: difference in average age between patients with unaffected and affected lymph nodes.\n\n- Define dummy variabele\n$$x_i = \\left\\{ \\begin{array}{ll}\n1 & \\text{affected lymph nodes} \\\\\n0 & \\text{unaffected lymph nodes} \\end{array}\\right.$$\n\n- group with $x_i=0$ is referred to as the  **reference group**.\n\n- Regression model remains unaltered,\n$$Y_i = \\beta_0 + \\beta_1 x_i +\\epsilon_i$$\nwith $\\epsilon_i \\text{ iid } N(0,\\sigma^2)$\n\n\nBecause $x_i$ only can take two values, we can study the regression model for each value of  $x_i$ separately:\n$$ \\begin{array}{lcll}\n   Y_i &=& \\beta_0 +\\epsilon_i &\\text{unaffected lymph nodes} (x_i=0) \\\\\n   Y_i &=& \\beta_0 + \\beta_1 +\\epsilon_i &\\text{ affected lymph nodes} (x_i=1) .\n \\end{array}$$\nSo\n \\begin{eqnarray*}\n   E\\left[Y_i\\mid x_i=0\\right] &=& \\beta_0 \\\\\n   E\\left[Y_i\\mid x_i=1\\right] &=& \\beta_0 + \\beta_1,\n\\end{eqnarray*}\n\n Hence, the interpretation of $\\beta_1$:\n$$   \\beta_1 = E\\left[Y_i\\mid x_i=1\\right]-E\\left[Y_i\\mid x_i=0\\right]$$\n\n$\\beta_1$ is the average age difference between patients with affected and patients with unaffected lymph nodes (reference group).\n\nWith notation $\\mu_0= E\\left[Y_i\\mid x_i=0\\right]$ and $\\mu_1= E\\left[Y_i\\mid x_i=1\\right]$ this becomes\n$$\\beta_1 = \\mu_1-\\mu_0.$$\n\nWe can show that\n$$\\begin{array}{ccll}\n \\hat\\beta_0\n   &=& \\bar{Y}_1&\\text{ (sample mean of reference group)} \\\\\n \\hat\\beta_1\n   &=& \\bar{Y}_2-\\bar{Y}_1&\\text{(estimator of effect size)} \\\\\n \\text{MSE}\n   &=& S_p^2 .\n\\end{array}$$\n\nTests $H_0:\\beta_1=0$ vs.  $H_1:\\beta_1\\neq0$ can be used to assess the null hypothesis of the  two-sample $t$-test, $H_0:\\mu_1=\\mu_2$ vs $H_1:\\mu_1\\neq\\mu_2$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca$node <- as.factor(brca$node)\nt.test(age ~ node, brca, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  age by node\nt = -2.7988, df = 30, p-value = 0.008879\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -15.791307  -2.467802\nsample estimates:\nmean in group 0 mean in group 1 \n       59.94737        69.07692 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm3 <- lm(age ~ node, brca)\nsummary(lm3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = age ~ node, data = brca)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-19.9474  -5.3269   0.0526   5.3026  18.0526 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   59.947      2.079  28.834  < 2e-16 ***\nnode1          9.130      3.262   2.799  0.00888 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.063 on 30 degrees of freedom\nMultiple R-squared:  0.207,\tAdjusted R-squared:  0.1806 \nF-statistic: 7.833 on 1 and 30 DF,  p-value: 0.008879\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(lm3)\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-40-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-40-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-40-4.png){width=672}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrca |> ggplot(aes(x = node |> as.factor(), y = age)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(3, 3))\nset.seed(354)\nmu0 <- brca |> pull(age) |> mean()\nSp <- sigma(lm3)\nfor (i in 1:9) plot(rnorm(32, mean=mu0, sd=Sp) ~ node, brca, ylab = \"Age under H0\")\n```\n\n::: {.cell-output-display}\n![](06-linearRegression_files/figure-html/unnamed-chunk-42-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n# Observational study\n\n- We cannot conclude that age causes a higher risk for affected lymph nodes.\n- Possibly **confounding**: no randomisation $\\rightarrow$ groups of patients with affected and unaffected lymph nodes. They can also differ in other characteristics.\n\n- We can only conclude that there is an association between lymph node status and age.\n\n- However, the association does not have to be causal!\n\n\n- Note, that this is also the case for the linear model for $\\log_2$-S100A8-expression.\n\n    - Because we were not able to fix the  ESR1-expression experimentally we cannot conclude that a higher ESR1-expression causes a decrease in the S100A8-expression.\n    - We can only conclude that there is a negative association.\n    - To assess the impact of a gene on other gene typically knockout mutants are used in the lab.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}